import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.32 — Manual-fallback performance practice: rehearsed redundancy
 * under degraded primaries.
 *
 * Generated by the v1.49.581 MUS wave-7 fleet (W7-G).
 * Cross-references:
 *   NASA 1.32 (Mercury-Atlas 9 / Faith 7; Cooper manual retrofire over Japan
 *     after Orbit 19/20 ASCS telemetry-bus cascade; final Mercury solo
 *     orbital mission; 22 orbits, 34h 19m 49s; 1963-05-15 to 1963-05-16),
 *   ELC 1.32 (pending),
 *   MUS 1.5  (cryptobiotic encore — domain-12 suspended-solo corner),
 *   MUS 1.42 (coupled-endurance practice — domain-12 continuous-coupled-pair
 *             corner),
 *   MUS 1.22 (sustained-collective execution — domain-12 continuous-
 *             collective corner; this concept closes Domain 12 to the wave-7
 *             target of 4 entries on the orthogonal redundancy-mechanism
 *             axis: degraded-primary-with-rehearsed-backup).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 *
 * Domain 12 (Performance practice) — fourth and CLOSING MUS degree in this
 * domain. The four-corner partition is now complete:
 *   1.5  = suspended-solo                (silence does the preservation work)
 *   1.42 = continuous-coupled-pair       (the partner does the preservation work)
 *   1.22 = continuous-collective         (the colony does the preservation work)
 *   1.32 = degraded-primary-with-backup  (the kept-warm parallel mode does the
 *                                         preservation work — this concept)
 * The four entries together establish a four-axis quadrant model for
 * future-pass Domain 12 deepening: cardinality (1, 2, ≥3, n×modes), continuity
 * (suspended, continuous, continuous, continuous), redundancy-mechanism
 * (silence, partner, colony, parallel-mode). Pass-2 Domain 12 work can refine
 * each corner without contesting the quadrant partition.
 */
export const manualFallbackRehearsedRedundancy: RosettaConcept = {
  id: 'mus-1.32-manual-fallback-rehearsed-redundancy',
  name: 'Manual-fallback performance practice: rehearsed redundancy under degraded primaries',
  domain: 'music',
  description:
    'A performance-practice primitive describing how a structurally-sufficient ' +
    'BACKUP MODE is agreed and drilled beforehand, carried in continuous parallel ' +
    'through the performance during nominal operation (kept WARM at audible-trace ' +
    'level), and activated within the gesture\'s characteristic period when the ' +
    'primary degrades. Distinct from clutch-improvisation (improvised in the moment) ' +
    'and from cold-start emergency procedure (backup goes cold during nominal). ' +
    'Four pedagogical conditions: (1) PRE-EVENT AGREEMENT — the fallback mode is ' +
    'rehearsed in a setting analogous to but distinct from live performance ' +
    '(simulator session for the spacecraft pilot; soundcheck for the bassist; ' +
    'developmental ontogeny for the dual-compass bird); (2) CONTINUOUS ACTIVATION ' +
    'DURING NOMINAL — the backup is kept warm during nominal operation rather than ' +
    'cold-started at the moment of failure (Cooper kept manual hand-controller ' +
    'active during automatic flight; Rabb kept the alternate bassline at audible- ' +
    'trace level throughout sets; gambelii WCS reads the night sky every flight); ' +
    '(3) TRANSITION TIME BOUNDED BY GESTURE PERIOD — primary-to-backup transition ' +
    'completes within the gesture\'s own characteristic period (one wing-beat for ' +
    'the bird; one bar for the bassist; the burn-execution window for the ' +
    'spacecraft); (4) FIDELITY-ENVELOPE MATCH — backup at full activation produces ' +
    'operational fidelity matching or exceeding the primary\'s (Cooper\'s hand-flown ' +
    'retrofire produced the most accurate Mercury splashdown on record at 6.4 km ' +
    'from USS Kearsarge; Rabb\'s alternate basslines harmonically substitutable for ' +
    'the primary; gambelii arriving on stellar compass alone in species-appropriate ' +
    'range with dialect intact). Anchored exemplars: Mercury-Atlas 9 / Faith 7 ' +
    'manual-retrofire over Japan on Orbit 22 after Orbits 19-20 ASCS telemetry-bus ' +
    'cascade (Cooper, 1963-05-15; Swenson Grimwood Alexander 1966 NASA SP-4201 ' +
    'ch. 14); Luther Rabb section-player rehearsed-redundancy discipline across ' +
    'Ballin\' Jack 1969-1973 (Columbia C-30344, KC-31195; Mercury SRM-1-668) and ' +
    'Santana session work 1976-1977 (Amigos Columbia PC-33576; Festival PC-34423); ' +
    'White-crowned Sparrow Z. l. gambelii subspecies dual-compass parallel-mode ' +
    'architecture (Marler 1970 J Comp Physiol Psych Monograph 71(2); Marler & ' +
    'Tamura 1962 Condor 64; Emlen 1967a/b Auk 84; Wiltschko & Wiltschko 1995; ' +
    'Mouritsen 2018 Nature 558:50-59).',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-performance-practice',
      description: 'Manual-fallback rehearsed-redundancy extends performance-practice into the parallel-mode regime; only domain 12 admits the across-event temporal frame in which a primary degrades on the most consequential cue and a kept-warm parallel mode takes over without transition penalty, and only domain 12 admits the discipline-level analysis of pre-event rehearsal as the structural feature.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.5-cryptobiotic-encore',
      description: 'Domain-12 anchored corner — suspended-solo case (cardinality 1; silence does the preservation work). MUS 1.5 preserves a gesture across an arbitrary-duration quiescence by single-performer dormancy and full-amplitude resumption on reactivation. MUS 1.32 preserves a gesture across a primary-failure event by continuous parallel-mode activation. Same domain, orthogonal preservation mechanism (silence vs. parallel-mode); same condition (3) transition-time-bounded-by-gesture-period; different cardinality and different temporal regime (across-decade quiescence vs. within-event substitution).',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.42-coupled-endurance-practice',
      description: 'Domain-12 anchored corner — continuous-coupled-pair case (cardinality 2; the partner does the preservation work). MUS 1.42 preserves a gesture across continuous load with real-time partner correction. MUS 1.32 preserves a gesture across a primary-failure event by parallel-mode internal redundancy rather than partnered correction. The two concepts share the no-silent-resumption clause (both insist on continuous activation rather than suspension) but differ in redundancy-mechanism: 1.42 distributes redundancy across two performers; 1.32 carries redundancy as parallel modes within a single performer or system.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.22-sustained-collective-execution',
      description: 'Domain-12 anchored corner — continuous-collective case (cardinality ≥3; the colony does the preservation work via local-interaction-graph dynamics). MUS 1.22 preserves a gesture across n-voice continuous load by emergent local-interaction coordination. MUS 1.32 preserves a gesture across a primary-failure event by single-actor parallel-mode redundancy. The two concepts share the failure-at-coordination-layer condition (failure is diagnosable at the architecture level rather than at any single component) but differ in redundancy locus: 1.22 distributes redundancy across the colony graph; 1.32 carries redundancy internally as parallel modes.',
    },
    {
      type: 'dependency',
      targetId: 'music-rehearsal-discipline',
      description: 'Pre-event-agreement-on-backup-procedure (condition 1) and continuous-activation-during-nominal (condition 2) depend on a rehearsal-discipline framework treating the soundcheck/simulator/developmental-ontogeny session as a structurally-distinct rehearsal substrate from live performance. Berliner 1994 ch. 12-15 and Monson 1996 anchor the rehearsal-discipline frame; the rehearsed-redundancy primitive sits at the intersection of rehearsal-discipline and parallel-mode architecture.',
    },
  ],
  metadata: {
    musDegree: '1.32',
    exemplars: {
      s36Artist: 'Luther Rabb',
      s36Works: [
        'Ballin\' Jack — Ballin\' Jack (Columbia C-30344, 1970): Rabb bass and lead vocals; PNW Latin-rock with multi-vocal-lead and horn-section-doubling rehearsed-redundancy',
        'Ballin\' Jack — Buzzard Luck (Columbia KC-31195, 1972): continuation of the Ballin\' Jack stagecraft architecture',
        'Ballin\' Jack — Special Pride (Mercury SRM-1-668, 1973): final Ballin\' Jack album',
        'Santana — Amigos (Columbia PC-33576, 1976): Rabb session bassist; bass-and-organ duets exemplary of the structural-timekeeping-redundancy frame against percussion-saturated primary timekeeping',
        'Santana — Festival (Columbia PC-34423, 1977): continued Rabb session presence in the percussion-saturated 1976-1977 Santana band',
      ],
      spsSpecies: 'White-crowned Sparrow (Zonotrichia leucophrys), Z. l. gambelii migratory subspecies (Alaska-breeding long-distance migrant)',
      spsAcousticFeature:
        'Dual-compass parallel-mode navigational architecture: magnetic-inclination compass (primary in nominal; reads geomagnetic-field inclination angle for absolute directional reference) operates in continuous redundancy with the stellar-compass (reads rotational centre of the night sky around the celestial pole). Both compasses kept active throughout 8,600 km annual round-trip migration; either is individually sufficient to produce species-appropriate orientation. Acoustic correlate: Z. l. gambelii dialect-stability under migration stress — males sing the same dialect on breeding ground, on stopover, and in winter quarters, with cross-generational cultural transmission via critical-period song-learning (Marler 1970; Marler & Tamura 1962; Baptista & King 1980). The Z. l. gambelii subspecies takes the navigational-architecture axis distinct from MUS 1.48\'s Z. l. pugetensis dialect-axis treatment.',
      nasaMission: 'Mercury-Atlas 9 / Faith 7 (Cooper, 1963-05-15 to 1963-05-16; Atlas 130-D launch from LC-14 Cape Canaveral; capsule #20; 22 orbits, 34h 19m 49s, perigee 161 km / apogee 267 km / inclination 32.5° / period 88.7 min). Orbit 19: false 0.05g indicator triggers ASCS reentry-attitude-hold mode prematurely; Cooper overrides manually. Orbit 20: telemetry-bus short propagates; ASCS loses yaw gyro, horizon sensors, full attitude-hold authority. Orbit 22: manual retrofire over coast of Japan executed by hand — painted +34° pitch reticle on window aligned to horizon for pitch reference, two visually identified stars for yaw, wristwatch for T-0/T+5/T+10 burn timing, manual hand-controller cold-gas thrusters for attitude-hold against drift. John Glenn at Zanzibar served as CAPCOM. Splashdown 6.4 km from USS Kearsarge — most accurate Mercury recovery on record. Last American solo spaceflight until Mike Melvill\'s SpaceShipOne 2004 (41-year gap). Cf. Swenson Grimwood Alexander 1966 NASA SP-4201 ch. 14.',
    },
    domain12Quadrant: 'degraded-primary-with-rehearsed-backup (FOURTH and CLOSING corner of the domain-12 quadrant model; orthogonal to MUS 1.5 suspended-solo, MUS 1.42 continuous-coupled-pair, and MUS 1.22 continuous-collective on the redundancy-mechanism axis)',
    domain12Closure: {
      target: 4,
      current: 4,
      corners: {
        'suspended-solo': 'mus-1.5-cryptobiotic-encore',
        'continuous-coupled-pair': 'mus-1.42-coupled-endurance-practice',
        'continuous-collective': 'mus-1.22-sustained-collective-execution',
        'degraded-primary-with-rehearsed-backup': 'mus-1.32-manual-fallback-rehearsed-redundancy',
      },
    },
    cluster10Anchors: ['PRS', 'SOC', 'FAIL'],
    references: [
      'Swenson, L. S., Grimwood, J. M., & Alexander, C. C. (1966). This New Ocean: A History of Project Mercury. NASA SP-4201, ch. 14',
      'Carpenter, J. R., & Cooper, L. G. (1962). Mercury Spacecraft Operations: Astronaut\'s Procedures and the Manual-Reentry Sequence. NASA-TM-X-58004',
      'Grimwood, J. M., Hacker, B. C., & Vorzimmer, P. J. (1969). Project Gemini Technology and Operations: A Chronology. NASA SP-4002',
      'Marler, P. (1970). A comparative approach to vocal learning: song development in white-crowned sparrows. J Comp Physiol Psych Monograph 71(2), 1-25 (and Sci Am Oct 1970)',
      'Marler, P., & Tamura, M. (1962). Song dialects in three populations of White-crowned Sparrows. The Condor 64, 368-377',
      'Baptista, L. F., & King, J. R. (1980). Geographical variation in song and song dialects of montane White-crowned Sparrows. The Condor 82, 267-284',
      'Emlen, S. T. (1967a). Migratory orientation in the Indigo Bunting: I. Evidence for use of celestial cues. The Auk 84(3), 309-342',
      'Emlen, S. T. (1967b). Migratory orientation in the Indigo Bunting: II. Mechanism of celestial orientation. The Auk 84(4), 463-489',
      'Wiltschko, W., & Wiltschko, R. (1995). Magnetic Orientation in Animals. Springer-Verlag',
      'Mouritsen, H. (2018). Long-distance navigation and magnetoreception in migratory animals. Nature 558, 50-59',
      'Lerdahl, F., & Jackendoff, R. (1983). A Generative Theory of Tonal Music. MIT Press, §3-4',
      'Persichetti, V. (1961). Twentieth-Century Harmony. W. W. Norton, ch. 8-9',
      'Berliner, P. (1994). Thinking in Jazz. University of Chicago Press, ch. 12-15',
      'Monson, I. (1996). Saying Something: Jazz Improvisation and Interaction. University of Chicago Press',
      'Cogan, R. (1984). New Images of Musical Sound. Harvard University Press',
      'de Barros, P. (1993). Jackson Street After Hours: The Roots of Jazz in Seattle. Sasquatch Books',
    ],
  },
};
