/**
 * C04 — chapter.mjs idempotent-write test
 *
 * Asserts that writeChapterIdempotent() preserves hand-authored content by
 * default and regenerates DB-derivable openers / empty files / missing files.
 * Verifies the --force-regenerate code path overrides preservation.
 *
 * Authored 2026-04-28 in v1.49.585 component C04.
 * Spec: .planning/missions/v1-49-585-concerns-cleanup/components/04-chapter-idempotent.md
 *
 * NOTE: this test file lives at tools/release-history/__tests__/ which is
 * OUTSIDE the current vitest include glob (vitest.config.ts scopes to
 * src/**, .college/**, tests/**). It is forward-ready: a future milestone
 * widening vitest scope to tools/** will activate this test automatically.
 * For v1.49.585, the same assertions are run inline at the C04 sanity
 * check (chapter.mjs zero-diff against v1.49.584 hand-authored chapters).
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeChapterIdempotent } from '../chapter.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, 'fixtures/chapter-idempotent');

const HAND_AUTHORED = readFileSync(join(FIXTURES, 'hand-authored-00-summary.md'), 'utf-8');
const DB_DERIVED = readFileSync(join(FIXTURES, 'db-derived-opener.md'), 'utf-8');

const GENERATED_OPENER_TEMPLATE = `# Summary — v1.49.585

- **Version:** \`v1.49.585\`
- **Shipped:** 2026-04-28
- **Branch:** dev
- **Tag:** v1.49.585

(generated by chapter.mjs)
`;

describe('C04 — writeChapterIdempotent', () => {
  let tmp;

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), 'chapter-idempotent-'));
  });

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it('CF-C04-01: hand-authored chapter NOT clobbered (preserve)', () => {
    const target = join(tmp, '00-summary.md');
    writeFileSync(target, HAND_AUTHORED);
    const before = readFileSync(target, 'utf-8');

    const result = writeChapterIdempotent(target, GENERATED_OPENER_TEMPLATE, false);

    expect(result.wrote).toBe(false);
    expect(result.reason).toMatch(/non-derivable|preserved/);
    const after = readFileSync(target, 'utf-8');
    expect(after).toBe(before);
  });

  it('CF-C04-02: DB-derivable opener IS regenerated when content drifts', () => {
    const target = join(tmp, '00-summary.md');
    writeFileSync(target, DB_DERIVED);

    const result = writeChapterIdempotent(target, GENERATED_OPENER_TEMPLATE, false);

    // DB_DERIVED has a similar-template opener but different body; helper writes through.
    expect(result.wrote).toBe(true);
    expect(result.reason).toMatch(/DB-derivable|content drift/);
    expect(readFileSync(target, 'utf-8')).toBe(GENERATED_OPENER_TEMPLATE);
  });

  it('CF-C04-03: --force-regenerate flag overrides preservation', () => {
    const target = join(tmp, '00-summary.md');
    writeFileSync(target, HAND_AUTHORED);

    const result = writeChapterIdempotent(target, GENERATED_OPENER_TEMPLATE, true);

    expect(result.wrote).toBe(true);
    expect(result.reason).toMatch(/force-regenerate/);
    expect(readFileSync(target, 'utf-8')).toBe(GENERATED_OPENER_TEMPLATE);
  });

  it('CF-C04-04: empty existing file IS regenerated', () => {
    const target = join(tmp, '00-summary.md');
    writeFileSync(target, '');

    const result = writeChapterIdempotent(target, GENERATED_OPENER_TEMPLATE, false);

    expect(result.wrote).toBe(true);
    expect(result.reason).toMatch(/<200 bytes|stub/);
    expect(readFileSync(target, 'utf-8')).toBe(GENERATED_OPENER_TEMPLATE);
  });

  it('CF-C04-05: missing existing file IS regenerated', () => {
    const target = join(tmp, '00-summary.md');
    expect(existsSync(target)).toBe(false);

    const result = writeChapterIdempotent(target, GENERATED_OPENER_TEMPLATE, false);

    expect(result.wrote).toBe(true);
    expect(result.reason).toMatch(/did not exist/);
    expect(readFileSync(target, 'utf-8')).toBe(GENERATED_OPENER_TEMPLATE);
  });

  it('byte-identical content: PRESERVE (no-op)', () => {
    const target = join(tmp, '00-summary.md');
    writeFileSync(target, GENERATED_OPENER_TEMPLATE);

    const result = writeChapterIdempotent(target, GENERATED_OPENER_TEMPLATE, false);

    expect(result.wrote).toBe(false);
    expect(result.reason).toMatch(/byte-identical/);
  });
});
