import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.61 — Spaceborne attitude-system self-test: Sun-tracker zero-crossing,
 * Earth-tracker null-balance, and the Lunar Orbiter 5 program-closure
 * validation campaign.
 *
 * Generated by the v1.49.581 ELC Wave-2 Phase C backfill (slot E2-H,
 * domain 14 first-entry, era si-discrete).
 *
 * Cross-references: NASA 1.61 (Lunar Orbiter 5 final flight of the LO
 * program; commanded impact 1968-01-31 closing the program at 5-of-5),
 * MUS 1.61 (musical analog of the program-closure validation form).
 * Subject derivation rubric at
 * .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md.
 */
export const attitudeSystemSelfTest: RosettaConcept = {
  id: 'elc-1.61-attitude-system-self-test',
  name: 'Spaceborne attitude-system self-test (BIT) — Sun-tracker zero-crossing, Earth-tracker null-balance, reaction-wheel back-EMF tachometer',
  domain: 'electronics',
  description:
    'A test-and-measurement engineering primitive describing how spaceborne ' +
    'attitude-control electronics certify their own correctness in flight via ' +
    'Built-In-Test (BIT) by stimulus injection plus null/zero-response readout. ' +
    'The composable inequality BIT_pass(t) = |response(t) − expected_response(stimulus(t))| ' +
    '< tolerance(t) decomposes the certification across three subsystems: a quad-cell ' +
    'photodiode Sun-tracker with zero-crossing detection (matched-stimulus null produces ' +
    'logic-high on-Sun flag), a thermopile-bridge Earth-tracker with null-balance integrator ' +
    'servo (zero-imbalance produces zero servo output), and a reaction-wheel drive with ' +
    'back-EMF tachometer feedback (commanded rate equals measured tachometer voltage produces ' +
    'zero loop error). Each subsystem passes its independent BIT covariance check; the joint ' +
    'pass condition certifies the bus. The Lunar Orbiter 5 program-closure validation ' +
    'campaign (1967-08-01 launch / 1968-01-31 commanded impact) captured ~10⁶ telemetry ' +
    'frames each containing ~24 BIT covariance checks across 184 days of lunar-orbital ' +
    'operation, producing ~2.4 × 10⁷ pass/fail observations that certified the ' +
    'Boeing-Seattle attitude-control bus design at 5-of-5 program success.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-instrumentation-amp',
      description:
        'BIT covariance checks operate on differential-amplifier outputs (err_x, err_y, ' +
        'null_serv, loop_err); understanding instrumentation-amplifier topology is ' +
        'prerequisite to applying the BIT covariance equation across a multi-subsystem chain',
    },
    {
      type: 'dependency',
      targetId: 'elec-zero-crossing-comparator',
      description:
        'The Sun-tracker zero-crossing detector with hysteresis produces the digital flag ' +
        'that the BIT mux samples; the Schmitt-trigger / hysteretic-comparator topology is ' +
        'the structural building block of the BIT discipline',
    },
    {
      type: 'dependency',
      targetId: 'elec-closed-loop-rate-feedback',
      description:
        'The reaction-wheel back-EMF tachometer + drive-amp feedback loop is one of the ' +
        'three BIT covariance checks; understanding closed-loop rate-feedback architecture is ' +
        'prerequisite to interpreting the BIT response of the reaction-wheel subsystem',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.61-program-closure-validation',
      description:
        'The BIT covariance check (response equals expected response within tolerance, ' +
        'sustained across many telemetry samples) is the structural rhyme of the ' +
        'program-closure validation form MUS 1.61 catalogues: a closing track in an ' +
        'album-as-thesis composition does not introduce new material but instead validates ' +
        'thesis material from earlier tracks by resolving harmonic/rhythmic patterns that ' +
        'have been established, the same way the BIT covariance dataset validates the bus ' +
        'design that has been established across earlier flights of the program',
    },
  ],
  metadata: {
    elcDegree: '1.61',
    domain: 14,
    domainName: 'Test & measurement',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Boeing Space Division (Seattle, WA) standardized Lunar Orbiter spacecraft bus, ' +
      'attitude-control electronics — Bendix Eclipse-Pioneer Division Sun-tracker (silicon ' +
      'quad-cell photodiode + chopper-stabilised differential preamp + zero-crossing ' +
      'comparator) + Barnes Engineering horizon-scanner Earth-tracker (thermopile bridge + ' +
      'null-balance servo) + Sperry-built reaction-wheel drive (PWM H-bridge + back-EMF ' +
      'tachometer) + on-board attitude-test self-monitoring multiplexer + S-band telemetry ' +
      'feed; flew 1967-08-01 to 1968-01-31 on Lunar Orbiter 5',
    keyEquation:
      'BIT_pass(t) = |response(t) − expected_response(stimulus(t))| < tolerance(t); for ' +
      'matched stimulus the response is null, for stimulus injection the response is the ' +
      'predicted analytical model output, and the tolerance is set by the hysteresis window ' +
      'or the integrator clamp; multi-subsystem covariance check passes when all three ' +
      'inequalities hold simultaneously',
    benchReplication: {
      photodiodeArray: 'Hamamatsu S5980 quad-cell silicon photodiode (Mouser 630-S5980)',
      transimpedanceAmp: 'OPA827AID (TI) — JFET-input, 4 nV/√Hz, 2.2 fA/√Hz',
      instrumentationAmp: 'INA126U (TI) — programmable-gain integrated diff-amp',
      zeroCrossingComparator: 'LM311N (TI) — bipolar, latch-immune, 50 mV hysteresis',
      bitMux: 'CD74HC4051 8-channel CMOS analog mux + Raspberry Pi Pico harness',
      modernIMU: 'Honeywell HG1700 inertial measurement unit (modern descendant)',
      eraOriginal:
        'Bendix Eclipse-Pioneer Division IL-50-class quad-cell photodiode + 2N4416 + 2N2222 ' +
        'cascode + 100 MΩ glass-encapsulated wirewound feedback resistor; Barnes Engineering ' +
        'horizon-scanner thermopile bridge + null-balance servo; Sperry-built BLDC reaction-' +
        'wheel drive with discrete-BJT H-bridge and back-EMF tachometer',
    },
    references: [
      'Wertz, J.R. — *Spacecraft Attitude Determination and Control* (Reidel/Springer 1978; reprinted 1990s), ch. 6',
      'Sidi, M.J. — *Spacecraft Dynamics and Control: A Practical Engineering Approach* (Cambridge UP 1997), ch. 8',
      'Markley, F.L. & Crassidis, J.L. — *Fundamentals of Spacecraft Attitude Determination and Control* (Springer 2014), ch. 4',
      'Byers, B.K. — *Destination Moon: A History of the Lunar Orbiter Program*, NASA SP-4316 (1977) §10',
      'Hacker, B.C. & Grimwood, J.M. — *On the Shoulders of Titans: A History of Project Gemini*, NASA SP-4214 (1977)',
      'Bendix Corporation Eclipse-Pioneer Division — Sun-tracker design notes for Lunar Orbiter, NASA-CR-72193 (1967)',
      'MIL-STD-1521B — Technical Reviews and Audits for Systems, Equipments, and Computer Software (BIT discipline)',
      'IEEE Std 1149.1 (JTAG, 1990) — historical descendant of the discrete BIT primitive demonstrated on LO5',
      'Honeywell Aerospace — HG1700 Inertial Measurement Unit datasheet, https://aerospace.honeywell.com/us/en/learn/products/sensors/hg1700-inertial-measurement-unit',
      'Texas Instruments — OPA827 Low-Noise JFET-Input Op-Amp, https://www.ti.com/lit/ds/symlink/opa827.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.61,
    imaginary: 0.14,
    magnitude: Math.sqrt(0.61 ** 2 + 0.14 ** 2),
    angle: Math.atan2(0.14, 0.61),
  },
};
