import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.33 — Counterpoint as displacement: rival-voice intrusion,
 * partial-displacement, and the silenced-but-present countervoice.
 *
 * Generated by the v1.49.581 MUS Wave-7 backfill fleet (agent W7-H).
 * Closes the Counterpoint domain (4 of 4 entries) with the displacement
 * sub-mode of two-voice counterpoint. Domain partners: MUS 1.35
 * (redundancy), MUS 1.10 (symbiosis), MUS 1.8 (voice-to-section
 * rivalry-and-resistance).
 *
 * Cross-references:
 *   NASA 1.33 (Ranger 6 — 1964 silent impact; cameras dead at impact)
 *   ELC 1.33  (pending — competitive-congener invasions / displacement)
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const counterpointAsDisplacement: RosettaConcept = {
  id: 'mus-1.33-counterpoint-as-displacement',
  name: 'Counterpoint as displacement: rival-voice intrusion, partial-displacement, and the silenced-but-present countervoice',
  domain: 'music',
  description:
    'A music-theoretic primitive describing two-voice counterpoint in which one ' +
    'voice is composed into the texture but performed silent, while the silenced ' +
    'voice retains its structural commitment to the texture even when its ' +
    'acoustic contribution is zero. The contrapuntal signature of the ' +
    'displacement mode is recoverability: when the displacing voice or event is ' +
    'removed, the silenced voice can re-emerge into audibility. This is distinct ' +
    'from MUS 1.35 redundancy (both voices audible, same message), MUS 1.10 ' +
    'symbiosis (both voices audible, complementary), and MUS 1.8 voice-to-section ' +
    'rivalry-and-resistance (both voices audible, asymmetric mass). Three ' +
    'substrates exemplify the same primitive: the Northern Spotted Owl ' +
    '(Strix occidentalis caurina) being progressively silenced by the ' +
    'range-expanding Barred Owl (Strix varia) in old-growth Pacific Northwest ' +
    'forest, with population-scale call-rate recovery under the USFWS ' +
    'experimental removal program (Wiens et al. 2021); Damien Jurado\'s ' +
    'silenced-instrument-track sparse-arrangement folk practice on the Richard ' +
    'Swift-produced Maraqopa trilogy (Secretly Canadian SC257 2012, SC288 2014, ' +
    'SC323 2016), where instrument tracks are recorded full-band and then ' +
    'progressively muted in mix; and NASA Ranger 6\'s arrival at Mare ' +
    'Tranquillitatis on 1964-02-02 with all six TV cameras electrically dead ' +
    'from ascent corona-discharge, the spacecraft otherwise nominal — arrived ' +
    'but did not testify. The Cage 4\'33" and Berio Sequenza negative-space ' +
    'lineage anchor the silenced-voice tradition in 20th-century composition; ' +
    'Aldwell-Schachter §32 voice-removability and Schoenberg 1911 §1 are the ' +
    'pedagogical frame. Closes the Counterpoint domain target to 4 of 4.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-harmony',
      description: 'Counterpoint extends the harmony foundation by composing voice-independence with the additional displacement requirement that one voice retains structural commitment under acoustic suppression',
    },
    {
      type: 'analogy',
      targetId: 'music-song-form',
      description: 'Form treats the multi-voice texture as an outcome; counterpoint treats it as a discipline. The displacement mode is the limiting case where the discipline of voice-independence is preserved while the acoustic texture is reduced to one voice — the silenced voice\'s structural function persists in the score even when its performance is silent',
    },
  ],
  metadata: {
    musDegree: '1.33',
    exemplars: {
      s36Artist: 'Damien Jurado',
      s36Works: [
        'Maraqopa (Secretly Canadian SC257, 2012) — Richard Swift production at National Freedom Studio, Cottage Grove OR; track 1 "Nothing is the News" exemplifies the silenced-instrument-track decision at the verse-to-chorus structural transition',
        'Brothers and Sisters of the Eternal Son (Secretly Canadian SC288, 2014) — track "Silver Joy" exemplifies the bridge-level emergence-and-withdrawal of a silenced choir-stack',
        'Visions of Us on the Land (Secretly Canadian SC323, 2016) — track "Mellow Blue Polka Dot" exemplifies the intermittent silenced Mellotron-string bed across verses',
        'Waters Ave S. (Sub Pop SP400, 1997) — constitutive sparse-arrangement debut establishing the practice that the Swift collaboration crystallised',
      ],
      spsSpecies: 'Northern Spotted Owl (Strix occidentalis caurina, Merriam 1898)',
      spsAcousticFeature: 'four-note territorial hoot at 1-2 kHz fundamental, ~1 km carry through old-growth canopy in still-air conditions; suppressed by 50-70% in territories where Barred Owls are calling within audible range (Wiens, Anthony & Forsman 2014); call-rate recovery within 1-3 breeding seasons under Barred Owl removal (Wiens et al. 2021 USFWS experimental removal program). The species-scale displacement primitive: resident voice silenced by intruding voice\'s superior projection, structural commitment retained, recovery demonstrable under removal of the displacing voice.',
    },
    references: [
      'Aldwell, Schachter & Cadwallader, Harmony and Voice Leading (5e, Cengage 2011), §32-34 species counterpoint and the voice-removability test',
      'Schoenberg, Theory of Harmony (1911; Carter trans. 1978), §1 introduction — counterpoint as voice-removability with explicit treatment of the silenced-but-present countervoice',
      'Cage, J. (1961) Silence: Lectures and Writings (Wesleyan UP) — 4\'33" framing; the silenced voice as composed content',
      'Berio, L. (1968) Sequenza programmatic notes — negative-space counterpoint',
      'Tymoczko, A Geometry of Music (Oxford, 2011), ch. 9 voice-leading and counterpoint',
      'Lerdahl & Jackendoff, A Generative Theory of Tonal Music (MIT, 1983), §4 prolongational reduction',
      'Forsman, Meslow & Wight (1984) Distribution and biology of the Spotted Owl in Oregon, Wildlife Monographs 87:1-64',
      'Gutiérrez, Cody, Courtney & Franklin (2007) The invasion of Barred Owls and its potential effect on the Spotted Owl, Studies in Avian Biology 32:26-39',
      'Wiens, Anthony & Forsman (2014) Competitive interactions and resource partitioning between Northern Spotted Owls and Barred Owls in western Oregon, Wildlife Monographs 185:1-50',
      'Wiens, Dugger, Higley, Lesmeister, Franklin, Hamm et al. (2021) Effects of experimental removal of Barred Owls on population demography of Northern Spotted Owls, Wildlife Monographs 208:1-50',
      'USFWS (2011) Revised Recovery Plan for the Northern Spotted Owl, Strix occidentalis caurina',
      'Hall, R. C. (1977) Lunar Impact: A History of Project Ranger (NASA SP-4210)',
      'NASA TM-X-71068 (1964) Ranger VI Mission Failure Investigation Report',
    ],
  },
};
