import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.61 — Program-as-suite: counted-completion form, satisfaction-plateau cadence.
 *
 * Generated by the v1.49.581 MUS Phase-C Wave-4 backfill (Slot W4-H).
 * Cross-references: NASA 1.61 (Lunar Orbiter 5, 5-of-5 program closure August 1, 1967),
 *                   ELC 1.61 (pending — comprehensive-mapping mission-class as ecological-survey form),
 *                   MUS 1.20 (Form-domain interrupted-closure complement),
 *                   MUS 1.62 (Form-domain closed-thesis complement).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const programAsSuite: RosettaConcept = {
  id: 'mus-1.61-program-as-suite-completed-arc',
  name: 'Program-as-suite: counted-completion form, satisfaction-plateau cadence',
  domain: 'music',
  description:
    'A music-theoretic primitive describing form whose closure is delivered by counted ' +
    'traversal at full success of a pre-budgeted finite ordered set of homogeneous instances. ' +
    'The cadential signature is the satisfaction-curve — a rising-then-plateauing perceptual ' +
    'trajectory that resolves when the count reaches the budget rather than when a descending ' +
    'line arrives at the tonic (the closed-thesis closure-form complement) or when a deceptive ' +
    'cadence is later resumed (the unfinished-cycle interrupted-closure complement). The form ' +
    'scales across phrase, song, song-cycle, multi-album arc, multi-flight space program, and ' +
    'multi-stage annual migration cycle. Canonical art-music exemplars: Bach Well-Tempered ' +
    'Clavier (24-key counted cycle, twice over for Books I and II), Goldberg Variations (30 ' +
    'variations bracketed by aria), Schubert Winterreise (24-song cycle), Bartók Mikrokosmos ' +
    '(153 graded studies). Death Cab for Cutie (Bellingham/WWU origin 1997, Barsuk + Atlantic + ' +
    'ANTI- multi-arc catalog 1998-2026, Walla-era seven-album sequence as a closed inner suite) ' +
    'is the canonical PNW indie-rock multi-arc-suite exemplar; the humpback whale (Megaptera ' +
    'novaeangliae, Borowski 1781; Payne & McVay 1971 hierarchical song analysis; Noad et al. ' +
    '2000 cultural revolution) furnishes the bioacoustic analog at both song-suite scale ' +
    '(themes traversed in fixed order, bout closes after a complete song) and migration-cycle ' +
    'scale (five-stage 4,000 km annual cycle). The Form-domain closure-mechanism triad is now ' +
    'complete: counted-completion (this concept), descending-line completion (closed-thesis ' +
    'complement), and deferred completion (unfinished-cycle complement) cover the principal ' +
    'closure-mechanism cases that musical and biological forms exhibit.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-song-form',
      description: 'Program-as-suite extends song-form to the multi-instance counted-traversal scale; the form is a finite ordered sequence of homogeneous song-form-class instances closed by counted completion at full success rather than by tonal-functional cadence',
    },
    {
      type: 'analogy',
      targetId: 'music-harmony',
      description: 'The cyclic Urlinie spanning all movements of a multi-movement work (Aldwell-Schachter §28; Schenker free-composition framework) is the harmonic-functional analog of the suite-cycle closure; program-as-suite lifts the same gesture to the band-catalog and program-flight scales where tonal-region traversal is no longer the binding constraint',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.62-album-as-thesis-closure-form',
      description: 'Form-domain complement: the closed-thesis exemplar achieves closure through descending-phrase cadence at every nested time-scale; program-as-suite achieves closure through counted-traversal-at-full-success. The two are structurally orthogonal closure mechanisms — the descending-line case requires a single tonic to arrive at; the counted-completion case requires a fixed cardinality to reach. Together they frame two of the three closure-mechanism classes in the Form domain.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.20-unfinished-cycle-interrupted-closure',
      description: 'Form-domain complement: the unfinished-cycle exemplar achieves closure through deferral and later resumption (deceptive cadence + multi-decade recovery narrative); program-as-suite achieves closure through pre-budgeted counted completion at full success — no deferral, no recovery, just the count having reached the budget. Together they frame two of the three closure-mechanism classes in the Form domain.',
    },
  ],
  metadata: {
    musDegree: '1.61',
    exemplars: {
      s36Artist: 'Death Cab for Cutie',
      s36Works: [
        'Walla-era seven-album sequence: Something About Airplanes (Barsuk SBR021, 1998), We Have the Facts and We\'re Voting Yes (Barsuk SBR026, 2000), The Photo Album (Barsuk SBR029, 2001), Transatlanticism (Barsuk SBR032, 2003, RIAA platinum), Plans (Atlantic 83834-2, 2005, RIAA platinum + Billboard 200 #4), Narrow Stairs (Atlantic 451995-2, 2008, Billboard 200 #1), Codes and Keys (Atlantic 525677-2, 2011), Kintsugi (Atlantic 547977-2, 2015, last Walla-produced)',
        'Atlantic Records arc: Plans (2005) through Kintsugi (2015) and beyond as a 22-year single-major-label arc closing with January 2026 ANTI- transition; I Built You a Tower (ANTI-, 2026 forthcoming) opens the next arc',
        'WWU origin (1997, Bellingham); Walla departure (September 2014); Dave Depper + Zac Rae permanent additions (2016); Jason McGerr drums (continuous since 2003)',
      ],
      spsSpecies: 'Humpback Whale (Megaptera novaeangliae, Borowski 1781) — first Balaenopteridae in the corpus',
      spsAcousticFeature: 'hierarchical male breeding-season song organised as themes → phrases → subphrases → units → subunits (Payne & McVay 1971 Science 173:585); a complete song traverses several themes in fixed order across 4-33 minutes; Hawaiian-recording bouts up to 7 hours of continuous repetition; frequency 100 Hz to 4 kHz dominant with harmonics to 24 kHz; source level up to 188 dB re 1 μPa at 1 m. North Pacific 4,000 km annual migration scaffolds a five-stage cycle: subarctic feed (Apr-Oct) → southbound transit (Oct-Nov) → tropical breed (Nov-Mar) → northbound transit (Mar-Apr) → return to feed. Each annual cycle is a counted-completed five-stage suite repeated across a 50-year individual lifespan. Noad et al. 2000 (Nature 408:537) east-Australian song revolution documents wholesale across-population song replacement in approximately 2 years (third cultural-transmission axis exemplar in 61-degree corpus after MUS 1.58 Bewick\'s Wren neighborhood scale + MUS 1.59 SRKW matriline scale; humpback extends to ocean-basin scale + rapid-revolution temporal mode).',
    },
    references: [
      'Aldwell, Schachter & Cadwallader, Harmony and Voice Leading (5e, Cengage 2011), §27 large-scale tonal closure; §28 fundamental structure / Urlinie at multi-movement scale',
      'Bach, J. S. (1722/1742), The Well-Tempered Clavier Book I BWV 846-869 and Book II BWV 870-893; Goldberg Variations BWV 988 (1741)',
      'Caplin, W. E. (1998), Classical Form: A Theory of Formal Functions for the Instrumental Music of Haydn, Mozart, and Beethoven (Oxford UP) — multi-movement classical-period suite as counted-completion form',
      'Cerchio, S., Jacobsen, J. K. & Norris, T. F. (2001), Temporal and geographical variation in songs of humpback whales: synchronous change in Hawaiian and Mexican breeding assemblages, Animal Behaviour 62: 313-329',
      'Hepokoski, J. & Darcy, W. (2006), Elements of Sonata Theory (Oxford UP), ch. 22 the rotation principle; cyclical-form treatment of the multi-movement work as a single closed structure',
      'Noad, M. J., Cato, D. H., Bryden, M. M., Jenner, M. N. & Jenner, K. C. S. (2000), Cultural revolution in whale songs, Nature 408: 537',
      'Payne, R. S. & McVay, S. (1971), Songs of humpback whales, Science 173(3997): 585-597',
      'Schubert, F. (1827), Winterreise D.911',
      'Suzuki, R., Buck, J. R. & Tyack, P. L. (2006), Information entropy of humpback whale songs, JASA 119(3): 1849-1866',
      'Tymoczko, D. (2011), A Geometry of Music (Oxford UP), ch. 9 multi-movement large-scale structure',
    ],
  },
};
