import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.20 — Unfinished cycle: form as interrupted closure, recovery as narrative continuation.
 *
 * Generated by the v1.49.581 MUS Phase-C Wave-3 backfill (Slot W3-C).
 * Cross-references: NASA 1.20 (Mercury-Redstone 4 / Liberty Bell 7 hatch failure + 1999 abyssal recovery),
 *                   ELC 1.20 (pending — Salish Sea dive-cycle ecology),
 *                   MUS 1.62 (polarity counterpart: closed-thesis closure-form).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const unfinishedCycle: RosettaConcept = {
  id: 'mus-1.20-unfinished-cycle-interrupted-closure',
  name: 'Unfinished cycle: form as interrupted closure, recovery as narrative continuation',
  domain: 'music',
  description:
    'A music-theoretic primitive describing form whose closure is structurally deferred ' +
    'across an interruption, where the interruption is part of the form rather than a defect ' +
    'of it. The deceptive authentic cadence (V→vi rather than V→I; Aldwell-Schachter §18) is ' +
    'the canonical phrase-level case; Hepokoski & Darcy (2006) ch. 11 deformations (non-resolving ' +
    'recapitulation, failed exposition, tonal interruption) generalize the same structure to ' +
    'sonata form; Caplin (1998) formal-function theory frames it as the discrete formal event ' +
    'of an interrupted-then-recovered cadential progression. The unfinished-cycle form scales ' +
    'across phrase, song, residency, catalog, mission, and species-cycle time-scales. The ' +
    'deliberate polarity counterpart of the closed-thesis form (MUS 1.62, album-as-thesis): ' +
    'where 1.62 closes its thesis with descending-phrase cadence and refusal of a third album, ' +
    '1.20 defers closure with deceptive cadence, residency-cycle catalog accumulation, and ' +
    'multi-decade deferred recovery (Liberty Bell 7\'s 1961-1999 narrative arc). Fly Moon Royale ' +
    '(Seattle Central District jazz/soul collective, 2012-present, self-released) is the canonical ' +
    'PNW open-form exemplar; the harbor seal mother-pup contact-call cycle across the dive-and-' +
    'resurface interval (Renouf 1985; Renouf & Diemand 1984) furnishes the bioacoustic analog ' +
    'of cyclical interruption-and-resumption.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-song-form',
      description: 'Unfinished-cycle form extends song-form to the residency/catalog scale by deferring closure across multi-bar, multi-song, and multi-release intervals; the form is the cycle of release-performance-re-release rather than a single closed sequence',
    },
    {
      type: 'analogy',
      targetId: 'music-harmony',
      description: 'The deceptive cadence (V→vi) that defers a phrase-level close is the harmonic-functional ground; unfinished-cycle form lifts the same deferral gesture across the song, residency, and catalog scales',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.62-album-as-thesis-closure-form',
      description: 'Polarity counterpart in domain 5: 1.62 catalogues the closed-thesis form (descending-phrase cadence, refusal of a third album); 1.20 catalogues the open unfinished-cycle form (deceptive cadence with recovery, residency-cycle accumulation, multi-decade deferred recovery). Together the two MUS Form-domain entries frame the closed/open polarity.',
    },
  ],
  metadata: {
    musDegree: '1.20',
    exemplars: {
      s36Artist: 'Fly Moon Royale',
      s36Works: [
        'Self-released EP-and-single sequence (2012-present), Seattle Central District collective',
        'Royal Room (Columbia City) residency recordings; Sea Monster Lounge (Wallingford) live sets',
        'Shared-personnel network with Maktub, Polyrhythmics, Whitney Menge (S36 rows 18, 20, 21)',
      ],
      spsSpecies: 'Pacific Harbor Seal (Phoca vitulina richardii) — second SPS appearance after MUS 1.60',
      spsAcousticFeature: 'mother-pup contact-call cycle across the air-water boundary during the 4-6 week lactation window: brief individually-distinct above-water calls (~250 ms, 200 Hz–2 kHz dominant, 3-5 calls per surfacing burst) alternating with 3-7 minute foraging-dive silent intervals; cyclical interruption-and-resumption architecture',
    },
    references: [
      'Aldwell, Schachter & Cadwallader, Harmony and Voice Leading (5e, Cengage 2011), §16 phrase rhythm; §18 deceptive cadence',
      'Caplin, W. E., Classical Form: A Theory of Formal Functions (Oxford UP, 1998), cadence taxonomy + formal-function theory',
      'Hepokoski, J. & Darcy, W., Elements of Sonata Theory (Oxford UP, 2006), ch. 11 deformations',
      'Lerdahl, F. & Jackendoff, R., A Generative Theory of Tonal Music (MIT, 1983), §3 grouping; §4 prolongational reduction',
      'Renouf, D. (1985), A demonstration of the ability of the harbour seal Phoca vitulina (L.) to discriminate among pup vocalizations, J. Exp. Mar. Biol. Ecol. 87: 41-46',
      'Renouf, D. & Diemand, D. (1984), Behavioural interactions between harbour seal mothers and pups during weaning, Behaviour 87: 50-71',
      'Bigg, M. A. (1981), Harbour seal — Phoca vitulina and P. largha, in Ridgway & Harrison eds. Handbook of Marine Mammals vol. 2',
      'Sabinsky, P. F. et al. (2017), Temporal and spatial variation in harbor seal roar calls, JASA 141(3): 1824-1834 — bout-temporal-structure framework',
    ],
  },
};
