/**
 * Bregman Projection -- mathematics concept (June-2026 arXiv cohort, T2).
 * @module departments/mathematics/concepts/bregman-projection
 */

import type { RosettaConcept } from '../../../rosetta-core/types.js';

const theta = 23 * 2 * Math.PI / 33;
const radius = 0.60;
const real = radius * Math.cos(theta);
const imaginary = radius * Math.sin(theta);

export const bregmanProjection: RosettaConcept = {
  id: "math-bregman-projection",
  name: "Bregman Projection",
  domain: 'mathematics',
  description:
    "The Bregman divergence generated by a strictly convex, differentiable potential phi is D_phi(x,y) = phi(x) - phi(y) - <grad phi(y), x - y>: the gap between phi and its first-order Taylor tangent at y, hence nonnegative and zero only when x=y, yet in general asymmetric. The Bregman projection of a reference point y onto a convex family C is the minimizer of this divergence over C -- the single convex-geometry operation this concept isolates. Because the divergence has two slots, projection comes as a dual pair: the m-projection minimizes D_phi(.,y) (mean/moment coordinates) and the e-projection minimizes D_phi(y,.) (natural coordinates), the two exchanged by the Legendre conjugate phi* whose gradient grad phi* inverts grad phi. A generalized Pythagorean theorem governs them: for the projection x* of y onto C and any z in C, D_phi(z,y) = D_phi(z,x*) + D_phi(x*,y) whenever C is flat. Bregman's original 1967 method is iterative: to project onto an intersection of convex constraint sets one cycles through them, taking a single Bregman projection onto each in turn, and the successive projections converge to the Bregman projection onto the whole intersection -- the alternating scheme behind Sinkhorn iteration, iterative proportional fitting, and POCS. Choosing phi = half||.||^2 recovers Euclidean least squares, whose divergence D_phi(x,y) = half||x - y||^2 is symmetric; phi = negative entropy recovers the Kullback-Leibler divergence sum_i x_i log(x_i / y_i), which is asymmetric -- on a two-point distribution D_phi(x,y) generally differs from D_phi(y,x), the very gap the m-/e-projection pair keeps track of. This makes maximum-entropy inference, GLM fitting, EM, and variational inference all instances of one projection (arXiv:2606.21714v1, 2026).",
  panels: new Map([
    ['python', {
      panelId: 'python',
      explanation: "In numpy the potential is a callable phi with gradient grad_phi; a Bregman divergence is one vectorized line D = phi(x) - phi(y) - grad_phi(y) @ (x - y), broadcast over a batch with np.einsum. An m-projection onto a linear set is scipy.optimize.minimize of D(x, y) with x on the affine hull; swapping phi for its Legendre conjugate gives the dual e-projection. A list comprehension over [half_sq, neg_entropy] tiles least-squares and KL as one code path. See Bregman 1967.",
    }],
    ['cpp', {
      panelId: 'cpp',
      explanation: "C++ keeps the reference point and iterates in a contiguous Eigen::VectorXd owned by an RAII Projection handle; the potential is a template parameter Phi exposing value() and grad(), so squared-norm or negative-entropy selects Euclidean or KL at compile time with no virtual dispatch. The divergence is one fused expression phi.value(x) - phi.value(y) - phi.grad(y).dot(x - y); the dual e-projection reinstantiates on ConjugatePhi. See Bregman 1967.",
    }],
    ['lisp', {
      panelId: 'lisp',
      explanation: "(bregman-divergence phi x y) expands to (- (phi x) (phi y) (dot (grad phi y) (- x y))) -- the divergence is literally the s-expression of phi minus its tangent. Homoiconicity lets (with-conjugate phi ...) rewrite an m-projection form into its dual e-projection at macro-expansion time by swapping phi for phi*, so Legendre duality is a symbolic transform, not a solver call. Maximum entropy is (project (neg-entropy) y moments). See Bregman 1967.",
    }],
  ]),
  relationships: [
    {
      type: "dependency",
      targetId: "mathematics-cramer-wold-slicing",
      description: "Bregman projection generalizes the project-onto-a-constraint operation Cramer-Wold slicing performs with linear subspaces: replace the Euclidean orthogonal projection with the minimizer of a Bregman divergence onto a distributional family, so directional slicing becomes divergence projection onto a flat",
    },
    {
      type: "dependency",
      targetId: "math-information-geometry",
      description: "The e-/m-projection dual pair and the generalized Pythagorean theorem are exactly the dually-flat structure of information geometry; this concept is the concrete divergence face of that umbrella, with KL as the canonical Bregman divergence of negative entropy",
    },
    {
      type: "analogy",
      targetId: "math-optimal-transport",
      description: "Two ways to project onto a family of probability measures: the Bregman/divergence projection driven by a convex potential, versus the optimal-transport projection driven by a ground-cost Wasserstein metric -- both minimize a discrepancy but with different geometries",
    },
    {
      type: "cross-reference",
      targetId: "math-exponential-decay",
      description: "The natural (e-) coordinates of a Bregman projection are the natural parameters of an exponential family, and the Legendre conjugate is its log-partition function; the exponential map is what links moment coordinates to natural coordinates",
    },
  ],
  complexPlanePosition: {
    real,
    imaginary,
    magnitude: Math.sqrt(real * real + imaginary * imaginary),
    angle: Math.atan2(imaginary, real),
  },
};
