/**
 * Cayley Graph Fourier Embedding -- mathematics concept (June-2026 arXiv cohort, T2).
 * @module departments/mathematics/concepts/cayley-graph-fourier-embedding
 */

import type { RosettaConcept } from '../../../rosetta-core/types.js';

const theta = 24 * 2 * Math.PI / 33;
const radius = 0.65;
const real = radius * Math.cos(theta);
const imaginary = radius * Math.sin(theta);

export const cayleyGraphFourierEmbedding: RosettaConcept = {
  id: "math-cayley-graph-fourier-embedding",
  name: "Cayley Graph Fourier Embedding",
  domain: 'mathematics',
  description:
    "Classical graph signal processing builds a graph Fourier transform from the eigenvectors of the Laplacian, but an arbitrary graph carries no group structure, so there is no genuine shift, no modulation, and the time-frequency duality of classical Fourier analysis breaks. The Cayley Graph Fourier Embedding (GE-GSP) repairs this by embedding a connected graph isometrically into a Cayley graph Cay(A,S) of a finitely generated abelian group A. Each edge is labeled by a generator, and consistency around every cycle forces the labeling to be a cocycle — a homomorphism from the cycle space into A. Solving these constraints over GF(2) or over Z, via the Smith normal form of the cycle-incidence matrix, recovers A and the embedding. On the ambient Cayley graph the characters of A (its Pontryagin dual) form an exact Fourier basis, translation by a group element is a true shift, modulation is pointwise multiplication by a character, and the convolution theorem and wavelet dilations hold exactly. Restricting to the embedded image transplants this rigorous harmonic analysis onto graph signals. (arXiv:2606.29391v1, 2026)",
  panels: new Map([
    ['python', {
      panelId: 'python',
      explanation: "Build the abelian group A once, then everything is FFT-shaped. Label edges as generator vectors, stack the cycle-incidence matrix C, and read A off its Smith normal form; characters are then just chi = np.exp(2j*np.pi * k[:,None]*x[None,:] / orders). The transform is chi @ f, convolution is elementwise in that basis (f_hat*g_hat) with an inverse transform back, and shifts are index rolls — no per-vertex loops, just a comprehension over generators. See Puschel & Moura 2008.",
    }],
    ['cpp', {
      panelId: 'cpp',
      explanation: "Model A as a compile-time GroupTraits<Rank, Torsion> so the character table is a template parameter. Store edge labels in a std::vector<std::array<int,Rank>>; assemble the cycle-incidence matrix as an Eigen::MatrixXi and factor it with an integer Smith-normal-form pass (RAII owns the scratch buffers). The transform is one contiguous Eigen::MatrixXcd multiply and convolution is an Eigen coefficient-wise product — cache-friendly, zero heap churn in the inner loop. See Puschel & Moura 2008.",
    }],
    ['lisp', {
      panelId: 'lisp',
      explanation: "Represent the group as symbolic data: '(abelian (Z 0) (Z/2 1) ...) is simultaneously the group and the program that builds its characters. Edge labels are s-expressions summed by recursive list processing; a cycle closes exactly when (reduce #'group+ labels) returns the identity. A defmacro expands the character basis at read time — code is data, so the Fourier operator is itself a manipulable list — and convolution is (mapcar #'* f-hat g-hat). See Puschel & Moura 2008.",
    }],
  ]),
  relationships: [
    {
      type: "dependency",
      targetId: "mathematics-tonnetz-lattice",
      description: "The Tonnetz is a concrete abelian Cayley graph — a lattice generated by the pitch-class intervals of thirds and fifths — on which group-character (DFT) analysis of harmony already lives; the embedding generalizes that setting, teaching an arbitrary graph to borrow exactly this lattice harmonic analysis.",
    },
    {
      type: "cross-reference",
      targetId: "math-dual-space-interpolation",
      description: "The Fourier basis here is the Pontryagin dual: the character group A-hat is the dual space of the abelian group A, so the graph Fourier transform is a duality pairing between vertex signals and characters, exactly the vertex/dual-space perspective.",
    },
    {
      type: "cross-reference",
      targetId: "math-transform-uncertainty-principle",
      description: "Because translation and modulation become genuine dual operations on the embedded Cayley graph, the classical time-frequency duality is restored, and graph signals now obey a real translation-modulation uncertainty principle rather than the broken spectral surrogate.",
    },
    {
      type: "analogy",
      targetId: "math-discrete-nodal-domains",
      description: "Standard spectral GSP reads structure from Laplacian eigenvector sign patterns (nodal domains); the Cayley embedding replaces that ad hoc basis with the group's character basis, so oscillation is indexed by dual-group frequency instead of by counted nodal regions.",
    },
  ],
  complexPlanePosition: {
    real,
    imaginary,
    magnitude: Math.sqrt(real * real + imaginary * imaginary),
    angle: Math.atan2(imaginary, real),
  },
};
