import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.29 — Matrilineal timbral signature: family-band orchestration as
 * identity-marker transmitted along a maternal lineage.
 *
 * Generated by the v1.49.581 MUS backfill fleet Wave 7 (W7-E).
 * Cross-references: NASA 1.29 (Mariner 2 — first successful interplanetary
 * spacecraft; two-channel microwave radiometer confirmed Venus 460 C
 * runaway-greenhouse), ELC 1.29 (pending; matrilineal-cultural transmission
 * of generational ecological knowledge as climate-scale analog).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const matrilinealTimbralSignature: RosettaConcept = {
  id: 'mus-1.29-matrilineal-timbral-signature',
  name: 'Matrilineal timbral signature: family-band orchestration as identity-marker transmitted along a maternal lineage',
  domain: 'music',
  description:
    'A music-theoretic primitive describing how a fixed orchestration recipe ' +
    'functions as a culturally-transmitted band-identity marker, with the ' +
    'recipe persisting across personnel turnover under the curation of a ' +
    'senior maternal-lineage anchor. Formally: ' +
    'Sig_band(f) = sum over slots of alpha_i * Spectrum_i(f), where the ' +
    'instrument-set { I_i } and mix-weights { alpha_i } persist while ' +
    'individual Spectrum_i (the actual performers) turn over. The Southern ' +
    'Resident Killer Whale (Orcinus orca) J/K/L pod community is the ' +
    'canonical bioacoustic exemplar: each pod maintains a distinct repertoire ' +
    'of 7-17 discrete pulsed-call types (Ford 1989 Can. J. Zool. 67(3):727-745; ' +
    'Ford 1991 Can. J. Zool. 69(6):1454-1483), culturally transmitted from ' +
    'matriarch to calf along the maternal lineage with both sexes exhibiting ' +
    'natal philopatry. Ray Charles + the Raelettes (Margie Hendrix 1958-1964; ' +
    'Mable John 1964-1976; Estella Yarbrough 1969-1985) is the canonical S36 ' +
    'studio-orchestra exemplar: the Charles signature is a fixed orchestration ' +
    'recipe (piano lead + tenor/baritone sax + Hammond B3 + Raelettes chorus + ' +
    'upright bass) and the Raelettes role-as-slot persisted across decades of ' +
    'personnel turnover, preserving the band identity even as individual ' +
    'performers were replaced. The signature is closure-marked by recipe ' +
    'persistence across personnel turnover, by a maternal-lineage curation ' +
    'channel, and by joint-reading distinguishability from competing band ' +
    'signatures at the same scale.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-instrument-families',
      description: 'The matrilineal-timbral-signature primitive depends on the instrument-family taxonomy: the band recipe is composed of slots filled by representatives from specific families (string, wind, brass, keyboard, voice, percussion). The recipe choice is the structural compositional move that builds on family-level instrumentation knowledge.',
    },
    {
      type: 'dependency',
      targetId: 'music-vocal-technique',
      description: "The Raelettes role within the recipe requires shared vocal-technique knowledge across successive Raelettes (call-and-response timing, blend-for-chorus voicing, gospel-derived inflection). Vocal-technique foundations are a prerequisite for the slot-as-inheritable-role framing.",
    },
    {
      type: 'analogy',
      targetId: 'music-acoustics',
      description: 'The band-signature-as-spectral-sum framing is the orchestration-scale generalization of single-instrument acoustic source-filter modeling. The acoustic primitive is the building block; the matrilineal-timbral-signature primitive is the ensemble-as-extended-source-filter-system. The two primitives compose hierarchically.',
    },
  ],
  metadata: {
    musDegree: '1.29',
    exemplars: {
      s36Artist: 'Ray Charles',
      s36Works: [
        'What\'d I Say (Atlantic single 2031, July 1959): canonical Atlantic-era exemplar of the Hendrix-led Raelettes call-and-response curation signal; Hot 100 #6, R&B #1',
        'Hit the Road Jack (ABC-Paramount single 10244, August 1961): Hendrix-anchored answering vocal as the song\'s structural premise; Hot 100 #1 for two weeks October 1961',
        'Modern Sounds in Country and Western Music vol. 1 (ABC-Paramount LP 410, March 1962): Hot 100 #1 for 14 weeks; the genre-fusion exemplar with the orchestration recipe doing the band-identity work over country source material; arrangements by Marty Paich + Gerald Wilson',
        'Genius + Soul = Jazz (ABC-Paramount LP S395, 1961): Quincy Jones / Gerald Wilson big-band charts; Charles + Count Basie Orchestra musicians + Raelettes recipe configuration',
      ],
      spsSpecies: 'Southern Resident Killer Whale (Orcinus orca, ecotype \'resident\', Salish Sea J/K/L pod community)',
      spsAcousticFeature: 'matriline-specific call dialects — each of the three pods (J, K, L) maintains a distinct repertoire of 7-17 discrete pulsed-call types (Ford 1989 Can. J. Zool. 67(3):727-745; Ford 1991 Can. J. Zool. 69(6):1454-1483); calves learn the natal-pod dialect from their mother and matrilineal relatives during the first 12-18 months of life (Yurk et al. 2002 Anim. Behav. 63(6):1103-1119); both sexes exhibit natal philopatry, remaining with the matriline for life. Pod identity is encoded in the call-set rather than in any single call. mtDNA correlates loosely with vocal repertoire across the North Pacific resident/transient/offshore split (Foote et al. 2010 Mol. Ecol. 19:5193-5198).',
    },
    references: [
      'Roads, C. (1996) The Computer Music Tutorial (MIT Press), Part II spectral analysis + Part III synthesis fundamentals on ensemble-as-spectral-sum',
      'Cogan, R. (1984) New Images of Musical Sound (Harvard UP), ch. 4 on ensemble-spectrum analysis',
      'Sethares, W. A. (2005) Tuning, Timbre, Spectrum, Scale (2e, Springer), ch. 4 on timbre as spectrum-conditioned percept',
      'Persichetti, V. (1961) Twentieth-Century Harmony (W. W. Norton), chs. 7-8 on orchestration as structural compositional element',
      'Ford, J. K. B. (1989) Acoustic behaviour of resident killer whales (Orcinus orca) off Vancouver Island, BC. Can. J. Zool. 67(3):727-745',
      'Ford, J. K. B. (1991) Vocal traditions among resident killer whales (Orcinus orca) in coastal waters of BC. Can. J. Zool. 69(6):1454-1483',
      'Foote et al. (2010) Genetic differentiation among North Pacific killer whale populations from broad-scale mtDNA. Mol. Ecol. 19:5193-5198',
      'Yurk et al. (2002) Cultural transmission within maternal lineages: vocal clans in resident killer whales in southern Alaska. Anim. Behav. 63(6):1103-1119',
      'Charles, R. & Ritz, D. (1978) Brother Ray: Ray Charles\' Own Story (Da Capo / Dial Press)',
      'Lydon, M. (1998) Ray Charles: Man and Music (Riverhead Books)',
    ],
  },
};
