/**
 * MeetingRecordGenerator — auto-generate markdown meeting records on bundle
 * commit and keep the per-decision Outcome lines updated as status events
 * arrive.
 *
 * Records live at `<recordsRoot>/M-{YYYY-MM-DD}-{NNNN}.md`. Static "what was
 * decided" sections (briefing, decisions header, discussion notes, deferred,
 * dismissed) are FROZEN after generation. Outcome lines are the ONLY dynamic
 * content (D-25-20). Any user-added content after the auto-generated footer is
 * preserved across all subsequent updates (D-25-21).
 *
 * Phase 825 / C11.
 *
 * Decisions honored: D-25-20..25, D-25-36.
 */

import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  Bundle,
  Decision,
  DecisionId,
  Finding,
  Meeting,
  MeetingId,
  Project,
  ProjectId,
  Briefing,
  BriefingId,
} from '../types.js';
import { atomicWriteFile } from '../emitter/staging.js';
import { renderTemplate } from '../emitter/template-render.js';

const here = dirname(fileURLToPath(import.meta.url));
const RECORD_TEMPLATE_PATH = join(here, 'templates', 'meeting-record.md.tmpl');

/** The auto-generated footer marks the boundary between auto + user content (D-25-21). */
const AUTO_FOOTER =
  '*This record was auto-generated by the Intelligence Dashboard.';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface RecordResult {
  meetingId: MeetingId;
  path: string;
  size: number;
}

export interface OutcomeUpdate {
  state: 'in_progress' | 'complete' | 'blocked' | 'failed';
  detail: string;
  result_path?: string;
  updated_at: string;
}

export interface RecordSummary {
  meetingId: MeetingId;
  path: string;
  started_at: string;
  committed_at: string;
  decisionCount: number;
  outcomesSummary: { complete: number; in_progress: number; blocked: number };
}

/** Subset of KB the meeting-record generator needs. */
export interface MeetingRecordKB {
  getMeeting(meetingId: MeetingId): Promise<Meeting | null>;
  getProject(p: ProjectId): Promise<Project | null>;
  getBriefing?(briefingId: BriefingId): Promise<Briefing | null>;
  getCurrentBriefing(p: ProjectId): Promise<Briefing | null>;
  /** All decisions for the meeting, including sent_now + bundled. */
  listAllDecisionsForMeeting?(meetingId: MeetingId): Promise<Decision[]>;
  /** Fallback for KBs that have only listDecisionsForMeeting. */
  listDecisionsForMeeting?(meetingId: MeetingId): Promise<Decision[]>;
  getBundleForMeeting?(meetingId: MeetingId): Promise<Bundle | null>;
  getMeetingLog?(
    meetingId: MeetingId,
  ): Promise<Array<{ kind: string; body: string; recorded_at: string }>>;
  getDecision(decisionId: DecisionId): Promise<Decision | null>;
  /**
   * Findings dismissed during this meeting (status=dismissed AND
   * addressed_by_decision is null). Optional; falls back to empty list.
   */
  getFindingsDismissedInMeeting?(
    meetingId: MeetingId,
  ): Promise<Finding[]>;
  /**
   * Resolve full Finding rows for the given IDs. (Used to render
   * source-finding labels in the decision section.)
   */
  getFindingsByIds?(ids: string[]): Promise<Finding[]>;
}

export interface MeetingRecordGeneratorOptions {
  kb: MeetingRecordKB;
  /** Directory where meeting records live (default: `.planning/intelligence/meetings/`). */
  recordsRoot: string;
  /** Optional now() injection for deterministic tests. */
  now?: () => Date;
}

// ─── MeetingRecordGenerator ──────────────────────────────────────────────────

export class MeetingRecordGenerator {
  private readonly kb: MeetingRecordKB;
  private readonly recordsRoot: string;
  private readonly now: () => Date;
  private readonly template: string;
  /**
   * Tracks the resolved record path per meeting id, so updateOutcome can find
   * the file even if the record path was computed via daily-sequence numbering
   * earlier and the directory state since changed.
   */
  private readonly recordPaths = new Map<string, string>();

  constructor(opts: MeetingRecordGeneratorOptions) {
    this.kb = opts.kb;
    this.recordsRoot = opts.recordsRoot;
    this.now = opts.now ?? (() => new Date());
    this.template = readFileSync(RECORD_TEMPLATE_PATH, 'utf8');
  }

  // ─── Public API ────────────────────────────────────────────────────────

  async generateOnCommit(meetingId: MeetingId): Promise<RecordResult | null> {
    const meeting = await this.kb.getMeeting(meetingId);
    if (!meeting) {
      throw new Error(`generateOnCommit: meeting ${meetingId} not found`);
    }
    const project = await this.kb.getProject(meeting.project_id);
    if (!project) {
      throw new Error(
        `generateOnCommit: project ${meeting.project_id} not found`,
      );
    }
    const decisions = await this.listAllDecisions(meetingId);

    // Empty bundle (no pending decisions at commit) → no record (PRD edge case)
    const bundled = decisions.filter(
      (d) => d.state === 'bundled' || d.state === 'sent_now',
    );
    if (bundled.length === 0) {
      return null;
    }

    const briefing = await this.resolveBriefing(meeting, project.id);
    const bundle = this.kb.getBundleForMeeting
      ? await this.kb.getBundleForMeeting(meetingId)
      : null;
    const log = this.kb.getMeetingLog ? await this.kb.getMeetingLog(meetingId) : [];
    const dismissed = this.kb.getFindingsDismissedInMeeting
      ? await this.kb.getFindingsDismissedInMeeting(meetingId)
      : [];

    // Compute path BEFORE rendering so the template can reference it.
    const recordPath = this.computeRecordPath(meeting);

    const rendered = await this.renderRecord({
      meeting,
      project,
      briefing,
      bundle,
      decisions: bundled,
      log,
      dismissed,
      recordPath,
    });

    atomicWriteFile(recordPath, rendered);
    this.recordPaths.set(meetingId, recordPath);
    return { meetingId, path: recordPath, size: rendered.length };
  }

  async updateOutcome(
    decisionId: DecisionId,
    outcome: OutcomeUpdate,
  ): Promise<void> {
    const decision = await this.kb.getDecision(decisionId);
    if (!decision) {
      // Status event for a decision that doesn't exist anywhere — log + ignore (PRD edge case)
      return;
    }
    const meeting = await this.kb.getMeeting(decision.meeting_id);
    if (!meeting) return; // Edge case: meeting evaporated

    const recordPath = await this.findRecordPath(meeting.id);
    if (!recordPath || !existsSync(recordPath)) {
      // Status event before record exists (out-of-order dispatch) — log + ignore.
      return;
    }
    const content = readFileSync(recordPath, 'utf8');
    const userAdditions = this.extractUserAdditions(content);
    const auto = this.stripUserAdditions(content);

    const sectionTitle = decision.ai_draft?.title ?? '(untitled)';
    const newOutcomeBlock = this.renderOutcomeBlock(outcome);

    const updated = this.replaceOutcomeAtSection(
      auto,
      sectionTitle,
      newOutcomeBlock,
    );
    const reattached = userAdditions ? `${updated}\n\n${userAdditions}` : updated;
    atomicWriteFile(recordPath, reattached);
  }

  async readRecord(meetingId: MeetingId): Promise<string> {
    const path = await this.findRecordPath(meetingId);
    if (!path || !existsSync(path)) {
      throw new Error(`readRecord: record for ${meetingId} not found`);
    }
    return readFileSync(path, 'utf8');
  }

  /**
   * List records for a project. Reads file HEADERS only (D-25-24); does not
   * load the full body. The header zone is the first ~30 lines.
   */
  async listRecords(projectId: ProjectId): Promise<RecordSummary[]> {
    if (!existsSync(this.recordsRoot)) return [];
    const out: RecordSummary[] = [];
    const entries = readdirSync(this.recordsRoot);
    for (const entry of entries) {
      if (!entry.startsWith('M-') || !entry.endsWith('.md')) continue;
      const full = join(this.recordsRoot, entry);
      const summary = this.summarizeRecord(full, projectId);
      if (summary) out.push(summary);
    }
    out.sort((a, b) => b.started_at.localeCompare(a.started_at));
    return out;
  }

  /**
   * Compute the path for a meeting record using daily-sequence numbering
   * (D-25-23). Format: `M-{YYYY-MM-DD}-{NNNN}.md`. Sequence resets per day.
   */
  computeRecordPath(meeting: Meeting): string {
    if (this.recordPaths.has(meeting.id)) {
      return this.recordPaths.get(meeting.id)!;
    }
    const date = (meeting.committed_at ?? meeting.started_at).slice(0, 10);
    const prefix = `M-${date}-`;
    let max = 0;
    if (existsSync(this.recordsRoot)) {
      for (const entry of readdirSync(this.recordsRoot)) {
        if (!entry.startsWith(prefix) || !entry.endsWith('.md')) continue;
        const m = /-(\d{4})\.md$/.exec(entry);
        if (m) {
          const n = parseInt(m[1], 10);
          if (n > max) max = n;
        }
      }
    }
    const seq = (max + 1).toString().padStart(4, '0');
    return join(this.recordsRoot, `${prefix}${seq}.md`);
  }

  // ─── Internal: rendering ───────────────────────────────────────────────

  private async renderRecord(args: {
    meeting: Meeting;
    project: Project;
    briefing: Briefing | null;
    bundle: Bundle | null;
    decisions: Decision[];
    log: Array<{ kind: string; body: string; recorded_at: string }>;
    dismissed: Finding[];
    recordPath: string;
  }): Promise<string> {
    const { meeting, project, briefing, bundle, decisions, log, dismissed } =
      args;

    // Sort decisions: in-bundle first by emission order (state=='bundled'),
    // then sent_now by emitted_at.
    const sorted = decisions.slice().sort((a, b) => {
      if (a.state === b.state) {
        return (a.emitted_at ?? '').localeCompare(b.emitted_at ?? '');
      }
      return a.state === 'sent_now' ? -1 : 1;
    });

    const findingIdsAcrossAll: string[] = [];
    for (const d of sorted) findingIdsAcrossAll.push(...d.source_findings);
    const findingsById = new Map<string, Finding>();
    if (this.kb.getFindingsByIds && findingIdsAcrossAll.length > 0) {
      const findings = await this.kb.getFindingsByIds(
        Array.from(new Set(findingIdsAcrossAll)),
      );
      for (const f of findings) findingsById.set(f.id, f);
    }

    const decisionEntries = sorted.map((d, i) => {
      const move = briefing?.suggested_moves.find(
        (m) => m.rank === d.source_move_rank,
      );
      const skill =
        d.kind === 'research_mission'
          ? 'research-mission-generator'
          : d.kind === 'analysis_run'
          ? 'analyze'
          : 'vision-to-mission';
      const speedHint = d.kind === 'research_mission' ? 'full' : 'fast';
      const crewProfile =
        d.kind === 'research_mission' ? 'squadron' : d.kind === 'vision_mission' ? 'patrol' : '';
      const findingsLabel =
        d.source_findings.length === 0
          ? 'none'
          : d.source_findings
              .map((id) => {
                const f = findingsById.get(id);
                return f ? `\`${id}\` (${f.kind})` : `\`${id}\``;
              })
              .join(', ');
      const modificationsLabel =
        d.developer_modifications.length === 0
          ? 'none'
          : d.developer_modifications.map((m) => `_${m}_`).join('; ');
      return {
        n: (i + 1).toString(),
        title: d.ai_draft?.title ?? '(untitled)',
        is_sent_now: d.state === 'sent_now',
        emitted_at: d.emitted_at ?? '',
        has_rank: d.source_move_rank != null,
        rank: d.source_move_rank ?? 0,
        ai_rationale:
          move?.rationale ?? d.ai_draft?.body?.slice(0, 80) ?? '(no rationale)',
        skill,
        speed_hint: speedHint,
        crew_profile: crewProfile,
        findings_label: findingsLabel,
        modifications_label: modificationsLabel,
      };
    });

    // Discussion notes: utterance + note kinds, in chronological order.
    const discussionNotes = log
      .filter((entry) => entry.kind === 'utterance' || entry.kind === 'note')
      .map((entry) => entry.body);

    // Deferred items: 'event' kind containing 'deferred' marker.
    const deferredItems = log
      .filter(
        (entry) =>
          entry.kind === 'event' &&
          entry.body.toLowerCase().includes('deferred'),
      )
      .map((entry) => entry.body);

    const dismissedItems = dismissed.map(
      (f) => `\`${f.id}\` (${f.kind}): ${f.dismissed_rationale ?? f.rationale}`,
    );

    // Bundle reference link
    const bundleRelativePath = bundle
      ? `../../staging/inbox/bundles/${bundle.id}.bundle.yaml`
      : '(no bundle)';

    const ctx: Record<string, unknown> = {
      meeting: {
        id: meeting.id,
        started_at: meeting.started_at,
        committed_at: meeting.committed_at ?? this.now().toISOString(),
        kb_snapshot: meeting.kb_snapshot,
      },
      project: {
        name: project.name,
      },
      bundle: {
        id: bundle?.id ?? meeting.id,
        relative_yaml_path: bundleRelativePath,
      },
      briefing: briefing
        ? { body: briefing.body, confidence: briefing.confidence }
        : null,
      decisions: decisionEntries,
      discussion_notes: discussionNotes,
      has_discussion: discussionNotes.length > 0,
      deferred_items: deferredItems,
      has_deferred: deferredItems.length > 0,
      dismissed_findings: dismissedItems,
      has_dismissed: dismissedItems.length > 0,
    };

    return renderTemplate(this.template, ctx);
  }

  // ─── Internal: helpers ─────────────────────────────────────────────────

  private async listAllDecisions(meetingId: MeetingId): Promise<Decision[]> {
    if (this.kb.listAllDecisionsForMeeting) {
      return this.kb.listAllDecisionsForMeeting(meetingId);
    }
    if (this.kb.listDecisionsForMeeting) {
      return this.kb.listDecisionsForMeeting(meetingId);
    }
    return [];
  }

  private async resolveBriefing(
    meeting: Meeting,
    projectId: ProjectId,
  ): Promise<Briefing | null> {
    if (!meeting.briefing_at_start) {
      return await this.kb.getCurrentBriefing(projectId);
    }
    if (this.kb.getBriefing) {
      return await this.kb.getBriefing(meeting.briefing_at_start);
    }
    return await this.kb.getCurrentBriefing(projectId);
  }

  private async findRecordPath(meetingId: MeetingId): Promise<string | null> {
    if (this.recordPaths.has(meetingId)) {
      const cached = this.recordPaths.get(meetingId)!;
      if (existsSync(cached)) return cached;
    }
    if (!existsSync(this.recordsRoot)) return null;
    // Scan directory for a record matching this meeting ID.
    // The meeting ID can appear in the file body (header) — read first ~30
    // lines and match.
    for (const entry of readdirSync(this.recordsRoot)) {
      if (!entry.startsWith('M-') || !entry.endsWith('.md')) continue;
      const path = join(this.recordsRoot, entry);
      try {
        const head = readFileSync(path, 'utf8').slice(0, 1500);
        if (head.includes(`Meeting ${meetingId}`)) {
          this.recordPaths.set(meetingId, path);
          return path;
        }
      } catch {
        // Ignore unreadable files
      }
    }
    return null;
  }

  /** Render a single outcome block (D-25-20 — only dynamic content). */
  private renderOutcomeBlock(outcome: OutcomeUpdate): string {
    const emoji =
      outcome.state === 'in_progress'
        ? '⏳'
        : outcome.state === 'complete'
        ? '✓'
        : outcome.state === 'blocked'
        ? '⚠'
        : '✗';
    const stateText = outcome.state.replace('_', ' ');
    const linkSuffix = outcome.result_path
      ? ` · [view result](${outcome.result_path})`
      : '';
    return [
      `- **Outcome:** ${emoji} ${stateText} · ${outcome.detail}`,
      `  *(Updated ${outcome.updated_at})*${linkSuffix}`,
    ].join('\n');
  }

  /** Replace the outcome block in the section identified by title. */
  private replaceOutcomeAtSection(
    content: string,
    sectionTitle: string,
    newOutcomeBlock: string,
  ): string {
    // Find the section heading. Title may appear with " *(sent now ...)*" or
    // " *(in bundle)*" suffix, so we anchor on the title prefix only.
    const headingPattern = new RegExp(
      `(### \\d+\\. ${escapeRegExp(sectionTitle)}[^\\n]*\\n)`,
      'g',
    );
    const m = headingPattern.exec(content);
    if (!m) {
      return content; // Section missing; silently ignore (PRD edge case)
    }
    const sectionStart = m.index + m[0].length;
    // Find the next `### ` or end-of-zone (---) — that's the section's end.
    const sectionEndRe = /\n(### |---\n)/;
    const after = content.slice(sectionStart);
    const endMatch = sectionEndRe.exec(after);
    const sectionEnd =
      endMatch === null ? content.length : sectionStart + endMatch.index;

    // Within [sectionStart, sectionEnd), find and replace the outcome block.
    const sectionBody = content.slice(sectionStart, sectionEnd);
    const outcomeBlockRe = /- \*\*Outcome:\*\* [^\n]+\n  \*\(Updated[^\n]*\)\*[^\n]*/;
    const outcomeMatch = outcomeBlockRe.exec(sectionBody);
    let newSectionBody: string;
    if (outcomeMatch) {
      newSectionBody =
        sectionBody.slice(0, outcomeMatch.index) +
        newOutcomeBlock +
        sectionBody.slice(outcomeMatch.index + outcomeMatch[0].length);
    } else {
      // Append outcome block at end of section if missing
      newSectionBody = sectionBody.trimEnd() + '\n' + newOutcomeBlock + '\n';
    }
    return (
      content.slice(0, sectionStart) +
      newSectionBody +
      content.slice(sectionEnd)
    );
  }

  /** Pull any user-added content after the auto-generated footer (D-25-21). */
  private extractUserAdditions(content: string): string | null {
    const idx = content.indexOf(AUTO_FOOTER);
    if (idx < 0) return null;
    // Find end-of-line of the footer's closing italic.
    const closeIdx = content.indexOf('*', idx + AUTO_FOOTER.length + 1);
    if (closeIdx < 0) return null;
    const after = content.slice(closeIdx + 1).trimStart();
    return after.length > 0 ? after : null;
  }

  /** Strip user additions, preserving the auto-generated footer. */
  private stripUserAdditions(content: string): string {
    const idx = content.indexOf(AUTO_FOOTER);
    if (idx < 0) return content;
    const closeIdx = content.indexOf('*', idx + AUTO_FOOTER.length + 1);
    if (closeIdx < 0) return content;
    return content.slice(0, closeIdx + 1).trimEnd() + '\n';
  }

  private summarizeRecord(
    path: string,
    _projectIdFilter: ProjectId,
  ): RecordSummary | null {
    // D-25-24 contract: read FILE HEADERS only (no full content load) for
    // performance. The header zone is ~1500 bytes which captures the meeting
    // id, started/committed timestamps, briefing summary, and bundle ref.
    //
    // Project filtering: the PRD's `listRecords(projectId)` signature implies
    // KB-side filtering; record files do NOT carry project IDs in their
    // headers (project name only). Callers therefore JOIN this list against
    // KB.listMeetings(projectId) to filter — this method emits all records
    // it discovers in the directory, in started_at-desc order.
    try {
      const fs = require('node:fs');
      const fd = fs.openSync(path, 'r');
      try {
        const buf = Buffer.alloc(1500);
        fs.readSync(fd, buf, 0, 1500, 0);
        const head = buf.toString('utf8');
        const idMatch = /^# Meeting (M-[^\s—]+)/.exec(head);
        if (!idMatch) return null;
        const meetingId = idMatch[1] as MeetingId;
        const startedMatch = /\*\*Started:\*\* (.+)/.exec(head);
        const committedMatch = /\*\*Committed:\*\* (.+)/.exec(head);

        // For outcome counts + decision count we need the body. Cap at 32 KiB
        // (typical record stays well under this) so listRecords stays cheap.
        const fileSize = statSync(path).size;
        const bodySize = Math.min(fileSize, 32 * 1024);
        const bodyBuf = Buffer.alloc(bodySize);
        fs.readSync(fd, bodyBuf, 0, bodySize, 0);
        const body = bodyBuf.toString('utf8');
        const counts = countOutcomes(body);
        const decisionCount = (body.match(/^### \d+\. /gm) ?? []).length;

        return {
          meetingId,
          path,
          started_at: startedMatch?.[1].trim() ?? '',
          committed_at: committedMatch?.[1].trim() ?? '',
          decisionCount,
          outcomesSummary: counts,
        };
      } finally {
        fs.closeSync(fd);
      }
    } catch {
      return null;
    }
  }
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function countOutcomes(content: string): {
  complete: number;
  in_progress: number;
  blocked: number;
} {
  return {
    complete: (content.match(/- \*\*Outcome:\*\* ✓ /g) ?? []).length,
    in_progress: (content.match(/- \*\*Outcome:\*\* ⏳ /g) ?? []).length,
    blocked: (content.match(/- \*\*Outcome:\*\* ⚠ /g) ?? []).length,
  };
}
