/**
 * Acoustics domain — Ch 1-3: physics of sound, hearing, psychoacoustics.
 */

import type { AudioConcept } from '../types.js';

export const physicsOfSoundConcepts: AudioConcept[] = [
  {
    id: 'overtone-series',
    name: 'Overtone Series',
    domain: 'acoustics',
    chapter: 1,
    summary: 'Natural harmonic frequencies above a fundamental tone at integer multiples',
    meshMapping: 'thresholds.json = timbre map — each threshold is a harmonic of the base quality signal',
    complexPlanePosition: { angle: 0.1, magnitude: 0.9 },
    relatedConcepts: ['standing-waves', 'resonance', 'frequency-response'],
    keywords: ['harmonics', 'partials', 'fundamental', 'overtones', 'timbre'],
  },
  {
    id: 'standing-waves',
    name: 'Standing Waves',
    domain: 'acoustics',
    chapter: 1,
    summary: 'Constructive and destructive interference patterns in enclosed spaces',
    meshMapping: 'mesh node resonance — nodes amplify or cancel signals based on network topology',
    complexPlanePosition: { angle: 0.2, magnitude: 0.85 },
    relatedConcepts: ['resonance', 'room-modes', 'overtone-series'],
    keywords: ['interference', 'nodes', 'antinodes', 'room-modes', 'wavelength'],
  },
  {
    id: 'resonance',
    name: 'Resonance',
    domain: 'acoustics',
    chapter: 1,
    summary: 'Frequency-specific amplification when driving frequency matches natural frequency',
    meshMapping: 'skill activation — skills resonate when context matches their activation patterns',
    complexPlanePosition: { angle: 0.3, magnitude: 0.95 },
    relatedConcepts: ['standing-waves', 'overtone-series', 'frequency-response'],
    keywords: ['natural-frequency', 'amplification', 'sympathetic', 'resonant'],
  },
  {
    id: 'frequency-response',
    name: 'Frequency Response',
    domain: 'acoustics',
    chapter: 1,
    summary: 'How a system amplifies or attenuates different frequencies across the spectrum',
    meshMapping: 'model capability profile — each model has different strengths across task types',
    complexPlanePosition: { angle: 0.15, magnitude: 0.8 },
    relatedConcepts: ['resonance', 'fletcher-munson', 'equalization'],
    keywords: ['spectrum', 'bandwidth', 'rolloff', 'flat-response', 'curve'],
  },
  {
    id: 'fletcher-munson',
    name: 'Fletcher-Munson Curves',
    domain: 'acoustics',
    chapter: 2,
    summary: 'Equal-loudness contours showing human hearing sensitivity varies with frequency and level',
    meshMapping: 'user perception bias — system quality perceived differently at different usage levels',
    complexPlanePosition: { angle: 0.5, magnitude: 0.7 },
    relatedConcepts: ['frequency-response', 'psychoacoustics', 'masking'],
    keywords: ['equal-loudness', 'iso-226', 'loudness', 'sensitivity', 'perception'],
  },
  {
    id: 'psychoacoustics',
    name: 'Psychoacoustics',
    domain: 'acoustics',
    chapter: 3,
    summary: 'Study of how the brain constructs sound perception from raw auditory signals',
    meshMapping: 'user experience layer — how users perceive system quality vs raw metrics',
    complexPlanePosition: { angle: 0.6, magnitude: 0.75 },
    relatedConcepts: ['fletcher-munson', 'masking', 'cocktail-party-effect'],
    keywords: ['perception', 'cognition', 'auditory-scene-analysis', 'brain'],
  },
  {
    id: 'masking',
    name: 'Masking',
    domain: 'acoustics',
    chapter: 3,
    summary: 'A louder sound rendering quieter sounds at nearby frequencies inaudible',
    meshMapping: 'priority routing — high-priority tasks mask lower-priority ones in the execution queue',
    complexPlanePosition: { angle: 0.4, magnitude: 0.65 },
    relatedConcepts: ['psychoacoustics', 'cocktail-party-effect', 'frequency-response'],
    keywords: ['simultaneous-masking', 'temporal-masking', 'threshold', 'inaudible'],
  },
  {
    id: 'cocktail-party-effect',
    name: 'Cocktail Party Effect',
    domain: 'acoustics',
    chapter: 3,
    summary: 'Ability to focus attention on a single voice in a noisy environment via auditory stream segregation',
    relatedConcepts: ['psychoacoustics', 'masking'],
    keywords: ['attention', 'stream-segregation', 'focus', 'noise'],
  },
];
