import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.14 — Storage time and minority-carrier diffusion as the small-signal
 * bit-rate ceiling: Pioneer 5 Digital Telebit germanium-NPN switching encoder
 * at 1/8/64/512 bps over the 36.2M km deep-space link.
 *
 * Generated by the v1.49.581 ELC Wave-5 fleet (Domain 2 second entry,
 * tube-Ge era).
 *
 * Cross-references: NASA 1.14 (Pioneer 5 Atlas-Able 4 deep-space probe
 * + Abe-Karp Telebit communications experiment), MUS 1.14 (sibling
 * structural-rhyme partner). Sibling Domain-2 entry: ELC 1.2 (Juno I
 * Sergeant igniter, h-parameter active-region rise tail).
 *
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const storageTimeBitRateLimit: RosettaConcept = {
  id: 'elc-1.14-storage-time-bit-rate-limit',
  name: 'Storage time as small-signal-derived bit-rate ceiling for saturating-switch BJTs',
  domain: 'electronics',
  description:
    'A small-signal-modelling primitive describing how the storage time t_s of a saturating-switch ' +
    'BJT — derived from the Ebers-Moll charge-control model as t_s = τ_S × ln((I_B1 - I_B2) / ' +
    '(I_B(EOS) - I_B2)), where τ_S = (τ_F + τ_R × β_F) / (1 + β_F) is the saturation effective ' +
    'time constant — sets the hard upper bound on the achievable bit rate of a keying topology: ' +
    'f_KEY(max) ≈ 1 / (4 × t_s). The storage time is fundamentally a small-signal-derived ' +
    'quantity: the parameters β_F, τ_F, τ_R that determine t_s come from the same Ebers-Moll ' +
    'model from which the active-region h-parameter box (h_fe, h_ie, h_oe) is extracted. ' +
    'Combined with cold-soak h_FE thermal derating (which can grow t_s by ~60% at -40 °C ' +
    'deep-space cold-soak by deepening β_forced for the same I_C), the storage time gives ' +
    'the design engineer a single small-signal-derivable inequality bounding the maximum bit ' +
    'rate of any saturating-switch topology in any thermal environment. The canonical 1960 ' +
    'flight exemplar is the Pioneer 5 Digital Telebit communications experiment encoder ' +
    '(Abe & Karp, STL, 1960), which keyed the spacecraft 401 MHz beacon at four uplink-' +
    'commanded bit rates (1, 8, 64, 512 bps) through a 2N1308-class germanium NPN switching ' +
    'transistor. The keying-transistor storage-time ceiling was approximately 1 MHz at room ' +
    'temperature with C_BS speed-up; the commanded 512 bps top rate sat ~2000× below the ' +
    'ceiling, and held DSN downlink lock to 36.2M km on 1960-06-26 — a slant-range record ' +
    'that stood until Mariner 2 in December 1962.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-transistor-amplifiers',
      description:
        'The Ebers-Moll charge-control model from which t_s is derived is the same model ' +
        'from which the active-region h-parameter box and the hybrid-π extraction come; the ' +
        'storage-time and the small-signal-active descriptions are two facets of one model.',
    },
    {
      type: 'dependency',
      targetId: 'elec-semiconductor-physics',
      description:
        'The forward-transit time τ_F is set by the base-region minority-carrier diffusion ' +
        'time τ_F ≈ W_B² / (2 × D_n) where W_B is base width and D_n is electron diffusion ' +
        'coefficient. The reverse-transit τ_R (longer than τ_F) sets the saturation-region ' +
        'storage. Both are pure semiconductor-physics quantities; their values shift between ' +
        'germanium (W_B = 5-10 µm, D_n = 99 cm²/s) and silicon (W_B = 1-2 µm, D_n = 36 cm²/s) ' +
        'producing the 5× modern-vs-era storage-time gap.',
    },
    {
      type: 'analogy',
      targetId: 'elc-1.2-small-signal-pyro-igniter',
      description:
        'Sibling Domain-2 entry. ELC 1.2 anchored the active-region rise tail of a single-shot ' +
        'pyrotechnic switch (h-parameter regime at the leading edge); ELC 1.14 anchors the ' +
        'storage tail of a continuous keying signal (Ebers-Moll regime at the falling edge). ' +
        'The two degrees together cover the complete small-signal-plus-Ebers-Moll description ' +
        'of a saturating-switch BJT.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.14-structural-rhyme-partner',
      description:
        'The bit-rate-ceiling-from-stored-energy pattern is the structural rhyme of how the ' +
        'inherent decay time of an instrument\'s voiced tone bounds the maximum musical-phrase ' +
        'rate that retains intelligibility. Both are operating-point models of how stored ' +
        'energy bounds the information-carrying rate of a signal; both expose hard limits ' +
        'derived from physical first principles that no amount of design effort can exceed.',
    },
  ],
  metadata: {
    elcDegree: '1.14',
    domain: 2,
    domainName: 'Small-signal models',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware:
      'Pioneer 5 (Pioneer Atlas-Able 4) Digital Telebit communications-experiment encoder — ' +
      '2N1308-class germanium NPN switching transistor (STL flight build) keying the 401 MHz ' +
      'coherent beacon at four uplink-commanded bit rates (1, 8, 64, 512 bps) — held DSN ' +
      'downlink lock to 36.2M km on 1960-06-26',
    keyEquation:
      't_s = τ_S × ln((I_B1 - I_B2) / (I_B(EOS) - I_B2)) ; τ_S = (τ_F + τ_R × β_F) / (1 + β_F) ; ' +
      'f_KEY(max) ≈ 1 / (4 × t_s) ; cold-soak: h_FE(-40°C) ≈ 0.5 × h_FE(25°C) for Ge NPNs',
    benchReplication: {
      activeDevice: '2N3904 (ON Semi) — silicon NPN general-purpose, h_fe=100-300, f_T=300 MHz, t_s≈50 ns',
      eraOriginal: '2N1308 (GE / Sylvania / Philco-Ford, 1958-1965) — germanium NPN, h_fe=70, f_T=40 MHz, t_s≈250 ns',
      keyingLineSubstitute: '1 kΩ wirewound + scope probe at q1_collector (no actual RF chain needed)',
      busSupply: '22 V bench DC supply at 1 A current limit (Rigol DP832A or equivalent)',
      driverInput: 'function generator with 50 ns rise/fall TTL pulse, 1 kHz repetition for storage-tail measurement',
      speedUpCap: '470 pF NPO/C0G ceramic across base-drive resistor (modern substitute for era-original polystyrene)',
    },
    references: [
      'Ebers, J.J., & Moll, J.L. (1954). Large-signal behavior of junction transistors. Proc. IRE 42(12), 1761-1772 — canonical Ebers-Moll derivation',
      'Abe, J.M., & Karp, R.M. (1960). The Telebit digital communications experiment for Pioneer V. Proc. IRE WESCON 4(5), 132-141',
      'GE Transistor Manual SC-12 (1965), p. 9 — 2N1308 germanium NPN switching-transistor specification + storage-time spec',
      'Sedra & Smith, Microelectronic Circuits (8e, Oxford 2020), ch. 6 (h-parameters) + ch. 14 (storage time)',
      'Gray, Hurst, Lewis, Meyer, Analysis and Design of Analog Integrated Circuits (5e, Wiley 2009), §1.4 + §1.7 — h-parameters and charge-control storage time',
      'Horowitz & Hill, The Art of Electronics (3e, Cambridge 2015), §2.1-§2.4 + §13.x — switching transients, Baker clamp, speed-up cap',
      'NASA TM-X-58 (1962) Space Technology Laboratories Pioneer Atlas-Able Final Report',
      'ON Semi 2N3904 datasheet, https://www.onsemi.com/pdf/datasheet/2n3904-d.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.22,
    imaginary: 0.28,
    magnitude: Math.sqrt(0.22 ** 2 + 0.28 ** 2),
    angle: Math.atan2(0.28, 0.22),
  },
};
