[display]
viewport=1280x720

[gource]
seconds-per-day=0.1
auto-skip-seconds=0.5
file-idle-time=0
highlight-users=true
hide=mouse,progress,filenames
camera-mode=overview
multi-sampling=false
bloom-multiplier=0.5
stop-at-end=true
output-framerate=30
