[display]
viewport=1920x1080

[gource]
seconds-per-day=1.0
auto-skip-seconds=1
file-idle-time=0
highlight-users=true
highlight-all-users=true
hide=mouse,progress
camera-mode=overview
multi-sampling=true
bloom-multiplier=1.2
bloom-intensity=0.8
user-scale=1.5
user-font-size=18
font-size=24
dir-font-size=14
filename-time=2.0
caption-size=22
caption-duration=6
caption-colour=FFFFFF
stop-at-end=true
output-framerate=60
key=true
