import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.47 — Target-side RCS degradation as effective noise contribution:
 * radar-equation noise budget for the Gemini 9A 'angry alligator' ATDA approach.
 *
 * Generated by the v1.49.581 ELC Wave-6 backfill.
 * Cross-references: NASA 1.47 (Gemini 9A 1966-06-03, Stafford / Cernan, ATDA
 * shroud failed to separate, docking impossible), MUS 1.47 (margin-collapse as
 * structural primitive — the SNR-margin gesture as the cross-track analog of
 * the multiplicative-budget invariance under term substitution).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md
 */
export const rcsNoiseRadarEquation: RosettaConcept = {
  id: 'elc-1.47-rcs-noise-radar-equation',
  name: 'Target-RCS-as-noise: Friis radar equation in SNR-budget form',
  domain: 'electronics',
  description:
    'A Domain-4 (Noise) primitive describing how the monostatic radar equation in its ' +
    'SNR-budget form admits term-substitution invariance: target-side terms (radar cross- ' +
    'section sigma) and receiver-side terms (system noise figure NF) sit in the same ' +
    'multiplicative chain, so degradation of one is indistinguishable at the integrator output ' +
    'from degradation of the other. Friis equation: SNR = P_TX * G_TX * G_RX * lambda^2 * sigma ' +
    '/ ((4*pi)^3 * r^4 * k_B * T_sys * B * L_other). The canonical flight exemplar is the ' +
    'Gemini 9A rendezvous-radar approach to the Augmented Target Docking Adapter on 1966-06-03 ' +
    "(Stafford / Cernan); the ATDA's protective shroud failed to separate (Cernan: 'looks like " +
    "an angry alligator'), degrading the effective coherent-return RCS from +13 dBsm clean-Agena " +
    'spec to +5 dBsm partially-deployed-shroud, propagating through the Westinghouse Ku-band ' +
    'radar SNR budget as exactly 8 dB of margin loss (14 dB nominal -> 6 dB observed). The ' +
    'pedagogical insight is that the angry alligator added no thermal energy to the receiver ' +
    "but stole 8 dB of SNR margin; the receiver could not tell the difference between the " +
    'target-side dropout and an equivalent receiver-side noise-figure increase.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-friis-transmission',
      description:
        'Target-RCS-as-noise depends on the Friis transmission equation as the foundational ' +
        'link-budget formula; spreading-loss-applied-twice gives the 1/r^4 monostatic range law, ' +
        'and the multiplicative chain of P_TX, G_TX, G_RX, lambda^2, sigma is the structural ' +
        'reason term-substitution invariance holds at the SNR-ratio level',
    },
    {
      type: 'dependency',
      targetId: 'elec-coherent-doppler-integration',
      description:
        'The coherent-Doppler integrator is the receiver-side process that turns instantaneous ' +
        'SNR into integrated SNR via process gain. Diffuse-scattering loss from a degraded ' +
        'target geometry (the angry-alligator shroud) cannot be recovered by coherent ' +
        'integration because the diffuse component is uncorrelated with the carrier reference',
    },
    {
      type: 'analogy',
      targetId: 'elc-1.6-strain-gauge-noise-budget',
      description:
        'ELC 1.6 covers the low-source-impedance corner of the Domain-4 noise-budget design ' +
        'space (350 ohm bridge -> voltage-noise-dominated). ELC 1.47 covers a third structural ' +
        'corner: target-side noise contribution. Both are noise budgets in the additive-dB ' +
        'sense but differ in where the noise enters the chain: ELC 1.6 at the source impedance, ' +
        'ELC 1.47 at the target reflection coefficient',
    },
    {
      type: 'analogy',
      targetId: 'elc-1.62-enc-cr-rc-shaping',
      description:
        'ELC 1.62 covers the high-source-impedance corner of the Domain-4 noise-budget design ' +
        'space (CSP summing node ~ 100 Mohm -> current-noise-dominated). ELC 1.47 extends the ' +
        'taxonomy to include a target-side contribution rather than a receiver-side one. The ' +
        'three Domain-4 entries (1.6, 1.62, 1.47) span low-Z source, high-Z source, and ' +
        'target-side corners of the design space',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.47-margin-collapse',
      description:
        'The SNR-margin collapse from 14 dB to 6 dB at the Gemini 9A approach is the structural ' +
        'rhyme of the dynamic-range-margin gesture MUS 1.47 catalogues: each is a margin gesture ' +
        'that resolves at a structurally weighted point — for the radar SNR budget, the dB ' +
        'margin at which the integrator can or cannot recover the carrier; for the musical ' +
        'gesture, the level at which the structural detail clears or fails to clear the ' +
        'masking floor',
    },
  ],
  metadata: {
    elcDegree: '1.47',
    domain: 4,
    domainName: 'Noise',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware: "Westinghouse Ku-band rendezvous radar (15.04 GHz uplink / 15.08 GHz downlink) interrogator + ATDA transponder pair (Gemini 9A 1966-06-03; ATDA shroud failed to separate, the 'angry alligator')",
    keyEquation: 'SNR = P_TX * G_TX * G_RX * lambda^2 * sigma / ((4*pi)^3 * r^4 * k_B * T_sys * B * L_other)',
    benchReplication: {
      activeCarrierSource: 'Texas Instruments LM7001 PLL synthesiser at 1 kHz (audio-band analog of 15 GHz Ku-band)',
      eraOriginal: 'Westinghouse cavity-stabilised reflex klystron + reflex multiplier (250 mW CW at 15.04 GHz)',
      activeLNA: 'OPA827 JFET-input op-amp cascade (4 nV/sqrt(Hz), 100 dB total gain)',
      eraOriginalLNA: 'Microwave Associates 1N23 point-contact mixer + 2N918 silicon planar IF strip',
      pathLossAttenuator: '5-position resistive divider (-60 dB nominal; sweepable -20/-40/-60/-80 dB to demonstrate 1/r^4 law)',
      rcsAnalog: '10-turn precision pot with DPDT switch — 1 kohm (clean Agena +13 dBsm) / 6.3 kohm (angry alligator +5 dBsm)',
      integrationTime: '1 ms coherent integrator (audio-band analog of 10 ms Ku-band)',
    },
    references: [
      'Skolnik, M.I. (1980). Introduction to Radar Systems (2e), McGraw-Hill — ch. 1 the radar equation; ch. 11 receivers and noise figure',
      'Knott, E.F., Shaeffer, J.F., & Tuley, M.T. (2004). Radar Cross Section (2e), SciTech — ch. 2 RCS concept; ch. 5 high-frequency RCS prediction',
      'Pozar, D.M. (2012). Microwave Engineering (4e), Wiley — ch. 14 noise figure cascade and Friis formula',
      'NASA (1966). Gemini Program Mission Report — Gemini IX-A, MSC-G-R-66-6 — flight events and post-flight ATDA shroud-failure analysis',
      'Hacker, B.C., & Grimwood, J.M. (1977). On the Shoulders of Titans: A History of Project Gemini, NASA SP-4203 — ch. 14 covers Gemini 9A in full',
      'Cernan, E., & Davis, D. (1999). The Last Man on the Moon, St. Martin\'s — first-hand description of the angry-alligator approach',
      'Westinghouse Electric Corporation (1966). Gemini Rendezvous Radar System — Final Report, NAS9-915',
      'TI LM7001 datasheet, https://www.ti.com/lit/ds/symlink/lm7001.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.47,
    imaginary: 0.66,
    magnitude: Math.sqrt(0.47 ** 2 + 0.66 ** 2),
    angle: Math.atan2(0.66, 0.47),
  },
};
