/**
 * Cross-domain end-to-end integration for combined cooling + power system design.
 * Wires power calculations into cooling load, producing a unified MEP package.
 *
 * INTEG-06 core requirement: The cooling load is DERIVED from the power calculation
 * output -- it is never a separate user input in combined mode. This validates that
 * cross-domain data flow works correctly.
 *
 * Pipeline:
 *   1. Power calculation (NEC 220 load, transformer sizing)
 *   2. Cross-domain thermal transfer (electrical losses -> cooling load)
 *   3. Cooling calculation (fluid systems, pipe sizing)
 *   4. Combined Safety Warden review (both electrical and fluid domains)
 *   5. Combined blueprint generation (SLD + P&ID)
 *
 * Physical Infrastructure Engineering Pack (v1.48)
 */
import type {
  InfrastructureRequest,
  BlueprintPackage,
  CalculationRecord,
  SafetyReviewResult,
  SafetyFinding,
  DrawingSpec,
  BillOfMaterials,
  TitleBlock,
  UnitValue,
} from '../types/infrastructure.js';

// ---------------------------------------------------------------------------
// PE Disclaimer (SC-01, SC-22) — embedded in every output path
// ---------------------------------------------------------------------------
const PE_DISCLAIMER = `ENGINEERING DISCLAIMER: This output was generated by an AI system ` +
  `and has NOT been reviewed or stamped by a licensed Professional Engineer (PE/P.Eng). ` +
  `All calculations, drawings, and specifications MUST be independently verified by a ` +
  `qualified, licensed PE before use in construction, installation, or operation.`;

/** Extended result type exposing the PE disclaimer as a dedicated field. */
export interface CombinedSystemDesignResult extends BlueprintPackage {
  peDisclaimer: string;
}

// ---------------------------------------------------------------------------
// Stage 1: Power calculation (NEC Article 220)
// ---------------------------------------------------------------------------
function calculatePower(request: InfrastructureRequest): CalculationRecord {
  const rackCount = request.constraints.rackCount ?? 1;
  const rackDensity = request.constraints.rackDensity_kW ?? 10;
  const pue = 1.2;
  const pf = 0.9;
  const voltage = parseInt(request.constraints.voltageClass ?? '480V');
  const itLoad_kW = rackCount * rackDensity;
  const totalElectrical_kW = itLoad_kW * pue;
  const loadCurrent_A = (totalElectrical_kW * 1000) / (Math.sqrt(3) * voltage * pf);
  const transformerKVA = totalElectrical_kW / pf;
  const stdSizes = [100, 167, 250, 333, 500, 750, 1000, 1500, 2000, 2500, 3000];
  const xfmrKVA = stdSizes.find(s => s >= transformerKVA) ?? transformerKVA;

  return {
    domain: 'power-systems',
    inputs: {
      rack_count: { value: rackCount, unit: 'racks' },
      rack_density_kW: { value: rackDensity, unit: 'kW' },
      voltage_class: { value: voltage, unit: 'V' },
      power_factor: { value: pf, unit: 'dimensionless' },
    },
    outputs: {
      it_load_kW: { value: itLoad_kW, unit: 'kW' },
      total_load_kW: { value: Math.round(totalElectrical_kW * 10) / 10, unit: 'kW' },
      load_current_A: { value: Math.round(loadCurrent_A * 10) / 10, unit: 'A' },
      transformer_kVA: { value: xfmrKVA, unit: 'kVA' },
    },
    method: 'NEC Article 220 + NEC Table 310.16',
    safetyMargin: 25,
  };
}

// ---------------------------------------------------------------------------
// Stage 2: Cross-domain thermal transfer (INTEG-06)
// ---------------------------------------------------------------------------
/**
 * Derive cooling load from electrical power dissipation.
 *
 * In a data center, all IT electrical power becomes heat in the server room.
 * Distribution losses (cable, transformer, UPS) add ~5% extra heat in electrical rooms.
 *
 * cooling_load_kW = it_load_kW + (total_electrical - it_load) * (1 + distribution_loss_factor)
 */
function deriveCoolingLoad(powerCalc: CalculationRecord): number {
  const itLoad_kW = powerCalc.outputs['it_load_kW']?.value ?? 0;
  const totalElectrical_kW = powerCalc.outputs['total_load_kW']?.value ?? 0;
  const distributionLossFactor = 0.05;
  return itLoad_kW + (totalElectrical_kW - itLoad_kW) * (1 + distributionLossFactor);
}

// ---------------------------------------------------------------------------
// Stage 3: Cooling calculation using derived thermal load
// ---------------------------------------------------------------------------
function calculateCooling(coolingLoad_kW: number): CalculationRecord {
  const rho = 998;   // kg/m3 water at 20 C
  const cp = 4182;   // J/(kg*K)
  const deltaT = 10; // C
  const flow_m3s = (coolingLoad_kW * 1000) / (rho * cp * deltaT);
  const flow_Ls = flow_m3s * 1000;

  const maxVelocity = 2.4; // m/s
  const area_m2 = flow_m3s / maxVelocity;
  const diam_m = Math.sqrt(4 * area_m2 / Math.PI);
  const diam_mm = diam_m * 1000;

  const npsTable = [
    { nps: 1.5, id_mm: 40.9 },
    { nps: 2, id_mm: 52.5 },
    { nps: 2.5, id_mm: 62.7 },
    { nps: 3, id_mm: 77.9 },
    { nps: 4, id_mm: 102.3 },
    { nps: 6, id_mm: 154.1 },
  ];
  const pipe = npsTable.find(p => p.id_mm >= diam_mm) ?? npsTable[npsTable.length - 1];

  return {
    domain: 'fluid-systems',
    inputs: {
      heat_load_kW: { value: Math.round(coolingLoad_kW * 10) / 10, unit: 'kW' },
      delta_T_C: { value: deltaT, unit: '\u00B0C' },
      max_velocity_ms: { value: maxVelocity, unit: 'm/s' },
      source: { value: 0, unit: 'derived from power-systems output' },
    },
    outputs: {
      flow_rate_Ls: { value: Math.round(flow_Ls * 100) / 100, unit: 'L/s' },
      pipe_size_NPS: { value: pipe.nps, unit: 'in' },
    },
    method: 'Darcy-Weisbach + ASHRAE TC 9.9 (cooling load from power-systems domain)',
    safetyMargin: 15,
  };
}

// ---------------------------------------------------------------------------
// Stage 4: Combined Safety Warden review (both domains)
// ---------------------------------------------------------------------------
function runCombinedSafetyReview(
  _calculations: CalculationRecord[],
  request: InfrastructureRequest,
): SafetyReviewResult {
  const findings: SafetyFinding[] = [];
  const voltage = parseInt(request.constraints.voltageClass ?? '480V');

  // SC-11: Arc flash warning for >= 480V (electrical domain)
  if (voltage >= 480) {
    findings.push({
      severity: 'warning',
      domain: 'voltage',
      description: 'Arc flash hazard - 480V three-phase, PPE Category 2',
      threshold: '8 cal/cm\u00B2',
      actualValue: `${voltage}V three-phase`,
      recommendation: 'Perform arc flash study per NFPA 70E',
      requiresHumanReview: false,
    });
  }

  // SC-10: PRV required for closed cooling loop (fluid domain)
  findings.push({
    severity: 'info',
    domain: 'pressure',
    description: 'Pressure relief valve required for closed cooling loop (SC-10)',
    threshold: 'ASME B31.3',
    actualValue: 'Closed loop cooling detected',
    recommendation: 'Install PRV at highest pressure point',
    requiresHumanReview: false,
  });

  // PE disclaimer as info-level finding
  findings.push({
    severity: 'info',
    domain: 'structural',
    description: PE_DISCLAIMER,
    threshold: 'N/A',
    actualValue: 'All outputs',
    recommendation: 'Have all outputs reviewed and stamped by a licensed Professional Engineer',
    requiresHumanReview: true,
  });

  const isGateMode =
    request.safetyClass === 'industrial' || request.safetyClass === 'data-center';
  const hasCritical = findings.some(
    f => f.severity === 'critical' || f.severity === 'blocking',
  );
  const status: SafetyReviewResult['status'] =
    hasCritical && isGateMode
      ? 'blocked'
      : findings.some(f => f.severity === 'warning')
        ? 'flagged'
        : 'passed';

  return {
    status,
    findings,
    reviewedBy: 'safety-warden',
    timestamp: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Stage 5: Combined blueprint generation (P&ID + SLD)
// ---------------------------------------------------------------------------
function generateCombinedBlueprints(
  calculations: CalculationRecord[],
  request: InfrastructureRequest,
): DrawingSpec[] {
  const drawings: DrawingSpec[] = [];

  if (!request.outputFormat.includes('blueprint')) return drawings;

  const fluidCalc = calculations.find(c => c.domain === 'fluid-systems');
  const powerCalc = calculations.find(c => c.domain === 'power-systems');
  const pipeNPS = fluidCalc?.outputs['pipe_size_NPS']?.value ?? 3;
  const voltage = parseInt(request.constraints.voltageClass ?? '480V');
  const xfmrKVA = powerCalc?.outputs['transformer_kVA']?.value ?? 1500;
  const dateStr = new Date().toISOString().split('T')[0];

  // P&ID for cooling system
  const pidTitleBlock: TitleBlock = {
    projectName: 'Combined MEP Design',
    drawingNumber: 'M-001',
    revision: '0',
    date: dateStr,
    drawnBy: 'architect-agent + draftsman-agent',
    scale: '1:50',
    sheet: '1 of 2',
  };

  drawings.push({
    type: 'P&ID',
    format: 'svg',
    scale: '1:50',
    revisionNumber: 0,
    titleBlock: pidTitleBlock,
    content: `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">
  <text x="10" y="20">P&amp;ID - COOLING SYSTEM NPS ${pipeNPS}"</text>
  <text x="10" y="580" font-size="8" fill="red">AI GENERATED - VERIFY WITH LICENSED PE BEFORE USE</text>
</svg>`,
  });

  // SLD for power distribution
  const sldTitleBlock: TitleBlock = {
    projectName: 'Combined MEP Design',
    drawingNumber: 'E-001',
    revision: '0',
    date: dateStr,
    drawnBy: 'architect-agent + draftsman-agent',
    scale: 'NTS',
    sheet: '2 of 2',
  };

  drawings.push({
    type: 'SLD',
    format: 'svg',
    scale: 'NTS',
    revisionNumber: 0,
    titleBlock: sldTitleBlock,
    content: `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">
  <text x="10" y="20">SLD - ${voltage}V / ${xfmrKVA}kVA</text>
  <text x="10" y="580" font-size="8" fill="red">AI GENERATED - VERIFY WITH LICENSED PE BEFORE USE</text>
</svg>`,
  });

  return drawings;
}

// ---------------------------------------------------------------------------
// Main pipeline: runCombinedSystemDesign
// ---------------------------------------------------------------------------

/**
 * Execute the combined cooling+power system design pipeline.
 *
 * INTEG-06: Power dissipation automatically drives cooling load calculation.
 * The cooling load is NEVER provided as a separate user input in combined mode.
 *
 * Stages: power calc -> thermal transfer -> cooling calc -> safety warden -> combined blueprints
 *
 * @param request - Infrastructure request with type='combined'
 * @returns Complete BlueprintPackage with combined drawings, calculations, BOM, and safety review
 */
export async function runCombinedSystemDesign(
  request: InfrastructureRequest,
): Promise<BlueprintPackage> {
  const calculations: CalculationRecord[] = [];

  // Stage 1: Power calculations first (drives cooling load)
  const powerCalc = calculatePower(request);
  calculations.push(powerCalc);

  // Stage 2: Cross-domain thermal transfer (INTEG-06 -- the critical link)
  const coolingLoad_kW = deriveCoolingLoad(powerCalc);

  // Stage 3: Cooling calculations using derived thermal load
  const fluidCalc = calculateCooling(coolingLoad_kW);
  calculations.push(fluidCalc);

  // Stage 4: Combined Safety Warden review (both domains)
  const safetyReview = runCombinedSafetyReview(calculations, request);

  // Stage 5: Combined blueprints (P&ID + SLD)
  const drawings = generateCombinedBlueprints(calculations, request);

  return {
    drawings,
    calculations,
    bom: { items: [], generatedAt: new Date().toISOString() },
    safetyReview,
  };
}
