/**
 * End-to-end integration wiring for cooling system design.
 * Connects architect -> calculator -> safety -> draftsman pipeline.
 *
 * Pipeline stages:
 *   1. Architect decomposition — parse request into cooling subsystem spec
 *   2. Calculator (fluid systems) — flow rate, pipe sizing via Darcy-Weisbach
 *   3. Safety Warden — pressure review, PRV requirements, PE disclaimer
 *   4. Draftsman — P&ID drawing + BOM generation
 *
 * Physical Infrastructure Engineering Pack (v1.48)
 */
import type {
  InfrastructureRequest,
  BlueprintPackage,
  CalculationRecord,
  SafetyReviewResult,
  SafetyFinding,
  DrawingSpec,
  BillOfMaterials,
  BomItem,
  TitleBlock,
  UnitValue,
} from '../types/infrastructure.js';

// ---------------------------------------------------------------------------
// PE Disclaimer (SC-01, SC-22) — embedded in every output path
// ---------------------------------------------------------------------------
const PE_DISCLAIMER = `ENGINEERING DISCLAIMER: This output was generated by an AI system ` +
  `and has NOT been reviewed or stamped by a licensed Professional Engineer (PE/P.Eng). ` +
  `All calculations, drawings, and specifications MUST be independently verified by a ` +
  `qualified, licensed PE before use in construction, installation, or operation.`;

// ---------------------------------------------------------------------------
// Internal types
// ---------------------------------------------------------------------------
interface CoolingSubsystemSpec {
  totalHeatLoad_kW: number;
  supplyTemp_C: number;
  returnTemp_C: number;
  deltaT_C: number;
  safetyClass: InfrastructureRequest['safetyClass'];
  outputFormat: InfrastructureRequest['outputFormat'];
}

/** Extended result type exposing the PE disclaimer as a dedicated field. */
export interface CoolingSystemDesignResult extends BlueprintPackage {
  peDisclaimer: string;
}

// ---------------------------------------------------------------------------
// Stage 1: Architect decomposition
// ---------------------------------------------------------------------------
function decomposeRequest(request: InfrastructureRequest): CoolingSubsystemSpec {
  const totalHeatLoad_kW =
    request.constraints.heatLoad_kW ??
    (request.constraints.rackCount ?? 1) * (request.constraints.rackDensity_kW ?? 10);

  return {
    totalHeatLoad_kW,
    supplyTemp_C: 18,   // ASHRAE TC 9.9 A2 class default
    returnTemp_C: 28,   // DeltaT = 10 C
    deltaT_C: 10,
    safetyClass: request.safetyClass,
    outputFormat: request.outputFormat,
  };
}

// ---------------------------------------------------------------------------
// Stage 2: Calculator — fluid systems + dimensional analysis
// ---------------------------------------------------------------------------
function calculateFluidSystem(spec: CoolingSubsystemSpec): CalculationRecord {
  // Flow rate: Q = P / (rho * Cp * DeltaT)
  // Water at 20 C: rho = 998 kg/m3, Cp = 4182 J/(kg*K)
  const rho = 998;
  const cp = 4182;
  const flow_m3s = (spec.totalHeatLoad_kW * 1000) / (rho * cp * spec.deltaT_C);
  const flow_Ls = flow_m3s * 1000;

  // Pipe sizing: velocity <= 2.4 m/s for ASHRAE TC 9.9 cooling water
  // A = Q/v; D = sqrt(4A/pi)
  const maxVelocity_ms = 2.4;
  const area_m2 = flow_m3s / maxVelocity_ms;
  const diameter_m = Math.sqrt((4 * area_m2) / Math.PI);
  const diameter_mm = diameter_m * 1000;

  // Select NPS (Nominal Pipe Size in inches, ID approximately)
  const npsTable = [
    { nps: 1.5, id_mm: 40.9 },
    { nps: 2, id_mm: 52.5 },
    { nps: 2.5, id_mm: 62.7 },
    { nps: 3, id_mm: 77.9 },
    { nps: 4, id_mm: 102.3 },
    { nps: 6, id_mm: 154.1 },
  ];
  const selected = npsTable.find(p => p.id_mm >= diameter_mm) ?? npsTable[npsTable.length - 1];

  return {
    domain: 'fluid-systems',
    inputs: {
      heat_load_kW: { value: spec.totalHeatLoad_kW, unit: 'kW' },
      delta_T_C: { value: spec.deltaT_C, unit: '\u00B0C' },
      max_velocity_ms: { value: maxVelocity_ms, unit: 'm/s' },
    },
    outputs: {
      flow_rate_Ls: { value: Math.round(flow_Ls * 100) / 100, unit: 'L/s' },
      flow_rate_m3s: { value: Math.round(flow_m3s * 10000) / 10000, unit: 'm\u00B3/s' },
      min_pipe_diameter_mm: { value: Math.round(diameter_mm * 10) / 10, unit: 'mm' },
      pipe_size_NPS: { value: selected.nps, unit: 'in' },
    },
    method: 'Darcy-Weisbach + ASHRAE TC 9.9',
    safetyMargin: 15,
  };
}

// ---------------------------------------------------------------------------
// Stage 3: Safety Warden review
// ---------------------------------------------------------------------------
function runSafetyReview(
  calculations: CalculationRecord[],
  request: InfrastructureRequest,
): SafetyReviewResult {
  const findings: SafetyFinding[] = [];
  const workingPressure_PSI =
    (request.constraints as Record<string, unknown>).workingPressure_PSI as number ?? 50;

  if (workingPressure_PSI > 300) {
    findings.push({
      severity: 'blocking',
      domain: 'pressure',
      description: 'Working pressure exceeds blocking threshold',
      threshold: '300 PSI max',
      actualValue: `${workingPressure_PSI} PSI`,
      recommendation: 'Redesign for lower working pressure or consult licensed PE',
      requiresHumanReview: true,
    });
  } else if (workingPressure_PSI > 150) {
    findings.push({
      severity: 'critical',
      domain: 'pressure',
      description: 'Working pressure in critical range',
      threshold: '150 PSI max (warning)',
      actualValue: `${workingPressure_PSI} PSI`,
      recommendation: 'Verify pipe class rating and add pressure relief valve',
      requiresHumanReview: true,
    });
  } else if (workingPressure_PSI > 80) {
    findings.push({
      severity: 'warning',
      domain: 'pressure',
      description: 'Elevated working pressure',
      threshold: '80 PSI threshold',
      actualValue: `${workingPressure_PSI} PSI`,
      recommendation: 'Verify pipe rating; include pressure relief valve',
      requiresHumanReview: false,
    });
  }

  // Always add PRV recommendation for closed systems (SC-10)
  findings.push({
    severity: 'info',
    domain: 'pressure',
    description: 'Pressure relief valve required for closed cooling system (SC-10)',
    threshold: 'N/A',
    actualValue: 'Closed loop system detected',
    recommendation: 'Install PRV per ASME B31.3 at highest pressure point',
    requiresHumanReview: false,
  });

  // PE disclaimer as info-level finding
  findings.push({
    severity: 'info',
    domain: 'structural',
    description: PE_DISCLAIMER,
    threshold: 'N/A',
    actualValue: 'All outputs',
    recommendation: 'Have all outputs reviewed and stamped by a licensed Professional Engineer',
    requiresHumanReview: true,
  });

  const blockingFindings = findings.filter(f => f.severity === 'blocking');
  const criticalFindings = findings.filter(
    f => f.severity === 'critical' || f.severity === 'blocking',
  );
  const isGateMode =
    request.safetyClass === 'industrial' || request.safetyClass === 'data-center';

  const status: SafetyReviewResult['status'] =
    blockingFindings.length > 0
      ? 'blocked'
      : criticalFindings.length > 0 && isGateMode
        ? 'blocked'
        : findings.some(f => f.severity !== 'info')
          ? 'flagged'
          : 'passed';

  return {
    status,
    findings,
    reviewedBy: 'safety-warden',
    timestamp: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Stage 4: Draftsman — blueprint generation
// ---------------------------------------------------------------------------
function generateBlueprint(
  calculations: CalculationRecord[],
  _safetyReview: SafetyReviewResult,
  request: InfrastructureRequest,
): { drawings: DrawingSpec[]; bom: BillOfMaterials } {
  const drawings: DrawingSpec[] = [];
  const bomItems: BomItem[] = [];

  if (request.outputFormat.includes('blueprint')) {
    const fluidCalc = calculations.find(c => c.domain === 'fluid-systems');
    const pipeNPS = fluidCalc?.outputs['pipe_size_NPS']?.value ?? 3;

    const titleBlock: TitleBlock = {
      projectName: 'Cooling System Design',
      drawingNumber: 'M-001',
      revision: '0',
      date: new Date().toISOString().split('T')[0],
      drawnBy: 'architect-agent + draftsman-agent',
      scale: '1:50',
      sheet: '1 of 1',
    };

    drawings.push({
      type: 'P&ID',
      format: 'svg',
      scale: '1:50',
      revisionNumber: 0,
      titleBlock,
      content: `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">
  <!-- ISA-5.1 P&ID: Cooling System ${request.constraints.rackCount ?? 1} Racks -->
  <text x="10" y="20" font-size="12">COOLING SYSTEM P&amp;ID - NPS ${pipeNPS}" SUPPLY/RETURN</text>
  <!-- PE Disclaimer embedded -->
  <text x="10" y="580" font-size="8" fill="red">AI GENERATED - VERIFY WITH LICENSED PE BEFORE USE</text>
</svg>`,
    });

    // Generate BOM from drawing content
    if (request.outputFormat.includes('construction')) {
      bomItems.push(
        {
          lineNumber: 1,
          description: `Carbon steel pipe NPS ${pipeNPS}"`,
          quantity: 1,
          unit: 'LOT',
          notes: 'ASTM A106 Grade B',
        },
        {
          lineNumber: 2,
          description: 'Gate valves',
          quantity: 4,
          unit: 'EA',
          notes: `NPS ${pipeNPS}", 150# class`,
        },
        {
          lineNumber: 3,
          description: 'Centrifugal pump',
          quantity: 2,
          unit: 'EA',
          notes: 'N+1 redundancy',
        },
        {
          lineNumber: 4,
          description: 'Pressure relief valve',
          quantity: 1,
          unit: 'EA',
          notes: 'Required by SC-10',
        },
      );
    }
  }

  return {
    drawings,
    bom: { items: bomItems, generatedAt: new Date().toISOString() },
  };
}

// ---------------------------------------------------------------------------
// Main pipeline: runCoolingSystemDesign
// ---------------------------------------------------------------------------

/**
 * Execute the full cooling system design pipeline.
 *
 * Stages: architect decomposition -> fluid calculator -> safety warden -> draftsman
 *
 * @param request - Infrastructure request with type='cooling'
 * @returns Complete BlueprintPackage with drawings, calculations, BOM, and safety review
 */
export async function runCoolingSystemDesign(
  request: InfrastructureRequest,
): Promise<BlueprintPackage> {
  // Stage 1: Architect decomposition
  const spec = decomposeRequest(request);

  // Stage 2: Calculator
  const fluidCalc = calculateFluidSystem(spec);
  const calculations = [fluidCalc];

  // Stage 3: Safety Warden (mandatory gate)
  const safetyReview = runSafetyReview(calculations, request);

  // Stage 4: Draftsman (blueprint generation)
  const { drawings, bom } = generateBlueprint(calculations, safetyReview, request);

  return { drawings, calculations, bom, safetyReview };
}
