/**
 * End-to-end integration wiring for power distribution design.
 * Connects architect -> calculator -> safety -> draftsman pipeline for power systems.
 *
 * Pipeline stages:
 *   1. NEC Article 220 load calculation (IT load, PUE, transformer sizing)
 *   2. NEC 690 Solar PV sizing (optional, when solarAvailable_m2 provided)
 *   3. BESS sizing (optional, when batteryRuntime_min provided)
 *   4. Safety Warden — arc flash (SC-11), rapid shutdown (SC-12), BESS thermal (SC-16)
 *   5. Draftsman — SLD (Single Line Diagram) generation
 *
 * Physical Infrastructure Engineering Pack (v1.48)
 */
import type {
  InfrastructureRequest,
  BlueprintPackage,
  CalculationRecord,
  SafetyReviewResult,
  SafetyFinding,
  DrawingSpec,
  BillOfMaterials,
  TitleBlock,
  UnitValue,
} from '../types/infrastructure.js';

// ---------------------------------------------------------------------------
// PE Disclaimer (SC-01, SC-22) — embedded in every output path
// ---------------------------------------------------------------------------
const PE_DISCLAIMER = `ENGINEERING DISCLAIMER: This output was generated by an AI system ` +
  `and has NOT been reviewed or stamped by a licensed Professional Engineer (PE/P.Eng). ` +
  `All calculations, drawings, and specifications MUST be independently verified by a ` +
  `qualified, licensed PE before use in construction, installation, or operation.`;

/** Extended result type exposing the PE disclaimer as a dedicated field. */
export interface PowerDistributionDesignResult extends BlueprintPackage {
  peDisclaimer: string;
}

// ---------------------------------------------------------------------------
// Stage 1: NEC Article 220 load calculation
// ---------------------------------------------------------------------------
function calculateITLoad(request: InfrastructureRequest): CalculationRecord {
  const rackCount = request.constraints.rackCount ?? 1;
  const rackDensity_kW = request.constraints.rackDensity_kW ?? 10;
  const pue = 1.2; // Default PUE for N+1 data center
  const itLoad_kW = rackCount * rackDensity_kW;
  const totalLoad_kW = itLoad_kW * pue;
  const voltageClass = request.constraints.voltageClass ?? '480V';
  const voltage = parseInt(voltageClass);
  const pf = 0.9;
  // I = P / (sqrt(3) * V * PF) for 3-phase
  const current_A = (totalLoad_kW * 1000) / (Math.sqrt(3) * voltage * pf);
  const kVA = totalLoad_kW / pf;
  // Next standard transformer size
  const standardSizes = [100, 167, 250, 333, 500, 750, 1000, 1500, 2000, 2500, 3000];
  const transformerKVA = standardSizes.find(s => s >= kVA) ?? kVA;

  return {
    domain: 'power-systems',
    inputs: {
      rack_count: { value: rackCount, unit: 'racks' },
      rack_density_kW: { value: rackDensity_kW, unit: 'kW' },
      voltage_class: { value: voltage, unit: 'V' },
      power_factor: { value: pf, unit: 'dimensionless' },
    },
    outputs: {
      it_load_kW: { value: itLoad_kW, unit: 'kW' },
      total_load_kW: { value: Math.round(totalLoad_kW * 10) / 10, unit: 'kW' },
      load_current_A: { value: Math.round(current_A * 10) / 10, unit: 'A' },
      transformer_kVA: { value: transformerKVA, unit: 'kVA' },
    },
    method: 'NEC Article 220 + NEC Table 310.16',
    safetyMargin: 25,
  };
}

// ---------------------------------------------------------------------------
// Stage 2: Solar PV sizing (NEC 690)
// ---------------------------------------------------------------------------
function calculateSolar(request: InfrastructureRequest): CalculationRecord | null {
  if (!request.constraints.solarAvailable_m2 && !request.constraints.batteryRuntime_min) {
    return null;
  }
  if (!request.constraints.solarAvailable_m2) return null;

  // Target: annual production for NEC 690.7 sizing
  const targetEnergy_kWh_yr =
    (request.constraints.powerBudget_kW ?? 1000) * 8760 * 0.3; // 30% solar fraction
  const psh = 5.5; // Peak sun hours
  const systemEff = 0.80;
  const solar_kWp = targetEnergy_kWh_yr / (psh * 365 * systemEff);

  return {
    domain: 'power-systems-solar',
    inputs: {
      target_energy_kWh_yr: { value: Math.round(targetEnergy_kWh_yr), unit: 'kWh/yr' },
      peak_sun_hours: { value: psh, unit: 'h/day' },
      system_efficiency: { value: systemEff, unit: 'dimensionless' },
    },
    outputs: {
      solar_kWp: { value: Math.round(solar_kWp * 10) / 10, unit: 'kWp' },
    },
    method: 'NEC Article 690 PV sizing',
    safetyMargin: 10,
  };
}

// ---------------------------------------------------------------------------
// Stage 3: BESS sizing
// ---------------------------------------------------------------------------
function calculateBESS(request: InfrastructureRequest): CalculationRecord | null {
  const runtime_min = request.constraints.batteryRuntime_min;
  if (!runtime_min) return null;

  const load_kW = request.constraints.powerBudget_kW ?? 500;
  const dod = 0.85;
  const roundtripEff = 0.90;
  const energy_kWh = (load_kW * runtime_min / 60) / (dod * roundtripEff);

  return {
    domain: 'power-systems-bess',
    inputs: {
      load_kW: { value: load_kW, unit: 'kW' },
      runtime_min: { value: runtime_min, unit: 'min' },
      depth_of_discharge: { value: dod, unit: 'dimensionless' },
      roundtrip_efficiency: { value: roundtripEff, unit: 'dimensionless' },
    },
    outputs: {
      bess_capacity_kWh: { value: Math.round(energy_kWh * 10) / 10, unit: 'kWh' },
    },
    method: 'BESS sizing: E = P*t / (DoD * eta_rt)',
    safetyMargin: 20,
  };
}

// ---------------------------------------------------------------------------
// Stage 4: Safety Warden — power-specific review
// ---------------------------------------------------------------------------
function runPowerSafetyReview(
  calculations: CalculationRecord[],
  request: InfrastructureRequest,
): SafetyReviewResult {
  const findings: SafetyFinding[] = [];
  const voltage = parseInt(request.constraints.voltageClass ?? '480V');
  const hasSolar = calculations.some(c => c.domain === 'power-systems-solar');
  const hasBESS = calculations.some(c => c.domain === 'power-systems-bess');

  // SC-11: Arc flash warning on 480V 3-phase
  if (voltage >= 480) {
    findings.push({
      severity: 'warning',
      domain: 'voltage',
      description: 'Arc flash hazard at 480V three-phase - PPE Category 2 minimum',
      threshold: '8 cal/cm\u00B2 boundary',
      actualValue: '480V three-phase system',
      recommendation:
        'Perform arc flash study per NFPA 70E. Minimum PPE Category 2 (8 cal/cm\u00B2).',
      requiresHumanReview: false,
    });
  }

  // SC-12: NEC 690.12 rapid shutdown for solar
  if (hasSolar) {
    findings.push({
      severity: 'info',
      domain: 'voltage',
      description: 'NEC 690.12 Rapid Shutdown System required for rooftop PV',
      threshold: 'NEC 690.12 - 30V/240VA within 30s',
      actualValue: 'Solar PV system detected',
      recommendation:
        'Install NEC 690.12 compliant rapid shutdown device. Label PV DC conductors.',
      requiresHumanReview: false,
    });
  }

  // SC-16: BESS thermal management + NFPA 855
  if (hasBESS) {
    findings.push({
      severity: 'info',
      domain: 'temperature',
      description:
        'Lithium battery BESS requires thermal management per NFPA 855',
      threshold: 'NFPA 855 - maximum installation size and setbacks',
      actualValue: 'Li-ion BESS detected',
      recommendation:
        'Design thermal management system. Reference NFPA 855 for indoor energy storage limits.',
      requiresHumanReview: false,
    });
  }

  // PE disclaimer as info-level finding
  findings.push({
    severity: 'info',
    domain: 'structural',
    description: PE_DISCLAIMER,
    threshold: 'N/A',
    actualValue: 'All outputs',
    recommendation: 'Have all outputs reviewed and stamped by a licensed Professional Engineer',
    requiresHumanReview: true,
  });

  const criticalOrBlocking = findings.filter(
    f => f.severity === 'critical' || f.severity === 'blocking',
  );
  const isGateMode =
    request.safetyClass === 'industrial' || request.safetyClass === 'data-center';
  const status: SafetyReviewResult['status'] =
    criticalOrBlocking.length > 0 && isGateMode
      ? 'blocked'
      : findings.some(f => f.severity === 'warning' || f.severity === 'critical')
        ? 'flagged'
        : 'passed';

  return {
    status,
    findings,
    reviewedBy: 'safety-warden',
    timestamp: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Stage 5: Draftsman — SLD generation
// ---------------------------------------------------------------------------
function generateSLD(
  calculations: CalculationRecord[],
  _safetyReview: SafetyReviewResult,
  request: InfrastructureRequest,
): { drawings: DrawingSpec[]; bom: BillOfMaterials } {
  const drawings: DrawingSpec[] = [];

  if (request.outputFormat.includes('blueprint')) {
    const powerCalc = calculations.find(c => c.domain === 'power-systems');
    const voltage = parseInt(request.constraints.voltageClass ?? '480V');
    const transformerKVA = powerCalc?.outputs['transformer_kVA']?.value ?? 1500;

    const titleBlock: TitleBlock = {
      projectName: 'Power Distribution Design',
      drawingNumber: 'E-001',
      revision: '0',
      date: new Date().toISOString().split('T')[0],
      drawnBy: 'architect-agent + draftsman-agent',
      scale: 'NTS',
      sheet: '1 of 1',
    };

    drawings.push({
      type: 'SLD',
      format: 'svg',
      scale: 'NTS',
      revisionNumber: 0,
      titleBlock,
      content: `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">
  <!-- IEEE SLD: Power Distribution ${voltage}V / ${transformerKVA}kVA Transformer -->
  <text x="10" y="20">SINGLE LINE DIAGRAM - ${voltage}V, ${transformerKVA}kVA XFMR</text>
  <text x="10" y="580" font-size="8" fill="red">AI GENERATED - VERIFY WITH LICENSED PE BEFORE USE</text>
</svg>`,
    });
  }

  return {
    drawings,
    bom: { items: [], generatedAt: new Date().toISOString() },
  };
}

// ---------------------------------------------------------------------------
// Main pipeline: runPowerDistributionDesign
// ---------------------------------------------------------------------------

/**
 * Execute the full power distribution design pipeline.
 *
 * Stages: NEC 220 load calc -> solar PV -> BESS -> safety warden -> SLD draftsman
 *
 * @param request - Infrastructure request with type='power'
 * @returns Complete BlueprintPackage with drawings, calculations, BOM, and safety review
 */
export async function runPowerDistributionDesign(
  request: InfrastructureRequest,
): Promise<BlueprintPackage> {
  const calculations: CalculationRecord[] = [];

  // Stage 1: NEC Article 220 load calculation
  calculations.push(calculateITLoad(request));

  // Stage 2: Solar PV (optional)
  const solar = calculateSolar(request);
  if (solar) calculations.push(solar);

  // Stage 3: BESS (optional)
  const bess = calculateBESS(request);
  if (bess) calculations.push(bess);

  // Stage 4: Safety Warden (mandatory gate)
  const safetyReview = runPowerSafetyReview(calculations, request);

  // Stage 5: Draftsman (SLD generation)
  const { drawings, bom } = generateSLD(calculations, safetyReview, request);

  return { drawings, calculations, bom, safetyReview };
}
