/**
 * SCRIBE-recommended SVGO configuration — T2 cartridge thin wrapper.
 *
 * Canonical source: src/scribe/svg-validator/svgo-config.ts
 *   createSvgoConfig({ preserveRoundTrip: false })
 *
 * This config is the T2 a11y-baseline config (no round-trip protections).
 * It preserves role/aria-*/title/desc/viewBox and prevents destructive path
 * transformations, while allowing safe size reductions.
 *
 * Run via: npx svgo --config validators/svgo.config.js input.svg -o output.svg
 *
 * Substrate invariants (NEVER modify these — Component 09 conformance test
 * asserts they are opt-out):
 *   removeTitle: false
 *   removeDesc: false
 *   removeMetadata: false
 *
 * See a11y-checklist.md for the full discipline this config supports.
 *
 * Component 03 sync'd-copy approach:
 *   Canonical config is generated by createSvgoConfig({ preserveRoundTrip: false })
 *   in src/scribe/svg-validator/svgo-config.ts. This file is the static export
 *   of that config for environments where the TypeScript source cannot be run.
 *
 * Mission: SCRIBE (v1.49.621), Component 03.
 */

module.exports = {
  multipass: true,
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          // Never remove viewBox; required for resolution-independent rendering.
          removeViewBox: false,
          // SUBSTRATE INVARIANT: Never remove title/desc/metadata.
          removeTitle: false,
          removeDesc: false,
          removeMetadata: false,
          // Keep the document XML declaration in standalone files.
          removeXMLProcInstruction: false,
          // Don't collapse groups when they carry semantic role / aria-label.
          collapseGroups: false,
          // Don't merge or simplify paths; the SCRIBE author has authored the
          // path shape deliberately and downstream tooling may inspect command structure.
          mergePaths: false,
          convertShapeToPath: false,
        },
      },
    },
    // Explicitly preserve aria-* attributes; some SVGO versions need this
    // even with overrides on preset-default.
    {
      name: 'removeAttrs',
      params: {
        attrs: '(class:none)', // no-op pattern — preserveAttrs is the active constraint
        preserveAttrs: ['aria-.*', 'role', 'tabindex'],
      },
    },
  ],
};
