import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.37 — Bent-string blue-third microtonality: continuous-pitch ornamentation,
 * mechanically-produced microtonal events, and the compressed-pitch-arc.
 *
 * Generated by the v1.49.581 MUS wave-6 backfill (W6-H fleet slot).
 * Cross-references: NASA 1.37 (Ranger 8 Sea of Tranquility imaging), ELC 1.37 (pending).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const bentStringBlueThirdMicrotonality: RosettaConcept = {
  id: 'mus-1.37-bent-string-blue-third-microtonality',
  name: 'Bent-string blue-third microtonality: continuous-pitch ornamentation, mechanically-produced microtonal events, and the compressed-pitch-arc',
  domain: 'music',
  description:
    'A music-theoretic primitive describing microtonal pitch as a continuous arc through a region between equal-tempered grid points, expressed as a brief moment-of-attack pitch event whose perceptual identity depends on the arc itself rather than on a held centroid. The blue-third in the electric-blues idiom — typically bent up from the minor third (300 ¢) toward but not reaching the major third (400 ¢), centred on a ~50-cent-flat-of-major-third blue-third region per Titon 1994 and Weisethaunet 2001 — is the canonical human-music exemplar; Jimi Hendrix\'s 1962-1966 R&B sideman period (Curtis Knight & the Squires, Isley Brothers, Little Richard, King Curtis) furnishes the documented apprentice form before post-1966 amplification overtones obscured the microtonal detail. Anna\'s Hummingbird (Calypte anna) display-dive tail-feather chirp (~4 kHz at ~83 dB SPL during 27 m/s vertical dive; Clark & Feo 2008 Proc. Roy. Soc. B 275:955-962) is the canonical mechanically-produced exemplar: pitch is set by aerodynamic flutter of the spread outer rectrix R5 rather than by syringeal vocalisation, demonstrating that microtonal-arc events can be produced by physical-resonance mechanisms equivalent to the bent-string\'s tension-and-length mechanics. The closure condition is not single-pitch correctness but arc-shape consistency: the system is closed when the directionality, compressed terminal timing, and mechanical or expressive resonance source are reproducibly deployed.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-scales-intervals',
      description:
        'Bent-string blue-third analysis requires familiarity with equal-temperament cents arithmetic (the 12-TET reference grid against which the bend is measured), the minor/major third boundary (300 ¢ / 400 ¢), and the blues idiom\'s vocabulary of melodic embellishment.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.50-microtonal-dialect-just-intonation',
      description:
        'Where microtonal dialect (MUS 1.50) describes population-level discrete cents-offset realisations of a shared template, bent-string blue-third microtonality describes within-event continuous-arc realisations. Both are closed local pitch systems; the difference is whether the system is gridded at population-stable points (dialect) or continuous through a region (arc).',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.26-sympatric-pitch-divergence-chorus-shifting',
      description:
        'Sympatric pitch-divergence describes within-chorus active separation between simultaneous voices; bent-string blue-third microtonality describes within-event continuous-pitch arc within a single voice. Both involve pitch as a continuous-region phenomenon rather than a discrete grid point.',
    },
  ],
  metadata: {
    musDegree: '1.37',
    exemplars: {
      s36Artist: 'Jimi Hendrix (early-blues sideman context, 1962-1966)',
      s36Works: [
        'The Isley Brothers — "Testify" (T-Neck T-501, 1964): Hendrix on rhythm guitar; bent-third stabs in off-beat slivers between vocal phrases',
        'Little Richard — "I Don\'t Know What You\'ve Got" (Vee-Jay VJ-698, 1965): Hendrix as backing guitarist; phrase-level rhythmic placement of bent-third gestures',
        'Curtis Knight & the Squires — PPX/Ed Chalpin sessions (1965-1966): subsequently released as You Can\'t Use My Name (Capitol/Atco) and various compilations',
        'King Curtis — Atlantic-session singles (1966): Hendrix on session guitar (cf. McDermott et al. 1995 §session lists)',
        'Lonnie Youngblood — NYC R&B sessions (1966): documented in Cross 2005 and McDermott et al. 1995',
      ],
      spsSpecies: 'Anna\'s Hummingbird (Calypte anna, Lesson 1829; family Trochilidae)',
      spsAcousticFeature:
        'Display-dive tail-feather chirp — a mechanically-produced single-pitch microtonal event generated by aerodynamic flutter of the spread outer rectrix R5 during the male\'s courtship dive. Peak frequency 3,950-4,150 Hz (centre ~4 kHz); duration ~50-70 ms; SPL up to ~83 dB at 1 m; produced at peak airspeed ~27 m/s (~385 body lengths/sec, the highest body-length-normalised speed in any vertebrate; Clark 2009 J. Exp. Biol. 212:3713-3721) at the bottom of the dive\'s pullout arc with 9-10 g centripetal acceleration. Clark & Feo 2008 (Proc. Roy. Soc. B 275:955-962) experimentally demonstrated the mechanical-flutter mechanism via R5-trimming; pitch is set by feather mass distribution and rachis stiffness, not by syringeal vocalisation. The chirp is in fact a brief glissando descending ~80 Hz across the 60 ms event as airspeed varies through the pullout — a continuous-pitch arc set by aeroelastic resonance.',
    },
    references: [
      'Sethares, W. A. (2005). Tuning, Timbre, Spectrum, Scale (2nd ed.). Springer. — ch. 4-5, ch. 8 inharmonic spectra',
      'Aldwell, Schachter & Cadwallader, Harmony and Voice Leading (5e, Cengage 2011), §1, §3',
      'Persichetti, V. (1961). Twentieth-Century Harmony. W. W. Norton. — ch. 3',
      'Tymoczko, D. (2011). A Geometry of Music. Oxford UP. — ch. 1',
      'Titon, J. T. (1994). Early Downhome Blues: A Musical and Cultural Analysis (2nd ed.). UNC Press. — canonical ethnomusicological treatment of the blue-third as a flexible region',
      'Weisethaunet, H. (2001). Is there such a thing as the "blue note"? Popular Music 20(1): 99-116.',
      'Cross, C. R. (2005). Room Full of Mirrors: A Biography of Jimi Hendrix. Hyperion. — chapters 4-7 on the 1962-66 chitlin\'-circuit period',
      'McDermott, J., Kramer, E., & Cox, B. (1995). Hendrix: Setting the Record Straight. Warner Books.',
      'Clark, C. J., & Feo, T. J. (2008). The Anna\'s hummingbird chirps with its tail: a new mechanism of sonation in birds. Proc. Roy. Soc. B 275(1637): 955-962.',
      'Clark, C. J. (2009). Courtship dives of Anna\'s hummingbird offer insights into flight performance limits. J. Exp. Biol. 212: 3713-3721.',
      'Clark, C. J., Elias, D. O., & Prum, R. O. (2011). Aeroelastic flutter produces hummingbird feather songs. Science 333(6048): 1430-1433.',
      'Hurly, T. A., Scott, R. D., & Healy, S. D. (2001). The function of displays of male rufous hummingbirds. Condor 103: 647-651.',
      'Stiles, F. G. (1982). Aggressive and courtship displays of the male Anna\'s Hummingbird. Condor 84: 208-225.',
      'Russell, S. M. (1996). Anna\'s hummingbird (Calypte anna). BNA #226.',
    ],
  },
};
