import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.47 — Infrasonic-floor pitch: the sub-audible fundamental as compositional substrate.
 *
 * Generated by the v1.49.581 MUS wave-8 backfill (W8-F fleet slot).
 * Cross-references: NASA 1.47 (Gemini 9A "angry alligator" ATDA shroud failure),
 *                   ELC 1.47 (pending; alligator-as-keystone-ecosystem-engineer).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const infrasonicFloorPitchSubstrate: RosettaConcept = {
  id: 'mus-1.47-infrasonic-floor-pitch-substrate',
  name: 'Infrasonic-floor pitch: the sub-audible fundamental as compositional substrate',
  domain: 'music',
  description:
    'A music-theoretic primitive describing a structurally weighted lowest fundamental whose ' +
    'frequency may lie at or below the lower threshold of audible pitch perception (~20 Hz), on ' +
    'which the audible-band surface (vocal melody, chord voicings, narrative line) is staged as ' +
    'harmonic or quasi-harmonic content. The American Alligator (Alligator mississippiensis, ' +
    'Daudin 1802) male advertisement bellow is the canonical bioacoustic exemplar: a 7-10 Hz ' +
    'infrasonic dorsal-muscle pulse train (Britton 1991 Behaviour 119: 99-126; Vliet 1989 Am. ' +
    'Zool. 29: 1019-1031) — visible as the "water dance" of droplet ejection from the dorsal ' +
    'surface — synchronises with an audible 50-300 Hz harmonic surface (Riede & Tokuda 2010 J. ' +
    'Acoust. Soc. Am. 127: EL15-EL21), and the bellow\'s perceptual identity depends on the ' +
    'superposition of the two layers. Rocky Votolato\'s West-Seattle / Barsuk-era catalog ' +
    "(Makers 2006, The Brag and Cuss 2007, True Devotion 2010) furnishes the human idiomatic " +
    'analog: dropped-D acoustic-guitar drone-floor at ~73 Hz sustained through narrative songs ' +
    'while the vocal melody and upper-string chord voicings ride above as the harmonic surface. ' +
    'The closure condition is that both layers must reach the receiver through their appropriate ' +
    'propagation channels (air for the audible surface, substrate or body-coupling for the ' +
    'infrasonic floor); channel mismatch — playback on phone speakers, radio rolloff — strips ' +
    'the substrate and dissolves the structural identity. Pedagogical extension: the Schenkerian ' +
    'pedal-tone treatment (Aldwell-Schachter §29) admits substrate pitches below the audibility ' +
    'threshold; structurally weighted lowest pitch is independent of audible-band placement.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-scales-intervals',
      description:
        'Infrasonic-floor pitch analysis requires familiarity with the lower bound of audible pitch perception (~20 Hz; the lowest octaves of usable musical pitch on the keyboard sit between A0 27.5 Hz and C2 65 Hz; the dropped-D acoustic-guitar low string at ~73 Hz sits at the threshold-of-audibility band) and with the bass-voice-as-foundation role from common-practice harmony.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.26-sympatric-pitch-divergence-chorus-shifting',
      description:
        'Where sympatric pitch-divergence (MUS 1.26) describes ACTIVE within-band horizontal pitch separation between simultaneous voices, infrasonic-floor pitch describes VERTICAL stratification across the audibility threshold: a load-bearing substrate below the surface\'s audible band. Both are closed-pitch-system architectures; the difference is whether the structural separation is horizontal-within-band (1.26) or vertical-across-bands (1.47).',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.37-bent-string-blue-third-microtonality',
      description:
        'Where bent-string blue-third microtonality (MUS 1.37) describes a continuous-pitch ARC through a region between equal-tempered grid points within the audible band, infrasonic-floor pitch describes a structural lowest pitch BELOW the audibility threshold that grounds the audible-band surface. Both are continuous-pitch architectures; 1.37 is a within-event continuous arc, 1.47 is a between-channel continuous substrate.',
    },
  ],
  metadata: {
    musDegree: '1.47',
    exemplars: {
      s36Artist: 'Rocky Votolato (West Seattle / Barsuk-era indie-folk singer-songwriter; ex-Waxwing 1996-2003)',
      s36Works: [
        'Makers (Barsuk BARK35, 2006): "White Daisy Passing" track 1 — opening dropped-D acoustic-guitar phrase establishes the ~73 Hz substrate before vocal entry; "Makers" track 9 — title-track dropped-D narrative.',
        'The Brag and Cuss (Barsuk BARK52, 2007): "Pillar of Salt" track 2 — fuller-band arrangement with upright bass DOUBLING the dropped-D drone an octave below at ~37 Hz, extending the substrate into the proper sub-bass region.',
        'True Devotion (Barsuk BARK101, 2010): "The Hereafter" track 1, "Sun Devil" track 5, "Lucky Clover Coin" track 9 — full demonstrations of the dropped-D substrate-and-surface architecture.',
        'Suicide Medicine (Second Nature 2002 / Barsuk BARK33 2003): the early catalog establishing the weathered-baritone vocal-and-acoustic-guitar idiom.',
        'Hospital Handshakes (No Sleep 2015) and Wild Roots (Glitterhouse 2020): later catalog continuing the dropped-D / DADGAD substrate practice.',
      ],
      spsSpecies: 'American Alligator (Alligator mississippiensis, Daudin 1802; Alligatoridae)',
      spsAcousticFeature:
        'Male advertisement bellowing — multi-component low-frequency display deployed during spring breeding (April-June across the Gulf Coast / Florida / Mississippi alluvial range). Audible component: 3-10 deep moaning bellows per bout, fundamental ~50-60 Hz with strong harmonics through 200-300 Hz, individual bellow duration 0.7-1.2 s, bouts 30-90 s, bout repeat interval 5-30 min during chorus periods (Vliet 1989 Am. Zool. 29: 1019-1031; Garrick, Lang & Herzog 1978 Bull. AMNH 160: 153-192). Infrasonic component (Britton 1991 Behaviour 119: 99-126): synchronised 7-10 Hz dorsal-muscle pulse train generates the visible "water dance" — droplets ejected up to 30 cm above the dorsal surface in a 30-50 cm wide pattern aligned with the body axis at the muscle-pulse rate. The 7-10 Hz substrate is BELOW the human auditory threshold (~20 Hz); humans feel it as body-vibration. Female alligators within ~50 m respond to substrate-conducted infrasonic content as well as airborne audible bellow (Mazzotti & Brandt 1994 in Davis & Ogden eds., Everglades, ch. 19). The bellow is a closed signal only when both layers are present; the audible surface alone is incomplete and the infrasonic substrate alone is a vibration but not a call. Vocal-tract length / body-size / call-frequency relationship per Riede & Tokuda 2010 (J. Acoust. Soc. Am. 127: EL15-EL21).',
    },
    references: [
      'Aldwell, Schachter & Cadwallader (2011). Harmony and Voice Leading (5e). Schirmer/Cengage. — §1, §6, §13, §29 (pedal points).',
      'Sethares, W. A. (2005). Tuning, Timbre, Spectrum, Scale (2nd ed.). Springer. — ch. 1, ch. 4.',
      'Persichetti, V. (1961). Twentieth-Century Harmony. W. W. Norton. — ch. 4, ch. 9.',
      'Tymoczko, D. (2011). A Geometry of Music. Oxford UP. — ch. 2.',
      'Roads, C. (1996). The Computer Music Tutorial. MIT Press. — ch. 4, ch. 22.',
      'Cogan, R. (1984). New Images of Musical Sound. Harvard UP.',
      'Vliet, K. A. (1989). Social displays of the American alligator (Alligator mississippiensis). American Zoologist 29(3): 1019-1031.',
      'Britton, A. R. C. (1991). The dance of the alligator: an analysis of the male advertisement bellow of Alligator mississippiensis. Behaviour 119(1-2): 99-126.',
      'Garrick, L. D., Lang, J. W., & Herzog, H. A. (1978). Social signals of adult American alligators. Bulletin of the American Museum of Natural History 160(3): 153-192.',
      'Garrick, L. D., & Lang, J. W. (1977). Social signals and behaviors of adult alligators and crocodiles. American Zoologist 17(1): 225-239.',
      'Mazzotti, F. J., & Brandt, L. A. (1994). Ecology of the American alligator in a seasonally fluctuating environment. In Davis & Ogden eds., Everglades: The Ecosystem and Its Restoration, ch. 19. St. Lucie Press.',
      'Mazzotti, F. J., et al. (2009). Alligators and crocodiles as indicators for restoration of Everglades ecosystems. Ecological Indicators 9S: S137-S149.',
      'Riede, T., & Tokuda, I. T. (2010). Vocal tract length, body size, and call frequency in male American alligators. J. Acoust. Soc. Am. 127: EL15-EL21.',
      'Brattstrom, B. H. (1955). Notes on the herpetology of the Pribilof Islands, Alaska. Copeia 1955(2): 173-175.',
      'NASA SP-138 (1967). Gemini Summary Conference. NASA Manned Spacecraft Center. — Gemini 9A mission report; ATDA shroud failure analysis; Cernan EVA debrief.',
      'Hacker, B. C., & Grimwood, J. M. (1977). On the Shoulders of Titans: A History of Project Gemini. NASA SP-4203. — ch. 12 covers Gemini 9A; "angry alligator" radio call documented verbatim.',
      'Cernan, E., & Davis, D. (1999). The Last Man on the Moon. St. Martin\'s Press.',
    ],
  },
};
