import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.48 — Modal vocabulary against pop-rock convention: Mixolydian/Dorian/Lydian
 * dialect choices and the orbital-resonance ratio.
 *
 * Generated by the v1.49.581 MUS wave-3 backfill (W3-F fleet slot).
 * Cross-references: NASA 1.48 (Gemini 10 first dual rendezvous + M=4 phasing),
 * ELC 1.48 (pending). Sibling domain-1 entry: the earlier reference treats
 * within-collection microtonal cents-deviation; this entry treats
 * across-collection discrete scale-selection — complementary axes of the
 * Pitch & scales domain.
 *
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const modalVocabulary: RosettaConcept = {
  id: 'mus-1.48-modal-vocabulary-orbital-resonance',
  name: 'Modal vocabulary against pop-rock convention: Mixolydian/Dorian/Lydian dialect choices and the orbital-resonance ratio',
  domain: 'music',
  description:
    'A music-theoretic primitive describing scale-collection selection from a ' +
    'discrete diatonic inventory, where the modal collection itself is the ' +
    'structural choice — distinct from within-collection cents-deviation. The ' +
    'inventory is the seven church modes (Ionian, Dorian, Phrygian, Lydian, ' +
    'Mixolydian, Aeolian, Locrian); the dialect-marking parameter is which ' +
    'mode the song selects on its tonic. Pop-rock convention strongly defaults ' +
    'to Ionian (major) and Aeolian (natural minor); writers who choose a ' +
    'non-default mode are choosing a different language for the song rather ' +
    'than a different accent. The closure condition is parallel-mode mixture: ' +
    'modulation between modes sharing a tonic via small-interval shifts on the ' +
    'mode-marking degrees (third, sixth, seventh, fourth). The bioacoustic ' +
    'exemplar is the White-crowned Sparrow (Zonotrichia leucophrys pugetensis, ' +
    'the Puget Sound subspecies; Marler & Tamura 1962, 1964; Baker 1975; ' +
    'Baptista & Petrinovich 1984, 1986) whose terminal-trill dialects differ ' +
    'at the scale-collection layer (which set of trill elements, frequency ' +
    'bands, and syllable shapes) rather than at the cents-deviation layer. ' +
    "Pedro the Lion (David Bazan's Jade Tree / Polyvinyl indie-folk catalog " +
    '1998–2024) furnishes the human idiomatic exemplar: deliberate Mixolydian, ' +
    'Dorian, and Lydian preferences against pop-rock Ionian/Aeolian convention, ' +
    'with parallel-mode mixture as a primary structural compositional device, ' +
    'preserved in mix by the Greenwood/Seattle indie-rock production tradition ' +
    '(T.W. Walsh / Phil Ek lineage). The orbital-resonance ratio anchor: ' +
    "Gemini 10's M=4 phasing for the first Agena rendezvous and the " +
    'distinct-ratio transfer to the second Agena are exercises in choosing ' +
    'rational integer ratios from a small finite menu — the orbital-mechanics ' +
    'image of modal-collection selection.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-scales-intervals',
      description:
        'Modal-vocabulary analysis requires familiarity with the seven church modes as discrete rotations of a single seven-note diatonic collection, and with the mode-marking degrees (third, sixth, seventh, fourth) that uniquely identify each mode against the others on a shared tonic.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.50-microtonal-dialect-just-intonation',
      description:
        'Where the earlier domain-1 MUS reference treats within-collection cents-deviation (the same template realised at population-specific frequencies that deviate from 12-TET), this entry treats across-collection scale-selection (the same tonic realised in different discrete modal collections). The two framings are complementary axes of the Pitch & scales domain; together they cover the principal ways pitch-system locality is realized in the wild and in human music.',
    },
    {
      type: 'analogy',
      targetId: 'music-melodic-contour',
      description:
        'Where melodic contour describes the shape of pitch motion within a fixed collection, modal vocabulary describes the choice of which collection contains the contour — the same melodic contour realised in different modes constitutes different songs in the dialect-marking sense.',
    },
  ],
  metadata: {
    musDegree: '1.48',
    exemplars: {
      s36Artist: 'Pedro the Lion (David Bazan; Jade Tree / Polyvinyl indie-folk; Greenwood/Seattle)',
      s36Works: [
        "It's Hard to Find a Friend (Made in Mexico / Jade Tree JT-1029, 1998)",
        'Winners Never Quit (Jade Tree JT-1059, 2000)',
        'Control (Jade Tree JT-1078, 2002) — Dorian-prominent record; raised-6th over minor-i tonic',
        'Achilles Heel (Jade Tree JT-1095, 2004) — Mixolydian-prominent; I–bVII–IV cadence cycle as Mixolydian fingerprint',
        'David Bazan, Curse Your Branches (Barsuk BARK85, 2009)',
        'Phoenix (Polyvinyl PRC-336, 2019) — parallel-mode mixture as autobiographical-narrative device',
        'Havasu (Polyvinyl PRC-414, 2022)',
        'Santa Cruz (Polyvinyl PRC-470, 2024) — Lydian-prominent introductions',
      ],
      spsSpecies: 'White-crowned Sparrow (Zonotrichia leucophrys, Forster 1772; pugetensis subspecies, Ridgway 1898 — the Puget-Sound subspecies)',
      spsAcousticFeature:
        'Population-level terminal-trill DIALECT differentiation as scale-collection selection. Z. l. pugetensis supports ~12 distinct dialect zones along the PNW coast (Baker 1975 Auk 92(4): 631–661); each dialect chooses a different COLLECTION of admissible terminal-trill elements (frequency band, element shape, duration, count) rather than a different cents-position of a single template. Marler & Tamura (1962 Condor 64(5): 368–377; 1964 Science 146: 1483–1486) established the canonical sparrow-dialect framework. Baptista & Petrinovich (1984 Anim. Behav. 32: 172–181; 1986 Anim. Behav. 34: 1359–1371) demonstrated experimentally that pugetensis males will learn heterospecific song under social-tutoring conditions, confirming that the song-template is a learned scale-COLLECTION rather than an innate cents-frequency. Marler 1970 (J. Comp. Phys. Psych. Monograph 71(2, pt. 2): 1–25) established the auditory-template model that constrains which collections are admissible.',
    },
    references: [
      'Persichetti, V. (1961). Twentieth-Century Harmony. W. W. Norton. — ch. 2 modal scales',
      'Aldwell, Schachter & Cadwallader, Harmony and Voice Leading (5e, Cengage 2011), §1, §28 mixture',
      'Tymoczko, D. (2011). A Geometry of Music. Oxford UP. — ch. 4 voice-leading geometry of scale collections',
      'Schoenberg, A. (1922/1978). Theory of Harmony (Carter trans.). UC Press. — pt. III on church-mode origins of major-minor system',
      'Marler, P. (1970). A comparative approach to vocal learning: song development in white-crowned sparrows. J. Comp. Phys. Psych. Monograph 71(2, pt. 2): 1–25.',
      'Marler, P., & Tamura, M. (1962). Song "dialects" in three populations of White-crowned Sparrows. The Condor 64(5): 368–377.',
      'Marler, P., & Tamura, M. (1964). Culturally transmitted patterns of vocal behavior in sparrows. Science 146(3650): 1483–1486.',
      'Baker, M. C. (1975). Song dialects and genetic differences in White-crowned Sparrows (Zonotrichia leucophrys). The Auk 92(4): 631–661.',
      'Baptista, L. F., & Petrinovich, L. (1984). Social interaction, sensitive phases and the song template hypothesis. Animal Behaviour 32(1): 172–181.',
      'Baptista, L. F., & Petrinovich, L. (1986). Song development in the white-crowned sparrow: social factors and sex differences. Animal Behaviour 34(5): 1359–1371.',
    ],
  },
};
