#!/bin/bash
# =============================================================================
# Sandbox Runner — Profile-Driven Platform Dispatch
# =============================================================================
#
# Dispatches command execution to the appropriate OS sandbox:
#   - Linux:  bubblewrap (bwrap) with profile-driven args from JSON
#   - macOS:  sandbox-exec with Seatbelt profile
#   - Other:  direct exec with warning (no sandboxing)
#
# Usage:
#   run-in-sandbox.sh --profile PROFILE_JSON -- COMMAND [ARGS...]
#
# The profile JSON is generated by generate-sandbox-profile.sh (Phase 368).
# It contains a bwrap_args array that is parsed and passed to bwrap directly.
# No hardcoded bwrap args — everything comes from the profile.
#
# Phase 373-01 / 516-03 — Bootstrap Phase 0
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source helpers if available (for logging)
if [ -f "$SCRIPT_DIR/phase0-helpers.sh" ]; then
    source "$SCRIPT_DIR/phase0-helpers.sh"
else
    # Minimal fallback logging
    phase0_log()   { echo "[Phase0] $1"; }
    phase0_warn()  { echo "[Phase0 WARN] $1" >&2; }
    phase0_error() { echo "[Phase0 ERROR] $1" >&2; }
fi

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
PROFILE_JSON=""
COMMAND=()

while [ $# -gt 0 ]; do
    case "$1" in
        --profile)
            PROFILE_JSON="$2"
            shift 2
            ;;
        --)
            shift
            COMMAND=("$@")
            break
            ;;
        *)
            shift
            ;;
    esac
done

if [ ${#COMMAND[@]} -eq 0 ]; then
    phase0_error "No command specified after -- separator"
    echo "Usage: run-in-sandbox.sh --profile PROFILE_JSON -- COMMAND [ARGS...]" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Detect platform
# ---------------------------------------------------------------------------
PLATFORM="unsupported"
case "$(uname -s)" in
    Linux)  PLATFORM="linux" ;;
    Darwin) PLATFORM="macos" ;;
esac

# Override from profile JSON if available
if [ -n "$PROFILE_JSON" ] && [ -f "$PROFILE_JSON" ]; then
    PROFILE_PLATFORM=$(grep -o '"platform"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROFILE_JSON" 2>/dev/null \
        | head -1 | sed 's/.*"platform"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
    if [ -n "$PROFILE_PLATFORM" ]; then
        PLATFORM="$PROFILE_PLATFORM"
    fi
fi

# ---------------------------------------------------------------------------
# Parse bwrap_args from profile JSON
# ---------------------------------------------------------------------------
parse_bwrap_args() {
    local profile_file="$1"

    # Prefer jq for reliable JSON parsing
    if command -v jq > /dev/null 2>&1; then
        jq -r '.bwrap_args[]? // empty' "$profile_file" 2>/dev/null
        return
    fi

    # Fallback: grep-based extraction for bwrap_args array
    # Extracts quoted strings between "bwrap_args": [ ... ]
    local in_array=false
    while IFS= read -r line; do
        if echo "$line" | grep -q '"bwrap_args"'; then
            in_array=true
            continue
        fi
        if [ "$in_array" = true ]; then
            if echo "$line" | grep -q ']'; then
                break
            fi
            # Extract quoted string value
            local val
            val=$(echo "$line" | sed -n 's/.*"\([^"]*\)".*/\1/p')
            if [ -n "$val" ]; then
                echo "$val"
            fi
        fi
    done < "$profile_file"
}

# ---------------------------------------------------------------------------
# Platform dispatch
# ---------------------------------------------------------------------------
case "$PLATFORM" in
    linux)
        # Linux: exec bwrap with profile-driven args
        if command -v bwrap > /dev/null 2>&1; then
            phase0_log "Running in bubblewrap sandbox"

            # Parse bwrap_args from profile JSON
            BWRAP_ARGS=()
            if [ -n "$PROFILE_JSON" ] && [ -f "$PROFILE_JSON" ]; then
                while IFS= read -r arg; do
                    BWRAP_ARGS+=("$arg")
                done < <(parse_bwrap_args "$PROFILE_JSON")
            fi

            if [ ${#BWRAP_ARGS[@]} -gt 0 ]; then
                # Profile-driven: use bwrap_args from JSON (skip "bwrap" command itself)
                phase0_log "Using profile-driven sandbox isolation"

                # Skip the first arg if it's "bwrap" (we exec bwrap directly)
                local_args=()
                local skip_first=true
                for arg in "${BWRAP_ARGS[@]}"; do
                    if [ "$skip_first" = true ] && [ "$arg" = "bwrap" ]; then
                        skip_first=false
                        continue
                    fi
                    skip_first=false
                    local_args+=("$arg")
                done

                # Ensure --dev and --proc are always present
                has_dev=false
                has_proc=false
                for arg in "${local_args[@]}"; do
                    [ "$arg" = "--dev" ] && has_dev=true
                    [ "$arg" = "--proc" ] && has_proc=true
                done
                if [ "$has_dev" = false ]; then
                    local_args+=("--dev" "/dev")
                fi
                if [ "$has_proc" = false ]; then
                    local_args+=("--proc" "/proc")
                fi

                exec bwrap "${local_args[@]}" -- "${COMMAND[@]}"
            else
                # No bwrap_args found: minimal safe fallback
                phase0_warn "No bwrap_args in profile — using minimal safe sandbox"
                exec bwrap \
                    --dev /dev \
                    --proc /proc \
                    --ro-bind /usr /usr \
                    --ro-bind /bin /bin \
                    --ro-bind /etc /etc \
                    --tmpfs "$HOME/.ssh" \
                    --tmpfs "$HOME/.aws" \
                    --tmpfs "$HOME/.config/gcloud" \
                    --tmpfs "$HOME/.gnupg" \
                    --die-with-parent \
                    -- "${COMMAND[@]}"
            fi
        else
            phase0_warn "bubblewrap not found — running without sandbox isolation"
            exec "${COMMAND[@]}"
        fi
        ;;

    macos)
        # macOS: exec sandbox-exec with Seatbelt profile
        if command -v sandbox-exec > /dev/null 2>&1; then
            phase0_log "Running in macOS Seatbelt sandbox"

            # Check for Seatbelt profile path in JSON
            SEATBELT_PATH=""
            if [ -n "$PROFILE_JSON" ] && [ -f "$PROFILE_JSON" ]; then
                SEATBELT_PATH=$(grep -o '"seatbelt_path"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROFILE_JSON" 2>/dev/null \
                    | head -1 | sed 's/.*"seatbelt_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
            fi

            if [ -n "$SEATBELT_PATH" ] && [ -f "$SEATBELT_PATH" ]; then
                exec sandbox-exec -f "$SEATBELT_PATH" -- "${COMMAND[@]}"
            else
                # Stub: use deny-default Seatbelt profile inline
                phase0_warn "No Seatbelt profile found — running with basic macOS sandbox"
                exec sandbox-exec -p '(version 1)(allow default)' -- "${COMMAND[@]}"
            fi
        else
            phase0_warn "sandbox-exec not found — running without sandbox isolation"
            exec "${COMMAND[@]}"
        fi
        ;;

    *)
        # Unsupported platform: run command directly
        phase0_warn "Unsupported platform ($PLATFORM) — running command without sandbox isolation"
        exec "${COMMAND[@]}"
        ;;
esac
