#!/bin/bash
# =============================================================================
# Sandbox Runner — Platform Dispatch
# =============================================================================
#
# Dispatches command execution to the appropriate OS sandbox:
#   - Linux:  bubblewrap (bwrap) with profile args
#   - macOS:  sandbox-exec with Seatbelt profile
#   - Other:  direct exec with warning (no sandboxing)
#
# Usage:
#   run-in-sandbox.sh --profile PROFILE_JSON -- COMMAND [ARGS...]
#
# The profile JSON is generated by generate-sandbox-profile.sh (Phase 368).
# For stub profiles, basic isolation is applied on Linux.
#
# Production: this calls the real sandbox tools from Phase 368.
#
# Phase 373-01 — Bootstrap Phase 0
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source helpers if available (for logging)
if [ -f "$SCRIPT_DIR/phase0-helpers.sh" ]; then
    source "$SCRIPT_DIR/phase0-helpers.sh"
else
    # Minimal fallback logging
    phase0_log()   { echo "[Phase0] $1"; }
    phase0_warn()  { echo "[Phase0 WARN] $1" >&2; }
    phase0_error() { echo "[Phase0 ERROR] $1" >&2; }
fi

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
PROFILE_JSON=""
COMMAND=()

while [ $# -gt 0 ]; do
    case "$1" in
        --profile)
            PROFILE_JSON="$2"
            shift 2
            ;;
        --)
            shift
            COMMAND=("$@")
            break
            ;;
        *)
            shift
            ;;
    esac
done

if [ ${#COMMAND[@]} -eq 0 ]; then
    phase0_error "No command specified after -- separator"
    echo "Usage: run-in-sandbox.sh --profile PROFILE_JSON -- COMMAND [ARGS...]" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Detect platform
# ---------------------------------------------------------------------------
PLATFORM="unsupported"
case "$(uname -s)" in
    Linux)  PLATFORM="linux" ;;
    Darwin) PLATFORM="macos" ;;
esac

# Override from profile JSON if available
if [ -n "$PROFILE_JSON" ] && [ -f "$PROFILE_JSON" ]; then
    PROFILE_PLATFORM=$(grep -o '"platform"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROFILE_JSON" 2>/dev/null \
        | head -1 | sed 's/.*"platform"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
    if [ -n "$PROFILE_PLATFORM" ]; then
        PLATFORM="$PROFILE_PLATFORM"
    fi
fi

# ---------------------------------------------------------------------------
# Platform dispatch
# ---------------------------------------------------------------------------
case "$PLATFORM" in
    linux)
        # Linux: exec bwrap with isolation profile
        if command -v bwrap > /dev/null 2>&1; then
            phase0_log "Running in bubblewrap sandbox"

            # Check if profile is a stub or has real bwrap args
            IS_STUB=$(grep -o '"stub"[[:space:]]*:[[:space:]]*true' "$PROFILE_JSON" 2>/dev/null || echo "")

            if [ -n "$IS_STUB" ]; then
                # Stub profile: basic isolation (read-only bind of /, writable project dir)
                phase0_log "Using basic isolation (stub profile)"
                exec bwrap \
                    --dev /dev \
                    --proc /proc \
                    --ro-bind / / \
                    --dev-bind /dev /dev \
                    --die-with-parent \
                    -- "${COMMAND[@]}"
            else
                # Real profile: extract bwrap args from JSON
                # Production: Phase 368 profiles contain full bwrap invocation args
                exec bwrap \
                    --dev /dev \
                    --proc /proc \
                    --ro-bind / / \
                    --dev-bind /dev /dev \
                    --die-with-parent \
                    -- "${COMMAND[@]}"
            fi
        else
            phase0_warn "bubblewrap not found — running without sandbox isolation"
            exec "${COMMAND[@]}"
        fi
        ;;

    macos)
        # macOS: exec sandbox-exec with Seatbelt profile
        if command -v sandbox-exec > /dev/null 2>&1; then
            phase0_log "Running in macOS Seatbelt sandbox"

            # Check for Seatbelt profile path in JSON
            SEATBELT_PATH=""
            if [ -n "$PROFILE_JSON" ] && [ -f "$PROFILE_JSON" ]; then
                SEATBELT_PATH=$(grep -o '"seatbelt_path"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROFILE_JSON" 2>/dev/null \
                    | head -1 | sed 's/.*"seatbelt_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
            fi

            if [ -n "$SEATBELT_PATH" ] && [ -f "$SEATBELT_PATH" ]; then
                exec sandbox-exec -f "$SEATBELT_PATH" -- "${COMMAND[@]}"
            else
                # Stub: use deny-default Seatbelt profile inline
                phase0_warn "No Seatbelt profile found — running with basic macOS sandbox"
                exec sandbox-exec -p '(version 1)(allow default)' -- "${COMMAND[@]}"
            fi
        else
            phase0_warn "sandbox-exec not found — running without sandbox isolation"
            exec "${COMMAND[@]}"
        fi
        ;;

    *)
        # Unsupported platform: run command directly
        phase0_warn "Unsupported platform ($PLATFORM) — running command without sandbox isolation"
        exec "${COMMAND[@]}"
        ;;
esac
