/**
 * script-generator.ts — Data Lifecycle: Promotion Script Creation
 *
 * WHAT THIS MODULE DOES
 * ---------------------
 * ScriptGenerator converts PromotionCandidate objects into executable bash scripts.
 * Each generated script replicates the behavior of the original tool operation,
 * wrapped in a metadata header and validated against the OffloadOperation schema.
 *
 * ScriptGenerator also supports dry-run validation: execute the generated script
 * and compare its output hash against the stored expected hash. A match means
 * the script faithfully replicates the original operation.
 *
 * WHERE THIS FITS IN THE PIPELINE
 * --------------------------------
 * The promotion pipeline is a 4-stage process:
 *   1. ExecutionCapture: record what tool calls happened
 *   2. DeterminismAnalyzer: classify which operations are reliable
 *   3. PromotionDetector: rank the best candidates for promotion
 *   4. PromotionGatekeeper: validate candidates against quality thresholds
 *   5. ScriptGenerator (this file): generate the actual scripts
 *
 * ScriptGenerator is the final creative act: turning statistical evidence
 * of deterministic behavior into runnable code.
 *
 * SUPPORTED TOOLS
 * ---------------
 * Currently 5 tools have bash script generation support:
 *
 *   Read  → cat "${file_path}"
 *     The simplest promotion: reading a file is always readable as cat.
 *
 *   Bash  → the command verbatim
 *     The original bash command is used as-is. Already a shell command.
 *
 *   Write → cat << 'SCRIPT_EOF' > "${file_path}"
 *     Heredoc write replicates Write tool's verbatim file creation.
 *     Single-quoted delimiter prevents variable expansion in content.
 *
 *   Glob  → find "${path}" -name "${pattern}" -type f | sort
 *     Converted from glob syntax to find(1) equivalent.
 *     Sort ensures deterministic output order (matches list behavior).
 *
 *   Grep  → grep -r "${pattern}" "${path}"
 *     Recursive grep replicates Grep tool's search behavior.
 *
 * Unsupported tools generate a stub script with exit 1 and a clear error message.
 * isValid is set to false for unsupported tools, so callers can filter them out.
 *
 * METADATA HEADER (SCRP-02)
 * --------------------------
 * Every generated script includes a header comment block:
 *   #!/bin/bash
 *   # Auto-generated by gsd-skill-creator promotion pipeline
 *   # Source pattern: toolName:inputHash
 *   # Confidence: compositeScore
 *   # Sessions: N distinct sessions that observed this pattern
 *   # Observations: frequency count
 *   # Generated: ISO timestamp
 *
 * The header serves multiple purposes:
 * - Identifies scripts as auto-generated (not hand-written)
 * - Provides traceability back to the observation that triggered generation
 * - Enables the DriftMonitor to correlate script executions with source patterns
 * - Documents the confidence level at generation time
 *
 * DRY-RUN VALIDATION (SCRP-03)
 * -----------------------------
 * dryRun() executes the generated script and compares stdout hash against
 * the stored expected hash. This verifies the script actually produces the
 * expected output before it's deployed for production use.
 *
 * Two failure modes:
 *   - Non-zero exit code: script execution failed (bash error, missing file, etc.)
 *   - Hash mismatch: script ran but produced different output than expected
 *
 * Hash comparison uses SHA-256 — consistent with FeedbackBridge and DriftMonitor.
 * A hash mismatch indicates the environment changed since observation: the file
 * was modified, the command behaves differently, etc.
 *
 * OFFLLOAD OPERATION CONFORMANCE (SCRP-04)
 * -----------------------------------------
 * Generated scripts are wrapped in OffloadOperation objects and validated
 * against OffloadOperationSchema (Zod). This ensures generated scripts conform
 * to the Blitter offload interface and can be executed by executeOffloadOp().
 *
 * If schema validation fails, the operation is used as-is but isValid is false.
 * This handles edge cases where the generated script has unexpected content.
 *
 * GLOB PATTERN CONVERSION
 * -----------------------
 * globToFindPattern() handles the mismatch between glob and find syntax.
 * Glob patterns often start with "**/" (any directory depth).
 * find -name doesn't understand "**/" — it takes just the basename pattern.
 * The conversion strips leading "**/" for find compatibility.
 *
 * This is a simplified conversion. Complex glob patterns (character classes,
 * alternation) may not translate correctly. The dry-run validation catches
 * this: if the pattern produces wrong output, the dry run fails.
 *
 * HASH CONSISTENCY
 * ----------------
 * computeInputHash() uses the same algorithm as DeterminismAnalyzer and
 * PromotionDetector: SHA-256 with JSON.stringify using sorted keys.
 * This consistency is critical for findRepresentativePair() to correctly
 * locate the stored pair matching a candidate's inputHash.
 *
 * SATISFIES
 * ---------
 * SCRP-01: Script generation from PromotionCandidate
 * SCRP-02: Metadata headers with provenance information
 * SCRP-03: Dry-run validation against stored expected hashes
 * SCRP-04: OffloadOperation schema conformance
 *
 * @see PromotionGatekeeper (promotion-gatekeeper.ts) — approves candidates that reach here
 * @see DriftMonitor (drift-monitor.ts) — monitors generated script outputs post-deployment
 * @see executeOffloadOp (services/chipset/blitter/executor.ts) — executes the scripts
 * @see BATCH-3-RETROSPECTIVE.md — Foxy's debrief on compression ratio as a first-class metric
 */

import { createHash } from 'crypto';
import { PatternStore } from '../../core/storage/pattern-store.js';
import { OffloadOperationSchema } from '../../services/chipset/blitter/types.js';
import { executeOffloadOp } from '../../services/chipset/blitter/executor.js';
import type { OffloadOperation, OffloadResult } from '../../services/chipset/blitter/types.js';
import type {
  PromotionCandidate,
  GeneratedScript,
  ScriptGeneratorConfig,
  DryRunResult,
  StoredExecutionBatch,
  ToolExecutionPair,
} from '../../core/types/observation.js';
import { DEFAULT_SCRIPT_GENERATOR_CONFIG } from '../../core/types/observation.js';

/**
 * Tools that have bash script generation support.
 * All other tools generate a stub with exit 1.
 */
const SUPPORTED_SCRIPT_TOOLS = new Set(['Read', 'Bash', 'Write', 'Glob', 'Grep']);

/**
 * Generates executable bash scripts from PromotionCandidate objects.
 *
 * Consumes candidates produced by PromotionDetector and stored execution data
 * from PatternStore, then produces OffloadOperation-conformant bash scripts
 * that replicate the original tool operations.
 *
 * Satisfies SCRP-01 (script generation), SCRP-02 (metadata headers),
 * and SCRP-04 (OffloadOperation conformance).
 */
export class ScriptGenerator {
  private store: PatternStore;
  private config: ScriptGeneratorConfig;

  constructor(
    store: PatternStore,
    config: ScriptGeneratorConfig = DEFAULT_SCRIPT_GENERATOR_CONFIG,
  ) {
    this.store = store;
    this.config = config;
  }

  /**
   * Generate an executable bash script from a promotion candidate.
   *
   * Pipeline:
   *   1. Check if the tool is supported for script generation
   *   2. Look up a representative stored execution pair (for actual input parameters)
   *   3. Generate tool-specific bash command(s)
   *   4. Wrap with metadata header (provenance, confidence, sessions, observations)
   *   5. Validate against OffloadOperationSchema
   *   6. Return GeneratedScript with isValid flag
   *
   * isValid is true only when the tool is supported, the script was generated,
   * AND OffloadOperationSchema validation passed.
   *
   * @param candidate - The promotion candidate to generate a script for
   * @returns A GeneratedScript with the operation, script content, and validity
   */
  async generate(candidate: PromotionCandidate): Promise<GeneratedScript> {
    const isSupportedTool = SUPPORTED_SCRIPT_TOOLS.has(candidate.toolName);

    // Look up stored execution pair data for this candidate's operation
    // The representative pair provides the actual input parameters used
    const representativePair = await this.findRepresentativePair(candidate);

    // Extract input from stored pair, fallback to empty object if not found
    const input = representativePair?.input ?? {};

    // Generate script body (or unsupported stub if tool is not in SUPPORTED_SCRIPT_TOOLS)
    const { body, supported } = this.generateScriptBody(candidate.toolName, input);

    // Generate metadata header — provenance block at the top of the script
    const header = this.generateMetadataHeader(candidate);

    // Combine header + body into full script
    const fullScriptContent = header + '\n' + body + '\n';

    // Build the OffloadOperation object for Blitter compatibility
    const operationData = {
      id: `${candidate.toolName}:${candidate.operation.score.operation.inputHash}`,
      script: fullScriptContent,
      scriptType: 'bash' as const,
      workingDir: this.config.defaultWorkingDir,
      timeout: this.config.defaultTimeout,
      env: {},
      label: `Auto-promoted ${candidate.toolName} operation`,
    };

    // Validate against OffloadOperationSchema (SCRP-04)
    const parseResult = OffloadOperationSchema.safeParse(operationData);
    const isValid = parseResult.success && isSupportedTool && supported;
    const operation: OffloadOperation = parseResult.success
      ? parseResult.data
      : operationData as OffloadOperation;

    return {
      operation,
      sourceCandidate: candidate,
      scriptContent: fullScriptContent,
      isValid,
    };
  }

  /**
   * Execute a generated script in dry-run mode and compare output against expected.
   * Uses Blitter's OffloadExecutor to run the script, then compares stdout hash
   * against the stored output hash from observations (SCRP-03).
   *
   * Two failure modes:
   *   - exitCode !== 0: script execution failed (error in bash commands)
   *   - hash mismatch: script produced different output than observed
   *
   * Early return for invalid scripts — no point executing a script that won't work.
   * Also early return when no stored pair data is available — nothing to compare against.
   *
   * The executor parameter allows injection for testing without real bash execution.
   *
   * @param generatedScript - The script to validate
   * @param executor - Optional custom executor function (default: executeOffloadOp from Blitter)
   * @returns DryRunResult with pass/fail, hashes, and failure reason
   */
  async dryRun(
    generatedScript: GeneratedScript,
    executor: (op: OffloadOperation) => Promise<OffloadResult> = executeOffloadOp,
  ): Promise<DryRunResult> {
    // Early return for invalid scripts — don't execute what can't succeed
    if (!generatedScript.isValid) {
      return {
        generatedScript,
        passed: false,
        actualOutputHash: '',
        expectedOutputHash: '',
        exitCode: -1,
        durationMs: 0,
        failureReason: 'Script is invalid or generated for unsupported tool',
      };
    }

    // Look up the expected output hash from stored execution pairs
    const representativePair = await this.findRepresentativePair(
      generatedScript.sourceCandidate,
    );

    if (!representativePair || !representativePair.outputHash) {
      return {
        generatedScript,
        passed: false,
        actualOutputHash: '',
        expectedOutputHash: '',
        exitCode: -1,
        durationMs: 0,
        failureReason: 'No stored execution data found for output comparison',
      };
    }

    const expectedOutputHash = representativePair.outputHash;

    // Execute the script using the executor (real or injected for testing)
    const result = await executor(generatedScript.operation);

    // Hash the actual stdout — consistent with FeedbackBridge hashing
    const actualOutputHash = createHash('sha256')
      .update(result.stdout)
      .digest('hex');

    // Compare hashes and exit code — both must succeed for pass
    const hashMatch = actualOutputHash === expectedOutputHash;
    const exitOk = result.exitCode === 0;
    const passed = hashMatch && exitOk;

    // Determine failure reason — only one of these can fire if !passed
    let failureReason: string | null = null;
    if (!exitOk) {
      failureReason = `Non-zero exit code: ${result.exitCode}`;
    } else if (!hashMatch) {
      failureReason = `Output hash mismatch: expected ${expectedOutputHash.slice(0, 12)}..., got ${actualOutputHash.slice(0, 12)}...`;
    }

    return {
      generatedScript,
      passed,
      actualOutputHash,
      expectedOutputHash,
      exitCode: result.exitCode,
      durationMs: result.durationMs,
      failureReason,
    };
  }

  /**
   * Find a representative stored execution pair matching the candidate's
   * toolName and inputHash. Returns the first complete pair found.
   *
   * The inputHash comparison uses this.computeInputHash() on each stored pair's
   * input, which must match DeterminismAnalyzer's algorithm for correct lookup.
   */
  private async findRepresentativePair(
    candidate: PromotionCandidate,
  ): Promise<ToolExecutionPair | null> {
    const entries = await this.store.read('executions');
    const targetInputHash = candidate.operation.score.operation.inputHash;

    for (const entry of entries) {
      const batch = entry.data as unknown as StoredExecutionBatch;
      for (const pair of batch.pairs) {
        if (pair.status !== 'complete') continue;
        if (pair.toolName !== candidate.toolName) continue;
        const pairInputHash = this.computeInputHash(pair.input);
        if (pairInputHash === targetInputHash) {
          return pair;
        }
      }
    }

    return null;
  }

  /**
   * Generate the metadata header comment block (SCRP-02).
   * Placed at the top of every generated script for provenance and traceability.
   *
   * The patternId (toolName:inputHash) uniquely identifies the source operation.
   * DriftMonitor uses this to correlate deployed script executions back to their
   * generation context.
   */
  private generateMetadataHeader(candidate: PromotionCandidate): string {
    const patternId = `${candidate.toolName}:${candidate.operation.score.operation.inputHash}`;
    const confidence = candidate.compositeScore;
    const sessions = candidate.operation.score.sessionIds.length;
    const observations = candidate.frequency;
    const generated = new Date().toISOString();

    return [
      '#!/bin/bash',
      '# ============================================================',
      '# Auto-generated by gsd-skill-creator promotion pipeline',
      `# Source pattern: ${patternId}`,
      `# Confidence: ${confidence}`,
      `# Sessions: ${sessions}`,
      `# Observations: ${observations}`,
      `# Generated: ${generated}`,
      '# ============================================================',
    ].join('\n');
  }

  /**
   * Generate tool-specific bash script body.
   * Returns the bash command(s) and whether the tool is supported.
   *
   * Each case translates the tool's input object into the corresponding bash equivalent.
   * The translation must be semantically equivalent — same input → same output.
   *
   * Unsupported tools get a stub with exit 1 to prevent silent misuse.
   */
  private generateScriptBody(
    toolName: string,
    input: Record<string, unknown>,
  ): { body: string; supported: boolean } {
    switch (toolName) {
      case 'Read':
        // cat replicates verbatim file reading
        return {
          body: `cat "${input.file_path as string}"`,
          supported: true,
        };

      case 'Bash':
        // Bash commands are already shell — use verbatim
        return {
          body: input.command as string,
          supported: true,
        };

      case 'Write':
        // Heredoc with single-quoted delimiter prevents variable expansion in content
        return {
          body: `cat << 'SCRIPT_EOF' > "${input.file_path as string}"\n${input.content as string}\nSCRIPT_EOF`,
          supported: true,
        };

      case 'Glob': {
        // find -name equivalent: strip **/ prefix for find compatibility
        const path = (input.path as string) || '.';
        const pattern = this.globToFindPattern((input.pattern as string) || '*');
        return {
          body: `find "${path}" -name "${pattern}" -type f | sort`,
          supported: true,
        };
      }

      case 'Grep': {
        // Recursive grep equivalent
        const path = (input.path as string) || '.';
        return {
          body: `grep -r "${input.pattern as string}" "${path}"`,
          supported: true,
        };
      }

      default:
        // Unsupported tool: clear error message and exit 1
        return {
          body: `# ERROR: Tool '${toolName}' is not supported for script generation\nexit 1`,
          supported: false,
        };
    }
  }

  /**
   * Convert a glob pattern to a find -name compatible pattern.
   * Strips leading **\/ for find -name compatibility.
   *
   * Note: This is a simplified conversion. Complex glob patterns may not
   * translate correctly. The dry-run validation catches such cases.
   */
  private globToFindPattern(pattern: string): string {
    return pattern.replace(/^\*\*\//, '');
  }

  /**
   * Compute SHA-256 hash of JSON-serialized input with sorted keys.
   * Must match DeterminismAnalyzer and PromotionDetector hashing.
   * Consistency across all pipeline stages is critical for correct pair lookup.
   */
  private computeInputHash(input: Record<string, unknown>): string {
    const canonical = JSON.stringify(input, Object.keys(input).sort());
    return createHash('sha256').update(canonical).digest('hex');
  }
}

export { DEFAULT_SCRIPT_GENERATOR_CONFIG };
