import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.24 — Discrete-germanium ring-counter sequencer timing margin:
 * propagation-delay budgeting, clock-skew tolerance, and the Ranger 3
 * Central Computer & Sequencer mid-course-pointing failure.
 *
 * Generated by the v1.49.581 ELC Wave-5 backfill (Domain 9 second entry,
 * tube-ge era, 1962). Complements the Domain 9 first entry at ELC 1.53
 * (Gemini 12 IBM SLT DTL Solid Logic Technology hybrid + ferrite-core
 * memory, si-discrete era, 1966): same pedagogical primitive (the
 * synchronous-design timing-margin inequality) anchored on the earlier
 * discrete-germanium-NPN bistable substrate rather than on early-IC DTL.
 *
 * Cross-references: NASA 1.24 (Ranger 3, missed Moon by 36,793 km on
 * 1962-01-26 after CC&S mid-course-pointing failure); MUS 1.24
 * (missed-target-harmony secondary-dominant-chains structural rhyme).
 *
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const discreteGermaniumRingCounterCcAndS: RosettaConcept = {
  id: 'elc-1.24-discrete-germanium-ring-counter-cc-and-s',
  name: 'Discrete-germanium ring-counter timing-margin inequality (Ranger Block II CC&S)',
  domain: 'electronics',
  description:
    'A digital-logic primitive applying the synchronous-design timing-margin inequality ' +
    't_clock >= t_PD,max + t_setup + t_hold + t_skew to the JPL Ranger Block II Central ' +
    'Computer & Sequencer (CC&S) — a discrete-germanium 2N1308-class NPN bistable flip-flop ' +
    'ring counter clocked at 38.4 kHz that gated the spacecraft\'s mid-course maneuver. ' +
    'The Ranger 3 mid-course-pointing failure on 1962-01-26 traces directly to corner-case ' +
    'stacking that violated this inequality: -55 °C cold-shadow stretched the saturated ' +
    'storage time t_s of the 2N1308 transistors from 3 µs to 9 µs; heavy-fanout C_LOAD ' +
    'on the mid-course-decoder line reached 480 pF; V_CC ripple modulated the trigger ' +
    'threshold by ±5%. The stacked sum 12.4 µs versus a 13.0 µs t_clock at the 76.8 kHz ' +
    'fast-decoder sub-rate left under 1 µs of margin — and the resulting setup violation ' +
    'latched the wrong attitude command, committing the spacecraft to a 60° pointing ' +
    'error during the maneuver-arming sequence. The Block III redesign that flew on ' +
    'Ranger 7 added Schottky-clamp diodes that bounded t_s and instituted an end-to-end ' +
    'pre-flight timing-margin validation campaign — directly ancestral to the modern ' +
    'static-timing-analyser tool that every FPGA build now runs.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-saturated-mode-bjt-switching',
      description:
        'The bistable flip-flop cell uses saturated-mode germanium NPN switching; the ' +
        'storage-time t_s of the saturated transistor is the dominant term in the cell\'s ' +
        'propagation delay and the device-physics-bound parameter that drives corner-case ' +
        'spread (Millman & Taub 1965 ch. 17-18; GE Transistor Manual 1964 ch. 6)',
    },
    {
      type: 'dependency',
      targetId: 'elec-sequential-logic-design',
      description:
        'The timing-margin inequality only applies to synchronous machines with edge-' +
        'triggered flip-flop storage; sequential-logic-design defines those flip-flops, ' +
        'their setup/hold windows, and the synchronous-design rules that the inequality ' +
        'enforces (Mano & Ciletti 5e ch. 6; Wakerly 4e §3.6)',
    },
    {
      type: 'sibling',
      targetId: 'elc-1.53-early-ic-digital-logic-sequencer',
      description:
        'Domain 9 first entry (ELC 1.53, Gemini 12 IBM SLT DTL + ferrite-core, si-discrete ' +
        'era 1966) shares the same pedagogical primitive — the synchronous-design timing-' +
        'margin inequality — but anchors on early-IC DTL gates and a 7.143 kHz clock. ' +
        '1.24 anchors on the earlier discrete-germanium-NPN bistable substrate at 38.4 kHz. ' +
        'A student reading both in sequence observes the inequality is invariant across ' +
        'the eras\' 3-orders-of-magnitude device-speed difference',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.24-missed-target-harmony-secondary-dominant-chains',
      description:
        'The timing-margin inequality breaking down under corner-case stacking is itself a ' +
        'missed-target gesture: the synchronous-design intent points at "all flip-flops ' +
        'settle before the next clock edge," and the corner-case stacking arrives at "one ' +
        'flip-flop did not settle, and the resulting wrong-but-stable state was committed ' +
        'to the spacecraft\'s attitude vector." Both are local-target-overshoot gestures ' +
        'whose informational value comes from the way the target was missed',
    },
  ],
  metadata: {
    elcDegree: '1.24',
    domain: 9,
    domainName: 'Digital logic',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'JPL Ranger Block II Central Computer & Sequencer (Caltech-JPL build 1961-1962) — 38.4 kHz crystal-controlled basic rate; ~80 discrete-germanium 2N1308-class NPN bistable flip-flops; ring-counter walking-one program counter; parallel command-decoder matrix; ~3000 discrete components; ~6.4 kg',
    keyEquation: 't_clock >= t_PD,max + t_setup + t_hold-margin + t_skew  (must hold at every device-parameter corner)',
    benchReplication: {
      activeBistable: 'ON Semi 2N3904 silicon NPN (Mouser 512-2N3904BU); t_s ≈ 200 ns corner-stable',
      eraOriginal: 'GE 2N1308 germanium NPN saturated-mode switching transistor; t_s = 1-3 µs typ at +25 °C, rises to 6-9 µs at -55 °C',
      triggerDiode: '1N5817 Schottky (modern; >1 kV HBM ESD) OR 1N34A point-contact germanium (era-original; <200 V HBM)',
      speedUpCap: '470 pF C0G NPO 0805 (AVX 581-08051A471JAT2A)',
      clockSource: 'NE555 RC oscillator OR Arduino Nano Timer1 divider at 38.4 kHz',
      cLoadSweep: '50 / 100 / 200 / 400 / 800 pF (DIP-switch selectable; traces t_PD vs C_LOAD timing-margin study)',
    },
    references: [
      'Millman, J., & Taub, H. (1965). Pulse, Digital, and Switching Waveforms. McGraw-Hill — ch. 17-18 saturated-mode bistable design and storage-time analysis',
      'Mano & Ciletti, Digital Design (5e, Pearson 2012) — ch. 6 synchronous sequential timing margin',
      'Wakerly, Digital Design (4e, Prentice Hall 2005), §3.6 — timing-margin inequality decomposition',
      'Horowitz & Hill, The Art of Electronics (3e, Cambridge 2015), §10.1-10.3 / §12.7 — bistable circuits and timing-margin pathologies',
      'Hall, R. C. (1977). Lunar Impact: A History of Project Ranger. NASA SP-4210, ch. 6-8 — Block II flight failures and Block III redesign',
      'JPL Technical Report 32-241 (1962). Ranger Block II Mission Operations and Spacecraft Description, §4 — CC&S architecture',
      'GE Transistor Manual (1964, 7th ed.) — section 6 germanium-NPN saturated-mode switching',
      'Searle, C. L., et al. (1964). Elementary Circuit Properties of Transistors. SEEC vol. 3, Wiley — ch. 8 charge-control formulation',
      'GE 2N1308 datasheet (1962-vintage; alldatasheet.com archival mirror) — V_CE(sat), h_FE, switching parameters',
    ],
  },
  complexPlanePosition: {
    real: 0.24,
    imaginary: 0.62,
    magnitude: Math.sqrt(0.24 ** 2 + 0.62 ** 2),
    angle: Math.atan2(0.62, 0.24),
  },
};
