import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.53 — Early IC digital logic and core memory: command-sequencer design,
 * propagation delay budget, and the Gemini 12 onboard computer architecture.
 *
 * Generated by the v1.49.581 ELC Wave-1 backfill (Domain 9 first entry).
 * Cross-references: NASA 1.53 (Gemini 12, last Gemini, 1966-11-11; manual
 * rendezvous after radar failure), MUS 1.53 (cadence-after-deceptive-resolution
 * structural rhyme).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const earlyIcDigitalLogicSequencer: RosettaConcept = {
  id: 'elc-1.53-early-ic-digital-logic-sequencer',
  name: 'Propagation-delay budget for early-IC digital command sequencers',
  domain: 'electronics',
  description:
    'A digital-logic primitive describing how a synchronous machine selects its clock period from ' +
    'the propagation-delay-budget inequality t_clock >= N_stages * t_PD_max + t_setup + t_hold + ' +
    't_skew, where N_stages is the deepest combinational-logic chain between two registers and ' +
    't_PD_max is the gate family worst-case propagation delay. The pedagogical anchor is the IBM ' +
    'Federal Systems Gemini Guidance Computer (Owego, NY, 1965-1966), which used DTL Solid Logic ' +
    'Technology hybrid modules running with ~12 ns t_PD against a 7.143 kHz / 140 µs major-cycle ' +
    'clock. The 1500x slack between gate speed and clock period was intentionally absorbed into ' +
    'core-memory cycle time, power-dissipation budget, clean clock-subdivision arithmetic, ' +
    'temperature margin, voltage margin, aging margin, and noise margin. The flight outcome was ' +
    'Aldrin\'s manual rendezvous on Gemini 12 (1966-11-11) after the rendezvous radar failed: the ' +
    'computer crunched the slant-range arithmetic in real time on a clock its designers had picked ' +
    'to be slow enough that no plausible failure could ever compromise it.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-sequential-logic-design',
      description:
        'The propagation-delay-budget inequality only applies to synchronous machines with edge-' +
        'triggered flip-flop storage; sequential-logic-design defines those flip-flops, their ' +
        'setup/hold windows, and the synchronous-design rules that the budget enforces',
    },
    {
      type: 'dependency',
      targetId: 'elec-combinational-logic',
      description:
        'N_stages in the inequality is the depth of combinational gates between two registers; ' +
        'optimising the depth via Karnaugh-map / Quine-McCluskey reduction is the proximate ' +
        'design lever for tightening the propagation-delay budget',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.53-cadence-after-deceptive-resolution',
      description:
        'The 1500x slack between gate speed and clock period in the Gemini computer is the ' +
        'structural rhyme of the cadence-after-deceptive-resolution pattern: each is a margin ' +
        'absorbed for resilience rather than for performance, and each is what allows the system ' +
        'to recover from an unexpected event (Gemini\'s rendezvous-radar failure; the song\'s ' +
        'deceptive cadence) without violating the underlying form',
    },
  ],
  metadata: {
    elcDegree: '1.53',
    domain: 9,
    domainName: 'Digital logic',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware: 'IBM Federal Systems Gemini Guidance Computer (1965-1966) — 39-bit word, 4096-word ferrite-core memory, 7.143 kHz clock, ~135 instruction set, ~1000 SLT DTL hybrid modules; Owego NY build site',
    keyEquation: 't_clock >= N_stages * (t_PHL_or_PLH_max) + t_setup + t_hold + t_skew',
    benchReplication: {
      activeNandGate: 'SN7400N (Texas Instruments) standard TTL — 10-15 ns t_PD; OR SN74HC00N CMOS pin-equivalent (~8 ns at +5V)',
      eraOriginal: 'IBM SLT (Solid Logic Technology) hybrid thick-film DTL NAND modules; 5-input NAND with internal level-shifter pair + PNP inverter',
      programCounter: 'CD4017BE decade counter wired as 5-stage walking-one ring',
      clockGenerator: 'Arduino Nano (ATmega328P) Timer1 divider OR NE555 RC oscillator at ~7 kHz',
      ferriteCoreSurrogate: '1 µH axial inductor + 47 Ω damping resistor',
      cLoadSweep: '5 / 18 / 50 / 100 / 200 pF (DIP-switch selectable; traces propagation delay vs RC charging)',
    },
    references: [
      'Mano & Ciletti, Digital Design (5e, Pearson 2012), ch. 3 — gate-level design, propagation delay, fan-out',
      'Wakerly, Digital Design: Principles and Practices (4e, Prentice Hall 2005), §3 — DTL/TTL families, noise margins',
      'Horowitz & Hill, The Art of Electronics (3e, Cambridge 2015), §10.1-§10.3 — digital logic families, glitches, metastability',
      'TI SN7400 datasheet, https://www.ti.com/lit/ds/symlink/sn7400.pdf',
      'Texas Instruments AN-243, "Bipolar Digital Integrated Circuits" (1966)',
      'IBM Federal Systems Division, Gemini Guidance Computer Programming Reference Manual (1965, NASA NTRS document N66-25502)',
      'Davis, E. M., et al. "Solid Logic Technology: Versatile, High-Performance Microelectronics", IBM Journal of Research and Development 8 (1964) 102-114',
      'NASA SP-138, Gemini Summary Conference (1967), §IV onboard guidance computer architecture and Gemini 12 rendezvous flight performance',
      'Hall, Eldon C., Journey to the Moon: The History of the Apollo Guidance Computer (AIAA 1996), ch. 2 — Gemini computer as Apollo predecessor',
      'Aldrin, Buzz, Men From Earth (Bantam 1989) — Gemini 12 rendezvous and the manual procedure used after radar failure',
    ],
  },
  complexPlanePosition: {
    real: 0.53,
    imaginary: 0.71,
    magnitude: Math.sqrt(0.53 ** 2 + 0.71 ** 2),
    angle: Math.atan2(0.71, 0.53),
  },
};
