import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.26 — Master-clock single-point-of-failure: oscillator startup
 * transient, sequencer-watchdog timer absence, and the Ranger 4 silent-
 * impact failure mode.
 *
 * Generated by the v1.49.581 ELC Wave-3 Phase C backfill (slot E3-H,
 * domain 13 second-entry, era si-discrete). Architectural-axis complement
 * to the component-axis reliability primitive registered at
 * elc-1.42-mtbf-derating-long-duration.
 *
 * Cross-references: NASA 1.26 (Ranger 4 silent-impact narrative), MUS 1.26
 * (dependence-form analog). Subject derivation rubric at
 * .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md.
 */
export const masterClockSinglePointFailure: RosettaConcept = {
  id: 'elc-1.26-master-clock-single-point-failure',
  name: 'Master-clock single-point-of-failure and watchdog supervision',
  domain: 'electronics',
  description:
    'A reliability-engineering primitive describing the architectural-axis ' +
    'reliability budget for serially-dependent spacecraft subsystems that share a ' +
    'common master clock. The composition rule λ_system ≥ λ_clock for the single- ' +
    'clock case becomes λ_clock² × t_restart for redundant clocks (six-orders-of- ' +
    'magnitude reliability improvement) and λ_clock × λ_supervisor × t_window for ' +
    'an independent watchdog supervisor (three-orders improvement at one-tenth the ' +
    'architectural cost). Ranger 4 (1962-04-23) flew with single-clock topology and ' +
    'no watchdog; a tantalum-bypass dendrite short on the +12 V CC&S supply rail ' +
    'collapsed the master-clock oscillator at T+14m; the divider chain ceased to ' +
    'count; the sequencer froze; the spacecraft impacted the lunar far side three ' +
    'days later returning no telemetry — the silent-impact mode that drove every ' +
    'subsequent JPL planetary spacecraft to redundant-clocks-plus-watchdog ' +
    'architecture, codified in NASA-STD-8719.13C §4. The pedagogical primitive is ' +
    'the SPOF composition rule: when subsystems share a coupling element the ' +
    'system reliability is gated by that element alone, regardless of downstream ' +
    'redundancy; the architectural fix is to break the coupling (redundancy) or to ' +
    'monitor it (independent supervisor on independent clock physics).',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-pierce-oscillator-loop-gain',
      description:
        'The master-clock chain begins with a Pierce-topology quartz oscillator; ' +
        'understanding the Butterworth-Van Dyke crystal model and the loop-gain ' +
        'condition |A × β| > 1 at series resonance is prerequisite to analysing ' +
        'the cold-start transient and the marginal-supply failure mode',
    },
    {
      type: 'dependency',
      targetId: 'elc-1.42-mtbf-derating-long-duration',
      description:
        'ELC 1.42 establishes the component-axis reliability budget via the MIL- ' +
        'HDBK-217 multiplicative π-factor model; ELC 1.26 builds on that base to ' +
        'establish the architectural-axis reliability budget via the SPOF ' +
        'composition rule. Both axes must be exercised for a flight build',
    },
    {
      type: 'dependency',
      targetId: 'elec-tantalum-capacitor-dendrite-failure',
      description:
        'The Ranger 4 silent-impact failure was triggered by a tantalum-bypass ' +
        'dendrite-growth short on the +12 V CC&S rail; the failure mechanism is ' +
        'a slow electrochemical growth of conductive silver dendrites across the ' +
        'wet-tantalum dielectric, accelerated by elevated temperature and DC bias',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.26-dependence-form',
      description:
        'The SPOF coupling-element framing has a structural rhyme in musical ' +
        'dependence-form: the moment in a phrase when one voice is the sole ' +
        'carrier of the harmonic information and the rest of the texture depends ' +
        'on it. When that voice falters there is no recovery mechanism in the ' +
        'texture itself; the listener perceives the silence as architectural — ' +
        'the same way that the Ranger 4 silent-impact was perceived as the ' +
        'architectural failure of the spacecraft, not just the failure of the ' +
        'capacitor that caused it',
    },
  ],
  metadata: {
    elcDegree: '1.26',
    domain: 13,
    domainName: 'Reliability & failure modes',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Ranger 4 (1962-04-23) Block II Central Computer & Sequencer (CC&S) master- ' +
      'clock chain — JPL-built quartz-crystal Pierce oscillator + emitter-follower ' +
      'buffer + 8-stage discrete-flip-flop binary divider tree producing 1 Hz ' +
      'mission-event clock + 7-event sequencer; powered from a single +12 V ' +
      'regulated bus with one tantalum bypass capacitor; NO watchdog supervisor; ' +
      'silent-impact failure on lunar far side 1962-04-26 (JPL TR 32-242 §3)',
    keyEquation:
      'λ_system ≥ λ_clock                         (single-clock; Ranger 4 as-flown) ' +
      'λ_system ≈ λ_clock² × t_restart             (redundant clocks) ' +
      'λ_system ≈ λ_clock × λ_supervisor × t_window (independent watchdog supervisor)',
    benchReplication: {
      activeBJT: 'P2N2222ABU (ON Semiconductor) for Pierce amp + emitter follower',
      eraOriginalOscillator: 'Bulova precision-quartz oscillator module, MIL-PRF-55310, ±10 ppm @ 25 °C',
      modernOscillator: 'Epson SG-3030CM TCXO, ±0.5 ppm @ 25 °C, ≤10 ms startup typical',
      dividerTree: '74HC4040 14-stage binary ripple counter (replaces 8 discrete-FF cards)',
      watchdog: 'NE555 monostable retriggered on each div_out edge; 1.5 s timeout via 1.5 MΩ × 1 µF',
      failureInjection: 'SPDT switch in parallel with C_BYPASS — manually replicates the dendrite-short of Ranger 4',
    },
    spiceArtifact: 'spice/flight-circuit.cir — Pierce + buffer + behavioural divider + sequencer + failure-injection switch + (commented) watchdog block',
    referencePapers: [
      'Hall 1977, Lunar Impact: A History of Project Ranger (NASA SP-4210), ch. 3',
      'JPL TR 32-242, Ranger 4 Mission Operations Report (1963), §3',
      'MIL-HDBK-217F Notice 2, §10 (oscillator failure-rate model)',
      'NASA-STD-8719.13C, §4 (independent watchdog timer requirement)',
      'Frerking 1978, Crystal Oscillator Design and Temperature Compensation',
      'Vig (current), Quartz Crystal Resonators and Oscillators (ARL tutorial)',
    ],
    crossTrack: {
      nasa: 'NASA 1.26 — Ranger 4: The Silent Arrival',
      mus: 'MUS 1.26 — Dependence-form analogue',
    },
  },
};
