import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.42 — MTBF, derating, and electromigration in long-duration spacecraft:
 * the Gemini 7 14-day environmental telemetry reliability validation.
 *
 * Generated by the v1.49.581 ELC Wave-1 Phase C backfill (slot E1-E,
 * domain 13 first-entry, era si-discrete).
 *
 * Cross-references: NASA 1.42 (Gemini 7 14-day endurance flight), MUS 1.42
 * (musical analog of the durative endurance form). Subject derivation
 * rubric at .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md.
 */
export const mtbfDeratingLongDuration: RosettaConcept = {
  id: 'elc-1.42-mtbf-derating-long-duration',
  name: 'MTBF and component derating in long-duration spacecraft electronics',
  domain: 'electronics',
  description:
    'A reliability-engineering primitive describing how the MIL-HDBK-217 multiplicative ' +
    'failure-rate model decomposes across acceleration factors (π_T temperature, π_S voltage ' +
    'stress, π_R rated-power, π_E environment, π_Q quality, π_C construction) so that a ' +
    'designer can trade independently across each dimension. The composable model converts a ' +
    'silicon BJT with a nominal full-ratings failure rate of 5e-8/hour into a derated flight ' +
    'failure rate of roughly 2e-9/hour by deciding to run the part at I_C/I_C_max ≈ 0.001 and ' +
    'V_CE/V_CEO ≈ 0.2 in a hermetic package with screened parts at moderate junction ' +
    'temperature — a 25× failure-rate reduction that composes through 6 transistors and 336 ' +
    'hours of continuous operation to predict effectively zero failures over Gemini 7\'s ' +
    '14-day endurance flight (Borman & Lovell, 1965-12-04 to 1965-12-18). The empirical ' +
    'observation matched: zero documented signal-stage transistor failures across the full ' +
    'Gemini-Apollo crewed-spacecraft corpus (~10^7 device-hours at the derated bias point), ' +
    'the dataset that pinned the 1974 MIL-HDBK-217B revision to flight-validated numbers.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-bjt-bias-point',
      description:
        'The derating equation operates on the BJT bias point (I_C, V_CE, T_J) directly; ' +
        'understanding common-emitter biasing and the SOA quarter-circle is prerequisite to ' +
        'applying the MIL-HDBK-217 acceleration factors',
    },
    {
      type: 'dependency',
      targetId: 'elec-bathtub-curve',
      description:
        'Burn-in screening (the π_Q quality factor) operates on the infant-mortality region ' +
        'of the bathtub-curve reliability model; the derated flight bias point places the part ' +
        'in the flat middle region after screening removes early-life failures',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.42-durative-endurance',
      description:
        'The MIL-HDBK-217 multiplicative composition (factors compose to drive the failure rate ' +
        'down by orders of magnitude) is the structural rhyme of the durative-form endurance ' +
        'piece MUS 1.42 catalogues: a long-form composition stays coherent because each ' +
        'sustained pitch is well within its acoustic envelope, the same way each derated ' +
        'transistor is well within its electrical envelope',
    },
  ],
  metadata: {
    elcDegree: '1.42',
    domain: 13,
    domainName: 'Reliability & failure modes',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Gemini 7 cabin-environment sensor chain — thermistor bridge + 2N2222 differential pair + ' +
      'emitter follower + 1.6 Hz LP filter + telemetry feed; three identical channels powered ' +
      'from the +28V fuel-cell bus regulated to +12V; flew 330 h 35 min 1965-12-04/18',
    keyEquation:
      'λ_p = λ_b × π_T × π_S × π_R × π_E × π_Q × π_C ; where each π_i ≤ 1 captures one ' +
      'derating axis; for Gemini 7 2N2222 at the flight bias point the π-product ≈ 0.04, ' +
      'driving λ_p to ~2e-9/hour (effectively zero failures over 14-day flight)',
    benchReplication: {
      activeBJT: 'P2N2222ABU (ON Semiconductor) — modern descendant, same JEDEC die',
      eraOriginal: 'Motorola 2N2222 metal-can TO-18, JANTX-screened, 168 h burn-in',
      bridgeElement: 'Vishay NTCLE100E3103 NTC10K B-3950 thermistor',
      shaperFc: '1.6 Hz two-pole RC LP (telemetry-rate noise rejection)',
      deratingRatios: 'I_C/I_C_max = 0.00125, V_CE/V_CEO = 0.16, P_D/P_max = 0.010',
    },
    references: [
      'MIL-HDBK-217F Notice 2 (1995) — Reliability Prediction of Electronic Equipment',
      'NASA SP-138 (1967) — Gemini Summary Conference, Section IV',
      'Black, J.R. — Electromigration, IEEE Trans. ED-16 (1969) 338',
      'JEDEC JEP122H (2016) — Failure Mechanisms and Models for Semiconductor Devices',
      'NASA-PRC-700 — Standard for Application-Specific Reliability Assurance',
      'ECSS-Q-ST-30-11C — Derating of Electronic Components',
      'Pecht & Nash — Predicting the Reliability of Electronic Equipment, Proc. IEEE 82 (1994) 992',
      'Hirsch — Modes of Electronic Failure (Wiley 1985), ch. 3 — secondary breakdown',
      'ON Semiconductor P2N2222A datasheet, https://www.onsemi.com/pdf/datasheet/p2n2222a-d.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.42,
    imaginary: 0.13,
    magnitude: Math.sqrt(0.42 ** 2 + 0.13 ** 2),
    angle: Math.atan2(0.13, 0.42),
  },
};
