import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.39 — Redundant-pair thruster-driver reliability under cycle-life
 * and shock loading: the Gemini 3 OAMS solenoid driver pair (Molly Brown,
 * 1965-03-23, Grissom + Young).
 *
 * Generated by the v1.49.581 ELC Wave-6 Phase C backfill (slot E6-A,
 * domain 13 third-entry, era si-discrete). Redundancy-axis complement to
 * the interconnect-axis primitive registered at
 * elc-1.17-ground-pin-abort-failure, the architectural-axis primitive
 * registered at elc-1.26-master-clock-single-point-failure, and the
 * component-axis primitive registered at
 * elc-1.42-mtbf-derating-long-duration. Together the four cover the
 * Domain-13 failure-mode taxonomy from physical interconnect SPOF
 * through component derating, architectural SPOF, and redundancy-CMF.
 *
 * Cross-references: NASA 1.39 (Gemini 3 mission narrative), MUS 1.39
 * (redundant-pair voicing analog). Subject derivation rubric at
 * .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md.
 */
export const redundantPairThrusterDriver: RosettaConcept = {
  id: 'elc-1.39-redundant-pair-thruster-driver-reliability',
  name: 'Redundant-pair n+1 majority-voting thruster-driver reliability with explicit common-mode-failure budget',
  domain: 'electronics',
  description:
    'A reliability-engineering primitive describing the redundant-pair n+1 majority-voting ' +
    'topology used on the Gemini Orbit Attitude and Maneuver System (OAMS) thruster-driver ' +
    'chain. Each of sixteen 25-lbf hypergolic MMH/N2O4 thrusters on Gemini 3 (Molly Brown, ' +
    '1965-03-23) was actuated by a solenoid valve driven by a redundant pair of low-side ' +
    'silicon BJT drivers (RCA 2N3055 JANTX in TO-3 hermetic), OR-summed through quorum diodes ' +
    'onto the coil node so that any single open-circuit driver failure left the survivor ' +
    'carrying the full coil current. The pedagogical primitive is the n+1 redundancy ' +
    'composition rule with explicit common-mode-failure (CMF) budget: P_pair = (1−β) × ' +
    'P_single² + β × P_single ≈ β × P_single for small P_single, where β is the IEC 61508 ' +
    'β-factor (fraction of failures that are common-mode). For the Gemini 3 OAMS at ' +
    'P_single = 2 × 10⁻⁷ per mission (per MIL-HDBK-217F derating: π_T × π_S × π_R × π_E × ' +
    'π_Q × π_C × π_cycle × π_shock ≈ 0.12) and β ≈ 0.05, the pair failure probability is ' +
    '~10⁻⁸ per mission — a factor of 20 improvement over single-driver, NOT the seven ' +
    'orders of magnitude that the independent-failure analysis predicts. The first lesson ' +
    'is therefore that the value of redundancy is set by the CMF rate, not by the single- ' +
    'channel rate; CMF mitigation (physical separation, bus-side redundancy, radiation- ' +
    'hardening, workmanship discipline) must come BEFORE adding more paired channels. ' +
    'On Molly Brown across approximately 1700 OAMS firings during the three-orbit four-' +
    'hour-fifty-two-minute mission, zero pair-failures were documented (NASA SP-138 §IV-D), ' +
    'consistent with the predicted 10⁻⁸ per mission. NASA TN D-4422 (1968) was the canonical ' +
    'OAMS FMEA document and directly informed the MIL-STD-1629A FMECA standard published in ' +
    '1980. The redundant-pair architecture continued through Apollo, Skylab, and Shuttle ' +
    'reaction-control systems.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-bjt-saturation-power-driver',
      description:
        'The redundant-pair driver operates each BJT in low-side saturation at 4 A peak ' +
        'coil current and ~0.7 V V_CE_sat; understanding common-emitter saturation, the ' +
        'I_C/I_B knee, and SOA quarter-circle is prerequisite to applying the per-driver ' +
        'derating that drops the single-channel failure rate to the level where pair ' +
        'redundancy provides meaningful margin',
    },
    {
      type: 'dependency',
      targetId: 'elec-flyback-diode-inductive-clamp',
      description:
        'The solenoid-coil inductive-kick at de-energise is clamped by the flyback diode ' +
        'across the coil; without flyback, V_CE on the BJT collectors rises above V_CEO ' +
        'and the driver enters secondary breakdown. Flyback-diode continuity is one of ' +
        'the FMECA single-point-of-failure modes that must be verified at integration',
    },
    {
      type: 'dependency',
      targetId: 'elc-1.17-ground-pin-abort-failure',
      description:
        'ELC 1.17 establishes the interconnect-axis SPOF primitive (single-pin abort-sense ' +
        'ground-circuit failure). ELC 1.39 layers the redundancy-axis primitive (n+1 pair- ' +
        'redundancy with β-factor CMF budget) onto the same Domain-13 taxonomy. The ' +
        'physical-interconnect SPOF rule of 1.17 is one of the CMF mechanisms that the ' +
        'pair-redundancy of 1.39 must explicitly account for in the β estimate',
    },
    {
      type: 'dependency',
      targetId: 'elc-1.26-master-clock-single-point-failure',
      description:
        'ELC 1.26 introduced the SPOF composition rule (system reliability gated by the ' +
        'coupling element). ELC 1.39 specialises that rule for the redundant-pair case: ' +
        'when the coupling element is the +28 V supply bus, system reliability is gated by ' +
        'the bus-side failure rate even with paired drivers. The β-factor analysis ties ' +
        'the architectural framing of 1.26 to the redundancy-axis primitive of 1.39',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.39-redundant-pair-voicing',
      description:
        'The redundant-pair driver topology has a structural rhyme in musical redundant- ' +
        'pair voicing: the moments in ensemble writing when two voices carry the same ' +
        'melodic line in unison, allowing one voice to falter without losing the line\'s ' +
        'continuity. The OAMS driver-pair is the engineering equivalent: two transistors ' +
        'carry the same firing command in unison; either one can drop out without losing ' +
        'the firing. The CMF analog is when both voices share the same breath-mark or ' +
        'follow the same conductor cue — a conductor lapse takes both voices out at the ' +
        'same instant, regardless of how independent the parts are notated',
    },
  ],
  metadata: {
    elcDegree: '1.39',
    domain: 13,
    domainName: 'Reliability & failure modes',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Gemini 3 (Molly Brown, 1965-03-23, Grissom + Young, three orbits, 4h52m) ' +
      'McDonnell-built Spacecraft 3 OAMS attitude/translation thruster cluster — ' +
      'sixteen Rocketdyne SE-7-2 hypergolic 25-lbf bipropellant thrusters (Aerozine-50 ' +
      '+ N2O4) each driven by redundant pair of RCA / Motorola 2N3055-class silicon NPN ' +
      'power BJTs in TO-3 hermetic metal can on the OAMS Sequencer Logic A50 module, ' +
      'OR-summed through 1N1184-class quorum diodes onto the solenoid valve coil ' +
      '(0.7 H, 7 Ω, 4 A peak); fed from the +28 VDC fuel-cell-conditioned bus through ' +
      'the Power Conditioning and Distribution Unit (PCDU); GMK squib-fired ' +
      'propellant-isolation valves on each tank arm the OAMS once on orbit; described ' +
      'in NASA TN D-4422 Gemini OAMS Failure Mode and Effects Analysis (1968) and ' +
      'NASA SP-138 Gemini Summary Conference (1967), Section IV-D',
    keyEquation:
      'P_fail_pair = (1−β) × P_fail_single² + β × P_fail_single ≈ β × P_fail_single ' +
      '(for small P_fail_single)                                                    [β-factor] ' +
      'P_fail_single = λ_b × π_T × π_S × π_R × π_E × π_Q × π_C × π_cycle × π_shock × t ' +
      'CN = β × α × λ_p × t                                       (MIL-STD-1629A criticality) ' +
      '— for Gemini 3 OAMS: P_single ≈ 2e-7/mission, β ≈ 0.05, P_pair ≈ 1e-8/mission, ' +
      'across 16 thrusters with thruster-level redundancy P_axis_loss ≈ 4e-16/mission',
    benchReplication: {
      activeBJT: 'ON Semi 2N3055G in TO-3 (modern descendant of era-original RCA 2N3055 JANTX hermetic)',
      eraOriginalBJT: 'RCA 2N3055 JANTX in TO-3 hermetic metal can, 168 h burn-in at +150°C, parametric retest',
      quorumDiodes: '1N4001 (modern); era-original 1N1184 fast-recovery silicon rectifier JANTX-screened',
      flybackDiode: '1N4001 (50 V / 1 A, fast enough for L/R = 100 ms coil)',
      load: 'TE Connectivity 1393808-1 24 VDC sealed armature relay (replaces era-original Allied Control SM-series)',
      driveCmd: 'NE555 monostable + TIP140 buffer (50 ms / 5 V firing-pulse simulation; replaces OAMS Sequencer Logic A50)',
      failureInjection: 'Two SPDT toggles on driver bases (kill_Q1A / kill_Q1B: NORMAL / OPEN / SHORTED) + third SPDT in series with bus supply (kill_BUS for CMF demonstration)',
      currentShunt: 'Ohmite LVK25R010FER 10 mΩ 1 W for I_coil scope monitoring',
      deratingRatios: 'I_C/I_C(max) = 0.27, V_CE/V_CEO = 0.012 saturated, P_D/P_max = 0.024',
    },
    spiceArtifact: 'spice/flight-circuit.cir — +28 V bus + dual 2N3055-class drivers + 1N4001 quorum diodes + 0.7 H/7 Ω solenoid coil + 1N4001 flyback + GMK squib-actuator chain with two-key safe/arm + parameter-sweep failure injection (kill_Q1A, kill_Q1B, kill_BUS)',
    referencePapers: [
      'NASA TN D-4422 (1968), Gemini OAMS Failure Mode and Effects Analysis (Manned Spacecraft Center)',
      'NASA SP-138 (1967), Gemini Summary Conference, Section IV-D',
      'MIL-STD-1629A (1980), Procedures for Performing FMECA',
      'MIL-HDBK-217F Notice 2 (1995), §5 (BJT) and §17 (solenoid)',
      'IEC 61508-6 (2010), β-factor analysis for SIL determination',
      'JEDEC JEP122H (2016), Failure Mechanisms and Models for Semiconductor Devices',
      'Mosher (1973), Squib Reliability in Aerospace Applications, NASA TM X-66293',
      'Black (1969), Electromigration: A Brief Survey, IEEE Trans. ED-16 338',
      'Hirsch (1985), Modes of Electronic Failure (Wiley), ch. 3 — secondary breakdown',
      'Kosmo (1971), Hypergolic Propellant Valve-Seat Erosion, JANNAF Combustion Meeting',
      'Hammer (ed., 1993), Product Safety Management and Engineering (Prentice-Hall), ch. 4 — quorum-voting',
      'Hacker & Grimwood (1977), On the Shoulders of Titans: A History of Project Gemini, NASA SP-4203, ch. 12',
      'ON Semiconductor 2N3055 datasheet (2020), rev 5',
      'TE Connectivity 1393808-1 datasheet (2024), rev 9',
    ],
    crossTrack: {
      nasa: 'NASA 1.39 — Gemini 3 (Molly Brown): The First Crewed Gemini',
      mus: 'MUS 1.39 — Redundant-pair voicing analogue',
    },
  },
  complexPlanePosition: {
    real: 0.39,
    imaginary: 0.13,
    magnitude: Math.sqrt(0.39 ** 2 + 0.13 ** 2),
    angle: Math.atan2(0.13, 0.39),
  },
};
