import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.25 — Single-sensor reliability under partial-information operations:
 * the Mercury-Atlas 6 Segment 51 stuck-switch false-alarm and the
 * redundant-confirmation rule (Friendship 7, Glenn 1962-02-20).
 *
 * Generated by the v1.49.581 ELC Wave-7 Phase C backfill (slot E7-D,
 * domain 13 fourth-entry; CLOSES domain 13 to its 4/4 target). Information-
 * axis complement to the interconnect-axis primitive registered at
 * elc-1.17-ground-pin-abort-failure, the architectural-axis primitive at
 * elc-1.26-master-clock-single-point-failure (referenced by ID;
 * concept itself is forward in build order), and the redundancy-axis
 * primitive at elc-1.39-redundant-pair-thruster-driver-reliability (also
 * forward in build order; this concept lists the relationship by id only
 * via the SPOF-taxonomy frame). Together the four axes — interconnect
 * (1.17), component, redundancy, information (1.25) — close the SPOF
 * taxonomy that Domain 13 was allocated to span.
 *
 * Cross-references: NASA 1.25 (Friendship 7 Segment-51 narrative + the
 * canonical artifacts/circuits/segment51-telemetry.md fact-pattern source),
 * MUS 1.25 (redundant-confirmation voicing analog). Subject derivation
 * rubric at .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md.
 */
export const singleSensorSegment51FalseAlarm: RosettaConcept = {
  id: 'elc-1.25-single-sensor-segment51-false-alarm',
  name: 'Single-sensor SPOF reliability and the no-single-sensor-decision flight rule',
  domain: 'electronics',
  description:
    'A reliability-engineering primitive describing the information-axis ' +
    'single-point-of-failure rule for sense circuits gating flight-critical ' +
    'decisions. The governing relation is that a sense bit B sourced from a ' +
    'single sensor with no redundant-confirmation channel cannot validate its ' +
    'own reading: P(B reads "event" | event) and P(B reads "event" | no event) ' +
    'are both non-trivial in the presence of stuck-sensor failure modes, and ' +
    'no information channel exists in the chain to distinguish the two cases. ' +
    'On Mercury-Atlas 6 / Friendship 7 (Glenn 1962-02-20) Segment 51 of the ' +
    'McDonnell PCM-FM telemetry frame carried the heat-shield-deploy / ' +
    'landing-bag indicator from a single reed-switch contact through one ' +
    'ITT-Cannon umbilical pin into a discrete-germanium pull-up driver and ' +
    'bit-latch. Shortly after orbit-1 capture the bit transitioned to ' +
    'UNLATCHED; flight director Chris Kraft and Mercury Control made the ' +
    'maximin judgement-under-ambiguity call to retain the retropack on the ' +
    'heat shield through reentry as a backup mechanical restraint. ' +
    'Post-flight inspection (NASA SP-6 1962 §V; Swenson, Grimwood, Alexander ' +
    'NASA SP-4201 ch. 13 §3) confirmed the heat shield was latched the entire ' +
    'flight; the fault was a stuck reed-switch contact in the single-sensor ' +
    'sense path, the armature having drifted into a stuck-open mechanical ' +
    'state under accumulated launch vibration. The architectural fix on ' +
    'subsequent Mercury capsules was parallel-redundant reed switches with ' +
    '2-of-2 voting before the bit was latched: P_pair = (1−β) × P_single² + ' +
    'β × P_single ≈ β × P_single, where β is the IEC 61508 common-mode-failure ' +
    'coefficient (~0.05 for separately routed independent switches), driving ' +
    'the per-flight false-alarm probability from ~10⁻⁵ to ~5 × 10⁻⁷. The fix ' +
    'propagated forward into every later crewed-spacecraft program and was ' +
    'eventually formalised in MIL-STD-1629A (1980) FMECA as the no-single-' +
    'sensor-decision flight rule. The pedagogical primitive is therefore the ' +
    'composition of three corollaries: (1) the no-detection corollary — a ' +
    'sense chain with no redundant-confirmation channel cannot detect its own ' +
    'failure; (2) the asymmetric-cost decision rule (maximin) — under partial ' +
    'information pick the path whose worst-case outcome is recoverable; and ' +
    '(3) architectural fix > component fix — adding parallel-redundant ' +
    'sensors with quorum logic eliminates the credible-failure path entirely, ' +
    'whereas component-axis improvements have asymptotic limits at the ' +
    'single-sensor failure rate. ELC 1.25 closes Domain 13 to its 4/4 target ' +
    'by spanning the full SPOF taxonomy at the information axis, complementing ' +
    'the interconnect-axis primitive established at ELC 1.17 (Mercury-Redstone ' +
    '1 single-pin abort-sense ground-circuit failure).',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-bjt-saturation-level-translator',
      description:
        'The driver in the Segment-51 chain operates as a saturated common- ' +
        'emitter level translator (V_BE(on) ~ 0.65 V silicon / 0.30 V ' +
        'germanium, V_CE(sat) ~ 0.2 V); understanding common-emitter ' +
        'saturation, the I_C/I_B knee, and SOA quarter-circle is prerequisite ' +
        'to recognising why the driver itself is reliable while the chain as ' +
        'a whole is not — the failure mode is upstream of the driver and the ' +
        'driver faithfully reports whatever the sense node says.',
    },
    {
      type: 'dependency',
      targetId: 'elc-1.17-ground-pin-abort-failure',
      description:
        'ELC 1.17 establishes the interconnect-axis SPOF primitive (single-pin ' +
        'abort-sense ground-circuit failure on Mercury-Redstone 1, 1960-11-21). ' +
        'ELC 1.25 layers the information-axis primitive (single sensor with no ' +
        'redundant-confirmation chain on Friendship 7, 1962-02-20) onto the same ' +
        'Domain-13 taxonomy. Both primitives admit the same architectural fix ' +
        'pattern (parallel-redundant pin assignment with quorum logic for 1.17; ' +
        'parallel-redundant sensors with quorum logic for 1.25) but on different ' +
        'axes. The 1.17 lesson — that interconnect-axis SPOFs are addressed by ' +
        'redundancy at the architectural level rather than by component improvement ' +
        '— carries forward directly into the 1.25 architectural fix.',
    },
    {
      type: 'dependency',
      targetId: 'reed-switch-armature-drift',
      description:
        'The actual MA-6 failure mode was mechanical stuck-contact in the reed ' +
        'switch under accumulated launch vibration loading. Reed-switch armature ' +
        'gap manufacturing tolerance, vibration-induced settling, and the JEDEC ' +
        'JEP122H drift taxonomy are all prerequisite to understanding why the ' +
        'specific component failed; ELC 1.25 then makes the architectural ' +
        'argument that no matter how reliable the reed switch, single-sensor ' +
        'gating of a flight-critical bit cannot detect its own failure.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.25-redundant-confirmation-voicing',
      description:
        'The redundant-confirmation pattern has a structural rhyme in ' +
        'ensemble-writing where two voices confirm a melodic event before ' +
        'the listener accepts it as a melodic event — the same logic as ' +
        'the 2-of-2 quorum gate. The ensemble parallel: a single voice ' +
        'declaring a melodic gesture with no second voice to confirm is ' +
        'easily mistaken for an ornament; two voices in unison make the ' +
        'gesture unambiguous. Mercury MA-6 forced the same composition rule ' +
        'on flight-critical sense chains: do not let a single voice (single ' +
        'sensor) declare an event that cannot be revisited.',
    },
  ],
  metadata: {
    elcDegree: '1.25',
    domain: 13,
    domainName: 'Reliability & failure modes',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware:
      'Mercury-Atlas 6 / Friendship 7 (Glenn 1962-02-20, three orbits, 4h55m) ' +
      'McDonnell-built Spacecraft 13 PCM-FM telemetry encoder (Segment 51 = ' +
      'heat-shield deploy / landing-bag indicator) — single reed-switch contact ' +
      'on the heat-shield latch arm + 5.1 kΩ pull-up to +28 V mercury-cell ' +
      'sense bus + AC-blocking + GE 2N1308-class germanium NPN pull-up driver ' +
      '+ Schmitt threshold + bit-latch in the discrete-RC encoder; flown with ' +
      'no parallel-redundant sense path on the same indicator; in-flight ' +
      'UNLATCHED reading post-orbit-1 was traced post-flight to a stuck reed ' +
      'contact whose armature had drifted into a stuck-open state under ' +
      'launch vibration; heat shield was latched the entire flight per NASA ' +
      'SP-6 §V post-flight inspection',
    keyEquation:
      'P(false alarm | single sensor) ≈ P(stuck) ≈ 10⁻⁵ per flight ' +
      '                                     [single-sensor SPOF rate]\n' +
      'P(false alarm | parallel-pair, β-factor) ≈ β × P(stuck) ≈ 5 × 10⁻⁷ ' +
      '                                     [2-of-2 with β ≈ 0.05]\n' +
      'P(false alarm | 2-of-3 quorum) ≈ β² × P(stuck)³ + corrections ' +
      '                                     [dominated entirely by CMF]\n' +
      '— the architectural fix (parallel-redundant sensors + quorum) drops ' +
      '  the per-flight false-alarm probability by a factor of 10–20× ' +
      '  beyond what any single-sensor screening protocol can achieve, ' +
      '  bounded below by the common-mode-failure coefficient β rather ' +
      '  than by single-sensor reliability.',
    benchReplication: {
      activeBJT: 'ON Semi 2N3904 (modern silicon NPN bench substitute)',
      eraOriginalBJT: 'GE / Sylvania 2N1308 germanium NPN, JANTX-screened TO-5 metal can',
      reedSwitch: 'Standex Electronics MK24 SPST-NO 10–15 AT (modern equivalent)',
      eraOriginalReed: '1961 Coto Coil / Standex / Western Electric reed armature, hand-screened gap',
      bitLatch: 'TI SN74HC74N D-FF (modern surrogate); era-original was discrete cross-coupled germanium-NPN bit-latch',
      schmitt: 'TI LM311N comparator with positive-feedback hysteresis',
      pullUp: 'Vishay 5.1 kΩ 1% 0805 metal-film',
      acBlock: 'Wima MKS2 100 nF film 50 V',
      decoupling: 'Vishay 173D 4.7 µF / 35 V wet tantalum, hermetic, 50% derated',
      failureInjection:
        'Magnet on a translation stage adjacent to K1 (move in/out for nominal CLOSED/OPEN); ' +
        'insulating wedge inside reed envelope mechanically blocks reed armature ' +
        '(magnet adjacent but reed cannot close — reproduces MA-6 stuck-contact failure)',
      architecturalFixDemo:
        'Add parallel K2 with separate magnet, separate routing, separate driver chain; ' +
        'add 2-input AND-gate quorum at bit-latch input — bit reads UNLATCHED only if ' +
        'both K1 and K2 channels report unlatched. Failure path eliminated.',
    },
    spiceArtifact:
      'spice/flight-circuit.cir — +28 V sense bus + 5.1 kΩ pull-up + reed-switch (R_REED ' +
      'parameter) + 2N3904-class level-translator + Schmitt + bit-latch; failure injection ' +
      'via R_REED swept from 50 mΩ (closed) to 100 MΩ (stuck open)',
    referencePapers: [
      'NASA SP-12 (1963), Mercury Project Summary including Glenn\'s Friendship 7 flight summary',
      'NASA SP-6 (1962), Results of the First U.S. Manned Orbital Space Flight: February 20, 1962',
      'Catchpole, J. (2001), Project Mercury: NASA\'s First Manned Space Programme, Springer-Praxis, ch. 14',
      'Swenson, L. S., Grimwood, J. M., & Alexander, C. C. (1966), This New Ocean: A History of Project Mercury, NASA SP-4201, ch. 13',
      'MIL-STD-1629A (1980), Procedures for Performing FMECA',
      'Lloyd, D. K. & Lipow, M. (1962), Reliability: Management, Methods, and Mathematics, Prentice-Hall',
      'MIL-HDBK-217 (1965, original revision), Reliability Prediction of Electronic Equipment',
      'JEDEC JEP122H (2016), Failure Mechanisms and Models for Semiconductor Devices',
      'IEC 61508-6 (2010), β-factor analysis for SIL determination',
      'NASA-PRC-700, Standard for Application-Specific Reliability Assurance',
      'NASA-STD-8729.1A, Planning, Developing, and Managing an Effective R&M Program',
      'ON Semiconductor 2N3904 datasheet (2020), rev 5',
      'Horowitz, P., & Hill, W. (2015), The Art of Electronics (3e), Cambridge UP',
    ],
    crossTrack: {
      nasa: 'NASA 1.25 — Mercury-Atlas 6 / Friendship 7: Glenn First US Orbital Flight',
      mus: 'MUS 1.25 — Redundant-confirmation voicing analogue',
    },
  },
  complexPlanePosition: {
    real: 0.25,
    imaginary: 0.13,
    magnitude: Math.sqrt(0.25 ** 2 + 0.13 ** 2),
    angle: Math.atan2(0.13, 0.25),
  },
};
