/**
 * Calibration wizard orchestrator.
 *
 * Composes the three calibration screens (color-picker, crt-settings,
 * theme-mode) with the wizard state machine. Handles navigation,
 * data accumulation, user-style persistence, CSS bridge application,
 * and engine updates on completion.
 */
import {
  createWizardState,
  nextScreen,
  prevScreen,
  skipScreen,
  getScreenIndex,
  SCREEN_ORDER,
  type WizardState,
} from './wizard-state.js';
import {
  DEFAULT_USER_STYLE,
  saveUserStyle,
  type UserStyle,
} from './user-style.js';
import { applyUserStyleCSS } from './css-bridge.js';
import { createColorPickerScreen, type ColorPickerResult } from './screen-color-picker.js';
import { createCRTSettingsScreen, type CRTSettingsResult } from './screen-crt-settings.js';
import { createThemeModeScreen, type ThemeModeResult } from './screen-theme-mode.js';
import { CRT_DEFAULTS } from '../engine/crt-config.js';
import { getPaletteColors } from '../engine/palette.js';
import type { CRTConfig } from '../engine/crt-config.js';
import type { PalettePreset } from '../engine/palette.js';
import type { Engine } from '../engine/engine.js';

interface WizardOptions {
  container: HTMLElement;
  engine?: Engine | null;
  onComplete: (style: UserStyle) => void;
}

/**
 * Orchestrates the three-screen calibration wizard.
 *
 * Manages screen transitions via the wizard state machine, accumulates
 * user choices, and on completion builds a final UserStyle that is
 * saved to localStorage, applied as CSS custom properties, and sent
 * to the WebGL engine.
 */
export class CalibrationWizard {
  private readonly container: HTMLElement;
  private readonly engine: Engine | null;
  private readonly onCompleteCallback: (style: UserStyle) => void;
  private state: WizardState;

  /** Colors generated by screen 1 (passed to screen 3 as customColors). */
  private generatedColors: string[] | null = null;

  constructor(options: WizardOptions) {
    this.container = options.container;
    this.engine = options.engine ?? null;
    this.onCompleteCallback = options.onComplete;
    this.state = createWizardState();
  }

  /** Mount the wizard into the container, showing the first screen. */
  start(): void {
    this.renderCurrentScreen();
  }

  /** Tear down the wizard DOM. */
  destroy(): void {
    this.container.innerHTML = '';
  }

  /** Render the current screen based on state machine position. */
  private renderCurrentScreen(): void {
    this.container.innerHTML = '';

    const screen = this.state.currentScreen;
    let screenEl: HTMLElement;

    switch (screen) {
      case 'color-picker':
        screenEl = this.renderColorPicker();
        break;
      case 'crt-settings':
        screenEl = this.renderCRTSettings();
        break;
      case 'theme-mode':
        screenEl = this.renderThemeMode();
        break;
    }

    this.container.appendChild(screenEl);

    // Progress indicator
    const progress = document.createElement('div');
    progress.className = 'calibration-progress';
    const stepNum = getScreenIndex(screen) + 1;
    progress.textContent = `Step ${stepNum} of ${SCREEN_ORDER.length}`;
    this.container.appendChild(progress);
  }

  /** Build color picker screen with callbacks wired to state machine. */
  private renderColorPicker(): HTMLElement {
    return createColorPickerScreen({
      onComplete: (result: ColorPickerResult) => {
        this.generatedColors = result.colors;
        this.state = nextScreen(this.state, { anchors: result.anchors });
        this.renderCurrentScreen();
      },
      onSkip: () => {
        this.state = skipScreen(this.state);
        this.renderCurrentScreen();
      },
      engine: this.engine,
    });
  }

  /** Build CRT settings screen with current defaults. */
  private renderCRTSettings(): HTMLElement {
    // Use accumulated CRT data or defaults
    const crtData = this.state.screenData['crt-settings'] as Partial<CRTConfig> | null;
    const defaults: CRTConfig = { ...CRT_DEFAULTS, ...crtData };

    return createCRTSettingsScreen({
      defaults,
      onComplete: (result: CRTSettingsResult) => {
        this.state = nextScreen(this.state, result.crt);
        this.checkComplete();
      },
      onSkip: () => {
        this.state = skipScreen(this.state);
        this.checkComplete();
      },
      onBack: () => {
        this.state = prevScreen(this.state);
        this.renderCurrentScreen();
      },
      engine: this.engine,
    });
  }

  /** Build theme mode screen with accumulated data. */
  private renderThemeMode(): HTMLElement {
    const themeData = this.state.screenData['theme-mode'] as {
      mode: 'light' | 'dark';
      preset: string;
    } | null;

    return createThemeModeScreen({
      defaults: {
        mode: (themeData?.mode ?? DEFAULT_USER_STYLE.mode) as 'light' | 'dark',
        preset: (themeData?.preset ?? DEFAULT_USER_STYLE.palette.preset) as PalettePreset,
      },
      customColors: this.generatedColors,
      onComplete: (result: ThemeModeResult) => {
        this.state = nextScreen(this.state, {
          mode: result.mode,
          preset: result.preset,
        });
        this.checkComplete();
      },
      onSkip: () => {
        this.state = skipScreen(this.state);
        this.checkComplete();
      },
      onBack: () => {
        this.state = prevScreen(this.state);
        this.renderCurrentScreen();
      },
      engine: this.engine,
    });
  }

  /** Check if the wizard is complete or skipped; if so, finalize. */
  private checkComplete(): void {
    if (this.state.status === 'complete' || this.state.status === 'skipped') {
      this.finalize();
    } else {
      this.renderCurrentScreen();
    }
  }

  /** Build final UserStyle, persist, apply, and call onComplete. */
  private finalize(): void {
    const finalStyle = this.buildFinalStyle();

    // Persist to localStorage
    saveUserStyle(finalStyle);

    // Apply CSS custom properties
    applyUserStyleCSS(finalStyle);

    // Update engine if provided
    if (this.engine) {
      this.engine.setPaletteColors(finalStyle.palette.colors);
      this.engine.updateConfig(finalStyle.crt);
    }

    // Notify caller
    this.onCompleteCallback(finalStyle);

    // Clean up wizard DOM
    this.destroy();
  }

  /**
   * Merge accumulated screenData with DEFAULT_USER_STYLE.
   * Skipped screens (null data) fall through to defaults.
   */
  private buildFinalStyle(): UserStyle {
    const sd = this.state.screenData;

    // Color picker data
    const colorPickerData = sd['color-picker'] as { anchors: string[] } | null;
    const anchors = colorPickerData?.anchors ?? DEFAULT_USER_STYLE.palette.anchors;
    const colors = this.generatedColors ?? DEFAULT_USER_STYLE.palette.colors;

    // CRT data
    const crtData = sd['crt-settings'] as Partial<CRTConfig> | null;
    const crt: CRTConfig = { ...CRT_DEFAULTS, ...crtData };

    // Theme mode data
    const themeData = sd['theme-mode'] as {
      mode: 'light' | 'dark';
      preset: string;
    } | null;
    const mode = themeData?.mode ?? DEFAULT_USER_STYLE.mode;
    const preset = (themeData?.preset ?? DEFAULT_USER_STYLE.palette.preset) as PalettePreset;

    // If a preset was chosen (not custom), use the preset colors
    const finalColors = themeData
      ? preset === 'custom'
        ? colors
        : getPaletteColors(preset)
      : colors;

    return {
      palette: {
        preset,
        colors: finalColors,
        anchors,
      },
      crt,
      mode,
      boot: { ...DEFAULT_USER_STYLE.boot },
      calibrated: true,
    };
  }
}
