/**
 * Wasserstein Gradient Flow Langevin try-session -- mathematics (June-2026 arXiv cohort, T2).
 * @module departments/mathematics/try-sessions/wasserstein-gradient-flow-langevin
 */

import type { TrySessionDefinition } from '../../../college/try-session-runner.js';

export const wassersteinGradientFlowLangevinSession: TrySessionDefinition = {
  id: 'math-wasserstein-gradient-flow-langevin-first-steps',
  title: "From Langevin Particles to a Wasserstein Gradient Flow",
  description:
    "Build a small particle simulation of mean-field Langevin dynamics, derive its free-energy functional and self-consistent stationary Gibbs measure, then sweep temperature to watch the low-temperature phase transition concentrate the cloud onto a hidden signal direction.",
  estimatedMinutes: 20,
  prerequisites: [],
  steps: [
    {
      instruction:
        "In a numpy scratch file, define the free-energy functional F(μ)=R(μ)+τ∫μ log μ for a planted-signal risk R(μ)=−½(∫⟨v,x⟩dμ)² with a fixed unit vector v, and label the two competing terms.",
      expectedOutcome:
        "You see that F trades risk-reduction (aligning mass with the signal v) against entropy (spreading mass out), and that τ sets the exchange rate between the two — a competition, not a single objective.",
      hint: "The entropy term alone is minimized by the maximally spread Gaussian; the risk term alone wants a point mass sitting on v.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-optimal-transport"],
    },
    {
      instruction:
        "Take the first variation δF/δμ = δR/δμ + τ(log μ + 1), set it constant on the support using a Lagrange multiplier for ∫μ=1, and solve for the stationary law.",
      expectedOutcome:
        "You derive μ_*(x) ∝ exp(−(1/τ)·δR/δμ_*(x)) and recognize it as a self-consistent (proximal Gibbs) fixed point, because δR/δμ itself depends on μ_*.",
      hint: "Exponentiate after moving the constant to the other side; the multiplier just fixes normalization.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin"],
    },
    {
      instruction:
        "Translate the Wasserstein gradient flow ∂_tμ=∇·(μ∇δF/δμ) into the particle SDE dX=−∇(δR/δμ_t)(X)dt+√(2τ)dB and code one Euler–Maruyama step over N particles.",
      expectedOutcome:
        "You observe the drift depends on the empirical law of ALL particles (mean-field coupling), and that the √(2τ) noise is precisely the diffusion generated by the entropy term.",
      hint: "The Laplacian τΔμ in the PDE is the Fokker–Planck signature of Brownian noise with variance 2τ per unit time.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-blow-up-dynamics"],
    },
    {
      instruction:
        "Log the empirical free energy F(μ_N) at every step of your simulation and confirm it is monotonically non-increasing; relate its dissipation rate to the Wasserstein-metric norm of ∇δF/δμ.",
      expectedOutcome:
        "You understand the flow as steepest descent of F in the W_2 geometry, with dF/dt = −∫μ|∇δF/δμ|² ≤ 0 — the Otto/JKO variational structure made empirical.",
      hint: "This energy-dissipation identity is exactly what the JKO minimizing-movement scheme discretizes step by step.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-optimal-transport"],
    },
    {
      instruction:
        "Sweep temperature τ from 2 down to 0.1 and plot the order parameter m=∫⟨v,x⟩dμ_N (the signal overlap) against τ at convergence.",
      expectedOutcome:
        "You see a sharp threshold τ_c of order one: above it m≈0 (diffuse, uninformative), below it m jumps to a nonzero value (concentration onto the hidden signal) — a genuine phase transition, not a gradual slope.",
      hint: "Look for a knee in the curve where the risk curvature suddenly beats the entropic diffusion.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-scale-critical-equations"],
    },
    {
      instruction:
        "At τ well below τ_c, track the particle-cloud variance over time and compare its collapse to aggregation in the Keller–Segel nonlinear Fokker–Planck model.",
      expectedOutcome:
        "You recognize low-temperature concentration as the same diffusion-versus-aggregation competition that governs blow-up: τΔ diffusion regularizes and spreads, while the drift pulls mass toward a point.",
      hint: "Blow-up dynamics is the same PDE archetype with the drift strength tuned so mass concentrates rather than disperses.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-blow-up-dynamics"],
    },
    {
      instruction:
        "Assume a log-Sobolev inequality with constant ρ for the proximal Gibbs measure and show the free-energy gap F(μ_t)−F(μ_*) decays like e^{−2ρτ t}.",
      expectedOutcome:
        "You connect the convergence speed to Bakry–Émery curvature-dimension and the log-Sobolev inequality, and see explicitly why the temperature τ multiplies the rate exponent.",
      hint: "Differentiate the free-energy gap in time, then use the LSI to bound relative entropy by the Fisher information you already computed.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-bakry-emery-curvature-dimension", "math-exponential-decay"],
    },
    {
      instruction:
        "Write a short synthesis note tying together how the Wasserstein gradient flow unifies optimal-transport geometry, entropy regularization, and the low-temperature signal-recovery transition of arXiv:2606.31429v1.",
      expectedOutcome:
        "You can articulate the full construction end to end: F=R+τH, W_2 steepest descent, the Gibbs fixed point, the τ_c phase transition, and log-Sobolev convergence — as one coherent object.",
      hint: "One paragraph linking geometry (OT), dynamics (Langevin), and statistics (signal recovery) is enough.",
      conceptsExplored: ["math-wasserstein-gradient-flow-langevin", "math-optimal-transport", "math-blow-up-dynamics"],
    },
  ],
};
