#!/usr/bin/env bash
# install-fs-uae.sh -- Cross-distro FS-UAE installation with Flatpak fallback
#
# Installs FS-UAE emulator using the package manager abstraction layer.
# Three-tier installation strategy:
#   1. Detect already-installed FS-UAE (native or Flatpak) -- skip if found
#   2. Try native package manager (apt, pacman) via pkg-abstraction.sh
#   3. Fall back to Flatpak (for dnf-based distros where FS-UAE is not in repos)
#
# Post-install: verifies FS-UAE runs, creates data directory structure.
#
# Usage:
#   bash infra/scripts/install-fs-uae.sh
#   bash infra/scripts/install-fs-uae.sh --prefix /custom/path
#   bash infra/scripts/install-fs-uae.sh --dry-run
#
# Exit codes:
#   0 - Installed successfully (or already was)
#   1 - Installation failed
#   2 - Usage error

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve script directory and source dependencies
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/pkg-abstraction.sh
source "${SCRIPT_DIR}/lib/pkg-abstraction.sh"

# discovery-common.sh is already sourced by pkg-abstraction.sh, but we
# explicitly document the dependency for has_command and warn helpers.

# ---------------------------------------------------------------------------
# Defaults and argument parsing
# ---------------------------------------------------------------------------

PREFIX="${HOME}/.local/share/fs-uae"
DRY_RUN=0
INSTALL_METHOD=""
FLATPAK_APP_ID="net.fs_uae.fs-uae"

usage() {
    printf "Usage: %s [OPTIONS]\n\n" "$(basename "$0")"
    printf "Install FS-UAE emulator with Flatpak fallback.\n\n"
    printf "Options:\n"
    printf "  --prefix <dir>   FS-UAE data directory (default: %s)\n" "${HOME}/.local/share/fs-uae"
    printf "  --dry-run        Show what would be done without making changes\n"
    printf "  -h, --help       Show this help message\n"
    exit 2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix)
            if [[ $# -lt 2 ]]; then
                printf "[ERROR] --prefix requires a directory argument\n" >&2
                usage
            fi
            PREFIX="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            printf "[ERROR] Unknown argument: %s\n" "$1" >&2
            usage
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

info() {
    printf "[INFO] %s\n" "$1"
}

error() {
    printf "[ERROR] %s\n" "$1" >&2
}

# Check if FS-UAE is installed via Flatpak
is_flatpak_installed() {
    has_command flatpak && flatpak list --app 2>/dev/null | grep -qi "fs.uae"
}

# Get installed FS-UAE version (native or Flatpak)
get_fs_uae_version() {
    if has_command fs-uae; then
        # FS-UAE may output version to stderr
        fs-uae --version 2>&1 | head -1 || echo "unknown"
    elif is_flatpak_installed; then
        flatpak info "${FLATPAK_APP_ID}" 2>/dev/null | grep -i "version" | head -1 || echo "Flatpak (version unknown)"
    else
        echo "not installed"
    fi
}

# Create FS-UAE data directory structure
create_data_dirs() {
    local dirs=(
        "${PREFIX}/Configurations"
        "${PREFIX}/ROMs"
        "${PREFIX}/Floppies"
        "${PREFIX}/Hard Drives"
        "${PREFIX}/Logs"
    )

    for dir in "${dirs[@]}"; do
        if [[ ${DRY_RUN} -eq 1 ]]; then
            info "Would create directory: ${dir}"
        else
            mkdir -p "${dir}"
            info "Created directory: ${dir}"
        fi
    done
}

# Create a wrapper script for Flatpak FS-UAE at ~/.local/bin/fs-uae
create_flatpak_wrapper() {
    local wrapper_dir="${HOME}/.local/bin"
    local wrapper="${wrapper_dir}/fs-uae"

    if [[ ${DRY_RUN} -eq 1 ]]; then
        info "Would create Flatpak wrapper at: ${wrapper}"
        return 0
    fi

    mkdir -p "${wrapper_dir}"

    cat > "${wrapper}" <<'WRAPPER'
#!/usr/bin/env bash
# Wrapper for Flatpak-installed FS-UAE
# Generated by install-fs-uae.sh
exec flatpak run net.fs_uae.fs-uae "$@"
WRAPPER

    chmod +x "${wrapper}"
    info "Created Flatpak wrapper: ${wrapper}"

    # Check if ~/.local/bin is in PATH
    if [[ ":${PATH}:" != *":${wrapper_dir}:"* ]]; then
        warn "install-fs-uae: ${wrapper_dir} is not in PATH. Add it to your shell profile:"
        warn "  export PATH=\"\${HOME}/.local/bin:\${PATH}\""
    fi
}

# ---------------------------------------------------------------------------
# Tier 1: Check if already installed
# ---------------------------------------------------------------------------

info "FS-UAE Installation Script"
info "Data directory: ${PREFIX}"
if [[ ${DRY_RUN} -eq 1 ]]; then
    info "Mode: DRY RUN (no changes will be made)"
fi

info "Checking for existing FS-UAE installation..."

# Detect backend early (needed for native install attempt)
pkg_detect_backend 2>/dev/null || {
    error "Failed to detect package manager backend"
    exit 1
}

if has_command fs-uae; then
    INSTALL_METHOD="native (already installed)"
    info "FS-UAE is already installed (native): $(get_fs_uae_version)"
    info "Ensuring data directory structure exists..."
    create_data_dirs
    info "Install method: ${INSTALL_METHOD}"
    exit 0
fi

if is_flatpak_installed; then
    INSTALL_METHOD="flatpak (already installed)"
    info "FS-UAE is already installed (Flatpak): $(get_fs_uae_version)"
    info "Ensuring data directory structure exists..."
    create_data_dirs
    info "Install method: ${INSTALL_METHOD}"
    exit 0
fi

info "FS-UAE not found. Attempting installation..."

# ---------------------------------------------------------------------------
# Tier 2: Try native package manager
# ---------------------------------------------------------------------------

info "Attempting native package manager installation..."

native_install_ok=0
if [[ ${DRY_RUN} -eq 1 ]]; then
    # In dry-run, check if the package resolves on this backend
    if resolve_pkg_name "fs-uae" "${_PKG_BACKEND}" >/dev/null 2>&1; then
        info "Would install fs-uae via ${_PKG_BACKEND} (native package available)"
        INSTALL_METHOD="native (${_PKG_BACKEND}, dry-run)"
        native_install_ok=1
    else
        info "fs-uae not available via ${_PKG_BACKEND}, would try Flatpak fallback"
    fi
else
    if pkg_install fs-uae 2>/dev/null; then
        INSTALL_METHOD="native (${_PKG_BACKEND})"
        native_install_ok=1
        info "FS-UAE installed successfully via ${_PKG_BACKEND}"
    else
        info "Native package installation failed or unavailable on ${_PKG_BACKEND}"
    fi
fi

# ---------------------------------------------------------------------------
# Tier 3: Flatpak fallback (for dnf-based distros where FS-UAE is not in repos)
# ---------------------------------------------------------------------------

if [[ ${native_install_ok} -eq 0 ]]; then
    info "Falling back to Flatpak installation..."

    if [[ ${DRY_RUN} -eq 1 ]]; then
        info "Would install flatpak via ${_PKG_BACKEND}"
        info "Would add Flathub remote (if not present)"
        info "Would install ${FLATPAK_APP_ID} via Flatpak"
        info "Would create wrapper script at ~/.local/bin/fs-uae"
        INSTALL_METHOD="flatpak (dry-run)"
    else
        # Step 1: Ensure flatpak is installed
        info "Installing flatpak package manager..."
        if ! pkg_install flatpak 2>/dev/null; then
            error "Failed to install flatpak. Cannot proceed."
            error "Manual install instructions:"
            error "  CentOS/Fedora: sudo dnf install flatpak"
            error "  Ubuntu/Debian: sudo apt-get install flatpak"
            error "  Arch: sudo pacman -S flatpak"
            exit 1
        fi

        # Step 2: Add Flathub remote
        info "Adding Flathub remote..."
        flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || {
            error "Failed to add Flathub remote"
            exit 1
        }

        # Step 3: Install FS-UAE from Flathub
        info "Installing FS-UAE from Flathub..."
        if ! flatpak install -y flathub "${FLATPAK_APP_ID}"; then
            error "Flatpak FS-UAE installation failed"
            error "Both native and Flatpak installation methods failed."
            error ""
            error "Manual install instructions:"
            error "  Flatpak: flatpak install flathub ${FLATPAK_APP_ID}"
            error "  From source: https://fs-uae.net/download"
            if [[ $(id -u) -ne 0 ]]; then
                error ""
                error "If package installation failed due to permissions, try running with sudo."
            fi
            exit 1
        fi

        # Step 4: Create wrapper script
        create_flatpak_wrapper
        INSTALL_METHOD="flatpak"
    fi
fi

# ---------------------------------------------------------------------------
# Post-install verification
# ---------------------------------------------------------------------------

if [[ ${DRY_RUN} -eq 1 ]]; then
    info "Would verify FS-UAE installation"
    info "Would create data directory structure at: ${PREFIX}"
    create_data_dirs
    info ""
    info "Dry run complete. Planned installation method: ${INSTALL_METHOD}"
    exit 0
fi

info "Verifying FS-UAE installation..."

# Verify fs-uae command works (check both stdout and stderr for version info)
if has_command fs-uae || is_flatpak_installed; then
    local_version="$(get_fs_uae_version)"
    info "FS-UAE verified: ${local_version}"
else
    error "FS-UAE installation could not be verified"
    error "The 'fs-uae' command is not available after installation"
    exit 1
fi

# Create data directory structure
info "Creating data directory structure..."
create_data_dirs

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

info ""
info "FS-UAE installation complete!"
info "  Install method: ${INSTALL_METHOD}"
info "  Data directory: ${PREFIX}"
info "  Subdirectories: Configurations, ROMs, Floppies, Hard Drives, Logs"
info ""
info "Next steps:"
info "  1. Run setup-aros-rom.sh to download the AROS ROM"
info "  2. Copy base.fs-uae to ${PREFIX}/Configurations/"
info "  3. Launch: fs-uae ${PREFIX}/Configurations/base.fs-uae"

exit 0
