import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.43 -- Acquisition-vs-tracking bandwidth allocation in a coherent
 * Ku-band rendezvous radar: IF-strip selectivity + Doppler-loop bandwidth
 * narrowing during closure, anchored to the Westinghouse Gemini 6A radar
 * (1965-12-15 first orbital rendezvous, ~1 ft / 40 km / 0.3 m/s).
 *
 * Generated by the v1.49.581 ELC Wave-6 backfill (slot E6-C).
 * Cross-references: NASA 1.43 (Gemini 6A first orbital rendezvous), MUS 1.43
 * (closure-form audio analog at the same degree).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md s5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md s3
 */
export const rendezvousRadarAcquisitionTrackingBandwidth: RosettaConcept = {
  id: 'elc-1.43-rendezvous-radar-acquisition-tracking-bandwidth',
  name: 'Acquisition-vs-tracking bandwidth allocation in a coherent Ku-band rendezvous radar: IF-strip selectivity, Doppler-loop bandwidth narrowing during closure, and the Westinghouse Gemini 6A radar that resolved Gemini 7 to one foot at 40 km',
  domain: 'electronics',
  description:
    'A frequency-response design primitive describing how a coherent tracking radar trades ' +
    'IF-strip noise-equivalent bandwidth and Doppler-loop closed-loop bandwidth across two ' +
    'antipodal operating modes: (a) wide IF + wide loop for *acquisition* when the targets ' +
    'Doppler offset is unknown and the search must cover a broad spectrum, (b) narrow IF + ' +
    'narrow loop for *tracking* once the target is acquired, dropping the integrated noise ' +
    'floor and improving phase-noise variance. The closure-phase trajectory is therefore a ' +
    'bandwidth-narrowing schedule driven by the radar equation SNR ~ 1/R^4: as range falls, ' +
    'SNR rises 12 dB per range-halving, which is what permits the bandwidth narrowing without ' +
    'losing lock. The two-axis tradeoff is governed by the IF noise N = k_B T_0 F B_IF and the ' +
    'second-order PLL noise-bandwidth B_L = (omega_n / 2)(zeta + 1/(4 zeta)), with a tracking-' +
    'rate threshold omega_dot_max = zeta omega_n^2 / pi setting the lower limit on B_L admissible ' +
    'under a given Doppler-rate dynamics. The canonical flight exemplar is the Westinghouse ' +
    'Aerospace Division Gemini Rendezvous Radar Set (interrogator on Gemini 6A, transponder on ' +
    'Gemini 7, 1965-12-15 stationkeeping over Mauritius), with two-mode IF strip (~5 MHz wide / ' +
    '~500 kHz narrow) and adaptively-narrowed Doppler PLL (~3 kHz at acquisition, ~30 Hz at ' +
    'terminal closure), delivering 1 ft range residual and 0.3 m/s closure-rate accuracy at ' +
    '40 km.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-pll-tracking-rate-threshold',
      description:
        'The Doppler-tracking PLLs tracking-rate threshold omega_dot_max = zeta omega_n^2 / pi ' +
        'sets the maximum smooth Doppler-rate the loop can follow without losing lock. Westinghouse ' +
        'narrow-track loop (zeta=0.28, omega_n=56 rad/s) gives omega_dot_max ~ 280 rad/s^2, ' +
        'comfortably above the Gemini terminal-closure thruster-firing transient.',
    },
    {
      type: 'dependency',
      targetId: 'elec-noise-bandwidth',
      description:
        'The loop-bandwidth formula B_L = (omega_n/2)(zeta + 1/(4 zeta)) is the noise-equivalent ' +
        'bandwidth of the closed-loop transfer function H(s); it is the integral of |H(j omega)|^2 ' +
        'd omega / pi over [0, infinity). The IF-strip noise-equivalent bandwidth follows the same ' +
        'construction generalised to bandpass: a synchronously-tuned LC cascade with shape factor ' +
        'B_NEQ / B_3dB = 1.10 (4-stage) drops to 1.04 (8-stage).',
    },
    {
      type: 'dependency',
      targetId: 'elec-radar-equation',
      description:
        'The radar equation SNR ~ P_t G_t G_r lambda^2 G_p / [(4 pi)^3 R^4 k_B T_0 F B_IF L] sets ' +
        'the closure-phase SNR-vs-range function: 12 dB SNR rise per range-halving. This is the ' +
        'driver for the bandwidth-narrowing program -- as SNR rises, B_IF and B_L narrow, dropping ' +
        'integrated noise without losing lock.',
    },
    {
      type: 'analogy',
      targetId: 'elc-1.16-doppler-microwave-receiver',
      description:
        'Echo 1 (ELC 1.16) opens the bandwidth-vs-noise-figure axis with paramp-fronted superheterodyne; ' +
        'this degree adds the bandwidth-vs-closure-time axis. Together with the FM-modulation-improvement ' +
        'axis at ELC 1.38 they form a triple in the Frequency-response domain that exhausts the era-' +
        'canonical bandwidth-related design tradeoffs.',
    },
    {
      type: 'analogy',
      targetId: 'elc-1.38-video-telemetry-bandwidth-budget',
      description:
        'Ranger 9 (ELC 1.38) Carson-rule + Friis-cascade primitive treats bandwidth allocation as a ' +
        'static feed-forward design parameter; this degree treats bandwidth as a dynamic, schedule-' +
        'driven parameter that narrows over the closure trajectory. The two are open-loop and closed-' +
        'loop dual statements of the same bandwidth-vs-noise principle.',
    },
    {
      type: 'analogy',
      targetId: 'elc-1.62-enc-cr-rc-shaping',
      description:
        'The series-vs-parallel noise crossover at tau_opt in the noise-domain reference (charge-' +
        'sensitive amplifier CR-RC shaping) has the same closure-form shape as the acquisition-vs-' +
        'tracking bandwidth-allocation program here: each is a balance gesture resolving at a ' +
        'structurally weighted point. The Gemini RRS narrowing schedule is the time-axis instance ' +
        'of the same closure-form pattern.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.43-closure-form',
      description:
        'The descending-phrase cadence in the MUS 1.43 song-cycle progression is the structural rhyme ' +
        'of the rendezvous-radar bandwidth narrowing: each is a closure-form gesture resolving at the ' +
        'narrowest admissible value -- the cadence at scale-degree 1, the radar at the narrowest ' +
        'B_L the targets dynamics permit.',
    },
  ],
  metadata: {
    elcDegree: '1.43',
    domain: 3,
    domainName: 'Frequency response',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware: 'Westinghouse Aerospace Division Gemini Rendezvous Radar Set: interrogator on Gemini 6A spacecraft (X-band 10 GHz pulse search + Ku-band 15.0 GHz CW-coherent track), cooperative transponder on Gemini 7 spacecraft (replacing the GATV transponder after the Agena Target Vehicle launch failure of 1965-10-25); two-mode IF strip (~5 MHz wide / ~500 kHz narrow) + speed-gate Doppler-tracking PLL (B_L narrowable from ~3 kHz at acquisition to ~30 Hz at terminal closure); reflex-klystron 15 GHz LO with cavity-stabilized AFC; 2N918 silicon NPN IF cascade.',
    keyEquation: 'B_L = (omega_n / 2)(zeta + 1 / (4 zeta)) ; omega_n = sqrt(K_d K_v / tau_1) ; zeta = 0.5 omega_n tau_2 ; N_IF = k_B T_0 F B_IF ; SNR ~ P_t G_t G_r G_p lambda^2 / [(4 pi)^3 R^4 k_B T_0 F B_IF L] ; sigma_phi = sqrt(B_L / (C/N_0)) ; sigma_v = (lambda / 4 pi) sigma_phi omega_n',
    benchReplication: {
      anchorLO: 'ADF4159BCPZ (Analog Devices) -- 13 GHz fractional-N PLL synthesizer with on-chip ramp generator',
      eraOriginal: 'Westinghouse reflex-klystron 15 GHz LO + Pound-discriminator + cavity-stabilized AFC + 2N918 silicon NPN IF cascade (1962-1965 hand-aligned bench builds at Westinghouse Aerospace Division Baltimore)',
      ifStrip: 'OPA847 (Texas Instruments) wideband op-amp + Coilcraft 1812FS-102M toroidal inductor + AVX 0805 C0G NPO 28 pF cap; two synchronously-tuned tanks at 30 MHz IF center; TS3A4751 SPST analog switch swaps damping resistors between 100 ohm (wide, Q=15, B_3dB=5 MHz) and 10k ohm (narrow, Q=150, B_3dB=500 kHz)',
      phaseDetector: 'AD630ARZ (Analog Devices) balanced modulator/demodulator (-120 dB carrier feedthrough, 5 MHz BW)',
      activeLoopFilter: 'OPA827 (Texas Instruments) JFET-input low-noise op-amp; en = 4 nV/rt-Hz; lag-lead network (R1=10k R2=100k C=100n for narrow-track giving B_L=30 Hz; R1=100 R2=1k C=10n for wide-acquire giving B_L=3.3 kHz); TS3A4751 SPST analog switch selects between modes',
      nominalLoop: 'narrow-track tau_1 = 1 ms, tau_2 = 10 ms -> omega_n = 56 rad/s, zeta = 0.28, B_L = 30 Hz; wide-acquire tau_1 = 10 us, tau_2 = 100 us -> omega_n = 560 rad/s, zeta = 0.28, B_L = 3.3 kHz',
    },
    references: [
      'Skolnik, M.I. Introduction to Radar Systems (3e, McGraw-Hill 2001), ch. 3 (CW + FM-CW radar), ch. 5 (tracking radar), ch. 11 (Doppler-loop noise) -- canonical radar textbook',
      'Gardner, F.M. Phaselock Techniques (3e, Wiley 2005), ch. 4 (loop noise), ch. 11 (acquisition + tracking) -- canonical PLL textbook',
      'Best, R.E. Phase-Locked Loops: Design, Simulation, Modeling (6e, McGraw-Hill 2007), ch. 5 -- Doppler-tracking second-order loops',
      'Barton, D.K. Radar System Analysis and Modeling (Artech 2005), ch. 6 -- coherent processing and Doppler-bandwidth budgeting',
      'Hovanessian, S.A. Radar Detection and Tracking Systems (Artech 1973) -- speed-gate tracker mathematics',
      'Pozar, D.M. Microwave Engineering (4e, Wiley 2011), ch. 12 -- mixer noise figure',
      'Hartz, E.A. and Bolton, W.S. (1967) Gemini Rendezvous Radar Set Performance Review, in NASA SP-138 Gemini Summary Conference (Manned Spacecraft Center)',
      'NASA TM-X-58030 (1966) Gemini-VI / Gemini-VII Postflight Mission Operation Report, s9',
      'Westinghouse Aerospace Division (1966) Final Report on the Gemini Rendezvous Radar Set, NASA contract NAS9-1574, Baltimore MD',
      'Analog Devices (2024) ADF4159 datasheet rev. F, https://www.analog.com/media/en/technical-documentation/data-sheets/ADF4159.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.34,
    imaginary: 0.55,
    magnitude: Math.sqrt(0.34 ** 2 + 0.55 ** 2),
    angle: Math.atan2(0.55, 0.34),
  },
};
