import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.12 — Spinning-spacecraft scan-camera signal chain: mechanical-trigger
 * sync, photomultiplier video preamp, AGC video amplifier, and the Explorer 6
 * first-orbital-photograph readout.
 *
 * Generated by the v1.49.581 ELC Wave-3 backfill (slot E3-D).
 * Cross-references: NASA 1.12 (Explorer 6 / S-2 — first orbital photograph of
 * Earth, 1959-08-14; STL Project Able spin-scan optical telescope; 5703-class
 * side-on photomultiplier + 6AK5 cathode-follower preamp + germanium-NPN AGC
 * video stage + sun-line photodiode mechanical-sync trigger + 5 kHz FM
 * subcarrier modulator), MUS 1.12 (call-and-response gesture in paired-vocalist
 * songbird antiphony — response-with-known-offset as the structural rhyme of
 * the per-revolution sun-line trigger setting the AGC's expectation that the
 * rest of the spin period answers at the V_AGC set-point).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const spinningScanCameraAgc: RosettaConcept = {
  id: 'elc-1.12-spinning-scan-camera-agc',
  name: 'Spinning-spacecraft scan-camera AGC video chain: asymmetric peak-detector dynamic-range compression for the Explorer 6 first-orbital-photograph readout',
  domain: 'electronics',
  description:
    'An analog-signal-conditioning primitive describing how a spinning-spacecraft optical ' +
    'telescope replaces the deflection coils of a 1959 cathode-ray TV camera with the angular ' +
    'momentum of the entire 64 kg vehicle, and how the resulting wide-dynamic-range optical ' +
    'video signal is compressed onto a fixed-bandwidth FM subcarrier by an asymmetric ' +
    'peak-detector AGC loop. The chain is five stages: (1) sun-line photodiode (1N34A point- ' +
    'contact germanium) generating one mechanical-sync trigger per spacecraft revolution, ' +
    '(2) photomultiplier video pickup (5703-class side-on PMT, 100 kΩ anode load) converting ' +
    'photon flux to voltage swing across a 60 dB illumination range, (3) cathode-follower ' +
    'preamp (6AK5 / EF95 subminiature pentode at +200 V plate) presenting the high-Z PMT ' +
    'anode to the low-Z AGC stage, (4) germanium-NPN transconductance-modulated variable- ' +
    'gain video amplifier (2N1308-class) whose small-signal gain follows A_v = G0/(1 + K·V_AGC) ' +
    'driven by an asymmetric peak-detector loop with τ_attack ≈ 1 s and τ_release ≈ 10 s ' +
    'against the 26-second 2.3-rpm spin period, and (5) 5 kHz cross-coupled-astable FM ' +
    'subcarrier modulator at ±1.5 kHz deviation feeding the spacecraft S-band downlink. ' +
    'The keystone observation is that the asymmetric peak-detector ODE (fast attack tracks ' +
    'bright illumination peaks within a single revolution; slow release preserves within-line ' +
    'contrast over the 26-second spin period) is the single equation that determines whether ' +
    'the photograph's 60 dB optical span survives compression onto the 5 kHz subcarrier. The ' +
    'canonical flight exemplar is the STL Project Able spin-scan optical telescope (Davis 1960 ' +
    '*Sky & Telescope*; STL Project Able Final Report 1960) whose hand-tuned AGC loop with ' +
    'the (τ_attack, τ_release) = (1 s, 10 s) flight setting delivered the first photograph of ' +
    'Earth taken from orbit (Explorer 6, 1959-08-14), assembled at STL from approximately ' +
    '6,000 individual scan lines transmitted across an 8-day mission.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-peak-detector-loop',
      description:
        'The keystone AGC stage is a peak-detector first-order ODE with asymmetric attack/ ' +
        'release time constants: τ_charge × dV_AGC/dt = V_in_peak - V_AGC during rising ' +
        'illumination; τ_discharge × dV_AGC/dt = -V_AGC during falling. The ratio τ_release/ ' +
        'τ_attack determines loop stability; values below ~5 lead to AGC squegging.',
    },
    {
      type: 'dependency',
      targetId: 'elec-variable-gain-amplifier',
      description:
        'The AGC stage is a transconductance-modulated common-emitter variable-gain ' +
        'amplifier whose static gain map A_v(V_AGC) = G0/(1 + K·V_AGC) derives from the ' +
        'small-signal transconductance gm = I_C/V_T of a germanium-NPN transistor with base ' +
        'bias linearly modulated by V_AGC. The 1/(1 + KV) hyperbolic curve gives smooth ' +
        'compression across the 60 dB span without over-compression of mid-tones.',
    },
    {
      type: 'dependency',
      targetId: 'elec-photomultiplier-readout',
      description:
        'The video front-end is a 5703-class side-on photomultiplier modeled as an ideal ' +
        'current source at the anode driving a 100 kΩ load resistor. The dynode-chain gain ' +
        'of ~7×10⁵ multiplies cathode-photocurrent shot noise to anode shot noise; the ' +
        'cathode-follower preamp downstream presents Megohm input impedance to preserve the ' +
        'high-Z PMT anode without loading.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.12-pacific-coast-songbird-antiphony',
      description:
        'The per-revolution sun-line photodiode trigger is the structural rhyme of the ' +
        'pacific-coast songbird antiphonal exchange: each is a response-with-known-offset ' +
        'gesture in time. The bird\'s terminal phrase predicts the mate\'s response phrase at ' +
        'a known dialect-frequency offset; the per-revolution sun crossing sets the AGC\'s ' +
        'expectation that the rest of the spin period answers at the V_AGC set-point. Both ' +
        'are call-and-response signals across a void: dialect across generations versus ' +
        'spin-axis across a celestial sphere.',
    },
  ],
  metadata: {
    elcDegree: '1.12',
    domain: 7,
    domainName: 'Analog signal conditioning',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware:
      'STL Project Able spin-scan optical telescope (Davis 1960) — 5703-class side-on photomultiplier + 6AK5/EF95 cathode-follower preamp + 2N1308-class germanium-NPN transconductance-modulated AGC video amplifier + 1N34A point-contact germanium sun-line photodiode trigger + cross-coupled astable 5 kHz FM subcarrier modulator',
    keyEquation:
      'τ_charge × dV_AGC/dt = V_in,peak − V_AGC ; τ_discharge × dV_AGC/dt = −V_AGC ; A_v(V_AGC) = G0 / (1 + K_AGC × V_AGC)',
    benchReplication: {
      activePmt: 'Hamamatsu R7400U-04 side-on photomultiplier (8-stage box-and-grid, bialkali photocathode, 7×10⁵ gain, 0.78 ns rise time)',
      eraOriginal: 'RCA 5703 side-on PMT (1959 STL flight build) + 6AK5 cathode-follower at +200 V plate / 6.3 V heater / 175 mA',
      eraFaithfulPath: '6AK5 / EF95 subminiature pentode from JJ Electronic boutique production for tube-faithful builds',
      preampOpAmp: 'Texas Instruments OPA827AID (4 nV/√Hz, 2.2 fA/√Hz)',
      agcStage: 'ON Semi 2N3904 silicon-NPN transconductance-modulated common-emitter (era-faithful 2N1308 from boutique distributors)',
      peakDetectorDiode: '1N4148 silicon (era-faithful 1N34A point-contact germanium from Vishay 78-1N34A)',
      agcHoldCap: '10 µF solid-tantalum CWR06 (Vishay 74-T55A106M050)',
      vco: 'NSC LM566CN (5 kHz centre, 1.5 kHz/V deviation)',
      agcTimeConstants: '(τ_attack, τ_release) = (1 s, 10 s) — 100 kΩ × 10 µF / 1 MΩ × 10 µF',
    },
    references: [
      'Davis, A. (1960). "Project Able and the Photographs of Earth from Explorer 6." Sky & Telescope 19(11): 643-647',
      'Space Technology Laboratories (1960). Explorer VI Photoscan Instrument Design and Image Reconstruction. STL Project Able Final Report (NASA NTRS)',
      'NASA NSSDC. Explorer 6 mission record. NSSDCA ID 1959-004A',
      'Heppner, J.P. et al. (1960). "Note on the Absence of a Whistler Observation from Explorer VI." Journal of Geophysical Research 65(11): 3600',
      'Horowitz & Hill, The Art of Electronics (3e, Cambridge 2015), §4.5 — peak detectors; §4.7 — AGC loops',
      'Razavi, Design of Analog CMOS Integrated Circuits (2e, McGraw-Hill 2017), §13 — photodetector front-ends',
      'Knoll, Radiation Detection and Measurement (4e, Wiley 2010), §9.II — photomultiplier readout chains',
      'Pease, Troubleshooting Analog Circuits (Newnes 1991), §11 — AGC loop pathologies',
      'Tietze & Schenk, Electronic Circuits (2e, Springer 2008), §29 — synchronous detection and sample-trigger timing',
      'Hamamatsu R7400U datasheet, https://www.hamamatsu.com/content/dam/hamamatsu-photonics/sites/documents/99_SALES_LIBRARY/etd/R7400U_TPMH1296E.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.31,
    imaginary: 0.59,
    magnitude: Math.sqrt(0.31 ** 2 + 0.59 ** 2),
    angle: Math.atan2(0.59, 0.31),
  },
};
