import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.59 — Signal-margin floor in degraded-link telemetry signal
 * conditioning: AGC carrier-tracking limiter + post-detection eye-margin
 * budget that delivered useful 2.5-minute final telemetry from
 * Surveyor 4 main-retro burn.
 *
 * Generated by the v1.49.581 ELC Wave-7 backfill (slot E7-M).
 * Cross-references: NASA 1.59 (Surveyor 4 — silent impact 2.5 min before
 * landing 1967-07-17 02:02:40 UT; engineering-lineage closure for the
 * Surveyor program; main-retro telemetry held nominal until catastrophic
 * loss; data carried Apollo decisions despite touchdown loss),
 * MUS 1.59 (engineering-lineage closure as a closure-form gesture
 * carrying material from earlier movements through to a final-movement
 * reprise — the structural rhyme of the eye-margin floor as a closure
 * gesture in the multi-parameter optimisation).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const surveyor4DegradedLinkMarginFloor: RosettaConcept = {
  id: 'elc-1.59-surveyor-4-degraded-link-margin-floor',
  name: 'Signal-margin floor in degraded-link telemetry signal conditioning: AGC carrier-tracking limiter + post-detection eye-margin budget that delivered useful 2.5-minute final telemetry from Surveyor 4 main-retro burn',
  domain: 'electronics',
  description:
    'An analog-signal-conditioning primitive describing how a degraded-link telemetry ' +
    'receiver chain holds its post-detection eye open under progressively narrowing signal ' +
    'margin until catastrophic spacecraft loss. The chain is five stages: (1) limiting IF ' +
    'amplifier with soft-clipped saturation modelling 30 dB log-conformity (Hughes-built ' +
    '10.7 MHz IF strip from 2N3866-class wideband cascode pairs), (2) envelope detector ' +
    '(1N4148 silicon rectifier into RC tank with one-time-constant 100 µs tracking the AGC ' +
    'error-signal dynamics), (3) AGC carrier-tracking loop closing on a fixed reference ' +
    '(τ_AGC ≈ 2 s in flight, scaled to 2 ms in the teaching variant for window fit), ' +
    '(4) post-detection low-pass filter at f_3dB ≈ 0.7 × bit rate per the matched-filter ' +
    'rule (single-pole RC; 2-pole Sallen-Key in modern bench substitute), and (5) Schmitt-' +
    'trigger threshold detector with ±100 mV hysteresis — the floor-defining stage. The ' +
    'keystone observation is that the worst-case eye-margin floor is set jointly by AGC ' +
    'headroom + matched-filter LPF pole placement + Schmitt-trigger hysteresis, not by ' +
    'any single one of them, and the equation that locates that floor is ' +
    'margin_dB = 20 × log10((V_swing_pp/2 - V_hysteresis) / (Q × V_noise_RMS)). The ' +
    'canonical flight exemplar is the Hughes Aircraft / JPL DSS-11 Surveyor S-band ' +
    'telemetry receiver chain that delivered useful 137-bps frames through the final ' +
    '2.5 minutes of Surveyor 4 main-retro burn until the abrupt 02:02:40 UT cutoff on ' +
    '17 July 1967, where the data — though not landing-site science — characterised the ' +
    'descent envelope to the cutoff instant and let the Surveyor program continue without ' +
    'redesign through Surveyors 5, 6, and 7.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-limiting-amplifier',
      description:
        'The keystone IF stage is a limiting amplifier with soft-clipped saturation. A 60 dB ' +
        'input dynamic range maps to a sub-3 dB output dynamic range at the limiter; the ' +
        'limiting topology gives constant output amplitude across the wide input range that ' +
        'protects the envelope detector and threshold detector from overdrive-induced offset ' +
        'shifts. Cost: small-signal amplitude information is no longer recoverable, but for ' +
        'PCM/FSK formats this is irrelevant.',
    },
    {
      type: 'dependency',
      targetId: 'elec-agc-carrier-tracking-loop',
      description:
        'The AGC error amplifier compares an envelope detector to a fixed reference and drives ' +
        'a VGA gain back toward maintaining the envelope at the reference. The closed-loop ' +
        'control law is approximately vga_gain = V_AGC_REF / V(env_filt) with hard-floor and ' +
        'ceiling protection. The AGC absorbs slow link-amplitude variation but cannot remove ' +
        'the noise pedestal — at low signal it raises the noise alongside the signal, defining ' +
        'the floor.',
    },
    {
      type: 'dependency',
      targetId: 'elec-matched-filter-lpf',
      description:
        'The post-detection low-pass filter at f_3dB = 0.7 × R_b implements the matched-filter ' +
        'approximation: maximises post-detection SNR for rectangular bit pulses; tighter LPF ' +
        'loses signal energy faster than noise (raises BER); wider LPF lets in inter-symbol ' +
        'interference. Pole-placement is a single-degree-of-freedom optimisation.',
    },
    {
      type: 'dependency',
      targetId: 'elec-schmitt-trigger-hysteresis',
      description:
        'The floor-defining stage. Schmitt-trigger hysteresis sets the worst-case eye-margin ' +
        'floor: bits are accepted only when the post-detection signal swings outside the ' +
        'hysteresis band. Tighter hysteresis lowers the floor but admits more false transitions ' +
        'on impulsive noise. The bench measurement is the hysteresis-vs-floor U-curve, and the ' +
        'optimum hysteresis is the joint minimum across BER and false-trigger rate.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.59-engineering-lineage-closure-form',
      description:
        'The engineering-lineage closure as a closure-form gesture in MUS 1.59 maps onto the ' +
        'eye-margin floor as a closure gesture in the multi-parameter optimisation. Both are ' +
        'local-floor gestures that resolve at structurally-weighted joint optima. The musical ' +
        'reprise resolves at the structurally-weighted return-of-material; the eye-margin floor ' +
        'resolves at the structurally-weighted joint optimum across AGC, LPF, and Schmitt ' +
        'parameters. Both are closure gestures whose mathematics is multi-parameter ' +
        'optimisation rather than single-knob decision.',
    },
  ],
  metadata: {
    elcDegree: '1.59',
    domain: 7,
    domainName: 'Analog signal conditioning',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Hughes Aircraft Surveyor S-band telemetry receiver post-detection signal-conditioning chain — limiting IF amplifier (10.7 MHz, 30 dB log-conformity, 2N3866-class cascode) + analog Costas AGC carrier-tracking loop (τ_AGC ≈ 2 s) + post-detection LPF (single-pole RC at 0.7 × bit rate) + Schmitt-trigger threshold detector (±100 mV hysteresis, discrete 2N930 regenerative pair) + bit-synchroniser + frame-sync correlator (Hughes SSD-68197R; NASA SP-184 §17; JPL TR 32-1265 Surveyor 4 Mission Report) — delivered useful 137-bps PCM/FSK frames through the final 2.5 minutes of Surveyor 4 main-retro burn until the abrupt 02:02:40 UT cutoff on 17 July 1967',
    keyEquation:
      'margin_dB = 20 × log10((V_swing_pp/2 - V_hysteresis) / (Q × V_noise_RMS)) ; floor reached when |V_swing_pp/2 - V_hysteresis| ≈ Q × V_noise_RMS',
    benchReplication: {
      postDetectionOpAmp: 'Texas Instruments OPA277UA (8 nV/√Hz, ±20 µV V_OS, 0.1 µV/°C drift)',
      eraOriginal: 'Fairchild µA709 / µA741-class bipolar op-amp',
      limitingIf: 'NXP / on-semi SA614AD FM IF subsystem IC (90 dB log-conformity at 10.7 MHz)',
      eraFaithfulPath: 'Discrete 2N3866 cascode wideband IF strip with 30 dB linear-then-limiting characteristic',
      thresholdDetector: 'Texas Instruments LM311N voltage comparator with positive-feedback resistor pair',
      eraFaithfulSchmitt: 'Discrete 2N930 two-transistor regenerative Schmitt with collector-divider hysteresis',
      agcVga: 'Analog Devices AD633JNZ analog multiplier (1% gain accuracy)',
      lpfTopology: 'Sallen-Key 2-pole around OPA277UA at f_3dB = 1 kHz (matched-filter pole at 0.7 × bit rate)',
      lpfCap: '100 nF C0G NPO 1206 (TC < 30 ppm/°C; AVX 581-12061A104JAT2A)',
      lpfResistor: '1.6 kΩ thin-film 0805 (Vishay 71-CRCW08051K60FKEA, 1% precision)',
      schmittHysteresisResistors: 'Matched-pair 10 kΩ thin-film 0805 (Vishay 71-CRCW080510K0FKEA, ±0.1% by selection)',
      bitClockRecovery: 'SN74HC74N dual D flip-flop (Texas Instruments 595-SN74HC74N) clocked off recovered bit clock',
    },
    references: [
      'NASA. (1969). Surveyor Program Results. NASA SP-184. §6 Mission Operations; §17 Telecommunications System; §17.4 Surveyor 4 Final Telemetry Analysis',
      'Jet Propulsion Laboratory. (1968). JPL Technical Report 32-1265: Surveyor 4 Mission Report. §4 Telemetry; §7 Anomaly Investigation; §10 DSN Receiver Operations Through Final Cutoff',
      'Hughes Aircraft Company. (1968). Surveyor Engineering Report SSD-68197R: Telecommunications Subsystem Design and Performance. Space Systems Division, El Segundo CA',
      'Razavi, B. (2017). Design of Analog CMOS Integrated Circuits (2e), McGraw-Hill — §9 receiver architectures; §9.5 signal-margin floor analysis',
      'Horowitz, P., & Hill, W. (2015). The Art of Electronics (3e), Cambridge UP — §13.18 limiting amplifiers and FM/PM detection',
      'Sklar, B. (2001). Digital Communications: Fundamentals and Applications (2e), Prentice Hall — §3.2 signal-to-noise ratio and bit-error-rate floor; §10 synchronisation and bit-timing recovery',
      'Proakis, J. G., & Salehi, M. (2007). Digital Communications (5e), McGraw-Hill — §5.1 coherent demodulation in AWGN; §6.4 eye-pattern analysis and timing margin',
      'Gardner, F. M. (2005). Phaselock Techniques (3e), Wiley — §6 Costas loop AGC + carrier tracking; §11 degraded-link noise budget',
      'Texas Instruments OPA277 datasheet, https://www.ti.com/lit/ds/symlink/opa277.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.41,
    imaginary: 0.71,
    magnitude: Math.sqrt(0.41 ** 2 + 0.71 ** 2),
    angle: Math.atan2(0.71, 0.41),
  },
};
