import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.15 — Spectrographic and aerial-imagery notation: the 2D analytic
 * surface as score.
 *
 * Generated by the v1.49.581 MUS wave-2 backfill (W2-C agent).
 * Cross-references: NASA 1.15 (TIROS-1 vidicon-raster cloud chart),
 *                   ELC 1.15 (control-system block-diagram readability, pending).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const spectrographicAerialNotation: RosettaConcept = {
  id: 'mus-1.15-spectrographic-aerial-notation',
  name: 'Spectrographic and aerial-imagery notation: the 2D analytic surface as score',
  domain: 'music',
  description:
    'A music-theoretic primitive describing how a flat two-dimensional substrate ' +
    '(time x frequency, time x scale-degree, time x surface-position, time x ' +
    'harmonic-identity) functions as an analytic notation system on which the ' +
    'reader inscribes marks that are simultaneously a record of what was heard ' +
    'and a prescription for what is to be played or read. Three 20th-century ' +
    'analytic notation systems converge on this primitive: spectrographic ' +
    'analysis (Cogan 1984, frequency-time energy patches), modern jazz lead-sheet ' +
    'notation (chord-symbol shorthand stacked above five-line staff voicings), ' +
    'and aerial / synoptic imagery (TIROS-1 vidicon scan-line raster as readable ' +
    'cloud-field substrate, Wexler 1954). The substrates differ; the structural ' +
    'commitment to a flat 2D plane with two genuinely orthogonal axes of ' +
    'analytic information is shared. Aaron Parks (Bremerton-born jazz pianist; ' +
    'Blue Note 2008, ECM 2017, Ropeadope 2018) is the canonical PNW exemplar ' +
    'of dual-axis lead-sheet practice; the osprey (Pandion haliaetus) furnishes ' +
    'the bioacoustic / behavioral analog via its hover-and-plunge aerial-search ' +
    'pattern, in which the bird reads the water surface as a 2D analytic substrate ' +
    'with sustained integration time before committing to the dive.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-staff-notation',
      description:
        'Spectrographic and dual-axis lead-sheet notation extend the staff-and-clef ' +
        'system to a fully two-dimensional substrate where neither axis is "the staff" ' +
        'and the other "the annotation"; both carry orthogonal analytic load.',
    },
    {
      type: 'analogy',
      targetId: 'remote-sensing-imagery',
      description:
        'The vidicon scan-line raster of TIROS-1 (1960) made the planetary atmosphere ' +
        'readable as a 2D analytic surface in the same way that Cogan-style ' +
        'spectrographic analysis makes a sonic event readable as a frequency-time field. ' +
        'Both convert sub-symbolic measurement fields into reader-ready charts.',
    },
    {
      type: 'analogy',
      targetId: 'raptor-foraging-strategy',
      description:
        'The osprey hover-and-plunge cycle, with its 5-20:1 observation-to-action ratio, ' +
        'is the behavioral analog of sustained-integration analytic reading: the bird ' +
        'plots marks against the water-surface staff, integrates over multiple frames, ' +
        'and only commits to a plunge once the analytic reading supports it.',
    },
  ],
  metadata: {
    musDegree: '1.15',
    exemplars: {
      s36Artist: 'Aaron Parks',
      s36Works: [
        'Invisible Cinema (Blue Note 5099950859221, 2008): "Nemesis", "Praise", "Roadside Distraction"',
        'Find the Way (ECM 2576, 2017): title track; "Hold Music"; "The Trickster"',
        'Little Big (Ropeadope RAD-555, 2018): four-piece electric ensemble project, triple-axis notation',
      ],
      spsSpecies: 'Osprey (Pandion haliaetus, Linnaeus 1758)',
      spsAcousticFeature:
        'aerial search-pattern as geometric notation precedent — hovering 10-40 m over water in 30-degree downward scan cone; observation:action ratio 5-20:1; the hover-track is a graphic record of attention scored against the water-surface analytic staff',
    },
    references: [
      'Cogan, R. (1984). New Images of Musical Sound. Harvard UP — spectrographic analysis as music-theoretic notation',
      'Schenker, H. (1935/1979). Free Composition (Der freie Satz), Oster trans. Longman — voice-leading reduction as graph-on-staff notation',
      'Cooper, G. & Meyer, L. B. (1960). The Rhythmic Structure of Music. U. Chicago — graphic prosodic notation',
      'Cone, E. T. (1968). Musical Form and Musical Performance. W. W. Norton',
      'Stone, K. (1980). Music Notation in the Twentieth Century. W. W. Norton — proportional, graphic, and aleatoric systems',
      'Lerdahl, F. & Jackendoff, R. (1983). A Generative Theory of Tonal Music. MIT Press — tree-and-bracket reduction notation',
      'Wexler, H. (1954). Observing the weather from a satellite vehicle. J. Brit. Interplanet. Soc. 13: 269-276',
      'Levine, M. (1989). The Jazz Piano Book. Sher Music',
      'Tymoczko, D. (2011). A Geometry of Music. Oxford UP',
      'Poole, A. F. (1989). Ospreys: A Natural and Unnatural History. Cambridge UP',
      'Bierregaard, R. O., Poole, A. F., Martell, M. S., Pyle, P., & Patten, M. A. (2016). Osprey (Pandion haliaetus). In Birds of North America No. 683. Cornell Lab of Ornithology',
    ],
  },
};
