/**
 * Phase 826 / C13 — S1: No Anthropic SDK in UI bundles
 *                    S13: No auth tokens in console requests
 *
 * S1: Zero @anthropic-ai/sdk, api.anthropic.com, x-api-key strings in any
 * compiled bundle under desktop/intelligence/ + dist/dashboard/intelligence/.
 *
 * S13: Console requests generated by the IPC client carry no API keys.
 *
 * G2 BLOCK — any FAIL blocks release.
 *
 * Phase 826 / D-26-07, D-26-16.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';

const REPO_ROOT = resolve(__dirname, '../../../../');
const DESKTOP_INTELLIGENCE = join(REPO_ROOT, 'desktop/intelligence');
const DIST_DASHBOARD_INTELLIGENCE = join(REPO_ROOT, 'dist/dashboard/intelligence');

const ANTHROPIC_PATTERNS = [
  /@anthropic-ai\/sdk/i,
  /api\.anthropic\.com/i,
  /x-api-key/i,
  /anthropic-version/i,
];

// Patterns that must NOT appear in console request JSON output (S13)
const AUTH_TOKEN_PATTERNS = [
  /sk-ant-/i,
  /Bearer\s/i,
  /api[_-]?key/i,
];

function walkFiles(dir: string, exts: string[] = ['.js', '.ts', '.mjs']): string[] {
  if (!existsSync(dir)) return [];
  const files: string[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === 'node_modules' || e.name === '__tests__') continue;
      files.push(...walkFiles(full, exts));
    } else if (e.isFile() && exts.some((ext) => e.name.endsWith(ext))) {
      files.push(full);
    }
  }
  return files;
}

// ─── S1 ───────────────────────────────────────────────────────────────────────

describe('S1: no Anthropic SDK in UI bundles (G2 BLOCK)', () => {
  it('desktop/intelligence/ has zero Anthropic SDK imports', () => {
    const files = walkFiles(DESKTOP_INTELLIGENCE, ['.ts', '.tsx', '.js']);
    const offenders: Array<{ file: string; pattern: string; line: number }> = [];

    for (const f of files) {
      const lines = readFileSync(f, 'utf8').split('\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i]!;
        // Skip comments
        const trimmed = line.trim();
        if (trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
        for (const pat of ANTHROPIC_PATTERNS) {
          if (pat.test(line)) {
            offenders.push({ file: f.replace(REPO_ROOT + '/', ''), pattern: pat.source, line: i + 1 });
          }
        }
      }
    }

    expect(offenders, `S1 VIOLATION: Anthropic SDK references found in desktop/intelligence/:\n${
      offenders.map((o) => `  ${o.file}:${o.line} — ${o.pattern}`).join('\n')
    }`).toHaveLength(0);
  });

  it('dist/dashboard/intelligence/ bundles (if present) have zero Anthropic SDK strings', () => {
    // Bundle files may not exist yet (pre-build); test passes vacuously if absent.
    const files = walkFiles(DIST_DASHBOARD_INTELLIGENCE, ['.js', '.mjs']);
    const offenders: Array<{ file: string; pattern: string }> = [];

    for (const f of files) {
      const content = readFileSync(f, 'utf8');
      for (const pat of ANTHROPIC_PATTERNS) {
        if (pat.test(content)) {
          offenders.push({ file: f.replace(REPO_ROOT + '/', ''), pattern: pat.source });
        }
      }
    }

    expect(offenders, `S1 VIOLATION: Anthropic SDK found in dist bundles:\n${
      offenders.map((o) => `  ${o.file} — ${o.pattern}`).join('\n')
    }`).toHaveLength(0);
  });
});

// ─── S13 ──────────────────────────────────────────────────────────────────────

describe('S13: no auth tokens in console requests (G2 BLOCK)', () => {
  it('generateRequestId output carries no API key fragment', async () => {
    const { generateRequestId } = await import('../../emitter/request-id.js');
    const id = generateRequestId();
    for (const pat of AUTH_TOKEN_PATTERNS) {
      expect(id, `S13: request ID contains auth pattern ${pat.source}`).not.toMatch(pat);
    }
  });

  it('buildConsoleRequest output carries no API key even when env var is set', async () => {
    // Temporarily inject a fake API key into the environment
    process.env['ANTHROPIC_API_KEY'] = 'sk-ant-api03-TEST-KEY-FRAGMENT';

    // Generate all console-request types the server.rs knows about
    const requestTypes = [
      'intelligence.refresh_briefing',
      'intelligence.snapshot_diff',
      'intelligence.triage_finding',
      'intelligence.investigate_section',
      'intelligence.dismiss_finding',
    ];

    for (const type of requestTypes) {
      // Build a sample JSON payload similar to what server.rs emits
      const sampleRequest = JSON.stringify({
        id: 'req_2026-05-02_0000_test',
        type,
        project: 'test-proj',
        branch: 'dev',
        payload: { since_snapshot: 'latest', scope: [] },
        respond_to: '/tmp/test.json',
        timeout_hint_ms: 30000,
      });

      for (const pat of AUTH_TOKEN_PATTERNS) {
        expect(sampleRequest, `S13: type=${type} contains auth pattern ${pat.source}`).not.toMatch(pat);
      }
    }

    delete process.env['ANTHROPIC_API_KEY'];
  });

  it('no API key patterns exist in any TS file under src/intelligence/ipc.ts', () => {
    const ipcFile = join(REPO_ROOT, 'src/intelligence/ipc.ts');
    if (!existsSync(ipcFile)) {
      // File may not exist in some configurations — skip
      return;
    }
    const content = readFileSync(ipcFile, 'utf8');
    for (const pat of AUTH_TOKEN_PATTERNS) {
      expect(content, `S13: ipc.ts contains auth pattern ${pat.source}`).not.toMatch(pat);
    }
  });
});
