/**
 * Data Assimilation 4D-Var concept -- variational state estimation.
 *
 * Data science at scale: the cost-function progression.
 * Optimal interpolation → 3D-Var → 4D-Var → EnKF → hybrid 4DEnVar
 * combines observations y°, background forecast x^b, and error
 * covariances B and R to produce the analysis x^a.
 *
 * @module departments/data-science/concepts/data-assimilation-4dvar
 */

import type { RosettaConcept } from '../../../rosetta-core/types.js';

// theta ~13*2pi/19, radius ~0.75
const theta = 13 * 2 * Math.PI / 19;
const radius = 0.75;
const real = radius * Math.cos(theta);
const imaginary = radius * Math.sin(theta);

export const dataAssimilation4dvar: RosettaConcept = {
  id: 'data-science-data-assimilation-4dvar',
  name: 'Data Assimilation 4D-Var',
  domain: 'data-science',
  description: 'The variational state-estimation progression that combines ' +
    'observations y°, short-range forecast background x^b, and error ' +
    'covariances B and R to produce the analysis x^a. 3D-Var minimizes ' +
    'J(x) = ½(x-x^b)^T B^(-1) (x-x^b) + ½(y°-H(x))^T R^(-1) (y°-H(x)) ' +
    'with observation operator H. 4D-Var generalizes over a time window ' +
    'using the model\'s tangent-linear and adjoint operators (ECMWF ' +
    'operational since 1997, Météo-France since 2000). The Ensemble Kalman ' +
    'Filter (Evensen 1994) estimates flow-dependent B from a Monte Carlo ' +
    'forecast ensemble. Hybrid 4DEnVar combines static climatological B ' +
    'with flow-dependent EnKF covariance -- NCEP operational in GFS since ' +
    '2016. Major centers ingest ~200 million observations per day.',
  panels: new Map([
    ['python', {
      panelId: 'python',
      explanation: 'Python data-assimilation stacks (DAPPER + xarray + scipy.optimize) load ERA5 background fields and observation streams into Dataset objects, then minimize J(x) = ½(x-x^b)^T B^(-1) (x-x^b) + ½(y°-H(x))^T R^(-1) (y°-H(x)) via L-BFGS over a 12-hour window. ' +
        'Notebook workflows compose the tangent-linear and adjoint operators as callables, run EnKF updates with flow-dependent covariance, and verify the analysis against withheld observations. ' +
        'See Evensen 1994.',
    }],
    ['cpp', {
      panelId: 'cpp',
      explanation: 'C++ operational DA cores (ECMWF IFS, NCEP GSI, Météo-France ARPEGE) implement incremental 4D-Var with tangent-linear and adjoint operators generated by the TAPENADE/OpenAD source transformers. ' +
        'Templated MinimiserState<IncrementalCG> holds the inner-loop state; MPI halo exchanges the control vector across tile boundaries; each outer iteration ingests ~200 million observations per 12-hour cycle. ' +
        'See Evensen 1994.',
    }],
    ['unison', {
      panelId: 'unison',
      explanation: 'Unison expresses data-assimilation operators as content-addressed ability-tracked functions: the observation operator H, the tangent-linear M_T, and the adjoint M_A each hash to a unique identifier. ' +
        'A 4D-Var analysis is a composition of these hashes applied to an immutable background field; the full assimilation history forms a Merkle-DAG where every analysis x^a is reproducible from its input hashes. ' +
        'See Evensen 1994.',
    }],
  ]),
  relationships: [
    {
      type: 'cross-reference',
      targetId: 'physics-primitive-equations',
      description: 'Data assimilation produces the initial condition that the primitive-equation integrator then evolves',
    },
    {
      type: 'dependency',
      targetId: 'math-ratios-proportions',
      description: 'The cost function weights observation vs background through error-covariance inverses -- precision ratios',
    },
  ],
  complexPlanePosition: {
    real,
    imaginary,
    magnitude: Math.sqrt(real * real + imaginary * imaginary),
    angle: Math.atan2(imaginary, real),
  },
};
