import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.9 — Bang-bang brake-motor controller stability:
 * angular-velocity threshold detection, brake-motor torque rise-time,
 * and the Pioneer 2 third-stage spin-arrest failure (1958-11-08).
 *
 * Generated by the v1.49.581 ELC Wave-4 backfill (slot E4-B, 2026-04-26).
 * Cross-references: NASA degree peer (Pioneer 2 / Thor-Able II 130),
 * MUS degree peer (threshold-tolerance gesture as the structural rhyme of
 * the one-shot bang-bang inequality).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const brakeControllerStability: RosettaConcept = {
  id: 'elc-1.9-brake-controller-stability',
  name: 'Bang-bang brake-motor controller stability — threshold-vs-rise-time inequality (Pioneer 2 third-stage spin-arrest failure)',
  domain: 'electronics',
  description:
    'A stability-engineering primitive describing how a one-shot bang-bang despin loop driven by ' +
    'a tachometer-fed Schmitt-trigger threshold comparator and a finite-rise-time brake-motor torque ' +
    'element achieves stable residual angular velocity at brake-motor cutoff iff the threshold-times-' +
    'rise-time product satisfies a closed-form inequality. The residual-rate equation ' +
    'omega_res = omega_th - tau_brake_full * tau_RISE / I_3 + epsilon_hyst is the BIBO-stability ' +
    'statement for the one-shot loop; violating the inequality leaves the spacecraft with residual ' +
    'angular velocity outside the design margin. The canonical flight exemplar is Pioneer 2 ' +
    '(Thor-Able II 130 / AFBMD lunar-orbit attempt, Cape Canaveral LC-17A 1958-11-08), whose threshold ' +
    'detector was mis-trimmed to fire at approximately 9 rad/s instead of the design 6 rad/s and whose ' +
    'brake-motor torque rise-time stretched from a design-budget 30 ms to approximately 80 ms owing ' +
    'to a colder-than-spec brake-actuation chamber. The combined error left the X-248 third-stage ' +
    'with approximately 1.8 rad/s residual angular velocity at brake-motor cutoff (six times the design ' +
    'margin), the third stage tipped during the subsequent 38-second X-248 burn enough to break the ' +
    'lunar-injection corridor, and the spacecraft re-entered over the north Atlantic at T+42 minutes. ' +
    'The pedagogical primitive scales: every NASA spin-stabilised solid-rocket-motor stage from 1958 ' +
    'onward (Vanguard, Juno, early Atlas-Agena combinations, Scout) carries the same despin-chain ' +
    'inequality as the first equation to write, with the threshold-and-rise-time tolerances as the ' +
    'design knobs that must be sized before flight. The Wertz §18 derivation is the canonical textbook ' +
    'treatment; the Hughes §6.3 spin-stabilisation analysis gives the residual-rate specifics; the ' +
    'Bryson & Ho §6 describing-function approach gives the relay-with-hysteresis formal underpinning.',
  panels: new Map(),
  relationships: [
    {
      type: 'related',
      targetId: 'elc-1.22-limit-cycle-cold-gas-attitude',
      description:
        'An earlier Domain-5 entry covers continuous limit-cycle bang-bang for cold-gas attitude control ' +
        '(deadband-vs-latency inequality). Both that concept and this concept extend continuous-time ' +
        'stability to switched-actuator topologies: the cold-gas case covers continuous limit-cycle ' +
        'where the loop fires repeatedly to maintain pointing; this case covers ONE-SHOT bang-bang ' +
        'where the loop fires exactly once per mission and the residual error after that firing must ' +
        'satisfy a stability inequality. The structural rhyme: a single design-knob choice (deadband ' +
        'width / threshold-times-rise-time product) that consumes the loop\'s stability budget and ' +
        'surfaces in flight as a single-event failure that the design equation could have flagged ' +
        'pre-flight.',
    },
    {
      type: 'related',
      targetId: 'elc-1.28-feedback-stability-guidance',
      description:
        'An earlier Domain-5 entry covers continuous-time phase-margin failure ' +
        '(smoothing-filter pole placement). Both that concept and this concept pin a single closed-loop ' +
        'stability inequality as the pedagogical primitive; that concept covers continuous-time pole ' +
        'placement; this concept covers one-shot bang-bang threshold detection. The structural rhyme ' +
        'is direct: a single design-time parameter sets the stability budget and a flight-failure event ' +
        'pins the consequences of violating it.',
    },
    {
      type: 'dependency',
      targetId: 'elec-feedback-stability',
      description:
        'The describing-function method depends on the closed-loop frequency-response framework; the ' +
        'relay-with-hysteresis describing function is an analytic continuation of the linear-loop-gain ' +
        'analysis to piecewise-linear nonlinear elements. This concept depends on the Domain-5 ' +
        'frequency-response primitives.',
    },
    {
      type: 'dependency',
      targetId: 'elec-power-electronics',
      description:
        'The brake-motor solenoid driver chain (germanium NPN switch + freewheel diode + solenoid coil) ' +
        'is a switched-power topology; the rise-time tau_RISE is set by the storage-time + L/R + ' +
        'mechanical-settling cascade. This concept depends on the switched-actuator power primitives ' +
        'in Domain 6.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.9-threshold-tolerance-gesture',
      description:
        'The threshold-vs-rise-time inequality is itself a balance gesture that resolves at a ' +
        'structurally weighted point — the threshold value at which the brake-pad torque has time to ' +
        'fully develop within the firing window. The musical gesture resolves at a parallel ' +
        'structurally weighted point: a threshold tolerance whose violation produces an over-active ' +
        'or under-active gesture rather than the intended one. Both are local-balance gestures whose ' +
        'effectiveness depends on parameter selection.',
    },
  ],
  metadata: {
    elcDegree: '1.9',
    domain: 5,
    domainName: 'Stability & feedback',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware:
      'Pioneer 2 (Thor-Able II 130) third-stage spin-stabilization despin electronics — Bulova-built ' +
      'rate-sensing tachometer + 1N34A point-contact germanium half-wave rectifier + RC envelope ' +
      'filter + 2N1308-class discrete-germanium-NPN Schmitt-trigger threshold comparator + 2N1308-' +
      'class common-emitter brake-motor solenoid driver gating the X-248 third-stage despin brake-' +
      'pad assembly; the brake-motor controller was the load-bearing teaching subset (AFBMD Pioneer 2 ' +
      'Post-Flight Analysis 1958; Corliss 1967 NASA SP-133 §3)',
    keyEquation:
      'omega_res = omega_th - tau_brake_full * tau_RISE / I_3 + epsilon_hyst ; ' +
      'omega_th <= omega_design + (tau_brake_full * tau_RISE / I_3) - epsilon_hyst (stability inequality)',
    benchReplication: {
      activeDriver:
        'DRV8873-Q1 (Texas Instruments) — automotive H-bridge motor driver, internal current-limit + ' +
        'freewheel-diode + shoot-through interlocks, AEC-Q100 grade-1',
      eraOriginal:
        '2N1308-class germanium NPN common-emitter switch + 1N34A point-contact germanium freewheel ' +
        'diode + AFBMD/STL custom brake-motor squib release',
      activeComparator:
        'LM311 (Texas Instruments) — single-supply comparator with explicit feedback-resistor ' +
        'hysteresis; Schmitt-trigger configuration with sweepable threshold and deadband',
      activeIntegrator:
        'OP07 (Texas Instruments) — precision bipolar op-amp x2 in cascade for the spacecraft-inertia ' +
        'integrator emulator',
      activeRectifier:
        'AD8676 (Analog Devices) — dual precision op-amp configured as half-wave rectifier + envelope ' +
        'filter buffer; replaces the era-original 1N34A rectifier',
      tachometerSurrogate:
        'Function-generator AM-modulated source (Rigol DG812 or equivalent) delivering a 50 Hz ' +
        'sinusoid amplitude-modulated by a slow ramp; modulation amplitude maps to instantaneous spin ' +
        'rate. Canonical educational substitute (Wertz §18 footnote on bench-test fixtures).',
      sideBySidePattern:
        'NOMINAL branch (omega_th = 6 rad/s, tau_RISE = 30 ms, residual ~0.3 rad/s) + FAILURE branch ' +
        '(omega_th = 9 rad/s, tau_RISE = 80 ms, residual ~1.8 rad/s) in a single .tran sweep — V(omega_a) ' +
        'and V(omega_b) at end of brake-motor cutoff are the bang-bang threshold-vs-rise-time inequality ' +
        'made literal',
    },
    references: [
      'Wertz, J. R. (1978). Spacecraft Attitude Determination and Control §18 — bang-bang control with hysteresis',
      'Bryson, A. E., & Ho, Y.-C. (1975). Applied Optimal Control §6 — relay control with hysteresis describing function',
      'Hughes, P. C. (2004). Spacecraft Attitude Dynamics §6.3 — spin stabilisation and despin',
      'AFBMD Pioneer 2 Post-Flight Analysis (1958) — primary engineering reconstruction',
      'Corliss, W. R. (1967). Scientific Satellites NASA SP-133 §3 — secondary-source narrative',
      'Hallion, R. P. (1984). On the Frontier: Flight Research at Dryden NASA SP-4303 — early Pioneer programme context',
      'Franklin, Powell, Emami-Naeini (2019). Feedback Control of Dynamic Systems (8e). Pearson — ch. 9 nonlinear control',
      'Ogata, K. (2010). Modern Control Engineering (5e). Prentice Hall — §6.7 phase margin; §10 BIBO stability',
      'Horowitz, P., & Hill, W. (2015). The Art of Electronics (3e). Cambridge UP — §4.3 Schmitt triggers',
      'TI DRV8873-Q1 datasheet, https://www.ti.com/lit/ds/symlink/drv8873-q1.pdf',
      'TI LM311 datasheet, https://www.ti.com/lit/ds/symlink/lm311.pdf',
    ],
    flightDate: '1958-11-08',
    designThreshold: '6 rad/s (mis-trimmed to ~9 rad/s in flight)',
    designRiseTime: '30 ms (stretched to ~80 ms in flight by cold-chamber bedding-in)',
    designResidualRate: '0.3 rad/s (flight residual ~1.8 rad/s at brake-motor cutoff)',
    flightOutcome:
      'Sub-orbital re-entry over north Atlantic at T+42 minutes; trans-lunar injection failed when ' +
      'residual angular velocity tipped the X-248 spin axis through the lunar-injection corridor during ' +
      'the 38-second third-stage burn',
    recoveryFlight:
      'Pioneer 3 (1958-12-06) and onward — despin chain redesigned with tighter threshold tolerances ' +
      'and faster brake-motor torque actuation; subsequent Thor-Able combinations reached cislunar ' +
      'space within design margin',
  },
} as RosettaConcept;
