import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.56 — Cutoff-logic stability in soft-landing feedback loops:
 * radar-altimeter latency, vernier-engine cutoff threshold, and the
 * Surveyor 3 bounce-landing causal chain.
 *
 * Generated by the v1.49.581 ELC Wave-2 backfill (slot E2-G, 2026-04-26).
 * Cross-references: NASA 1.56 (Surveyor 3 bounce-landing 1967-04-20),
 * MUS 1.56 (balance-and-recovery musical gesture — the cutoff-margin
 * inequality as the structural rhyme of the deferred cadence's resolution).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const cutoffLogicSoftLanding: RosettaConcept = {
  id: 'elc-1.56-cutoff-logic-soft-landing',
  name: 'Cutoff-margin stability for switched-actuator soft-landing loops (Surveyor 3 bounce-landing)',
  domain: 'electronics',
  description:
    'A stability-engineering primitive describing how a switched-actuator feedback loop achieves a soft ' +
    'cutoff iff the threshold-margin in altitude units exceeds the descent rate times the actuator latency. ' +
    'The cutoff-margin inequality M_cutoff = (h_threshold - h_target) - v_descent × τ_latency ≥ 0 is the ' +
    'BIBO-stability statement for a switched-actuator cutoff path; failing the inequality strands residual ' +
    'thrust past the target altitude and accumulates an upward velocity ΔV proportional to the deficit. ' +
    'The canonical flight exemplar is the Surveyor 3 bounce-landing on 1967-04-20, where the altitude-marking ' +
    'radar (Sperry Mark V) was bench-calibrated against a low-reflectivity reference plate; the actual mare ' +
    'regolith returned a ~3.5× stronger envelope; the cutoff comparator fired roughly ten metres above the ' +
    'intended 4.3 m altitude; and the 140 ms vernier-valve latency converted that margin deficit into a ' +
    '+1.5 m/s upward bounce-launch velocity. The spacecraft bounced to 10 m, 11 m, and 3 m successively before ' +
    'settling intact; the bounce was harmless because the structural margins absorbed it. The Surveyor 4-7 ' +
    'retrofit (lower V_TH + a coast phase) closed the cutoff-margin envelope to bracket the full reflectivity ' +
    'uncertainty range. The pedagogical primitive: every switched-actuator feedback loop selects its threshold-' +
    'and-latency budget at the same inequality, and the engineering question across all eras is the same — ' +
    'what is the worst-case M_cutoff under the full envelope of terrain-and-actuator uncertainty?',
  panels: new Map(),
  relationships: [
    {
      type: 'related',
      targetId: 'elc-1.28-feedback-stability-guidance',
      description:
        'ELC 1.28 (Mariner 1 missing-overbar) is the predecessor Domain-5 entry. Both ELC 1.28 and ELC 1.56 pin ' +
        'a single closed-loop stability inequality as the pedagogical primitive. ELC 1.28 covers continuous-time ' +
        'phase margin (PM = 180° + ∠L(jω_c)); ELC 1.56 extends to switched-actuator cutoff margin ' +
        '(M_cutoff = (h_threshold - h_target) - v_descent × τ_latency). The structural rhyme: a missing pole/zero ' +
        'or a calibration-envelope violation that consumes the loop\'s stability budget and surfaces in flight as ' +
        'a single-event failure that the design equation could have flagged pre-flight.',
    },
    {
      type: 'dependency',
      targetId: 'elec-frequency-response',
      description:
        'The cutoff-margin inequality is the time-domain analog of phase-margin; the τ_latency RC dominant pole ' +
        'sets the loop bandwidth and the threshold-margin inequality is its BIBO-stability statement. This ' +
        'concept depends on the frequency-response analysis primitives in Domain 3.',
    },
    {
      type: 'dependency',
      targetId: 'elec-power-electronics',
      description:
        'The vernier-valve driver chain (drive transistor + free-wheel diode + solenoid coil) is a switched-power ' +
        'topology; the latency τ_latency is set by the coil + valve mechanical dynamics. This concept depends ' +
        'on the switched-actuator power primitives in Domain 6.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.56-balance-and-recovery',
      description:
        'The cutoff-margin inequality is itself a balance gesture that resolves at a structurally weighted point ' +
        '(M_cutoff = 0, the BIBO boundary) — the moment where soft landing and bounce landing become ' +
        'indistinguishable. The musical gesture resolves at the same kind of point: a delayed cadence whose ' +
        'recovery depends on the listener\'s tolerance for the deferred resolution. Both are local-zero gestures ' +
        'in a balance equation, structurally weighted by the underlying mathematics.',
    },
  ],
  metadata: {
    elcDegree: '1.56',
    domain: 5,
    domainName: 'Stability & feedback',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware: 'Surveyor 3 RADVS chain — Sperry Gyroscope Mark V Altitude Marking Radar (AMR) + Doppler velocity radar + Hughes-built vernier-engine cutoff comparator + 28V hold-up bus to Thiokol TD-339 vernier throttle valves; AMR cutoff fired at high reflectivity outside calibration envelope on 1967-04-20',
    keyEquation: 'M_cutoff = (h_threshold - h_target) - v_descent × τ_latency ≥ 0 ; ΔV_residual ≈ -a_residual × M_cutoff / v_descent for M_cutoff < 0',
    benchReplication: {
      activeAltimeter: 'TUSS44x0 (Texas Instruments) — single-chip ultrasonic time-of-flight transceiver, 40-1000 kHz, programmable threshold + envelope-detector + cutoff comparator',
      eraOriginal: 'Sperry Gyroscope Mark V altitude-marking radar (9.3 GHz CW-modulated klystron, ~50 W peak, RC envelope-detector + bipolar threshold comparator)',
      activeOpAmp: 'OP07 (Texas Instruments) — precision bipolar, Vos=10µV typ, en=9.6 nV/√Hz; LM311 comparator buffer',
      vernierLatency: '140 ms (Thiokol TD-339 vernier valve mechanical settling time, scaled to ~30-50 ms via 12V hobby solenoid for bench)',
      cutoffThreshold: 'V_TH = 0.45 V (intended Surveyor 3 4.3 m cutoff altitude); sweepable 0.30-0.70 V to trace bounce-landing boundary',
      sideBySidePattern: 'NOMINAL branch (reflectivity = 1.0×, low-reflectivity terrain) + BOUNCE-LANDING branch (reflectivity = 3.5×, mare regolith) in a single .tran sweep — V(nominal) - V(bounce) at end-of-descent is the bounce-landing primitive made literal',
    },
    references: [
      'NASA SP-184, Surveyor: Program Results (1969) §5 — Surveyor 3 mission and the AMR-cutoff anomaly post-flight reconstruction',
      'Hall, C. F. (1967). Surveyor 3 Mission Report. JPL Technical Report 32-1177',
      'Cheng, R. T. (1968). "Surveyor Terminal Guidance." AIAA Journal of Spacecraft and Rockets 5: 1232-1238',
      'Franklin, Powell, Emami-Naeini (2019). Feedback Control of Dynamic Systems (8e). Pearson — ch. 7 on discrete-time control',
      'Åström, K. J., & Wittenmark, B. (1997). Computer-Controlled Systems: Theory and Design (3e). Prentice Hall — ch. 11 on sample-rate selection and finite-latency stability',
      'Ogata, K. (2010). Modern Control Engineering (5e). Prentice Hall — §6.7 phase margin; §10 BIBO stability of switched-actuator loops',
      'Razavi, B. (2017). Design of Analog CMOS Integrated Circuits (2e). McGraw-Hill — ch. 11 on comparator design',
      'TI TUSS4470 datasheet, https://www.ti.com/lit/ds/symlink/tuss4470.pdf',
    ],
    flightDate: '1967-04-20',
    bounceAltitudeMetres: [10, 11, 3],
    residualDeltaV: '+1.5 m/s upward at first surface contact; bounce-launch velocity from cutoff-margin deficit',
    recoveryFlight: 'Surveyor 4-7 (1967-1968) — V_TH lowered to 0.30 V + coast phase reduces v_descent to 0.8 m/s, M_cutoff ≥ 0 over full reflectivity envelope',
  },
} as RosettaConcept;
