import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.22 — Limit-cycle oscillation in cold-gas attitude control:
 * deadband design, valve driver hysteresis, and the Ranger 2
 * nitrogen-depletion failure (1961-11-18).
 *
 * Generated by the v1.49.581 ELC Wave-3 backfill (slot E3-G, 2026-04-26).
 * Cross-references: NASA 1.22 (Ranger 2 / Block I prototype),
 * MUS 1.22 (deadband-as-cadential-tolerance — the limit-cycle inequality
 * as the structural rhyme of an over-active ornamentation gesture).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const limitCycleColdGasAttitude: RosettaConcept = {
  id: 'elc-1.22-limit-cycle-cold-gas-attitude',
  name: 'Relay-with-hysteresis limit-cycle inequality for cold-gas attitude control (Ranger 2 nitrogen-depletion failure)',
  domain: 'electronics',
  description:
    'A stability-engineering primitive describing how a switched-actuator attitude-control loop driven ' +
    'by a relay-with-hysteresis comparator achieves stable settling iff the deadband-times-inertia product ' +
    'is large enough relative to the impulse-times-latency budget. The limit-cycle period equation ' +
    'T_LC = 4 × deadband × J / (impulse_per_pulse × 2) and its propellant-consumption corollary ' +
    'ṁ_propellant = (impulse_per_pulse × mass_per_pulse) / (2 × deadband × J) are the BIBO-stability ' +
    'statement for the bang-bang loop; violating the inequality yields a chatter mode that depletes the ' +
    'propellant reservoir faster than the design budget. The canonical flight exemplar is Ranger 2 ' +
    '(Atlas-Agena B / JPL Block I prototype, 1961-11-18), whose comparator deadband of approximately ' +
    '±0.05° combined with a finite valve-driver mechanical-settling latency drove the cold-gas reaction-' +
    'control thrusters into a bang-bang chatter at approximately 3 Hz, depleting the GN₂ tank within hours ' +
    'of injection and leaving the spacecraft tumbling with no recovery option. Ranger 3 onward redesigned ' +
    'the deadband (widened tenfold to ±0.5°) and added valve-driver hysteresis matched to mechanical ' +
    'settling, closing the inequality and bringing the propellant budget within mission margin. The ' +
    'pedagogical primitive scales: every NASA spacecraft attitude-control design from Mariner through ' +
    'Voyager to modern smallsat reaction-wheel hybrid loops carries the same deadband-vs-latency inequality ' +
    'as the first equation to write, with the propellant-consumption corollary as the design knob that ' +
    'must be turned before flight. The Wertz §18 derivation is the canonical textbook treatment; the ' +
    'Bryson & Ho §6 describing-function approach gives the relay-with-hysteresis specifics.',
  panels: new Map(),
  relationships: [
    {
      type: 'related',
      targetId: 'elc-1.28-feedback-stability-guidance',
      description:
        'ELC 1.28 (Mariner 1 missing-overbar) is an earlier Domain-5 entry covering continuous-time phase ' +
        'margin failure (PM = 180° + ∠L(jω_c)). Both ELC 1.28 and this concept pin a single closed-loop ' +
        'stability inequality as the pedagogical primitive: ELC 1.28 covers continuous-time pole placement; ' +
        'this concept covers relay-with-hysteresis bang-bang stability. The structural rhyme: a single ' +
        'design-knob choice (smoothing-filter pole / deadband width) that consumes the loop\'s stability ' +
        'budget and surfaces in flight as a single-event failure that the design equation could have flagged ' +
        'pre-flight.',
    },
    {
      type: 'related',
      targetId: 'elc-1.56-cutoff-logic-soft-landing',
      description:
        'ELC 1.56 (Surveyor 3 bounce-landing) is an earlier Domain-5 entry covering switched-actuator ' +
        'cutoff stability (M_cutoff = h_threshold - h_target - v_descent × τ_latency ≥ 0). Both ELC 1.56 and ' +
        'this concept extend continuous-time stability to switched-actuator topologies with finite latency ' +
        'paths: ELC 1.56 covers cutoff-margin for one-shot landing, this concept covers limit-cycle for ' +
        'continuous-operation attitude hold. The structural rhyme: a latency-times-rate budget that, when ' +
        'violated, converts the BIBO-stability deficit into a residual ΔV (Surveyor 3) or a propellant-' +
        'depletion rate (Ranger 2).',
    },
    {
      type: 'dependency',
      targetId: 'elec-feedback-stability',
      description:
        'The describing-function method depends on the closed-loop frequency-response framework; the relay-' +
        'with-hysteresis describing function is an analytic continuation of the linear-loop-gain analysis to ' +
        'piecewise-linear nonlinear elements. This concept depends on the Domain-5 frequency-response ' +
        'primitives.',
    },
    {
      type: 'dependency',
      targetId: 'elec-power-electronics',
      description:
        'The valve-driver chain (germanium NPN switch + freewheel diode + solenoid coil) is a switched-power ' +
        'topology; the latency τ_latency is set by the storage-time + L/R + mechanical-settling cascade. ' +
        'This concept depends on the switched-actuator power primitives in Domain 6.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.22-deadband-as-cadential-tolerance',
      description:
        'The deadband-vs-latency inequality is itself a balance gesture that resolves at a structurally ' +
        'weighted point — the deadband width at which the limit-cycle period equals the propellant-budget ' +
        'time horizon. The musical gesture resolves at a parallel structurally weighted point: a cadential ' +
        'tolerance whose violation produces over-active ornamentation rather than rest. Both are local-' +
        'balance gestures whose effectiveness depends on parameter selection.',
    },
  ],
  metadata: {
    elcDegree: '1.22',
    domain: 5,
    domainName: 'Stability & feedback',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'Ranger Block I attitude-control electronics (JPL flight-build) — three rate-integrating gyros phase-detected against a 400 Hz reference for PPM readout, three Schmitt-trigger deadband comparators built around discrete-germanium 2N1308-class NPN pairs, three 2N1308-class germanium NPN common-emitter solenoid valve drivers with 1N34A point-contact germanium freewheel diodes, twelve cold-gas (GN₂) thrusters arranged for couples on three axes; chattered Ranger 2\'s nitrogen tank empty within hours of injection on 1961-11-18',
    keyEquation: 'T_LC = 4 × deadband × J / (impulse_per_pulse × 2) ; ṁ_propellant = (impulse_per_pulse × mass_per_pulse) / (2 × deadband × J)',
    benchReplication: {
      activeDriver: 'DRV8243-Q1 (Texas Instruments) — automotive H-bridge solenoid driver, internal current-limit + freewheel-diode + shoot-through interlocks, AEC-Q100 grade-1',
      eraOriginal: '2N1308-class germanium NPN common-emitter switch + 1N34A point-contact germanium freewheel diode + JPL custom GN₂ thruster valve',
      activeComparator: 'LM311 (Texas Instruments) — single-supply comparator with explicit feedback-resistor hysteresis; Schmitt-trigger configuration with sweepable deadband',
      activeIntegrator: 'OP07 (Texas Instruments) — precision bipolar op-amp ×2 in cascade for the spacecraft-inertia double-integrator emulator',
      activeDemodulator: 'AD630 (Analog Devices) — synchronous demodulator IC; replaces the era-original 4× 1N34A ring demodulator',
      solenoidSurrogate: '12 V automotive fuel-injector solenoid (e.g. Bosch 0280155965, ~3 Ω coil resistance, ~1 mH inductance, 1-5 ms mechanical settling)',
      sideBySidePattern: 'STABLE branch (deadband ±0.5°, hysteresis matched) + CHATTER branch (deadband ±0.05°, hysteresis insufficient) in a single .tran sweep — V(att_a) - V(att_b) at end of disturbance is the limit-cycle primitive made literal',
    },
    references: [
      'JPL Technical Report 32-241, Ranger Block I Mission Operations Report (1962-04) §3 — primary investigation findings',
      'Hall, R. C. (1977). Lunar Impact: A History of Project Ranger. NASA SP-4210 §3 — secondary-source narrative',
      'Wertz, J. R. (1978). Spacecraft Attitude Determination and Control §18 — bang-bang limit-cycle equations',
      'Bryson, A. E., & Ho, Y.-C. (1975). Applied Optimal Control §6 — relay control with hysteresis describing function',
      'Franklin, Powell, Emami-Naeini (2019). Feedback Control of Dynamic Systems (8e). Pearson — ch. 9 nonlinear control',
      'Ogata, K. (2010). Modern Control Engineering (5e). Prentice Hall — §6.7 phase margin; §10 BIBO stability',
      'Horowitz, P., & Hill, W. (2015). The Art of Electronics (3e). Cambridge UP — §4.3 Schmitt triggers; §4.5 saturation behaviour',
      'TI DRV8243-Q1 datasheet, https://www.ti.com/lit/ds/symlink/drv8243-q1.pdf',
      'TI LM311 datasheet, https://www.ti.com/lit/ds/symlink/lm311.pdf',
    ],
    flightDate: '1961-11-18',
    deadbandRanger2: '±0.05° (too narrow given valve-driver latency)',
    deadbandRedesign: '±0.5° (tenfold widening, Ranger 3 onward)',
    limitCycleFrequency: '~3 Hz (latency-coupled, demodulator-pole locked)',
    propellantDepletionTime: '~6-12 hours from injection to empty tank',
    recoveryFlight: 'Ranger 3 (1962-01-26) and onward — deadband widened, valve-driver hysteresis matched to mechanical settling, propellant budget closes with margin',
  },
} as RosettaConcept;
