import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.45 — Sign-inverted feedback under stuck-actuator failure:
 * positive-feedback closure through a stuck-on thruster channel and
 * the Gemini 8 OAMS Thruster-8 emergency.
 *
 * Generated by the v1.49.581 ELC Wave-7 backfill (slot E7-H, 2026-04-27).
 * This concept CLOSES Domain 5 (Stability & feedback) of the ELC fleet.
 *
 * Cross-references: NASA 1.45 (Gemini 8 first orbital docking + thruster
 * stuck-on emergency 1966-03-16), MUS 1.45 (sign-inverted resolution /
 * deceptive-cadence-as-failover — the structural rhyme of the chord
 * that should-have-resolved-one-way resolving the opposite way and
 * recovered through a substitute-progression that restores expected
 * motion).
 *
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const stuckActuatorSignInversion: RosettaConcept = {
  id: 'elc-1.45-stuck-actuator-sign-inversion',
  name: 'Sign-of-loop-gain stability for switched-actuator loops under stuck-actuator failure (Gemini 8 OAMS)',
  domain: 'electronics',
  description:
    'A stability-engineering primitive describing how a switched-actuator attitude-control loop is BIBO-stable iff ' +
    'the gated-channel authority exceeds any single stuck-actuator\'s authority: K_stuck ≤ K_total_gated_max. ' +
    'Failing the inequality flips the loop\'s effective sign of feedback to positive through the stuck channel; ' +
    'the rate runs away; the only recovery is runtime loop redesign — disabling the stuck-actuator block and ' +
    'engaging a redundant block whose authority restores the negative-feedback sign. The canonical flight exemplar ' +
    'is the Gemini 8 OAMS Thruster-8 stuck-on emergency on 1966-03-16, where a 2N1132-class silicon-PNP solenoid ' +
    'driver collector-emitter shorted to the +28 V hold-up bus, latching Thruster No. 8 in continuous fire. The ' +
    'remaining three yaw thrusters (gated counter-authority = 0.75 K_OAMS) could not oppose the stuck thruster\'s ' +
    'continuous K_stuck = 1.0 K_OAMS authority; the inequality failed by a factor of 1.33; the loop ran away to ' +
    '~296°/s in approximately 13 seconds. Armstrong\'s OAMS-OFF / RCS-ON failover sequence — manually-commanded — ' +
    'is electrically a runtime loop redesign that swapped the dominant actuator authority for the redundant RCS ' +
    'block at K_RCS = 0.6 K_OAMS, restoring the sign of feedback to negative; the spacecraft damped over several ' +
    'minutes and committed to single-orbit emergency reentry. The pedagogical primitive: stuck-actuator failure ' +
    'is fundamentally a topology failure of feedback, not a margin failure; the recovery is fundamentally a runtime ' +
    'loop redesign, not a parameter retrim. This concept CLOSES Domain 5 of the v1.49.581 ELC fleet, completing ' +
    'a five-fold taxonomy of switched-actuator stability failures across the 1958-1968 era: threshold-vs-rise-time ' +
    '(ELC 1.9), deadband-vs-hysteresis (ELC 1.22), continuous-time phase-margin (ELC 1.28), cutoff-margin (ELC 1.56), ' +
    'and now sign-of-loop-gain (ELC 1.45) — four scalar margins + one topology = the complete taxonomy.',
  panels: new Map(),
  relationships: [
    {
      type: 'related',
      targetId: 'elc-1.56-cutoff-logic-soft-landing',
      description:
        'ELC 1.56 (Surveyor 3 cutoff-margin) is the immediate predecessor Domain-5 entry. Both ELC 1.56 and ELC 1.45 ' +
        'are switched-actuator stability degrees with a single-equation BIBO-stability inequality as the pedagogical ' +
        'primitive. ELC 1.56 covers cutoff-margin (a scalar margin under calibration-envelope violation); ELC 1.45 ' +
        'extends to sign-of-loop-gain (a topology failure under stuck-actuator). The pair forms the switched-actuator ' +
        'half of Domain 5; together they close the domain with continuous-time (ELC 1.28) and bang-bang (ELC 1.22) ' +
        'partners.',
    },
    {
      type: 'related',
      targetId: 'elc-1.28-feedback-stability-guidance',
      description:
        'ELC 1.28 (Mariner 1 missing-overbar) is a Domain-5 sibling. ELC 1.28 covers continuous-time phase margin; ' +
        'ELC 1.45 extends to sign-of-loop-gain under stuck-actuator failure. Both pin a single closed-loop stability ' +
        'inequality but at different layers of the loop description: ELC 1.28 at the linear-pole-placement level, ' +
        'ELC 1.45 at the topology-of-feedback level.',
    },
    {
      type: 'related',
      targetId: 'elc-1.22-limit-cycle-cold-gas-attitude',
      description:
        'ELC 1.22 (Ranger 2 cold-gas attitude limit-cycle) is a Domain-5 sibling at the bang-bang-control layer. ' +
        'Both ELC 1.22 and ELC 1.45 deal with switched-actuator attitude-control loops; ELC 1.22 covers the ' +
        'deadband-vs-hysteresis limit-cycle in the bang-bang regime, ELC 1.45 covers the sign-of-loop-gain flip ' +
        'under single-channel stuck-on failure. Same architecture, different failure axis.',
    },
    {
      type: 'related',
      targetId: 'elc-1.9-brake-controller-stability',
      description:
        'ELC 1.9 (Pioneer 2 brake-motor) is the earliest Domain-5 entry; pins threshold-vs-rise-time scalar margin. ' +
        'Both ELC 1.9 and ELC 1.45 deal with switched-actuator authority and the timing of authority engagement; ' +
        'ELC 1.9 covers the case where the threshold-detector fires too early and rise-time eats margin; ELC 1.45 ' +
        'covers the case where one channel of authority is committed beyond control of the loop.',
    },
    {
      type: 'dependency',
      targetId: 'elec-power-electronics',
      description:
        'The OAMS thruster-driver chain (2N1132 PNP common-emitter switch + 1N4148 freewheel diode + 8 mH solenoid ' +
        'coil) is a switched-power topology; the failure mode (collector-emitter short under inductive turn-off ' +
        'transient) is itself a power-electronics failure. The sign-inversion concept depends on the switched-' +
        'actuator power-driver primitives in Domain 6.',
    },
    {
      type: 'dependency',
      targetId: 'elec-frequency-response',
      description:
        'The Lyapunov-stability framework underlying the sign-of-loop-gain inequality requires the loop\'s ' +
        'continuous-time pole-placement description (V(ω) = ½ J ω² as Lyapunov function; dV/dt sign determined ' +
        'by loop sign). This concept depends on the frequency-response analysis primitives in Domain 3.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.45-sign-inverted-resolution',
      description:
        'The sign-of-loop-gain inequality is itself a sign gesture (the loop\'s polarity flips through a single ' +
        'channel) — exactly analogous to the deceptive-cadence-as-failover gesture in MUS 1.45 (the chord that ' +
        'should have resolved one way resolves the opposite way, recovered through a substitute-progression that ' +
        'restores expected motion). Both are sign-of-resolution gestures recovered through a substitution that ' +
        'restores expected directionality. The structural rhyme is exact.',
    },
  ],
  metadata: {
    elcDegree: '1.45',
    domain: 5,
    domainName: 'Stability & feedback',
    domainStatus: 'CLOSES Domain 5 (target 5, current 5 with this entry)',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Gemini 8 Orbital Attitude and Maneuvering System (OAMS) — McDonnell Aircraft Corporation 16-thruster ' +
      'hypergolic (MMH/N₂O₄) attitude-control + 25 lbf yaw Thruster No. 8 with 2N1132-class silicon-PNP common-' +
      'emitter solenoid driver on +28 V hold-up bus + IBM/Honeywell rate-integrating gyro analog feedback + ' +
      'manual proportional control stick + redundant Reentry Control System (RCS) thrusters; flown 1966-03-16 ' +
      'with Armstrong (CDR) + Scott (PLT)',
    keyEquation:
      'K_stuck ≤ K_total_gated_max (BIBO-stability iff inequality holds); under stuck-on failure with K_stuck > ' +
      'K_total_gated_max, sign of loop gain flips to positive and rate runs away. Recovery: K_OAMS → 0 + K_RCS = ' +
      '0.6 K_OAMS engaged; sign restored to negative.',
    benchReplication: {
      activeDriver:
        'DRV8873-Q1 (Texas Instruments) — automotive-grade integrated H-bridge solenoid driver with on-die ' +
        'current-limit, integrated freewheel diodes, programmable slew rate, and nFAULT open-drain diagnostic ' +
        'pin; nFAULT asserts within 100 µs of LOAD_SHORT_VM (the DRV8873\'s instantiation of the Gemini 8 ' +
        'failure mode)',
      eraOriginal:
        '2N1132 silicon-PNP common-emitter switching transistor (TI / Fairchild 1962-65) in TO-5 hermetic can + ' +
        '1N4148 silicon switching diode (freewheel) + 33 Ω collector resistor + 10 kΩ base resistor; hand-screened ' +
        'flight transistors with 1000-cycle 80%-rated-current pulse-test',
      activeComparator:
        'LM311 (Texas Instruments) with feedback-resistor hysteresis — Schmitt summing-junction; LM393 dual ' +
        'comparator for fault-detect on the primary driver\'s load-current sense',
      activeGyro:
        'MPU-6050 (TDK) 6-axis MEMS IMU with ±2000°/s yaw range — bench analog of the IBM/Honeywell rate-' +
        'integrating gyro; 3 orders of magnitude better noise floor and zero-bias drift',
      activeMicro:
        'STM32F407G-DISC1 — Cortex-M4F discovery kit running the 100 Hz attitude-loop + sign-flip detector + ' +
        'failover sequencer',
      stuckFractionThreshold:
        'Sign-inversion threshold sits at stuck-fraction = K_total_gated_max / K_OAMS; for the OAMS 4-thruster ' +
        'yaw architecture with 3 of 4 intact, threshold = 0.75. Below: negative feedback. Above: positive feedback.',
      sideBySidePattern:
        'Three-branch SPICE: NOMINAL (OAMS intact, negative feedback, rate damps) + STUCK-ON (Thruster 8 stuck, ' +
        'positive feedback, rate runs away) + RCS-FAILOVER (OAMS-OFF/RCS-ON at t = 4.0 s, sign restored, rate damps ' +
        'from peak) — all three render in a single .tran sweep so the failure-and-recovery primitive is directly ' +
        'observable',
    },
    references: [
      'Hacker, B. C., & Grimwood, J. M. (1977). On the Shoulders of Titans: A History of Project Gemini. NASA SP-4203 ch. 14',
      'NASA. (1966). Gemini 8 Mission Report. NASA TM-X-1184 (April 1966)',
      'Harrison, H. R. (1976). Computer Aided Design of Aerospace Systems. NASA TM-X-72814',
      'Armstrong, N. A. (2001). NASA Johnson Space Center Oral History Project Interview, 19 September 2001',
      'Franklin, Powell, Emami-Naeini (2019). Feedback Control of Dynamic Systems (8e). Pearson — ch. 5-6 + ch. 9',
      'Khalil, H. K. (2014). Nonlinear Systems (3e). Prentice Hall — §4.3-§4.4 + §10',
      'Hansen, J. R. (2005). First Man: The Life of Neil A. Armstrong. Simon & Schuster — ch. 14',
      'McDonnell Aircraft Corporation. (1965). Project Gemini Familiarization Manual, OAMS Subsystem (Volume IV). NASA SP-138 supplementary',
      'TI DRV8873-Q1 datasheet, https://www.ti.com/lit/ds/symlink/drv8873-q1.pdf',
    ],
    flightDate: '1966-03-16',
    crewCommanderRecovery: 'Armstrong (CDR) — manual OAMS-OFF / RCS-ON sequence; first US in-flight emergency abort of a crewed spacecraft',
    peakRunawayRate: '~296°/s yaw (joined Gemini 8 + Agena 8 stack); ~360°/s after undocking',
    timeToRunawaySaturation: '~13 seconds from disturbance to gyro-rail saturation',
    recoveryFlight: 'Gemini 9 onward (1966) — per-thruster fault-detect bus + automated cabin alarm + RCS-arm with proximity guard; OAMS architecture preserved',
  },
} as RosettaConcept;
