/**
 * Skill Materializer — Layer 3, Wave 3
 *
 * Generates executable SKILL.md files from validated recommendations.
 * Four skill categories: team compositions, decomposition rules,
 * routing policies, and safety gates. Every materialized skill includes
 * confidence score, evidence chain, and reasoning.
 */

import type {
  TeamScore,
  DecompositionTemplate,
  RoutingRule,
  GateSpec,
  Recommendation,
} from './types.js';

// ============================================================================
// SKILL.md Generation
// ============================================================================

/** Generated SKILL.md content with metadata */
export interface MaterializedSkill {
  skillName: string;
  category: 'team-composition' | 'task-decomposition' | 'routing-rule' | 'safety-gate';
  content: string;
  recommendation: Recommendation;
  filePath: string;
}

/**
 * Generate a SKILL.md file for a team composition recommendation.
 */
export function materializeTeamSkill(
  teamScore: TeamScore,
  confidence: number,
  evidence: string[],
): MaterializedSkill {
  const skillName = `team-${teamScore.teamId}`;
  const recommendation = createRecommendation(
    'team-composition',
    confidence,
    evidence,
    `Team ${teamScore.teamId} scores ${teamScore.overallScore.toFixed(2)} coverage ` +
    `with ${teamScore.gaps.length} gaps identified`,
    { teamScore },
  );

  const content = `---
name: ${skillName}
description: >
  Auto-generated team composition skill. Team ${teamScore.teamId} with
  ${teamScore.members.length} members and coverage score ${teamScore.coverageScore.toFixed(2)}.
  Generated by wasteland-integration skill materializer.
user-invocable: false
---

# Team Composition: ${teamScore.teamId}

## Members

${teamScore.members.map(m => `- ${m}`).join('\n')}

## Scores

| Metric | Score |
|--------|-------|
| Coverage | ${teamScore.coverageScore.toFixed(3)} |
| Gap Score | ${teamScore.gapScore.toFixed(3)} |
| Redundancy | ${teamScore.redundancyScore.toFixed(3)} |
| Overall | ${teamScore.overallScore.toFixed(3)} |
| Confidence | ${teamScore.confidence.toFixed(3)} |

## Gaps

${teamScore.gaps.length > 0 ? teamScore.gaps.map(g => `- ${g}`).join('\n') : 'No gaps detected.'}

## Evidence

${evidence.map(e => `- ${e}`).join('\n')}

## Confidence

Score: ${confidence.toFixed(3)}
`;

  return {
    skillName,
    category: 'team-composition',
    content,
    recommendation,
    filePath: `.claude/skills/${skillName}/SKILL.md`,
  };
}

/**
 * Generate a SKILL.md file for a decomposition template.
 */
export function materializeDecompositionSkill(
  template: DecompositionTemplate,
  confidence: number,
  evidence: string[],
): MaterializedSkill {
  const skillName = `decomp-${template.id}`;
  const recommendation = createRecommendation(
    'task-decomposition',
    confidence,
    evidence,
    `Decomposition template with ${template.phases.length} phases, ` +
    `${template.parallelizablePhases.length} parallel groups`,
    { template },
  );

  const phaseRows = template.phases.map((p, i) =>
    `| ${i + 1} | ${p.taskType} | ${p.recommendedArchetype} | ${(p.estimatedDurationMs / 60000).toFixed(1)}m |`
  ).join('\n');

  const content = `---
name: ${skillName}
description: >
  Auto-generated task decomposition skill from pattern ${template.sourcePatternId}.
  ${template.phases.length} phases with estimated duration
  ${(template.estimatedDurationMs / 60000).toFixed(0)} minutes.
  Generated by wasteland-integration skill materializer.
user-invocable: false
---

# Decomposition Template: ${template.id}

## Phases

| # | Task Type | Archetype | Duration |
|---|-----------|-----------|----------|
${phaseRows}

## Parallel Groups

${template.parallelizablePhases.length > 0
  ? template.parallelizablePhases.map((g, i) => `- Group ${i + 1}: ${g.join(', ')}`).join('\n')
  : 'No parallelizable phases identified.'}

## Evidence

${evidence.map(e => `- ${e}`).join('\n')}

## Confidence

Score: ${confidence.toFixed(3)}
`;

  return {
    skillName,
    category: 'task-decomposition',
    content,
    recommendation,
    filePath: `.claude/skills/${skillName}/SKILL.md`,
  };
}

/**
 * Generate a SKILL.md file for a routing rule.
 */
export function materializeRoutingSkill(
  rule: RoutingRule,
  confidence: number,
  evidence: string[],
): MaterializedSkill {
  const skillName = `route-${rule.id}`;
  const recommendation = createRecommendation(
    'routing-rule',
    confidence,
    evidence,
    `Route for ${rule.taskType}: ${rule.route.join(' -> ')} ` +
    `(success rate: ${(rule.successRateEstimate * 100).toFixed(1)}%)`,
    { rule },
  );

  const content = `---
name: ${skillName}
description: >
  Auto-generated routing rule for task type ${rule.taskType}.
  Route: ${rule.route.join(' -> ')}. Estimated success rate:
  ${(rule.successRateEstimate * 100).toFixed(1)}%.
  Generated by wasteland-integration skill materializer.
user-invocable: false
---

# Routing Rule: ${rule.id}

## Route

${rule.route.join(' -> ')}

## Metrics

| Metric | Value |
|--------|-------|
| Task Type | ${rule.taskType} |
| Latency Estimate | ${rule.latencyEstimateMs}ms |
| Success Rate | ${(rule.successRateEstimate * 100).toFixed(1)}% |
| Weight | ${rule.weight.toFixed(3)} |
| A/B Test Active | ${rule.abTestActive} |

## Evidence

${evidence.map(e => `- ${e}`).join('\n')}

## Confidence

Score: ${confidence.toFixed(3)}
`;

  return {
    skillName,
    category: 'routing-rule',
    content,
    recommendation,
    filePath: `.claude/skills/${skillName}/SKILL.md`,
  };
}

/**
 * Generate a SKILL.md file for a safety gate.
 */
export function materializeGateSkill(
  gate: GateSpec,
  confidence: number,
  evidence: string[],
): MaterializedSkill {
  const skillName = `gate-${gate.id}`;
  const recommendation = createRecommendation(
    'safety-gate',
    confidence,
    evidence,
    `${gate.type} gate: ${gate.name} (${gate.automationLevel})`,
    { gateId: gate.id, gateName: gate.name, type: gate.type },
  );

  const content = `---
name: ${skillName}
description: >
  Auto-generated safety gate: ${gate.name}.
  Type: ${gate.type}. Automation: ${gate.automationLevel}.
  Generated by wasteland-integration skill materializer.
user-invocable: false
---

# Safety Gate: ${gate.name}

## Configuration

| Property | Value |
|----------|-------|
| Type | ${gate.type} |
| Automation Level | ${gate.automationLevel} |
| Source Signatures | ${gate.sourceFailureSignatures.join(', ')} |
| TPR | ${gate.truePositiveRate.toFixed(3)} |
| FPR | ${gate.falsePositiveRate.toFixed(3)} |

## Evidence

${evidence.map(e => `- ${e}`).join('\n')}

## Confidence

Score: ${confidence.toFixed(3)}
`;

  return {
    skillName,
    category: 'safety-gate',
    content,
    recommendation,
    filePath: `.claude/skills/${skillName}/SKILL.md`,
  };
}

// ============================================================================
// Recommendation Creation
// ============================================================================

function createRecommendation(
  type: Recommendation['type'],
  confidence: number,
  evidenceChain: string[],
  reasoning: string,
  payload: Record<string, unknown>,
): Recommendation {
  return {
    id: `rec-${type}-${Date.now()}`,
    type,
    confidence,
    evidenceChain,
    reasoning,
    payload,
    createdAt: new Date().toISOString(),
  };
}

// ============================================================================
// Batch Materialization
// ============================================================================

/**
 * Materialize all pending recommendations into SKILL.md files.
 * Returns the generated skills for writing to disk.
 */
export function materializeAll(
  teams: TeamScore[],
  templates: DecompositionTemplate[],
  routes: RoutingRule[],
  gates: GateSpec[],
  confidenceThreshold: number = 0.7,
): MaterializedSkill[] {
  const skills: MaterializedSkill[] = [];

  for (const team of teams) {
    if (team.confidence >= confidenceThreshold) {
      skills.push(materializeTeamSkill(
        team,
        team.confidence,
        [`Team coverage: ${team.coverageScore.toFixed(2)}`, `Gaps: ${team.gaps.length}`],
      ));
    }
  }

  for (const tmpl of templates) {
    if (tmpl.confidence >= confidenceThreshold) {
      skills.push(materializeDecompositionSkill(
        tmpl,
        tmpl.confidence,
        [`Source pattern: ${tmpl.sourcePatternId}`, `Phases: ${tmpl.phases.length}`],
      ));
    }
  }

  for (const route of routes) {
    if (route.successRateEstimate >= confidenceThreshold) {
      skills.push(materializeRoutingSkill(
        route,
        route.successRateEstimate,
        [`Route: ${route.route.join(' -> ')}`, `Success: ${(route.successRateEstimate * 100).toFixed(1)}%`],
      ));
    }
  }

  for (const gate of gates) {
    skills.push(materializeGateSkill(
      gate,
      0.8, // Gates always start at baseline confidence
      [`Source: ${gate.sourceFailureSignatures.join(', ')}`, `Type: ${gate.type}`],
    ));
  }

  return skills;
}
