/**
 * Wing 2: Pythagorean Theorem — Understand Phase
 *
 * a^2 + b^2 = c^2. Distance formula. Generalization to n dimensions.
 */

import React, { useState } from 'react';

export interface UnderstandPhaseProps {
  onComplete: () => void;
}

export const UnderstandPhase: React.FC<UnderstandPhaseProps> = ({ onComplete }) => {
  const [acknowledged, setAcknowledged] = useState(false);

  return (
    <div className="phase understand-phase">
      <h2>Understanding the Relationship</h2>

      <p className="narrative-intro">
        You have seen the squares grow and shrink as the sides change. You have felt
        the invariant — no matter what values you choose, the relationship holds. Now
        we write it down.
      </p>

      <div className="formal-definitions" style={{ fontFamily: 'monospace', lineHeight: 2 }}>
        <h3>The Pythagorean Theorem</h3>

        <p>
          For any right triangle with legs a and b and hypotenuse c:
        </p>

        <div className="math-block" style={{ padding: '16px', background: '#0a0a2a', borderRadius: '8px', margin: '12px 0' }}>
          <div style={{ fontSize: '1.3em', textAlign: 'center' }}>
            a² + b² = c²
          </div>
        </div>

        <p>
          This is not just a formula — it is a statement about the structure of flat space.
          It says that distance is not additive (you cannot just add the sides to get the
          diagonal). Distance requires squaring, summing, and then taking the root. Space
          has a geometry, and this theorem encodes it.
        </p>

        <h3>The Distance Formula</h3>

        <p>
          Between any two points (x1, y1) and (x2, y2) in the plane:
        </p>

        <div className="math-block" style={{ padding: '16px', background: '#0a0a2a', borderRadius: '8px', margin: '12px 0' }}>
          <div style={{ textAlign: 'center' }}>
            d = sqrt((x2 - x1)² + (y2 - y1)²)
          </div>
        </div>

        <p>
          This is the Pythagorean theorem in disguise. The horizontal distance is one leg,
          the vertical distance is the other, and the distance d is the hypotenuse.
        </p>

        <h3>Generalization to n Dimensions</h3>

        <p>
          The theorem extends to any number of dimensions. In 3D:
        </p>

        <div className="math-block" style={{ padding: '16px', background: '#0a0a2a', borderRadius: '8px', margin: '12px 0' }}>
          <div>d = sqrt(dx² + dy² + dz²)</div>
        </div>

        <p>In n dimensions:</p>

        <div className="math-block" style={{ padding: '16px', background: '#0a0a2a', borderRadius: '8px', margin: '12px 0' }}>
          <div>d = sqrt(x1² + x2² + ... + xn²)</div>
        </div>

        <p>
          This is how your phone computes distances in high-dimensional feature spaces.
          The same relationship that connects two sides of a right triangle connects
          hundreds of dimensions in machine learning.
        </p>

        <h3>Pythagorean Triples</h3>

        <p>
          Some right triangles have integer sides. These are called Pythagorean triples:
        </p>

        <div className="math-block" style={{ padding: '16px', background: '#0a0a2a', borderRadius: '8px', margin: '12px 0' }}>
          <div>(3, 4, 5): 9 + 16 = 25</div>
          <div>(5, 12, 13): 25 + 144 = 169</div>
          <div>(8, 15, 17): 64 + 225 = 289</div>
          <div>(7, 24, 25): 49 + 576 = 625</div>
        </div>

        <p>
          There are infinitely many. They are generated by the formula:
          a = m² - n², b = 2mn, c = m² + n² for any integers m &gt; n &gt; 0.
        </p>
      </div>

      <div className="completion-check" style={{ margin: '20px 0' }}>
        <label style={{ cursor: 'pointer' }}>
          <input
            type="checkbox"
            checked={acknowledged}
            onChange={() => setAcknowledged((v) => !v)}
            style={{ marginRight: 8 }}
          />
          I understand: the Pythagorean theorem is how flat space measures distance
        </label>
      </div>

      <button className="phase-advance" disabled={!acknowledged} onClick={onComplete}>
        Continue
      </button>
    </div>
  );
};

export const understandMeta = {
  containsMath: true,
  interactiveElements: 0,
  formalConcepts: ['pythagorean-theorem', 'distance-formula', 'n-dimensions', 'triples'],
};
