import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.41 — Alkaline-fuel-cell polarisation curve and bus-regulator
 * dropout margin under cabin-environment-coupled heater overdraw:
 * the Gemini 5 GE IT-32 hydrogen-oxygen stack and the Day-1
 * reactant-supply heater excursion.
 *
 * Generated by the v1.49.581 ELC Wave-6 backfill (slot E6-B).
 * Cross-references: NASA 1.41 (Gemini 5, Cooper/Conrad 1965-08-21),
 * MUS 1.41 (when authored — series-stack voicing structure).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md
 */
export const alkalineFuelCellPolarisationCurve: RosettaConcept = {
  id: 'elc-1.41-alkaline-fuel-cell-polarisation-curve',
  name: 'Three-region V-I polarisation curve (activation / ohmic / mass-transport) of an alkaline H2-O2 fuel-cell stack composed with the linear bus-regulator dropout margin',
  domain: 'electronics',
  description:
    'A power-electronics primitive describing how a hydrogen-oxygen alkaline ' +
    'fuel-cell stack (32 series cells of GE IT-32 chemistry; 1.05 V/cell ' +
    'open-circuit; 30% KOH electrolyte in porous matrix; nickel anode + sintered ' +
    'nickel-oxide cathode; 200 °C / 4 atm operating envelope) drives a regulated ' +
    'spacecraft bus through a 2N1490-class linear series-pass regulator with ' +
    '0.6 V dropout margin. The stack terminal voltage V_FC = N × [E_OC − ' +
    'A·ln(I/I_0) − I·R_INT − B·ln(1 − I/I_LIMIT)] follows three distinct regions ' +
    'as I_FC rises from zero: activation polarisation (Tafel slope, slow ' +
    'electrochemical kinetics near zero current); ohmic loss (linear in current, ' +
    'dominated by electrolyte resistance); and mass-transport limit (sharp curve ' +
    'as reactant diffusion fails to keep up with current draw near I_LIMIT). The ' +
    'bus-regulator dropout-margin equation V_BUS = min(V_REG, V_FC − V_DROPOUT) ' +
    'is the second half of the primitive: regulation holds only while V_FC ' +
    'exceeds V_REG by at least V_DROPOUT volts. The Gemini 5 Day-1 anomaly ' +
    '(GET 04:30, 1965-08-21) demonstrated the failure mode of this composition: ' +
    'a chafed wire in the reactant-supply heater string presented a partial short ' +
    'to the oxygen-tank wall, dropping effective heater resistance from 4 Ω to ' +
    '~0.4 Ω, driving I_FC from 7 A nominal to ~50-60 A peak, dragging V_FC down ' +
    'the polarisation curve into the mass-transport region, sagging V_BUS below ' +
    'regulation, vapourising oxygen reactant out of the pressure-relief valve, ' +
    'and forcing Cooper and Conrad to cut the 14-day endurance flight to 8 days. ' +
    'The IT-32 was the first US flight of a fuel cell on a crewed mission and ' +
    'the qualifying flight for the Apollo lunar-mission power architecture.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-fuel-cell-electrochemistry',
      description:
        'The polarisation-curve operating point depends on the cell electrochemistry ' +
        '(Bagotsky 2012 ch. 17): activation overpotential (Tafel slope A), ohmic ' +
        'loss (electrolyte resistance R_INT), and mass-transport limit (reactant ' +
        'diffusion-limited I_LIMIT) jointly set V_FC versus I_FC',
    },
    {
      type: 'dependency',
      targetId: 'elec-linear-regulator-dropout',
      description:
        'Bus regulation depends on the series-pass dropout margin V_DROPOUT; the ' +
        'regulator can clamp V_BUS to its setpoint only while V_FC exceeds V_REG ' +
        'by at least V_DROPOUT volts. Below this margin the regulator enters its ' +
        'linear region and V_BUS becomes a linear function of V_FC',
    },
    {
      type: 'dependency',
      targetId: 'elec-cabin-environment-coupling',
      description:
        'The Day-1 fault propagation depends on cabin-environment coupling: a ' +
        'wire chafe in the heater string that crossed into the oxygen-tank wall ' +
        'presented a parallel current path that multiplied effective heater ' +
        'current and drove V_FC into the mass-transport region. The coupling ' +
        'path is non-electrical (thermal-mechanical) but its electrical ' +
        'consequence is bus collapse',
    },
    {
      type: 'predecessor',
      targetId: 'elc-1.37-squarewave-inverter-vacuum-tube',
      description:
        'The prior Domain-6 entry treated the saturating-core-flux-balance ' +
        'self-oscillating inverter primitive driving vacuum-tube heater rails ' +
        '(Ranger 8 vidicon power chain). ELC 1.41 treats the electrochemical-cell ' +
        'V-I polarisation primitive composed with linear-regulator dropout margin ' +
        'driving a regulated spacecraft bus (Gemini 5 fuel-cell power section). ' +
        'Together they expand the Domain-6 power-source taxonomy from the four ' +
        'prior entries (1.3 photovoltaic, 1.20 primary battery, 1.21 PV+shunt-reg, ' +
        '1.37 saturating-core inverter) to include electrochemical fuel-cell with ' +
        'regulated bus, completing the canonical 1960s flight-power primitives',
    },
    {
      type: 'predecessor',
      targetId: 'elc-1.31-sar-adc-vref-brownout',
      description:
        'The cross-domain predecessor at ELC 1.31 (Ranger 5 SAR-ADC + V_REF ' +
        'brownout, Domain 8 Data conversion) demonstrated the same "corner-clamp" ' +
        'structural primitive: a system that is well-behaved while a regulated ' +
        'rail stays above a corner threshold becomes catastrophic out of regulation. ' +
        'ELC 1.31 V_REF coupling to V_BUS and ELC 1.41 V_FC vs V_REG dropout are ' +
        'the same shape — divider/regulator output bounded only while source ' +
        'stays above corner — applied to different domains. Cross-domain primitive ' +
        'taxonomy class: corner-clamp',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.41-stack-voicing-degradation',
      description:
        'The 32 series cells of the IT-32 stack with each contributing a fraction ' +
        'of the open-circuit voltage is the structural rhyme of any musical structure ' +
        'where multiple voices sum to a composite chord and the degradation of any ' +
        'single voice sags the whole sonority — both are series-summation structures ' +
        'whose continuity depends on every contributing voice/cell remaining within ' +
        'its operating envelope. The dropout-margin corner is the cliff at which ' +
        'the bus-regulator can no longer hide the degraded source from the load',
    },
  ],
  metadata: {
    elcDegree: '1.41',
    domain: 6,
    domainName: 'Power electronics',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'GE Apollo Support Department (Lynn MA) IT-32 hydrogen-oxygen alkaline ' +
      'fuel-cell stack (two parallel sections of 32 series cells each; ~1 kW ' +
      'nominal at +25 V regulated bus; KOH 30% electrolyte in porous matrix; ' +
      'nickel anode + sintered nickel-oxide cathode; 200 °C / 4 atm reactant ' +
      'supply); Westinghouse 2N1490-class silicon NPN series-pass dissipator ' +
      '(TO-3 metal can) bus-regulator with 0.6 V dropout margin; reactant-supply ' +
      'hydrogen / oxygen pressure-vessel heater strings (~175 W nominal at +25 V); ' +
      'Sprague-Mallory 22 µF / 50 V hermetic tantalum bulk decoupling on bus rail',
    keyEquation:
      'V_FC(I_FC) = N × [ E_OC − A·ln(I_FC/I_0) − I_FC·R_INT − B·ln(1 − I_FC/I_LIMIT) ] ' +
      '(three-region polarisation per cell, summed over N = 32 cells in series); ' +
      'V_BUS = min( V_REG_setpoint, V_FC − V_DROPOUT ) (bus-regulator dropout corner); ' +
      'I_FC = I_AVIONICS + I_HEATER + I_TELEMETRY (total stack current = sum of bus loads); ' +
      'Gemini 5 design point V_FC = +27 V at I_FC = 7 A (V_cell = 0.84 V, ohmic region); ' +
      'Day-1 fault drove I_FC to ~60 A peak, dragging V_FC into mass-transport region',
    benchReplication: {
      activeStack:
        'Horizon H-1000 1 kW PEM fuel-cell stack — 32 cells, ~30 V V_OC, ' +
        '60 °C operating temperature, atmospheric Nafion polymer electrolyte ' +
        '(curve-faithful but not chemistry-faithful substitute for hot-KOH ' +
        'alkaline; safe atmospheric conditions for educational reproduction)',
      eraOriginal:
        'GE IT-32 alkaline H2-O2 stack (no commercial datasheet; flight-program ' +
        'specification archived in NASA SP-138 / NASA NTRS Gemini Summary ' +
        'Conference proceedings)',
      regulatorSubstitute:
        'Linear Technology LT3081 1.5 A LDO with monitoring (Path A; modern ' +
        'integrated thermal-shutdown + current-limit) OR 2N3055 + 1N753A 6.2 V ' +
        'Zener + matched 2N2222 long-tailed pair (Path B; era-faithful discrete ' +
        'series-pass topology with the 1960s 0.6 V dropout-margin signature)',
      heaterSubstitute:
        'Vishay LVR05R-200-4R0 4 Ω 5 W wirewound (nominal heater) + IRLZ44N-gated ' +
        'parallel-switchable LVR05R-200-0R5 0.5 Ω (fault-condition heater) — ' +
        'simulates the Day-1 chafe-induced effective-resistance drop from 4 Ω ' +
        'to 0.4 Ω at command from RP2040 GPIO',
      operatingPoint:
        'Design point V_BUS = +25.0 V regulated at I_BUS_TOTAL = 6.75 A ' +
        '(0.5 A avionics + 6.25 A heater); dropout corner V_FC ≥ V_BUS + V_DROPOUT ' +
        '= 25 + 0.6 = +25.6 V (Path B) or +26.2 V (Path A LT3081)',
    },
    references: [
      'Bagotsky, V. S. (2012). Fundamentals of Electrochemistry (2e, Wiley). Ch. 17',
      "O'Hayre, R., Cha, S.-W., Colella, W., & Prinz, F. B. (2016). Fuel Cell Fundamentals (3e, Wiley). Ch. 3-6",
      'Larminie, J., & Dicks, A. (2003). Fuel Cell Systems Explained (2e, Wiley). Ch. 3',
      'Hacker, B. C., & Grimwood, J. M. (1977). On the Shoulders of Titans: A History of Project Gemini. NASA SP-4203, ch. 12. https://history.nasa.gov/SP-4203/ch12-7.htm',
      'NASA SP-138 (1967). Gemini Summary Conference. Section on fuel-cell power source.',
      'Cohn, E. M. (1965). The first two years of fuel cell flight: Gemini and Apollo. Eighth IECEC Proceedings, IEEE: 451-462',
      'Warshay, M., & Prokopius, P. R. (1989). The fuel cell in space: yesterday, today, and tomorrow. Journal of Power Sources 29(1-2): 193-200',
      'Pressman, A. I. (1991). Switching Power Supply Design (2e, McGraw-Hill). Ch. 1 — linear pass-regulators and dropout-margin',
      'Berry, C. A. (1966). Medical aspects of Gemini 5 and 6 flights. Aerospace Medicine 37: 851-858',
      'Black, J. R. (1969). Electromigration: a brief survey and some recent results. IEEE Trans. Electron Devices 16(4): 338-347',
      'Linear Technology / Analog Devices LT3081 datasheet, https://www.analog.com/media/en/technical-documentation/data-sheets/LT3081.pdf',
      'Horizon H-1000 PEM fuel-cell stack datasheet, https://www.fuelcellstore.com/horizon-1000w-fuel-cell-stack-h-1000',
    ],
  },
  complexPlanePosition: {
    real: 0.41,
    imaginary: 0.6,
    magnitude: Math.sqrt(0.41 ** 2 + 0.6 ** 2),
    angle: Math.atan2(0.6, 0.41),
  },
};
