import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.3 — Selenium-cell beacon power and the minimum-energy radio carrier:
 * six photovoltaic cells, a 10 mW 108.03 MHz transmitter, and the orbital
 * persistence of the first solar-powered satellite (Vanguard 1, 1958-03-17).
 *
 * Generated by the v1.49.581 ELC Wave-3 backfill (slot E3-A).
 * Cross-references: NASA 1.3 (Vanguard 1, Vanguard TV-4 1958-03-17),
 * MUS 1.3 (when authored — minimum-energy carrier persistence structural rhyme).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md
 */
export const seleniumBeaconLowPowerRadio: RosettaConcept = {
  id: 'elc-1.3-selenium-beacon-low-power-radio',
  name: 'Minimum-energy radio carrier driven by an energy-harvesting photovoltaic bus',
  domain: 'electronics',
  description:
    'A power-electronics primitive describing how a low-current photovoltaic ' +
    'cell stack (Norton-source with V_OC asymptote, e.g. six Bell Labs / Western ' +
    'Electric 1955-vintage selenium PV cells delivering 100 µA at 0.30 V V_OC ' +
    'under AM0 1 AU full sun) drives a milliwatt-class radio-frequency beacon ' +
    'oscillator through a long-time-constant energy-harvesting bus capacitor ' +
    '(22 µF tantalum reservoir) with a redundant blocking-diode bridge ' +
    '(three-of-six 1N34A germanium point-contact rectifiers) preventing ' +
    'reverse-discharge during eclipse. The architecture is bistable: the ' +
    'oscillator either runs at its operating-point current draw (~50 µA) or ' +
    'is silent at zero draw, with a sharp transition at V_BE_min ≈ 0.05 V. ' +
    'The eclipse-survival horizon equation T_eclipse_max = R_LOAD × C_BUS × ' +
    'ln(V_OC / V_BE_min) gives the time-to-silent during full eclipse, but ' +
    'the architecture\'s persistence comes from the *silent* regime: once ' +
    'the bus drops below V_BE_min the oscillator stops drawing current, so ' +
    'the bus holds passively at the threshold indefinitely waiting for the ' +
    'next sun acquisition. The Vanguard 1 (1958-03-17 launch, 654 km × 3969 ' +
    'km × 132° elliptical orbit) Minitrack-B beacon transmitted continuously ' +
    'for 6.5 years on six selenium cells; the spacecraft itself remains in ' +
    'orbit and is the oldest human-made object still circling the Earth, ' +
    'with current orbital-decay forecast past calendar year 2245. Hans ' +
    'Ziegler\'s 1956 design-review argument that minimum-energy radio ' +
    'carriers are the right load to pair with a photovoltaic supply is the ' +
    'architectural template every solar-powered satellite that followed ' +
    'has descended from.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-solar-cell-iv-curve',
      description:
        'Bus-voltage operating point depends on the cell I-V characteristic at low ' +
        'illumination; the constant-current regime up to ~90% of V_OC and the ' +
        'V_OC asymptote above that determine the bus reservoir charging rate',
    },
    {
      type: 'dependency',
      targetId: 'elec-redundant-blocking-diode-bridge',
      description:
        'Eclipse-survival depends on the redundant blocking-diode bridge preventing ' +
        'reverse-discharge through the cells; three-of-six redundancy gives multi-year ' +
        'reliability against single-diode leakage growth',
    },
    {
      type: 'dependency',
      targetId: 'elec-bistable-oscillator-load',
      description:
        'Persistence depends on the oscillator behaving as a bistable load: ~50 µA ' +
        'when running, ~0 µA when silent, with sharp transition at V_BE_min. The ' +
        'silent regime is stable (no further bus drain), giving the architecture ' +
        'its multi-year operational history',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.3-minimum-energy-carrier-persistence',
      description:
        'The minimum-energy radio carrier surviving eclipse silence by holding its ' +
        'bus voltage passively at V_BE_min is the structural rhyme of a melodic phrase ' +
        'surviving the rest between cadences by holding its voicing passively in the ' +
        'listener\'s pattern memory; both are minimum-energy carrier structures whose ' +
        'persistence depends on a low-loss reservoir and a self-restart threshold',
    },
  ],
  metadata: {
    elcDegree: '1.3',
    domain: 6,
    domainName: 'Power electronics',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'Vanguard 1 (1958-03-17 Vanguard TV-4 launch) Minitrack-B beacon power chain — six Bell Labs / Western Electric 1955-vintage selenium photovoltaic cells (~50 µA I_SC at AM0 1 AU per cell, 0.10 V V_OC) wired three series-parallel pairs in a 60° equatorial belt around the 16.5 cm aluminum sphere; three-of-six redundant 1N34A germanium point-contact rectifier blocking bridge; 22 µF tantalum bus reservoir capacitor (6 V derated to 0.30 V working voltage); 2N1308-class germanium NPN Hartley oscillator at 108.03 MHz radiating ~10 mW through a quadrant slot antenna; transmitted continuously 1958-03-17 through May 1964 (6.5 years)',
    keyEquation: 'V_OC = cell-stack open-circuit voltage at full illumination = ~0.30 V for six selenium cells in three series-parallel pairs; V_BE_min = oscillator self-start threshold = ~0.05 V for germanium NPN (~0.7 V for silicon NPN); R_LOAD × C_BUS = bus discharge time constant = 30 kΩ × 22 µF = 0.66 s for Vanguard 1; eclipse-survival horizon T_eclipse_max = R_LOAD × C_BUS × ln(V_OC / V_BE_min) = 0.66 s × ln(6) = 1.18 s during running-oscillator regime; bus holds passively at V_BE_min indefinitely once oscillator goes silent (silent-regime stability is the architectural-persistence property); restart-after-eclipse condition I_PV_min × R_LOAD > V_BE_min',
    benchReplication: {
      activePaddle: 'Six 2 V 50 mA monocrystalline-Si hobby PV cells (educational substitute for Bell Labs / Western Electric 1955-vintage selenium cells)',
      eraOriginal: 'Western Electric / Bell Telephone Laboratories 1955-vintage selenium photovoltaic cell — 0.10 V V_OC, 50 µA I_SC, ~0.5% conversion efficiency at AM0 1 AU 30 °C; six cells in three series-parallel pairs gave Vanguard 1 a 100 µA / 0.30 V Norton-source bus characteristic',
      modernEquivalent: 'Spectrolab XTJ Prime triple-junction GaAs/Ge solar cell — 30.7% AM0 efficiency, 2.7 V V_OC per cell, 17.5 mA/cm² J_SC; the lineal industrial successor to the Hoffman/Bell-Labs heritage',
      blockingBridge: '1N34A germanium point-contact rectifier (still in production via NTE, Vishay, Sylvania); three-of-six redundancy. Modern bench substitute: 1N5817 silicon Schottky with ~10× lower forward drop and ~100× lower reverse leakage',
      reservoir: '22 µF / 6.3 V solid tantalum (Vishay 74-T354K226K006AS — modern part essentially identical in chemistry to era-original)',
      oscillatorTransistor: '2N1308 germanium NPN (era-original via surplus market); AC127 germanium NPN (modern-stocked NTE100 substitute); 2N3904 silicon NPN (substitute that requires V_OC stack to be sized for ~1.0 V instead of 0.30 V due to higher V_BE)',
      operatingPoint: 'Bus voltage 0.30 V at full sun (era-original cells) or 0.6 V at full sun (silicon-cell substitute); bistable oscillator load ~50 µA running / ~0 µA silent; eclipse-survival horizon ~1.18 s in running regime; silent-regime persistence indefinite',
    },
    references: [
      'Chapin, Fuller, Pearson 1954 — A New Silicon p-n Junction Photocell, J. Appl. Phys. 25(5)',
      'Hagen 1958 — The Viking and the Vanguard, American Scientist 46(2)',
      'Loferski 1956 — Theoretical considerations governing the choice of the optimum semiconductor for photovoltaic solar energy conversion, J. Appl. Phys. 27(7)',
      'Smits 1976 — History of silicon solar cells, IEEE Trans. Electron Devices 23(7)',
      'Rauschenbach 1980 — Solar Cell Array Design Handbook (Van Nostrand)',
      'Smith & Sanders 1994 — Spacecraft Power Systems (Wiley)',
      'Ziegler 1958 — Solar-cell power supply for Vanguard I, IRE Trans. Mil. Electron. MIL-2(1)',
    ],
  },
  complexPlanePosition: {
    real: 0.13,
    imaginary: 0.55,
    magnitude: Math.sqrt(0.13 ** 2 + 0.55 ** 2),
    angle: Math.atan2(0.55, 0.13),
  },
};
