import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.21 — Solar-cell power chain and shunt-regulator design under
 * attitude-coupled illumination dropout: the Ranger Block I primary
 * power architecture and the Sun-line-of-sight load-following operating point.
 *
 * Generated by the v1.49.581 ELC Wave-2 backfill (slot E2-D).
 * Cross-references: NASA 1.21 (Ranger 1, Atlas-Agena B 1961-08-23),
 * MUS 1.21 (when authored — load-following operating-point musical structure).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const solarCellShuntRegulator: RosettaConcept = {
  id: 'elc-1.21-solar-cell-shunt-regulator',
  name: 'Solar-paddle power-chain operating point under three-regime regulation',
  domain: 'electronics',
  description:
    'A power-electronics primitive describing how a solar paddle (Norton-source ' +
    'with V_OC asymptote, e.g. Hoffman 1S401D 8896-cell Block I paddle delivering ' +
    '4.5 A I_SC at 27 V V_OC under AM0 1 AU illumination) drives a regulated ' +
    'spacecraft bus through a linear shunt regulator (Zener-referenced 22.0 V + ' +
    'germanium-NPN dissipator) with a silver-zinc battery acting as load-following ' +
    'buffer. The bus operates in three regimes that hand off automatically as ' +
    'illumination varies: Regime A (paddle excess, shunt sinks I_PADDLE − I_LOAD), ' +
    'Regime B (paddle deficit, battery sources I_LOAD − I_PADDLE), Regime C ' +
    '(eclipse, battery sources I_LOAD entirely). The transition between Regime A ' +
    'and Regime B happens at the load-following crossover I_PADDLE = P_LOAD / V_REG. ' +
    'For Ranger Block I the numbers were V_REG = 22 V, P_LOAD = 132 W, giving a ' +
    '6 A crossover — and the AM0 nominal paddle output of 4.5 A sat just below ' +
    'crossover, leaving the battery to contribute 1.5 A during normal operations ' +
    'and the shunt regulator to absorb over-margin excursions only at peak ' +
    'illumination. The Ranger 1 shake-down flight (1961-08-23, Atlas-Agena B failure) ' +
    'validated the architecture in low Earth orbit despite never reaching its ' +
    'lunar-injection trajectory; every subsequent Ranger Block I and early Block II ' +
    'spacecraft inherited this exact regulator topology.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-solar-cell-iv-curve',
      description:
        'Solar-paddle Norton-source operating point depends on the cell I-V characteristic ' +
        '(constant-current regime up to ~90% of V_OC, V_OC asymptote above); paddle ' +
        'sizing budget pins the maximum-power-point at the regulated bus voltage',
    },
    {
      type: 'dependency',
      targetId: 'elec-shunt-regulator-topology',
      description:
        'Bus-voltage clamp depends on the shunt-regulator topology; shunt-vs-series ' +
        'choice is dominated by the failure-mode argument (shunt fails open → bus ' +
        'rises to V_OC, recoverable; series fails open → catastrophic bus loss)',
    },
    {
      type: 'dependency',
      targetId: 'elec-battery-load-following',
      description:
        'Three-regime hand-off depends on the battery acting as load-following buffer; ' +
        'cell-stack ESR sets the bus-voltage drop in Regime B (battery-buffered)',
    },
    {
      type: 'predecessor',
      targetId: 'elc-1.20-pyro-firing-battery-power',
      description:
        'The prior Domain-6 entry treated the pulse-load primitive (single multi-amp ' +
        'pulse through battery-bus impedance into a pyrotechnic bridgewire). ELC 1.21 ' +
        'treats the steady-state continuous-load primitive (solar-paddle power source ' +
        'feeding continuous avionics through a shunt regulator with battery buffering). ' +
        'The two together define the steady-state and pulse-load corners of Domain-6',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.21-load-following-crossover',
      description:
        'The load-following crossover between paddle-led (Regime A) and battery-led ' +
        '(Regime B) bus regulation is the structural rhyme of any musical structure ' +
        'where the operating point shifts continuously between two voicings as the ' +
        'harmonic context evolves — e.g. melody/bass crossover in contrapuntal duet, ' +
        'where one voice carries the line until the other takes over at the cadence; ' +
        'both are three-regime structures whose continuity depends on smooth transitions',
    },
  ],
  metadata: {
    elcDegree: '1.21',
    domain: 6,
    domainName: 'Power electronics',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'Ranger Block I two-paddle solar array (8896 Hoffman 1S401D cells, 14 sq ft total, 135 W at 1 AU AM0 30 °C); central spacecraft 22.0 V bus regulated by linear shunt-mode regulator (1N3036A Zener + 2N1490 germanium NPN dissipator); 14-cell Yardney HR-7 silver-zinc secondary battery as load-following buffer',
    keyEquation: 'I_PADDLE = paddle Norton current under illumination; I_LOAD = P_LOAD / V_REG = load demand at regulated bus voltage; load-following crossover I_PADDLE_crossover = I_LOAD; Regime A: I_PADDLE > I_LOAD, V_BUS = V_REG (shunt-clamped), I_SHUNT = I_PADDLE − I_LOAD; Regime B: I_PADDLE < I_LOAD, V_BUS = V_BAT − I_BAT × R_BAT, I_BAT = I_LOAD − I_PADDLE; Regime C (eclipse): I_PADDLE = 0, V_BUS = V_BAT − I_LOAD × R_BAT',
    benchReplication: {
      activePaddle: 'Voltaic V44 5 W amorphous-silicon flexible panel — 8 V V_OC, 0.6 A I_SC at 1 sun (educational substitute for Hoffman 1S401D Block I paddle pair, scaled by ~7×)',
      eraOriginal: 'Hoffman Electronics 1S401D p-on-n silicon solar cell — 0.55 V V_OC, 28 mA/cm² I_SC at AM0 1 AU 30 °C; 8896-cell Block I paddle pair gives 4.5 A I_SC, 27 V V_OC, 135 W',
      regulatorSubstitute: 'Linear Technology LT3652 single-chip solar charger with built-in MPPT logic (chip-scale modern equivalent); OR 2N3055 silicon NPN + 1N4742A 12 V Zener for direct linear-shunt-topology reproduction',
      batterySubstitute: '14-cell Panasonic Eneloop NiMH AA stack (16.8 V plateau, 50 mΩ ESR) OR 12 V 1.5 Ah Power-Sonic SLA (educational substitute for Yardney HR-7 silver-zinc 22 V secondary stack)',
      operatingPoint: 'Load-following crossover at I_PADDLE = P_LOAD / V_REG; for Block I: 6 A crossover at 22 V bus and 132 W load; for bench: ~0.6 A crossover at 16.8 V NiMH bus and 10 W load',
    },
    references: [
      'Rauschenbach, Solar Cell Array Design Handbook (Van Nostrand 1980), ch. 2 + ch. 5 — solar I-V curve, paddle sizing, shunt-vs-series tradeoffs',
      'Smith & Sanders, Spacecraft Power Systems (Wiley 1994), ch. 3 — primary battery and solar-paddle architecture',
      'Tirrell, NASA SP-4210 Lunar Impact (1977), §4 — Ranger Block I program history and power-system retrospective',
      'Linden & Reddy, Handbook of Batteries (4e, McGraw-Hill 2010), ch. 33 — silver-zinc primary and secondary cells',
      'Hoffman Electronics 1S401D datasheet (1961, El Monte CA), https://www.computerhistory.org/collections/catalog/102652259',
      'Linear Technology LT3652 datasheet, https://www.analog.com/media/en/technical-documentation/data-sheets/3652fe.pdf',
    ],
  },
  complexPlanePosition: {
    real: 0.21,
    imaginary: 0.62,
    magnitude: Math.sqrt(0.21 ** 2 + 0.62 ** 2),
    angle: Math.atan2(0.62, 0.21),
  },
};
