import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.37 — Squarewave DC-AC inverter for vacuum-tube heater power:
 * BJT push-pull topology, transformer leakage-inductance ringing,
 * and the Ranger 8 vidicon power chain.
 *
 * Generated by the v1.49.581 ELC Wave-4 backfill (slot E4-H).
 * Cross-references: NASA 1.37 (Ranger 8 / Mare Tranquillitatis),
 * MUS 1.37 (when authored — self-oscillating positive-feedback structure).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md
 */
export const squarewaveInverterVacuumTube: RosettaConcept = {
  id: 'elc-1.37-squarewave-inverter-vacuum-tube',
  name: 'Saturating-core flux-balance equation that sets the oscillation frequency of a Royer-class self-oscillating push-pull inverter',
  domain: 'electronics',
  description:
    'A power-electronics primitive describing how a primary-cell battery bus (Ag-Zn chemistry, ' +
    '24 V at 0.04 Ω stack ESR for the Yardney HR-22-2 16-cell auxiliary battery) drives a ' +
    'self-oscillating push-pull squarewave inverter through a saturating-core toroidal ' +
    'transformer to generate AC heater rails for vacuum-tube loads. The oscillation frequency ' +
    'is set by Faraday core-flux balance: V_PRIMARY × t_HALF = N × A_E × ΔB_SAT, where t_HALF ' +
    'is the half-period, N is primary turns, A_E is core effective cross-section, and ΔB_SAT ' +
    'is the saturation flux density swing. The leakage-inductance ringing on switch transitions ' +
    'sets the EMI signature: f_RING = 1/(2π × √(L_LEAK × C_PARASITIC)), typically 3-5 MHz for ' +
    'a Block III aerospace-grade build. The canonical flight exemplar is the Ranger 8 (1965-02-20) ' +
    'auxiliary-battery / vidicon-heater power chain, where a 24 V Yardney HR-22-2 stack drove a ' +
    'matched-pair 2N1100-class germanium NPN push-pull inverter at 400 Hz to deliver 6.3 V_RMS ' +
    'heater power to six RCA Block III vidicon-camera tubes through the 23-minute terminal ' +
    'descent that surveyed Mare Tranquillitatis for Apollo 11.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-saturating-core-magnetics',
      description:
        'Royer-class push-pull inverter depends on saturating-core magnetics; the core saturation ' +
        'is what gates each switch off and gives the inverter its self-oscillation property',
    },
    {
      type: 'dependency',
      targetId: 'elec-cross-coupled-positive-feedback',
      description:
        'Self-oscillation depends on a cross-coupled positive-feedback path between the two ' +
        'switch bases through the opposite primary half; remove either path and the topology dies',
    },
    {
      type: 'dependency',
      targetId: 'elec-emi-shielding-leakage-ringing',
      description:
        'Leakage-inductance ringing at switch transitions sets the EMI band that the spacecraft-' +
        'level shield must contain; without shielding the 5 MHz ringing radiates into the ' +
        'magnetometer and corrupts science telemetry',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.37-self-oscillating-positive-feedback',
      description:
        'The Royer self-oscillating cross-coupled feedback is the structural rhyme of any musical ' +
        'self-sustaining tension-and-resolution pattern that generates its own pulse from internal ' +
        'reinforcement rather than from an external clock — both are saturating-element structures ' +
        'whose frequency is set by an internal balance equation',
    },
  ],
  metadata: {
    elcDegree: '1.37',
    domain: 6,
    domainName: 'Power electronics',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware: 'Ranger Block III RA-7 / RA-8 vidicon-camera auxiliary power chain — Yardney HR-22-2 silver-zinc 16-cell auxiliary battery + Royer-class push-pull squarewave inverter (matched-pair 2N1100-class germanium NPN switches + bifilar-primary saturating-core ferrite toroid) generating 6.3 V_RMS / 400 Hz heater power and 250 V_RMS plate-supply for six RCA Block III 1-inch vidicon-camera tubes',
    keyEquation: 'V_PRIMARY × t_HALF = N × A_E × ΔB_SAT (Faraday flux balance setting f_OSC) ; f_RING = 1/(2π × √(L_LEAK × C_PARASITIC)) (leakage-inductance ringing) ; flyback peak ≈ 2 × V_BAT (must remain below V_CEO of switching transistors)',
    benchReplication: {
      activeBattery: '16-cell Panasonic Eneloop NiMH AA stack — 19.2 V plateau, 50 mΩ stack ESR (educational substitute for Yardney HR-22-2 Ag-Zn 16-cell stack)',
      eraOriginal: 'Yardney HR-22-2 Ag-Zn 16-cell stack — 24 V plateau, 40 mΩ stack ESR (1962-1965 JPL Block III flight build)',
      switchPair: 'ON-Semi 2N3055 silicon NPN power BJT (modern silicon equivalent for the 2N1100-class germanium era part); match V_BE within 5 mV at 100 mA for clean push-pull symmetry',
      transformer: 'Custom-wound 3C8 ferrite toroid; 12-turn bifilar primary (centre-tapped); 4-turn 6.3 V centre-tapped secondary; effective core area 8 mm²; saturation flux 0.4 T',
      controllerAlternative: 'TI UCC28063A push-pull controller as alternative-clock variant for students who prefer driven push-pull over self-oscillating Royer topology',
      heaterLoad: 'Six type-47 panel lamps (6.3 V / 0.6 A each) as visible thermal-emission stand-in for six RCA Block III vidicon-camera tubes',
    },
    references: [
      'Pressman, Switching Power Supply Design (2e, McGraw-Hill 1991), ch. 4 + ch. 10 — push-pull and full-bridge converter topologies; transformer-driven inverters and leakage-inductance ringing',
      'Royer, G. H. (1955). A switching transistor d-c to a-c converter having an output frequency proportional to the d-c input voltage. AIEE Transactions 74(I): 322-326',
      'NASA TR-32-700 Ranger 8 Mission Report (JPL, July 1965, NTRS 19660006005), §6.5 — auxiliary-battery and television-subsystem power architecture',
      'Sevastopoulos, A. & Schultz, R. (1962). Self-oscillating transistor inverters. Solid-State Design (June): 21-27',
      'Linden & Reddy, Handbook of Batteries (4e, McGraw-Hill 2010), ch. 33 — silver-zinc primary cells',
      'Eagle-Picher GAP-7239 datasheet, https://www.eaglepicher.com/sites/default/files/SLC-PrimaryCellGAP7239.pdf',
      'Texas Instruments UCC28063A datasheet, https://www.ti.com/lit/ds/symlink/ucc28063a.pdf',
      'Tirrell, NASA SP-4210 Lunar Impact (1977), ch. 6 — Block III spacecraft architecture and the television subsystem',
    ],
  },
  complexPlanePosition: {
    real: 0.37,
    imaginary: 0.55,
    magnitude: Math.sqrt(0.37 ** 2 + 0.55 ** 2),
    angle: Math.atan2(0.55, 0.37),
  },
};
