import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.51 — Squib-fired vernier-engine power chain failure mode and
 * GMK valve actuator energetics: bridgewire all-fire margin under
 * realistic CDU firing-bus impedance and the Surveyor 2 vernier-engine-3
 * no-fire on the midcourse-correction maneuver.
 *
 * Generated by the v1.49.581 ELC Wave-7 backfill (slot E7-J).
 * Cross-references: NASA 1.51 (Surveyor 2 1966-09-20 launch / 1966-09-22
 * midcourse-correction failure), MUS 1.51 (when authored — series-stack
 * single-failure colours-the-whole-sonority structural rhyme).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md
 */
export const squibCduVernierGmkPowerChain: RosettaConcept = {
  id: 'elc-1.51-squib-cdu-vernier-gmk-power-chain',
  name: 'Bridgewire all-fire energy budget under realistic CDU firing-bus impedance with welding-bead failure-mode parameter R_WELD',
  domain: 'electronics',
  description:
    'A power-electronics primitive describing how a +29 V Central Distribution ' +
    'Unit (CDU) firing bus + 100 µF Sprague-Mallory hermetic-tantalum firing ' +
    'capacitor + harness + welding-bead-resistance R_WELD + tungsten ' +
    'bridgewire R_BW = 1.0 Ω of an NSI-class single-bridgewire pyrotechnic ' +
    'initiator delivers integrated bridgewire energy E_BW = ∫I²R_BW dt to ' +
    'the booster charge of a Hughes Surveyor Gas-Mechanical-Kit (GMK) ' +
    'propellant-valve actuator. The instantaneous bridgewire current is ' +
    'I = V_C(t) / (R_BSRC + R_HARN + R_BW + R_WELD); the integrated ' +
    'energy must exceed the all-fire threshold E_ALL_FIRE = 50 mJ (per ' +
    'MIL-STD-1576 / NASA-STD-5018) for reliable booster ignition and ' +
    'subsequent mechanical latching of the propellant-valve poppets ' +
    'open, enabling hypergolic ignition of MMH + MON-10 in the throttleable ' +
    'vernier thrust chamber. The pedagogical keystone is that R_WELD — the ' +
    'series resistance of the welding bead at the bridgewire-cup interface ' +
    'inside the hermetic glass-to-metal-seal of the initiator — enters the ' +
    'energy budget non-linearly because both peak bridgewire current and ' +
    'energy-partition fraction R_BW / R_total fall together as R_WELD rises. ' +
    'A 4-10 Ω welding bead invisible to standard pre-flight inspection drives ' +
    'integrated energy below 50 mJ and prevents ignition. The canonical ' +
    'flight exemplar is the Surveyor 2 vernier-engine-3 no-fire on ' +
    '1966-09-22 04:00 UTC midcourse-correction maneuver, traced by ' +
    'JPL TR 32-1023 to a most-probable welding-bead failure mode at the ' +
    'bridgewire-cup interface, whose mitigations on the Surveyor 3 ' +
    'redesign — X-ray inspection of welding beads, end-of-line resistance ' +
    'screening, and the parallel-redundant dual-bridgewire NSI-class ' +
    'topology that became standard in NASA pyrotechnic practice — are ' +
    'the canonical reliability lessons every subsequent NASA flight ' +
    'programme adopted. CLOSES Domain 6 at target=6.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-firing-bus-source-impedance',
      description:
        'Bridgewire energy budget depends on the firing-bus source impedance R_BSRC; ' +
        'a stiffer source (lower R_BSRC) raises the energy partition into R_BW for ' +
        'any given R_WELD',
    },
    {
      type: 'dependency',
      targetId: 'elec-firing-capacitor-stored-energy',
      description:
        'The leading-edge firing-pulse energy is stored in C_FIRE; total stored ' +
        'energy E_C = ½ C V² (= 42 mJ at 100 µF / 29 V) is the bus-impedance-' +
        'independent energy reservoir that enables high peak current independent ' +
        'of source ESR',
    },
    {
      type: 'dependency',
      targetId: 'elec-bridgewire-cup-weld-quality',
      description:
        'R_WELD is set by the resistance-spot-weld geometry between the ' +
        'tungsten-rhenium bridgewire and the stainless-steel header pin; ' +
        'the welding-bead failure mode is the keystone reliability hazard ' +
        'this primitive teaches',
    },
    {
      type: 'dependency',
      targetId: 'elec-relay-interlock-topology',
      description:
        'CDU sequencer ARM-then-FIRE temporal interlock is the safety mechanism ' +
        'against single-event false positives; identical pattern to the ' +
        'Mercury Liberty Bell 7 dual-key safe/arm chain (ELC 1.20) but ' +
        'fully automatic (no human-in-loop) in unmanned spacecraft',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.51-series-stack-single-failure',
      description:
        'The bridgewire-cup welding-bead resistance is the structural rhyme of ' +
        'any musical series-stack structure where a single voice or single cell ' +
        'disproportionately colours the whole sonority — both are series-' +
        'partition structures where a small change at one element changes the ' +
        'whole-system output through the partition fraction',
    },
  ],
  metadata: {
    elcDegree: '1.51',
    domain: 6,
    domainName: 'Power electronics',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware:
      'Hughes Aircraft Co. Surveyor Pyrotechnic and Ordnance Subsystem — ' +
      'Central Distribution Unit (CDU) +29 V firing bus + 100 µF Sprague-Mallory ' +
      'hermetic-tantalum firing capacitor + ARM/FIRE relay sequence + harness + ' +
      'Hi-Shear/Atlas-Powder NSI-class single-bridgewire initiator (1.0 Ω hot ' +
      'bridgewire, 50 mJ all-fire) + booster charge + Gas-Mechanical-Kit (GMK) ' +
      'piston actuator + Reaction Motors / Thiokol-class TD-339 vernier-engine ' +
      'MMH/MON-10 hypergolic propellant valve',
    keyEquation:
      'I_BW(t) = V_C(t) / (R_BSRC + R_HARN + R_BW + R_WELD) ; ' +
      'E_BW = ∫ I_BW² × R_BW × dt over [t_FIRE, t_FIRE + T_pulse] ; ' +
      'GMK_OPEN ⇔ E_BW > E_ALL_FIRE = 50 mJ (per MIL-STD-1576) ; ' +
      'no-fire safety floor: 1 W applied for 5 min must NOT cause ignition',
    benchReplication: {
      activeBus:
        'Korad KEL103 programmable bench supply at +29 V, current-limited at 30 A ' +
        '(modern substitute for 22-cell silver-zinc spacecraft main bus)',
      eraOriginal:
        'Hughes Surveyor 22-cell silver-zinc primary bus + Sprague-Mallory ' +
        'hermetic tantalum 100 µF / 50 V firing capacitor + Allied Control ' +
        'tape-rotary armature ARM/FIRE relays',
      bridgewireSurrogate:
        '1.0 Ω 25 W vitreous-enamel wirewound + Bel Fuse F1A-T fast-blow fuse-wire ' +
        '(physically opens at all-fire energy threshold; gives discrete latch ' +
        'event for educational use); H3 halogen filament (visible-flash variant); ' +
        'PSEMC NSI-1A flight-grade initiator (REGULATED — supplier credentialling required)',
      firingPulse:
        '24 A peak at R_WELD=0; τ_RC = 120 µs; integrated E_BW ≈ 142 mJ ' +
        '(~3× margin to 50 mJ all-fire floor at nominal-good-weld case); ' +
        'transition to no-fire regime occurs at R_WELD ≈ 3-4 Ω',
    },
    references: [
      'Sutton & Biblarz, Rocket Propulsion Elements (9e, Wiley 2017), §6.4-§6.5 — hypergolic ignition; §10 — propellant valves and squib actuators',
      'Kornfeld, Pyrotechnic Initiator Design Handbook (NASA TM-X-64755, 1972) — bridgewire all-fire / no-fire characterisation',
      'MIL-STD-1576 / NASA-STD-5018 — Electroexplosive Subsystem Safety Requirements',
      'JPL Technical Report 32-1023 (1969) — Surveyor Project Final Report (Surveyor 2 vernier-engine-3 failure analysis)',
      'Hughes Aircraft Co. (1968) — Surveyor Spacecraft Final Report SSD-68000R',
      'NASA SP-480 Far Travelers (Bauer 1989) — Surveyor program failures',
      'Heyman 1966 — Atlas-Centaur AC-7 Surveyor 2 Post-Flight Trajectory Reconstruction',
      'Pacific Scientific Energetic Materials Corp NSI product page, https://www.psemc.com/products/initiators/nasa-standard-initiator/',
    ],
  },
  complexPlanePosition: {
    real: 0.51,
    imaginary: 0.60,
    magnitude: Math.sqrt(0.51 ** 2 + 0.60 ** 2),
    angle: Math.atan2(0.60, 0.51),
  },
};
