import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.3 — Persistent-source acoustics: long-duration broadcast carrier,
 * intimate-recording acoustic-physics, and wood-resonance harmonic spectrum.
 *
 * Generated by the v1.49.581 MUS wave-5 fleet pass (slot W5-A).
 * Domain 9 (Acoustics & psychoacoustics), THIRD entry — the structural-
 * persistence reading. Where the Domain 9 first entry reads identity through
 * narrow-band spectral PURITY (a single pure-tone whistle held against silent
 * gaps) and the Domain 9 second entry reads identity through broadband
 * AGGREGATE DENSITY (wing-beat low-band + chordotonal ultrasonic split-
 * spectrum), MUS 1.3 reads identity through STRUCTURAL PERSISTENCE: the
 * carrier or resonator that outlasts the active signal and continues to carry
 * a recoverable spectral identity long after the source-event has ended.
 *
 * Cross-references: NASA 1.3 (Vanguard 1, oldest still-orbiting human artifact),
 *                   ELC 1.3 (pending),
 *                   the two earlier Domain 9 entries (Varied Thrush
 *                   pure-tone identity and Monarch broadband-density
 *                   split-spectrum identity).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const persistentSourceAcousticsBroadcastIntimateWoodResonance: RosettaConcept = {
  id: 'mus-1.3-persistent-source-acoustics-broadcast-intimate-wood-resonance',
  name: 'Persistent-source acoustics: long-duration broadcast carrier, intimate-recording acoustic-physics, and wood-resonance harmonic spectrum',
  domain: 'music',
  description:
    'A music-theoretic primitive describing how the perceptual and material identity of an ' +
    'acoustic object can persist across timescales much longer than the active signal it once ' +
    'emitted, by lodging the identity in the structural resonance of a carrier rather than in ' +
    'the moment-to-moment radiated content. Three substrates instantiate the primitive: (1) a ' +
    'long-duration radio-frequency broadcast carrier whose signal-bearing transmitter has died ' +
    'but whose orbital structure continues to carry a recoverable identity through tracked ' +
    'state and historical record; (2) an intimate close-microphone vocal recording whose ' +
    'spectral identity is carried by the singer-body-and-room resonance rather than by the ' +
    "score, persisting across reissues at the recording's spectral-fingerprint level; and (3) " +
    'a wood-board harmonic-spectrum resonator (the cedar guitar-soundboard, the carved-cedar ' +
    'flute, the cedar plank-house) whose 1f:2f:3f:4f overtone ratio is set by the species-' +
    "specific modulus, density, and damping-Q of the wood, not by the player's input. The " +
    'pedagogy anchors in Fletcher & Rossing (1998) on string-soundboard coupling, in Cogan ' +
    '(1984) and Sethares (2005) on spectrum-as-compositional-surface and timbre-tuning ' +
    'co-evolution, in Eargle (2005) on the close-mic intimate-vocal acoustic signature, and ' +
    'in Ueda et al. (2013) on direct measurement of Western Red Cedar (Thuja plicata) ' +
    'soundboard properties (320–360 kg/m³ density, 7.5–9.5 GPa MoE along grain, damping-Q ' +
    '60–110 in 100–4000 Hz). The composite claim is that a sonic identity can outlast its ' +
    "active emission when the carrier's structural resonance is the load-bearing identity-" +
    'channel — the dead transmitter, the singer in print, the wood after the strike.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-acoustics',
      description: 'Persistent-source-acoustics is the structural-resonance specialisation of musical-acoustics that foregrounds carrier-resonance over moment-to-moment radiated content — Fletcher-Rossing string-soundboard coupling + Eargle close-mic intimacy + the orbital-state-as-broadcast-record observational framing',
    },
    {
      type: 'analogy',
      targetId: 'music-recording',
      description: 'Late-1950s Mercury close-mic vocal-jazz recording aesthetic (Ernestine Anderson sessions 1958–1962) is the recording-domain instantiation of persistent-source acoustics — the singer-body-and-room composite-resonator persisted at the spectral-fingerprint level across 67+ years of reissues, parallel to a still-orbiting structural identity',
    },
    {
      type: 'cross-reference',
      targetId: 'mus-1.55-spectral-content-as-identity',
      description: 'The Domain 9 narrow-band-purity counterpart reads identity in the PURITY of a single pure-tone partial held against silence; persistent-source acoustics reads identity in the STRUCTURAL PERSISTENCE of a carrier-resonator that outlasts the active signal. Pure-tone purity is a moment-to-moment property; persistence is a multi-decadal property.',
    },
    {
      type: 'cross-reference',
      targetId: 'mus-1.28-wing-beat-acoustics-soul-density-failure-spectrum',
      description: 'The Domain 9 broadband-density counterpart reads identity in the AGGREGATE DENSITY of a wide-band signal sustained by ongoing physical generation (wing-beat fundamentals, vortex-shedding tails, chordotonal ultrasonic reception); persistent-source acoustics shifts the reading to a passive carrier whose identity outlasts active generation. Together with MUS 1.55 the trio covers narrow-band, broadband-density, and structural-persistence axes of Domain 9 spectrum-as-identity.',
    },
  ],
  metadata: {
    musDegree: '1.3',
    exemplars: {
      s36Artist: 'Ernestine Anderson',
      s36Works: [
        'Hot Cargo (Mercury MG-20354, 1958, with the Rolf Ericson Quartet) — first US Mercury LP',
        'My Kinda Swing (Mercury MG-20496, 1960)',
        'Moanin\' (Mercury MG-20530, 1960)',
        'The Toast of the Nation\'s Critics (Mercury MG-20402, 1959)',
      ],
      spsSpecies: 'Western Red Cedar (Thuja plicata)',
      spsAcousticFeature:
        'Quarter-sawn cedar soundboard properties: density 320–360 kg/m³ (among the lowest of any commercially-significant softwood), modulus of elasticity 7.5–9.5 GPa along grain, damping-Q 60–110 in the 100–4000 Hz musical range. ' +
        'Even 1f:2f:3f:4f overtone ratio (~0 dB : −7 dB : −12 dB : −18 dB) on freshly-struck quarter-sawn cedar guitar tops — the canonical "opened-up" cedar-top sonority compared with the harder-attack 4f-rich Sitka-spruce-top alternative. ' +
        'Coast Salish carved-cedar-flute and plank-house architectural resonance complete the species\' wood-as-instrument acoustic role.',
    },
    references: [
      'Cogan, R. (1984). New Images of Musical Sound. Harvard University Press. — chs. 1–3 spectrographic analysis of timbre as compositional surface',
      'Sethares, W. A. (2005). Tuning, Timbre, Spectrum, Scale (2e). Springer. — chs. 3–5 sensory dissonance and inseparability of timbre and tuning',
      'Fletcher, N. H., & Rossing, T. D. (1998). The Physics of Musical Instruments (2e). Springer. — chs. 9–11 wood plates and string-soundboard coupling',
      'Plomp, R., & Levelt, W. J. M. (1965). Tonal consonance and critical bandwidth. JASA 38(4), 548–560.',
      'Eargle, J. M. (2005). The Microphone Book (2e). Focal Press. — chs. 5–7 large-diaphragm condenser response and proximity effect',
      'Newell, P., Castro, S. V., & Holland, K. (2017). Recording Studio Design (4e). Focal Press. — ch. 6 small studio acoustics',
      'Ueda, Y., et al. (2013). Acoustical properties of Western Red Cedar (Thuja plicata) for soundboard applications. Wood Science and Technology 47(2), 379–393.',
      'Ono, T., & Norimoto, M. (1983). Study on Young\'s modulus and internal friction of wood in relation to the evaluation of wood for musical instruments. Japanese Journal of Applied Physics 22(4), 611–614.',
      'Stewart, J. (1984). Cedar: Tree of Life to the Northwest Coast Indians. University of Washington Press.',
      'Roads, C. (1996). The Computer Music Tutorial. MIT Press. — ch. 4 frequency-domain analysis; ch. 12 spectral synthesis',
      'Hodgson, J. (2010). Understanding Records: A Field Guide to Recording Practice. Continuum.',
      'O\'Keefe, J. A., Eckels, A., & Squires, R. K. (1959). Vanguard measurements give pear-shaped component of Earth\'s figure. Science 129(3348), 565–566.',
      'JPL Space Programs Summary 37-N series (1958–1964). Vanguard 1 transmitter telemetry archive.',
      'NSSDC: Vanguard 1 spacecraft record (1958-002B). NASA/NSSDC.',
      'de Barros, P. (1993). Jackson Street After Hours: The Roots of Jazz in Seattle. Sasquatch Books.',
      'Tom Lord. The Jazz Discography. Lord Music Reference. — Ernestine Anderson Mercury-era sessionography',
    ],
  },
};
