import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.31 — Species-discriminative natal-stream psychoacoustics:
 * cross-modal olfactory-and-acoustic stream-fingerprinting under
 * intermittent-channel signal dropout.
 *
 * Generated by the v1.49.581 MUS wave-7 fleet pass (W7-F).
 * Cross-references: NASA 1.31 (Ranger 5 — Atlas-Agena B + Coho organism pairing),
 *                   ELC 1.31 (pending).
 * Sibling Domain 9 entries: 1.3 (persistent-source), 1.27 (locating-the-source),
 *                           1.28 (wing-beat aeroacoustics), 1.55 (spectral-content).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 */
export const speciesDiscriminativeNatalStreamPsychoacoustics: RosettaConcept = {
  id: 'mus-1.31-species-discriminative-natal-stream-psychoacoustics',
  name: 'Species-discriminative natal-stream psychoacoustics: cross-modal olfactory-and-acoustic stream-fingerprinting under intermittent-channel signal dropout',
  domain: 'music',
  description:
    'A psychoacoustic primitive describing how a receiver (animal, human listener, or ' +
    'engineering decoder) recovers the identity of a sound source from a degraded ' +
    'multi-modal carrier by cue-redundant fusion across channels rather than by ' +
    'improving any single channel\'s signal-to-noise ratio. Three perceptual ' +
    'conditions govern fusion quality: (1) channel redundancy — at least two ' +
    'cue-channels carry information about the same target identity; (2) reliability ' +
    'weighting — the receiver weights cues by reliability via maximum-likelihood ' +
    'cue-combination (Ernst & Banks 2002 visual-haptic integration generalised to all ' +
    'multi-modal cue fusion); (3) threshold commitment — once weighted evidence ' +
    'crosses a perceptual threshold, the receiver commits to an identity hypothesis. ' +
    'The Coho Salmon (Oncorhynchus kisutch) is the species-specific natural-world ' +
    'exemplar: a returning adult fish discriminates its natal stream by fusing ' +
    'olfactory imprint memory (Hasler 1966; Dittman & Quinn 1996), substrate-borne ' +
    'lateral-line acoustic signature (Bleckmann & Zelick 2009), and temporal autumn-' +
    'freshet phenological cue, under intermittent dropout from sediment plumes, ' +
    'variable flow, and climate-anomaly off-phase years. Coho-specific framing ' +
    'distinguished from the genus-scale Pacific Salmon framing of MUS 1.21 ' +
    '(Computational music; PID-feedback) and from the species-scale Chinook framing ' +
    'of MUS 1.19 (Form; cyclic-return cadence): Coho\'s 3-year life cycle, narrow ' +
    'smoltification imprint window, smaller adult body and quieter spawning signature, ' +
    'and tightly clustered late-October-to-November return all license the Acoustics-' +
    'domain framing as species-specifically psychoacoustic. Brenda Lee Eager is the ' +
    'canonical artist exemplar: the Mercury-Curtom intimate-vocal R&B idiom of 1971-1976 ' +
    '(Mercury SRM-1-655 I Wanna Be Where You Are, 1973; Mercury 73255 Ain\'t ' +
    'Understanding Mellow with Jerry Butler, 1971) instantiates cross-modal ' +
    'binding via close-mic proximity-effect low-mid bloom + Mayfield-aligned Curtom ' +
    'session-band rhythmic placement; the listener fuses pitch + breath + room + ' +
    'mic-distance + ensemble-placement into the singer-in-the-room percept that ' +
    'identifies *Brenda Lee Eager* across consumer-grade reproduction equipment of ' +
    'the period.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-acoustics',
      description: 'Species-discriminative natal-stream psychoacoustics is the multi-modal-fusion specialisation of musical-acoustics that foregrounds the receiver-side identity-recovery problem under degraded multi-channel evidence',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.55-spectral-content-as-identity',
      description: 'MUS 1.55 anchors spectral-content-as-identity (single-channel spectral fingerprint); MUS 1.31 anchors multi-modal-cue-fusion-as-identity (cross-channel binding under partial dropout). Complementary Domain 9 axes',
    },
    {
      type: 'cross-reference',
      targetId: 'mus-1.19-cyclic-return-natal-return-cadence',
      description: 'MUS 1.19 takes Chinook salmon natal-return into Form-domain cyclic-cadence framing. MUS 1.31 takes Coho salmon natal-return into Acoustics-domain multi-modal-cue-fusion framing. Same biological substrate (anadromous Pacific salmonid return), different music-theory primitives, mutual-exclusion preserved by the species-and-domain distinction',
    },
    {
      type: 'cross-reference',
      targetId: 'mus-1.21-recursive-return-pid-feedback',
      description: 'MUS 1.21 takes Pacific Salmon at genus scale into Computational-music PID-feedback framing of homing trajectory. MUS 1.31 takes Coho specifically into Acoustics multi-modal-fusion framing of the receiver-side discrimination problem at each tributary junction. Genus-scale closed-loop control vs species-scale multi-modal sensory cue-binding',
    },
  ],
  metadata: {
    musDegree: '1.31',
    exemplars: {
      s36Artist: 'Brenda Lee Eager',
      s36Works: [
        'I Wanna Be Where You Are (Mercury SRM-1-655, 1973): "I Wanna Be Where You Are", "If I Should Lose Your Love"',
        'Ain\'t Understanding Mellow / Close to You (Mercury 73255, 1971) — duet with Jerry Butler, US R&B #3, US Pop #21',
        'Maybe / Make the Difference (Mercury 73327, 1972)',
        'Take Me to the Mountains (Mercury 73411, 1973)',
        'Session work on Jerry Butler Power of Love (Mercury SRM-1-687, 1973) and One Mint Julep (Mercury SRM-1-1006, 1975)',
      ],
      spsSpecies: 'Coho Salmon (Oncorhynchus kisutch, Walbaum 1792)',
      spsAcousticFeature: 'multi-channel natal-stream return signal-discrimination problem; (1) olfactory imprint of dissolved organic compounds during smoltification window 3-6 weeks pre-ocean-entry (sharply narrower than Chinook); (2) substrate-borne lateral-line hydrodynamic + tactile signature at sub-Hz to ~200 Hz frequencies (Mauthner-cell network resolution); (3) temporal autumn-freshet phenological cue tightly clustered late-October-to-November; receiver fuses all three channels into single committal identity hypothesis under intermittent dropout (sediment plume olfactory occlusion, variable-flow acoustic masking, off-phase temporal anomaly); stray rate ~3% in undisturbed PNW systems vs higher under habitat-disturbance regimes; species-distinguishing features include 3-year life cycle, smaller adult body 3-5 kg with quieter narrower-band redd-construction tail-slap signature than Chinook 9-15 kg, and tighter return phenological clustering',
    },
    references: [
      'Bregman, A. S. (1990). Auditory Scene Analysis: The Perceptual Organization of Sound. MIT Press. — chs. 2-4 partial-cue redundancy + fusion under degraded carriers; ch. 7 sequential integration',
      'Cogan, R. (1984). New Images of Musical Sound. Harvard University Press. — chs. 1-3 spectrographic analysis of identity under noise',
      'Cogan, R., & Escot, P. (1976). Sonic Design: The Nature of Sound and Music. Prentice-Hall. — close-mic vocal intimacy and proximity effect',
      'Sethares, W. A. (2005). Tuning, Timbre, Spectrum, Scale (2e). Springer. — chs. 3-5 inseparability of timbre, spectrum, and source identity',
      'Roads, C. (1996). The Computer Music Tutorial. MIT Press. — ch. 12 frequency-domain analysis; ch. 13 source-filter modelling',
      'Ernst, M. O., & Banks, M. S. (2002). Humans integrate visual and haptic information in a statistically optimal fashion. Nature, 415(6870), 429-433. — maximum-likelihood multi-modal cue weighting',
      'Hasler, A. D. (1966). Underwater Guideposts: Homing of Salmon. University of Wisconsin Press.',
      'Hasler, A. D., & Wisby, W. J. (1951). Discrimination of stream odors by fishes. American Naturalist, 85(823), 223-238.',
      'Dittman, A. H., & Quinn, T. P. (1996). Homing in Pacific salmon. Journal of Experimental Biology, 199(1), 83-91.',
      'Quinn, T. P. (2018). The Behavior and Ecology of Pacific Salmon and Trout (2e). University of Washington Press. — ch. 5 imprinting + homing; ch. 7 species-specific life-history; ch. 8 spawning behavior + acoustics',
      'Bleckmann, H., & Zelick, R. (2009). Lateral line system of fish. Integrative Zoology, 4(1), 13-25.',
      'Pess, G. R., Quinn, T. P., Gephard, S. R., & Saunders, R. (2012). Re-colonization of Atlantic and Pacific rivers. Reviews in Fish Biology and Fisheries, 24(3), 881-900.',
      'Pruter, R. (1991). Chicago Soul. University of Illinois Press. — Mercury-Curtom session-band lineage',
      'Shannon, C. E. (1948). A mathematical theory of communication. Bell System Technical Journal, 27(3), 379-423.',
      'JPL (1962). Ranger Block II Mission V: Final Report. JPL Tech Report 32-381. — Ranger 5 power-system failure mode + intermittent telemetry recovery',
      'Eager, B. L. (1973). I Wanna Be Where You Are [LP]. Mercury SRM-1-655. Producer: Jerry Butler.',
      'Butler, J., & Eager, B. L. (1971). Ain\'t Understanding Mellow / Close to You [single]. Mercury 73255.',
    ],
  },
};
