import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.28 — Wing-beat acoustics and Soul-era density: ultrasonic mate-detection
 * psychoacoustics, low-frequency wing resonance, and the failure-mode noise
 * spectrum.
 *
 * Generated by the v1.49.581 MUS wave-3 fleet pass (slot W3-D).
 * Domain 9 (Acoustics & psychoacoustics), second entry — the broadband-density
 * counterpart to MUS 1.55's narrow-band-purity reading. Together MUS 1.55 and
 * MUS 1.28 cover both ends of the Domain 9 spectrum-as-identity axis.
 *
 * Cross-references: NASA 1.28 (Mariner 1, missing-overbar destruct at T+293 s),
 *                   ELC 1.28 (pending),
 *                   MUS 1.55 (Domain 9 first entry — narrow-band-purity counterpart).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const wingBeatAcousticsSoulDensityFailureSpectrum: RosettaConcept = {
  id: 'mus-1.28-wing-beat-acoustics-soul-density-failure-spectrum',
  name: 'Wing-beat acoustics and Soul-era density: ultrasonic mate-detection psychoacoustics, low-frequency wing resonance, and the failure-mode noise spectrum',
  domain: 'music',
  description:
    'A music-theoretic primitive describing how the perceptual identity of a sonic event is ' +
    'carried by its AGGREGATE spectral density across a wide frequency range, rather than by ' +
    'any single partial, voice, or line. The receiver-side reading is anchored in Bregman ' +
    '(1990, Auditory Scene Analysis, chs. 6-7) on stream-formation in dense polyphonic mixes, ' +
    'in Plomp & Levelt (1965) on critical-band masking, and in Moore (2012, chs. 3-5) on ' +
    'frequency selectivity, masking, and equal-loudness-contour mix engineering. Three ' +
    'perceptual conditions determine whether broadband density reads as one composite envelope: ' +
    'spectral-band continuity (no audible band left empty), common envelope alignment (sources ' +
    'rise and fall together), and a receiver-side masking integral that aggregates pairwise ' +
    'partial masking across the spectrum. The Monarch Butterfly (Danaus plexippus) is the ' +
    'natural-world exemplar: the wing-beat fundamental at 8-12 Hz, the wing-membrane resonance ' +
    'peak at 100-400 Hz, and the leading-edge-vortex shedding tail at 400-2000 Hz together ' +
    'comprise a broadband flight signature whose physical generation is unavoidable at the ' +
    "species' Reynolds number (Sane 2003). The species also carries chordotonal organs at the " +
    'wing-base sensitive in the 5-50 kHz ultrasonic band (Yack & Fullard 2000; Yack 2004), ' +
    'producing a SPLIT-SPECTRUM identity: emission below 2 kHz, reception above 5 kHz. The ' +
    "Dynamics (Seattle Soul / R&B vocal group, Central District, 1960s, Calla and regional " +
    'imprints) are the canonical artist exemplar: the seven-piece dense-mix Soul-era aggregate ' +
    'with horns, electric bass, drums, organ, and tight backing-vocal stack, mid-band-anchored ' +
    'in the Northwest Soul variant (de Barros 1993, Jackson Street After Hours, on Central ' +
    'District club scene). Mariner 1 (1962-07-22, Atlas-Agena destruct at T+293 s after the ' +
    'missing-overbar guidance-equation transcription error) supplies the structural rhyme: the ' +
    'destruct-event RF spectrum is a broadband density signature OF FAILURE, demonstrating that ' +
    'identity-through-spectrum applies symmetrically to success-mode and failure-mode signals. ' +
    "The complement to MUS 1.55's Lunar Orbiter 3 success-spectrum reading.",
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-acoustics',
      description: 'Broadband-density-as-identity is the psychoacoustic specialisation of musical-acoustics that foregrounds the receiver-side aggregation of broadband content across the audible spectrum — Bregman scene-analysis grouping rules + Plomp-Levelt masking integral',
    },
    {
      type: 'analogy',
      targetId: 'music-production',
      description: 'Soul-era dense-mix engineering (the Dynamics, Calla 1960s) is the production-domain instantiation of broadband-density-as-identity — every band populated, common envelope across the bar, the chorus heard as one composite density rather than as separable lines',
    },
    {
      type: 'cross-reference',
      targetId: 'mus-1.55-spectral-content-as-identity',
      description: 'MUS 1.55 (Domain 9 first entry) is the narrow-band-purity counterpart; MUS 1.28 (Domain 9 second entry) is the broadband-density complement. Together they cover both ends of the Domain 9 spectrum-as-identity axis. MUS 1.55 reads identity in the PURITY of a narrow signature; MUS 1.28 reads identity in the DENSITY of a broadband signature.',
    },
  ],
  metadata: {
    musDegree: '1.28',
    exemplars: {
      s36Artist: 'The Dynamics',
      s36Works: [
        'Calla Records sides (1965-1969 Calla discography era, regional Northwest distribution; specific catalogue numbers pending sessionography work)',
        'Central District club residencies (Birdland, Black and Tan, et al.) per de Barros 1993',
      ],
      spsSpecies: 'Monarch Butterfly (Danaus plexippus)',
      spsAcousticFeature:
        'Wing-beat fundamental 8-12 Hz cruise / 16-20 Hz powered launch, ' +
        'membrane-resonance peak 100-400 Hz, leading-edge-vortex broadband tail 400-2000 Hz; ' +
        'chordotonal-organ ultrasonic hearing 5-50 kHz at wing-base for bat-predator-avoidance ' +
        'and conspecific signalling. Split-spectrum identity: emits low broadband, receives high ultrasonic.',
    },
    references: [
      'Bregman, A. S. (1990). Auditory Scene Analysis. MIT Press. — chs. 2-4 grouping rules; chs. 6-7 stream-formation in dense polyphonic mixes',
      'Plomp, R., & Levelt, W. J. M. (1965). Tonal consonance and critical bandwidth. JASA 38(4), 548-560.',
      'Moore, B. C. J. (2012). An Introduction to the Psychology of Hearing (6e). Brill. — chs. 3-4 frequency selectivity and masking; ch. 5 loudness perception',
      'Sane, S. P. (2003). The aerodynamics of insect flight. J. Exp. Biol. 206, 4191-4208. — leading-edge-vortex unsteady-aerodynamic mechanism',
      'Yack, J. E., & Fullard, J. H. (2000). Ultrasonic hearing in nocturnal butterflies. Nature 403(6767), 265-266.',
      'Yack, J. E. (2004). The structure and function of auditory chordotonal organs in insects. Microscopy Research and Technique 63(6), 315-337.',
      'Roeder, K. D. (1962). The behaviour of free flying moths in the presence of artificial ultrasonic signals. Animal Behaviour 10(3-4), 300-304.',
      'Roeder, K. D., & Treat, A. E. (1957). Ultrasonic reception by the tympanic organ of noctuid moths. J. Exp. Zool. 134(1), 127-157.',
      'Reichardt, P. (1969). Studies on the wing-beat sounds of butterflies and moths.',
      'Cogan, R. (1984). New Images of Musical Sound. Harvard University Press. — chs. 1-3 spectrographic analysis as compositional surface',
      'Sethares, W. A. (2005). Tuning, Timbre, Spectrum, Scale (2e). Springer. — chs. 3-5 sensory dissonance',
      'Schaeffer, P. (1966). Traité des objets musicaux. Seuil. — sound-object framework',
      'Persichetti, V. (1961). Twentieth-Century Harmony. Norton.',
      'de Barros, P. (1993). Jackson Street After Hours: The Roots of Jazz in Seattle. Sasquatch Books.',
      'Tom Lord. The Jazz Discography. Lord Music Reference.',
      'JPL Space Programs Summary 37-16 (1962). — Mariner 1 post-flight investigation',
      'NSSDC: Mariner 1 spacecraft record. NASA/NSSDC.',
    ],
  },
};
