import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.51 — Information-theoretic rhythmic encoding: pulse-count-as-message.
 *
 * Generated by the v1.49.581 MUS backfill fleet (wave 9, final wave).
 * Cross-references: NASA 1.51 (Surveyor 2 vernier-3 midcourse-correction
 *                   failure, 1966-09-22 lunar impact + Mountain Chickadee
 *                   organism pairing),
 *                   ELC 1.51 (pending — information-theoretic signaling in
 *                   mixed-species winter flock alarm-call ecology at Cascade
 *                   subalpine elevation).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 *
 * Position: 7th Rhythm-and-meter domain entry (Domain 2 target: 8). The full
 * Domain 2 lineage at this concept's commit: MUS 1.30 (polyrhythm with terminal
 * accelerando/ritardando), 1.7 (pulse-time and entrainment), 1.16 (round-trip
 * rhythm), 1.6 (even-subdivision pulse and abbreviated bloom-cycle), 1.11
 * (dormancy-modulated pulse), 1.41 (diel-tracking long-period rhythm), 1.51
 * (this concept). Each prior entry reads pulse and meter as continuous-time
 * properties of an event train; MUS 1.51 reads pulse-count as a discrete
 * information channel where the integer count of repeated identical units
 * IS the message.
 *
 * The empirical anchor is Templeton, Greene & Davis 2005 Science on the
 * Black-capped Chickadee chick-a-dee call's D-note count as a graded threat-
 * level encoding (mean 2.3 D notes for Great Horned Owl / low threat; mean
 * 4.0 D notes for Northern Pygmy-Owl / high threat). McCallum 1990 BNA #453
 * confirms structurally identical call grammar in Mountain Chickadee
 * (Poecile gambeli). Hailman 1989 Bioacoustics estimates ~several bits per
 * call channel capacity. Bloomfield & Ratcliffe 2003 Journal of Comparative
 * Psychology validates receiver-side that conspecifics retrieve the encoded
 * threat information and modulate mobbing response accordingly.
 */
export const informationTheoreticPulseCountEncoding: RosettaConcept = {
  id: 'mus-1.51-information-theoretic-pulse-count-encoding',
  name: 'Information-theoretic rhythmic encoding: pulse-count-as-message',
  domain: 'music',
  description:
    'A rhythm-domain information channel in which the integer count of ' +
    'repeated identical motivic units across a bounded bout carries graded ' +
    'semantic content. The channel\'s information capacity scales as ' +
    'log_2(N) bits for N reliably distinguishable counts (typically 2-3 ' +
    'bits in human numerosity-perception terms; Hailman 1989 Bioacoustics ' +
    'estimates ~several bits per call for the chick-a-dee). Operability ' +
    'requires (a) phase coherence across the count, (b) distinguishable ' +
    'count values within the receiver\'s resolution limit, and (c) bounded ' +
    'bout duration with unambiguous start and end. Distinct from tempo-' +
    'curve readings of rhythm (MUS 1.30 polyrhythm with terminal ' +
    'accelerando/ritardando), entrainment-target readings (MUS 1.7 pulse-' +
    'time-entrainment), latency readings (MUS 1.16 round-trip rhythm), ' +
    'subdivision-regularity readings (MUS 1.6), dormancy readings (MUS ' +
    '1.11), and hierarchical-nesting readings (MUS 1.41 diel-tracking-' +
    'long-period). The information-theoretic substrate is Shannon 1948; ' +
    'the music-theoretic anchors are Persichetti 1961 §1 metric grouping + ' +
    '§10 polyrhythm, Roads 1996 ch. 19 score-as-information-channel, and ' +
    'Lerdahl & Jackendoff 1983 §4.2 grouping preference rules. The ' +
    'bioacoustic empirical anchor is Templeton, Greene & Davis 2005 ' +
    'Science 308(5730):1934-1937 on the Black-capped Chickadee chick-a-dee ' +
    'call\'s D-note count as graded threat-level encoding, with Bloomfield ' +
    '& Ratcliffe 2003 supplying receiver-side validation; the Mountain ' +
    'Chickadee (Poecile gambeli) carries a structurally identical call ' +
    'per McCallum 1990 BNA #453.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-rhythm',
      description:
        'Information-theoretic pulse-count-encoding is a special case of rhythm in ' +
        'which the integer count of repeated identical motivic units carries graded ' +
        'semantic content as a discrete information channel, distinct from continuous-' +
        'time tempo / accent / latency readings of the same event train',
    },
    {
      type: 'dependency',
      targetId: 'music-meter',
      description:
        'Phase coherence across the count requires the receiver\'s metric entrainment ' +
        'to remain well-formed across the bout duration; without entrainment the count ' +
        'collapses to noise and the channel fails (the Surveyor 2 failure mode)',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.30-polyrhythm-terminal-accelerando',
      description:
        'Sibling rhythm-domain primitive. MUS 1.30 reads tempo modulation as the ' +
        'closure-marking gesture (the bout closes by deliberate slowing); MUS 1.51 ' +
        'reads count completion as the closure-marking gesture (the bout closes when ' +
        'the integer count reaches its message-encoded total). Both close phase-' +
        'coherent at a structurally weighted final pulse; the structural mechanism ' +
        'differs (tempo curve vs count completion)',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.7-pulse-time-entrainment-hard-bop',
      description:
        'Sibling rhythm-domain entrainment primitive. MUS 1.7 reads the steady pulse ' +
        'as the entrainment target itself; MUS 1.51 reads count of pulses on top of an ' +
        'entrained pulse as the signal. Phase coherence is the operability prerequisite ' +
        'shared between them; what 1.7 establishes (the entrainment substrate) is what ' +
        '1.51 builds the count-encoded message on top of',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.16-round-trip-rhythm-passive-reflector-loop-yodel',
      description:
        'Sibling rhythm-domain primitive. MUS 1.16 reads inter-pulse latency as the ' +
        'timing-defining primitive (the round-trip propagation time IS the rhythmic ' +
        'identity); MUS 1.51 reads count of pulses without regard to inter-pulse ' +
        'interval (latency is the entrainment substrate, not the information variable). ' +
        'The two readings are orthogonal axes of the rhythm channel',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.6-even-subdivision-pulse-abbreviated-bloom-cycle',
      description:
        'Sibling rhythm-domain primitive. MUS 1.6 reads subdivision regularity as the ' +
        'rhythmic identity (un-swung eighths defining cool-jazz feel); MUS 1.51 reads ' +
        'count of subdivisions as the message. Subdivision regularity is the prerequisite ' +
        'for count-tracking; without it the count becomes ambiguous',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.11-dormancy-modulated-pulse',
      description:
        'Sibling rhythm-domain long-silent-interval primitive. MUS 1.11 reads silence ' +
        'as a counted-substrate inside an ongoing rhythmic statement (long silent ' +
        'interior between active phases of the same period); MUS 1.51 reads sound ' +
        '(repeated pulses) as the count itself. The two readings are complementary: ' +
        'silent counts vs sounding counts',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.41-diel-tracking-long-period-rhythm',
      description:
        'Sibling rhythm-domain hierarchical-nesting primitive. MUS 1.41 reads the slow ' +
        'level as built from a count of fast cycles (a slow cycle = N fast cycles); ' +
        'MUS 1.51 reads the count itself as a message channel orthogonal to any nested-' +
        'period frame. 1.41 builds a slow level by counting; 1.51 makes the count the ' +
        'message rather than the structural substrate',
    },
  ],
  metadata: {
    musDegree: '1.51',
    exemplars: {
      s36Artist: 'Lemolo (Meagan Grandall — Capitol Hill / Seattle indie-folk; 2010-2014 duo with Kendra Cox; 2015+ Grandall-led collective)',
      s36Works: [
        'The Kaleidoscope (self-released, 2012; producer: Phil Ek) — debut LP, count-driven verse-and-chorus structures up to ten repetitions per section; Phil Ek production lineage from Built to Spill / Modest Mouse / Fleet Foxes / Father John Misty',
        'Red Right Return (self-released, 2015) — sophomore LP after duo lineup change; title track holds synth-pad cycle for ~16 repetitions before lyric resolution; "Driftwood" works at the opposite extreme (six-repetition count with each rep harmonically distinct)',
        'KEXP Cheryl Waters Morning Show sessions (2014, 2017) — live in-studio documentation of the count-driven approach in stripped piano-and-voice arrangements; the count holds even when the production is removed',
      ],
      spsSpecies: 'Mountain Chickadee (Poecile gambeli) — second SPS appearance after NASA 1.51 hippocampal-plasticity / cache-and-recover cognition pairing',
      spsAcousticFeature:
        'chick-a-dee call terminal D-note count as graded threat-encoding ' +
        'channel. Hailman, Ficken & Ficken 1985 J. Comp. Psychol. 99(4): ' +
        '463-470 formalized the call\'s syntax (A-B-C-D in fixed order with ' +
        'count varying); Templeton, Greene & Davis 2005 Science 308(5730): ' +
        '1934-1937 demonstrated experimentally that D-note count is positively ' +
        'correlated with predator threat level (mean 2.3 D notes per call ' +
        'for Great Horned Owl / low threat; mean 4.0 D notes per call for ' +
        'Northern Pygmy-Owl / high threat); Bloomfield & Ratcliffe 2003 J. ' +
        'Comp. Psychol. 117(3): 286-294 validated receiver-side that ' +
        'conspecifics retrieve the encoded information and modulate mobbing ' +
        'response. Hailman 1989 Bioacoustics 2(1): 49-67 estimates ~several ' +
        'bits per call channel capacity. McCallum 1990 BNA #453 confirms ' +
        'structurally identical call grammar in P. gambeli across its ' +
        'montane western range, where mixed-species winter flocks use the ' +
        'call as the coordinated alarm channel. The COUNT of D notes is ' +
        'the information-bearing variable; the D notes themselves are ' +
        'acoustically uniform within a call, so only the count varies.',
    },
    references: [
      'Persichetti, Twentieth-Century Harmony (W. W. Norton, 1961) §1 metric grouping fundamentals; §10 polyrhythm and additive meters',
      'Roads, The Computer Music Tutorial (MIT Press, 1996) §3 rhythm and metric grids; ch. 19 score-as-information-channel and the bit-rate of musical notation',
      'Lerdahl & Jackendoff, A Generative Theory of Tonal Music (MIT Press, 1983) §2 metrical preference rules; §4.2 grouping preference rules',
      'Cope, Computer Models of Musical Creativity (MIT Press, 2005) §4 phrase-length analysis; ch. 7 motivic repetition as count-driven structure',
      'Tagg, Music\'s Meanings (MMMSP, 2013) ch. 22 long-arc song-form and repetition count as narrative weight',
      'Shannon, "A Mathematical Theory of Communication", Bell System Technical Journal 27(3): 379-423; 27(4): 623-656 (1948)',
      'Hailman, Ficken & Ficken, "The chick-a-dee calls of Parus atricapillus: A recombinant system of animal communication compared with written English", Journal of Comparative Psychology 99(4) (1985): 463-470',
      'Hailman, Ficken & Ficken, "Constraints on the structure of combinatorial chick-a-dee calls", Semiotica 67(1-2) (1987): 1-22',
      'Hailman, "The organization of major vocalizations in the Paridae", Bioacoustics 2(1) (1989): 49-67',
      'Templeton, Greene & Davis, "Allometry of alarm calls: Black-capped Chickadees encode information about predator size", Science 308(5730) (2005): 1934-1937',
      'Bloomfield & Ratcliffe, "Black-capped Chickadees (Poecile atricapillus) produce chick-a-dee calls in response to acoustic stimuli that simulate aerial predators", Journal of Comparative Psychology 117(3) (2003): 286-294',
      'McCallum, D. A., "Mountain Chickadee (Poecile gambeli)", in The Birds of North America No. 453 (Cornell Lab / AOU, 1990; account updated through 2002)',
      'Pravosudov & Roth, "Cognitive ecology of food hoarding: The evolution of spatial memory and the hippocampus", Annual Review of Ecology, Evolution, and Systematics 44 (2013): 173-193',
      'Dehaene, The Number Sense: How the Mind Creates Mathematics (Oxford, 1997)',
      'Cantlon, Platt & Brannon, "Beyond the number domain", Trends in Cognitive Sciences 13(2) (2009): 83-91',
      'NASA / Jet Propulsion Laboratory, Surveyor Project Final Report Volume II: Surveyor Spacecraft Performance (NASA SP-184, 1969)',
      'NSSDC, "Surveyor 2", Spacecraft catalog id 1966-084A (National Space Science Data Center)',
      'Lemolo, The Kaleidoscope [LP], self-released (2012); producer Phil Ek',
      'Lemolo, Red Right Return [LP], self-released (2015)',
      'KEXP archive, Cheryl Waters Morning Show sessions with Lemolo (2014, 2017)',
    ],
  },
};
