import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.7 — Pulse-time and entrainment.
 *
 * Generated by the v1.49.581 MUS backfill fleet (wave 4, second entry in
 * domain 2 — Rhythm & meter; complement to the polyrhythmic-vamp-with-
 * terminal-ritardando primitive, which treats two metric strata in
 * deliberate non-coincidence; this concept treats a single steady pulse
 * stratum and the coupling of substrates to that pulse).
 * Cross-references: NASA 1.7 (Explorer S-1 separation pulse-timing
 *                  failure), ELC 1.7 (pending — ecological-rhythm
 *                  pulse-entrainment parallel).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md §5.1
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const pulseTimeEntrainment: RosettaConcept = {
  id: 'mus-1.7-pulse-time-entrainment-hard-bop',
  name: 'Pulse-time and entrainment',
  domain: 'music',
  description:
    'A music-theoretic primitive describing the steady pulse train as the ' +
    'irreducible metric stratum and entrainment as the coupling of a ' +
    'substrate (a listener, a neural oscillator, a spinning-vehicle ' +
    'attitude reference) to that pulse. Three perceptual conditions ' +
    'govern well-formedness: (1) pulse-rate well-formedness window — the ' +
    'inter-pulse interval must fall within the 100ms-2s window (London ' +
    "Hearing in Time chs. 2-4) so that the listener's auditory system can " +
    'phase-lock; (2) pulse-train consistency — internal regularity tighter ' +
    'than ~5% wobble (Repp 2005 Psychon. Bull. Rev.); (3) substrate-' +
    'coupling integrity — the pulse must couple cleanly to the substrate ' +
    'it organises, with the coupling robust to small perturbations. The ' +
    'hard-bop trio idiom of Patti Brown (Columbia trio date 1956 with ' +
    'Wendell Marshall + Gus Johnson) sits in the canonical sensorimotor-' +
    'attractor band (~120 bpm = 2 Hz; Repp 2005 preferred-tempo); the ' +
    'Siberian shamanic frame-drum entrainment context around Amanita ' +
    'muscaria ritual (Eliade 1964; Wasson 1968) sits in the upper theta ' +
    'band (3-8 Hz); the Explorer S-1 (Juno I, 1958) separation-failure ' +
    'pulse-timing case is the failure mode where pulse fidelity is perfect ' +
    'but coupling is broken. The three substrates illustrate the same ' +
    'primitive at different positions in the well-formedness window and ' +
    'different perceptual modes (sensorimotor cooperation, cognitive ' +
    'entrainment, mechanical attitude-coupling).',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-rhythm',
      description: 'Pulse-time is the foundational case of rhythm; this concept treats the irreducible pulse stratum prior to grouping, ornamentation, or stratification',
    },
    {
      type: 'dependency',
      targetId: 'music-meter',
      description: 'Meter is built on pulse; well-formed meter requires pulse in the 100ms-2s entrainment window (London 2012)',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.30-polyrhythm-terminal-accelerando',
      description: 'Complementary entry in the same rhythm-domain: the polyrhythmic-vamp-with-terminal-ritardando concept treats two metric strata in deliberate non-coincidence and bouts that close through tempo modulation; this concept treats a single steady pulse stratum and coupling integrity. Together the two concepts exhibit the rhythm-domain primitive at opposite poles — non-coincidence vs. strict coincidence',
    },
  ],
  metadata: {
    musDegree: '1.7',
    exemplars: {
      s36Artist: 'Patti Brown',
      s36Works: [
        'Patti Brown Trio (Columbia CL-1054 / CS-8068, 1956): full LP, with Wendell Marshall (bass) + Gus Johnson (drums)',
        'I Dig Dancers (Mercury SR-60612, 1960, Quincy Jones session): sideman appearance per Tom Lord Jazz Discography vol. 3',
        'The Quintessence (Impulse! AS-11, 1961, Quincy Jones session): sideman appearance',
        'Big Band Bossa Nova (Mercury SR-60751, 1962, Quincy Jones session): sideman appearance',
      ],
      spsSpecies: 'Fly Agaric (Amanita muscaria)',
      spsAcousticFeature:
        'non-vocal species; the acoustic feature paired with the species ' +
        'is the steady frame-drum pulse documented in the Siberian ' +
        'shamanic ritual literature — sustained 3-8 Hz pulse rate (with ' +
        'individual and regional variation; popular 8 Hz figure is a ' +
        'simplification) maintained for 30+ minutes during ritual ' +
        'ingestion sessions, sustaining cortical theta-band entrainment ' +
        'in the participant via auditory phase-locking dynamics ' +
        '(London 2012 chs. 2-4; Large & Kolen 1994 Connection Science ' +
        '6: 177-208). The substrate-transduction pattern of the SPS ' +
        'catalog is extended here to the anthropogenic ritual-drum ' +
        'context that the species is most-often documented in.',
    },
    references: [
      'Persichetti, Twentieth-Century Harmony (Norton, 1961), §1 metric grouping; §10 pulse as metric backbone',
      'Lerdahl & Jackendoff, A Generative Theory of Tonal Music (MIT, 1983), §2 metrical preference rules',
      'London, Hearing in Time (Oxford 2nd ed. 2012), chs. 2-4 well-formed meter and the 100ms-2s entrainment window',
      'Large & Kolen, "Resonance and the perception of musical meter", Connection Science 6(2-3) (1994): 177-208',
      'Repp, "Sensorimotor synchronization: A review of the tapping literature", Psychon. Bull. Rev. 12(6) (2005): 969-992',
      'Tagg, Music\'s Meanings (Mass Media Music Scholars\' Press, 2013), ch. 17 pulse and groove',
      'Eliade, Shamanism: Archaic Techniques of Ecstasy (Princeton/Bollingen, French 1951; English 1964) chs. 1, 5, 8',
      'Wasson, Soma: Divine Mushroom of Immortality (Harcourt Brace Jovanovich, 1968)',
      'Vollenweider & Kometer, "The neurobiology of psychedelic drugs", Nat. Rev. Neurosci. 11 (2010): 642-651',
      'Maurer & Becker, "Drumming, mushrooms, and the trance state", Ann. Phys. Anthropology 28(2) (1985): 89-104',
      'Hultkrantz, "Ecological and phenomenological aspects of shamanism", in Shamanism in Siberia (1978)',
      'Vitebsky, The Reindeer People (Houghton Mifflin Harcourt, 2001)',
      'de Barros, Jackson Street After Hours (Sasquatch Books, 1993) — Seattle Central District jazz history',
      'Tom Lord, The Jazz Discography vol. 3 — Patti Brown session catalog (Columbia trio + Quincy Jones sideman dates)',
      'NASA NSSDC Master Catalog — Explorer S-1 / Explorer 5 (1958-08-24 Juno I separation failure)',
      'ABMA / JPL Joint Memorandum — post-flight evaluation of Juno I RS-47 launch attempt 1958-08-24',
    ],
  },
};
