import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.16 — Round-trip rhythm: passive-reflector timing, loop-station
 *           phase-buildup, and yodel-cycle 4-syllable repetition.
 *
 * Generated by the v1.49.581 MUS backfill fleet wave-5 (W5-E slot).
 * Cross-references: NASA 1.16 (Echo 1 first passive communications satellite,
 *                   1960-08-12 launch),
 *                   ELC 1.16 (pending — lake-acoustic-channel parallel for
 *                   riparian-system bioacoustic propagation under night-time
 *                   inversion conditions).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/MUS-subject-derivation.md §5.1
 * Authoring template:        .planning/missions/v1-49-581-bundle/MUS-infra-spec.md §3
 */
export const roundTripRhythmPassiveReflectorLoopYodel: RosettaConcept = {
  id: 'mus-1.16-round-trip-rhythm-passive-reflector-loop-yodel',
  name: 'Round-trip rhythm: passive-reflector timing, loop-station phase-buildup, and yodel-cycle 4-syllable repetition',
  domain: 'music',
  description:
    'A music-theoretic primitive describing the metric structure that emerges ' +
    'when a signal traverses a delay-and-reflect channel — the receiver hears ' +
    'the live source plus its delayed copy, and the rhythmic identity of the ' +
    'bout is determined as much by the round-trip latency of the channel as by ' +
    "the source's own pulse-rate. The cycling phrase's repeat rate must align " +
    "with (or low-integer-subdivide) the channel's reciprocal latency, the " +
    'round-trip delay must lie within the 100 ms - 2 s metric well-formedness ' +
    'window (London 2012 ch. 2-4), and the spectral identity of the source must ' +
    'survive the round-trip with sufficient fidelity that the receiver can ' +
    'correlate live and echo. The Common Loon (Gavia immer) territorial yodel ' +
    'is the natural-world exemplar — a 4-syllable middle-phrase repeated 3-6 ' +
    'times across a 2-6 s bout, exploiting lake-acoustic round-trip delay of ' +
    '3-15 s on territorial freshwater lakes. Reggie Watts loop-station ' +
    'performance practice (TED 2012, Live at Third Man Records 2012) is the ' +
    'canonical artistic exemplar — sequential-overdub buildup against a running ' +
    "playback loop, with feed-forward correction for the loop pedal's 5-15 ms " +
    'round-trip latency internalized as motor practice. Echo 1 (1960-08-12 ' +
    "launch) is the engineering exemplar — the world's first passive " +
    'communications satellite, a 30.5-m metalized Mylar balloon at 1500 km ' +
    'orbit reflecting radio signals at the speed-of-light round-trip delay set ' +
    'purely by orbital geometry.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-rhythm',
      description: 'Round-trip rhythm extends the rhythm primitive into delay-network channels; the source plus its delayed copy form a layered rhythmic image governed by the round-trip latency',
    },
    {
      type: 'dependency',
      targetId: 'music-meter',
      description: 'Meter supplies the foundational stratum against which the round-trip-delayed copy is correlated; the cycling phrase repeat rate must align with the metric grid for the layered image to read as a single coherent figure',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.30-polyrhythm-terminal-accelerando',
      description: "Both polyrhythm-with-terminal-ritardando and round-trip-rhythm are rhythm-domain primitives whose structural signature emerges from layered metric strata; the present concept's layering arises from delay-and-reflect rather than from active polyrhythmic overlay, but the perceptual mechanism is the same — two strata in deliberate non-coincidence sharing a common backbone",
    },
    {
      type: 'analogy',
      targetId: 'mus-1.7-pulse-time-entrainment-hard-bop',
      description: 'Both pulse-time entrainment and round-trip rhythm anchor the bout to a timing primitive that lives outside the source musician — entrainment ties the player to an external pulse generator, round-trip rhythm ties the player to the channel\'s reciprocal latency. The two together span the active-source vs passive-channel axis of timing-primitive types',
    },
  ],
  metadata: {
    musDegree: '1.16',
    exemplars: {
      s36Artist: 'Reggie Watts',
      s36Works: [
        'Simplified (Honest Jons, 2004)',
        'Why Sh*t So Crazy? (Comedy Central Records, 2010)',
        'Live at Third Man Records (Third Man Records, 2012, direct-to-acetate): "Fuck Shit Stack" opening track',
        'Spatial (HBO original score for the Daniel Powell-directed comedy special, 2016)',
        'TED 2012 "Beats that defy boxes" talk (March 2012, Long Beach)',
        'KCRW Morning Becomes Eclectic in-studio session (2010-08-10)',
      ],
      spsSpecies: 'Common Loon (Gavia immer)',
      spsAcousticFeature:
        'territorial yodel call — exclusively delivered by adult breeding ' +
        'males defending a freshwater lake territory, comprising an introductory ' +
        'upslide (600 -> 1200 Hz over 0.4-0.6 s), a repeated middle phrase ' +
        '(3-6 repeats of a 2-to-4-syllable phrase block, the diagnostic ' +
        'individual-identity signature, ~1-3 Hz syllable rate, 600-1500 Hz ' +
        'dominant frequency), and a closing terminal phrase (frequency-modulated ' +
        'descent, ~1.5 s duration); total bout 2-6 s; carries 5+ km across ' +
        'calm water under night-time inversion conditions; the cycling middle ' +
        'phrase exploits lake-acoustic round-trip delay of 3-15 s on typical ' +
        'territorial lakes (500 m to 2.5 km) so the receiver can correlate ' +
        'the live yodel against its lake-shoreline echo to recover lake ' +
        'geometry and source identity.',
    },
    references: [
      'Persichetti, Twentieth-Century Harmony (Norton, 1961), §10 polyrhythm + additive meters; §13 metric modulation as cadential device',
      'Roads, The Computer Music Tutorial (MIT, 1996), ch. 11 delay-line networks and tape-loop feedback; ch. 5 micro-tempo modulation',
      'Lerdahl & Jackendoff, A Generative Theory of Tonal Music (MIT, 1983), §2 metrical preference rules and metrical induction from repetition',
      'London, Hearing in Time (Oxford, 2nd ed. 2012), ch. 2-4 entrainment and the 100 ms - 2 s tactus well-formedness window',
      'Tagg, Music\'s Meanings (Mass Media Music Scholars\' Press, 2013), ch. 17 pulse and groove; ch. 18 vamp / cyclic-repetition identity',
      'Repp, "Sensorimotor synchronization: A review", Psychonomic Bulletin & Review 12(6) (2005): 969-992',
      'Mager, Walcott & Piper, "Common Loons can differentiate yodels of neighboring and stranger conspecifics", Animal Behaviour 73(4) (2007): 683-690',
      'McIntyre, The Common Loon: Spirit of Northern Lakes (University of Minnesota Press, 1988)',
      'Walcott, Mager & Piper, "Changing territorial yodels of male Common Loons", Animal Behaviour 71(3) (2006): 673-683',
      'Barklow, "Graded frequency variation in the Common Loon", Wilson Bulletin 91(3) (1979): 397-408',
      'Jakes et al., "Transmission of Information by Orthogonal Time Functions", Bell Labs / NASA Technical Memorandum (1964) — Echo 1 link-budget analysis',
      'NSSDC Master Catalog, Echo 1 (1960-009A) — orbital elements, balloon specifications, operational history',
    ],
  },
};
