import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * MUS 1.65 — Sustained-pitch as identity: the unwavering held tone as
 * carrier of compositional identity across multi-minute durations.
 *
 * Generated by the v1.49.583 forward-cadence build (the third three-track
 * simultaneous-ship degree under §3 NORMATIVE: NASA 1.65 + MUS 1.65 +
 * ELC 1.65 ship together, following the v1.64 ALL-UP COMMITMENT triple).
 *
 * Cross-references: NASA 1.65 (Pioneer 8 / P-A / NSSDC 1967-123A; third
 * of the four-platform Pioneer 6/7/8/9 heliocentric solar-monitoring
 * constellation; 28-year-8-month operational tenure), ELC 1.65
 * (Spin-modulated S-band deep-space downlink: 60 RPM body rotation
 * imposing 1 Hz amplitude modulation on the 2292 MHz carrier; 8 W
 * Watkins-Johnson WJ-274-class flight TWT; multi-decade reactivation
 * lifetime).
 *
 * Domain-1 differentiation: prior Domain 1 entries treat pitch across
 * structurally distinct axes — 1.26 sympatric-pitch-divergence (chorus
 * members shift pitch *away* from same-pitch neighbours; identity in the
 * spectral *gap* between voices), 1.37 bent-string blue-third microtonality
 * (continuous-pitch ornamentation; identity rides on the *bending arc
 * between* discrete pitches), 1.47 infrasonic-floor pitch (a 7-10 Hz
 * sub-audible carrier *underneath* the audible bellow; identity is the
 * inaudible substrate), 1.48 modal vocabulary (Mixolydian / Dorian /
 * Lydian *dialect* choices against the Ionian default; scale-level
 * commitment), 1.50 microtonal dialect (population-level deviations from
 * 12-TET; identity in the cents-level offsets *between* notional pitches
 * across many notes). MUS 1.65 occupies the structurally distinct
 * **sustained-pitch-as-identity** axis: a single pitch is *held unbroken*
 * for tens of seconds to minutes, and the work's compositional identity
 * rides on that holding. This entry CLOSES Domain 1 to 6/6.
 *
 * §6.6 PERSISTENT-CONSTELLATION-LISTENER: this MUS degree opens the
 * cross-track PERSISTENT-CONSTELLATION-LISTENER thread at single-exemplar
 * status. Pioneer 8 (28-year continuous beacon across a four-platform
 * heliocentric constellation), Earth (Dylan Carlson; uninflected
 * sustained drone-tone as the work's compositional identity across
 * multi-minute durations), and the Sandhill Crane (Antigone canadensis;
 * territorial bugle / unison call carried by the elongated coiled
 * trachea, identity-fixed across the bird's adult tenure) all embody
 * the structural decision to bear identity by *unbroken holding of a
 * single signal*. Variant joins §6.6 candidate amendments awaiting two
 * more exemplars; CHAIN-CONVENTIONS stays at v1.4.
 *
 * Subject derivation rubric: .planning/missions/v1-49-583-pioneer-8-persistent-constellation/MISSION-BRIEF.md
 * Authoring template:        www/tibsfox/com/Research/MUS/1.64/ (gold standard)
 */
export const sustainedPitchAsIdentity: RosettaConcept = {
  id: 'mus-1.65-sustained-pitch-as-identity',
  name: 'Sustained-pitch as identity: the unwavering held tone as carrier of compositional identity across multi-minute durations',
  domain: 'music',
  description:
    'A music-theoretic primitive describing the structural decision to ' +
    'commit a single pitch as the carrier of an entire work\'s identity, ' +
    'where the pitch is held unbroken for tens of seconds to minutes and ' +
    'the work\'s rhythmic articulation, harmonic motion, and dynamic event ' +
    'cadence all defer to the held tone. Formally: the sustained-pitch ' +
    'primitive is the assertion Identity_work = held({ f_0, overtone_series, ' +
    'amplitude_envelope }, t in [0, T]) for T >> tau_event, where tau_event ' +
    'is the listener\'s default expectation of the inter-event interval in ' +
    'the genre. Three perceptual closure conditions: (1) the held tone is ' +
    'audibly continuous across multi-second to multi-minute durations with ' +
    'no event articulation that would relocate identity onto the event ' +
    'cadence; (2) harmonic motion is implicit in the overtone series of the ' +
    'held tone, not in chord-progression motion; (3) the work\'s identity ' +
    'is recoverable from any non-zero window of the held tone — the ' +
    'listener can identify the work from a 5-second segment because the ' +
    'sustained pitch IS the work. The sustained-pitch axis is structurally ' +
    'distinct from the sympatric-pitch-divergence / blue-third-bend / ' +
    'infrasonic-substrate / modal-vocabulary / microtonal-dialect axes of ' +
    'the prior Domain 1 entries — those classify pitch as an inter-note or ' +
    'between-note structural decision, while the sustained-pitch axis ' +
    'classifies a single audible held tone as the work\'s irreducible ' +
    'compositional unit. The Sandhill Crane (Antigone canadensis) is the ' +
    'canonical bioacoustic exemplar of the sustained-trumpet-as-identity ' +
    'case: the territorial bugle / unison call is a 1-2 second resonant ' +
    'sustained tone (~280-440 Hz fundamental + strong low-frequency ' +
    'overtone series) produced via an elongated ~1.0-1.2 m coiled trachea ' +
    'acting as a half-wave resonant chamber, identity-fixed across the ' +
    'bird\'s adult tenure. Earth (Dylan Carlson) is the canonical PNW ' +
    'drone-metal exemplar of the whole-LP sustained-pitch case: Earth 2: ' +
    'Special Low-Frequency Version (Sub Pop SP185, 1993) comprises three ' +
    'tracks across approximately 73 minutes of slowly-modulated detuned ' +
    'guitar drones at glacial tempo, with no vocals and the sustained pitch ' +
    'as the entire compositional vocabulary.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'music-pitch-fundamentals',
      description:
        'The sustained-pitch primitive depends on pitch-fundamentals: ' +
        'fundamental frequency, overtone series, just-intonation harmonic ' +
        'relationships, and the audibility of partials within a held tone ' +
        'must be available as background concepts for the listener to hear ' +
        'the held tone as carrying compositional identity rather than as ' +
        'static noise.',
    },
    {
      type: 'dependency',
      targetId: 'music-recording-aesthetics',
      description:
        'The whole-LP sustained-pitch case depends on the recording-as- ' +
        'artifact ontology: the held tone over multi-minute durations must ' +
        'be honored in the production and playback chain (no compression ' +
        'side-chained to amplitude variation, no noise-gate truncating the ' +
        'sustain) for the primitive to obtain.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.64-all-up-first-take',
      description:
        'MUS 1.64 framed identity-as-the-take-itself on the all-up-first- ' +
        'take axis (whole performance committed at once, no overdub-as- ' +
        'correction). MUS 1.65 reframes a complementary committal pattern ' +
        'on the sustained-pitch axis (whole work committed to a held tone ' +
        'across multi-minute durations). Both occupy the discipline-of- ' +
        'frame family; the difference is the temporal axis the primitive ' +
        'operates on (event-cadence-suppression at performance vs ' +
        'event-cadence-suppression at composition). The two together span ' +
        'the v1.64 ALL-UP COMMITMENT thread\'s temporal sibling: ALL-UP is ' +
        'about the inaugural single first commit; sustained-pitch is about ' +
        'the temporal complement, the holding that follows.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.50-microtonal-dialect',
      description:
        'MUS 1.50 framed pitch as a population-level deviation from 12-TET ' +
        '(identity in the cents-level offsets between notional pitches ' +
        'across many notes). MUS 1.65 reframes a complementary pitch-as- ' +
        'identity pattern at a different scale: the sustained-pitch ' +
        'primitive holds a single pitch unbroken across multi-minute ' +
        'durations as the carrier of identity. Both are pitch-as-identity ' +
        'on Domain 1; the difference is the temporal grain (between-note ' +
        'cents-offsets vs single-note multi-minute hold).',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.47-infrasonic-floor-pitch',
      description:
        'MUS 1.47 framed pitch as a sub-audible 7-10 Hz substrate ' +
        'underneath the audible event (identity in the inaudible carrier). ' +
        'MUS 1.65 reframes the complementary pitch-as-identity pattern at ' +
        'the audible scale: the sustained pitch IS the audible work, held ' +
        'unbroken across multi-minute durations. Both are pitch-as-' +
        'identity-via-sustain; 1.47 is sub-audible substrate, 1.65 is ' +
        'audible held tone.',
    },
  ],
  metadata: {
    musDegree: '1.65',
    exemplars: {
      s36Artist: 'Earth (Dylan Carlson)',
      s36Works: [
        'Earth 2: Special Low-Frequency Version (Sub Pop SP185, 1993): the canonical Pacific Northwest drone-metal LP. Three tracks across approximately 73 minutes — Seven Angels (~14:35), Teeth of Lions Rule the Divine (~27:22), and Like Gold and Faceted (~30:49) — composed primarily of slowly-modulated detuned guitar drones at glacial tempo, with no vocals and no conventional rhythmic articulation. The signature gesture is the uninflected sustained pitch held for 20-90 seconds before any chord-change or pitch-shift; the entire identity of the work rests on the holding of the tone.',
        'Members (1990-present): Dylan Carlson (b. 1968; Olympia → Seattle WA; founder, primary songwriter, sole continuous member 1989 to present); Joe Preston (bass; original 1989-1996 lineup; also of Melvins / Sunn O))) lineage); Adrienne Davies (drums, 2005 reformation onward). Influence on Stephen O\'Malley + Greg Anderson (Sunn O)))) is explicit — the band-name Sunn O))) itself originating from the Earth orbit of the same Sub Pop / PNW underground.',
        'Carlson interview material consistently frames the sustained tone as the substance of the work rather than as backdrop or accompaniment. Cross-resonance with Pioneer 8 / NASA 1.65 and the Sandhill Crane / SPS: just as Earth 2 commits a single tonal signature to the entire 73-minute LP, Pioneer 8 commits a single 2292 MHz S-band carrier to its entire 28-year mission, and the Sandhill Crane bugle commits a single sustained trumpet-tone carried by the elongated coiled trachea as the bird\'s identity-broadcast across its adult tenure.',
      ],
      spsSpecies: 'Sandhill Crane (Antigone canadensis, formerly Grus canadensis; Linnaeus 1758; Pacific Flyway populations stage at Sauvie Island OR, Ridgefield National Wildlife Refuge WA, Sherman County / Lower Klamath Basin OR; greater sandhill cranes (A. c. tabida) breed across the Cascades and northern PNW; conservation status: A. c. tabida increasing in the PNW after mid-twentieth-century reductions, with active recovery in eastern Washington and Oregon)',
      spsAcousticFeature: 'territorial bugle / unison call — 1-2 second resonant trumpet-call delivered by adult cranes, fundamental ~280-440 Hz with strong low-frequency overtone series. Acoustic mechanism: an elongated trachea coiled within the keel of the sternum, reaching an unwound length of approximately 1.0-1.2 m in adult A. canadensis (closer to 1.5 m in the larger Grus americana whooping crane; ~5 m is the comparative anatomy figure for the trumpeter swan and is sometimes mis-attributed to cranes — sandhill crane tracheal coil is order ~1 m). The elongated trachea acts as a half-wave resonant chamber whose long air column supports the low-fundamental sustained tone with a pure harmonic series, giving the bugle its identity-fixed timbre. Identity-fixed across the bird\'s adult tenure: cranes pair-bond for life and the unison-call bugle is dyadic — both members of a bonded pair vocalize as a sustained-pitch duet, with male and female components interleaving into a single sustained acoustic signature that identifies the pair across territorial and migratory contexts.',
    },
    references: [
      'Eisenberg, E. (2005) The Recording Angel: Music, Records, and Culture from Aristotle to Zappa (2e, Yale UP) — chs. 4-5 on the recording-as-artifact ontology; sustained-tone recordings (Young, Niblock, Earth, Sunn O))) lineage) as a distinct ontological category from event-driven recordings',
      'Young, L. M. & Zazeela, M. (1965-present) The Theatre of Eternal Music / The Tortoise, His Dreams and Journeys / Dream House sustained-tone installations — foundational sustained-tone music theory; the held just-intonation drone as compositional substance, not backdrop',
      'Oliveros, P. (2005) Deep Listening: A Composer\'s Sound Practice (iUniverse) — sustained-tone listening practice and compositional intent; the holding of a tone as a meditative and structural commitment',
      'Reich, S. (1968) Music as a Gradual Process — process-based composition where the gradual unfolding of sustained material is the structural subject',
      'Tacha, T. C., Nesbitt, S. A. & Vohs, P. A. (1994) Sandhill Crane (Grus canadensis). The Birds of North America No. 31 (American Ornithologists\' Union / Academy of Natural Sciences) — definitive natural-history monograph on A. canadensis',
      'Walkinshaw, L. H. (1973) Cranes of the World (Winchester Press) — foundational comparative-cranes monograph; chapter on tracheal-elongation anatomy and its acoustic consequences across Gruidae',
      'Fitch, W. T. (1999) Acoustic exaggeration of size in birds via tracheal elongation: comparative and theoretical analyses. Journal of Zoology 248:31-48 — the comparative-anatomy paper for tracheal-elongation as acoustic-substrate adaptation',
      'Carlson, D. — interview material in The Wire, Decibel, and various long-form drone-metal documentaries discussing Earth\'s compositional method, the sustained-tone-as-substance theory, and the Olympia / Sub Pop / Pacific Northwest underground that produced Earth 2 (Sub Pop SP185, 1993)',
      'O\'Malley, S. & Anderson, G. (Sunn O)))) — published interview material crediting Earth as the originating drone-metal influence',
      'Walcott, C. (multi-year program) — comparative bioacoustics of long-trachea sustained-tone birds (Common Loon, Sandhill Crane, Trumpeter Swan); pedagogical bridge from MUS 1.64 Common Loon yodel (single-take identity-broadcast) to MUS 1.65 Sandhill Crane bugle (sustained-pitch identity-broadcast)',
    ],
  },
};
