import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.5 — Long-duration cumulative-TID dose budgeting for sustained Van Allen
 * belt dwell: germanium-PNP h_FE collapse and design-margin engineering on the
 * Explorer 4 Anton 314 GM-and-scintillator radiation-belt-survey mission
 * (1958-07-26 → 1958-10-05; 70-day continuous inner-belt dwell across 1,170 orbits).
 *
 * Generated by the v1.49.581 ELC Wave-7 backfill (slot E7-B).
 * Cross-references: NASA 1.5 (Explorer 4 / radiation-belt-survey + Operation Argus
 * declassified parallel role), MUS 1.5 (long-form harmonic motion partner;
 * structural rhyme of cumulative-dose accumulation as time-integrated
 * gesture that resolves at threshold).
 * Siblings in domain 12: ELC 1.10 (transit-TID + SEU on germanium NPN under brief
 * Van Allen traversal; Pioneer 3, ~38 hours), ELC 1.33 (Paschen-corona
 * environmental-electrical-discharge subfamily; Ranger 6 ascent-event).
 * ELC 1.5 reframes Domain 12 as long-duration cumulative-dose dwell —
 * the third disjoint mechanism-family regime alongside transit-TID (1.10)
 * and environmental-discharge (1.33).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const cumulativeTidDoseBudget: RosettaConcept = {
  id: 'elc-1.5-cumulative-tid-dose-budget',
  name: 'Long-duration cumulative-TID dose budgeting for sustained Van Allen belt dwell',
  domain: 'electronics',
  description:
    'A radiation-hardening primitive describing how cumulative ionising dose D(t) = ' +
    '∫₀ᵗ Φ(τ)·LET dτ accumulates monotonically over mission elapsed time and drives ' +
    'progressive bias-point drift in 1958-vintage germanium-PNP instrumentation amplifiers. ' +
    'The model has three additive parameter shifts whose dependences on cumulative dose ' +
    'separate cleanly over mission timescales: ' +
    'h_FE(D) = h_FE,0(1 − k_β·D) with k_β ≈ 1×10⁻⁵ per rad for 1958 Ge PNPs; ' +
    'I_CBO(D) = I_CBO,0 + k_I·D with k_I ≈ 50 nA per krad; ' +
    'PMT_dark(D) = PMT_dark,0(1 + k_pmt·D) with k_pmt ≈ 10% per 10 krad on era-original ' +
    'photocathodes. The mission-life budget T_mission = (D_failure − D_initial) / Φ̄·LET ' +
    'locates the elapsed time at which cumulative dose crosses chain failure dose. The ' +
    'canonical flight exemplar is Explorer 4 (Juno I RS-44, 1958-07-26), whose 70-day ' +
    'continuous inner-Van-Allen-belt dwell across 1,170 orbits accumulated 8-50 krad ' +
    'cumulative TID (depending on shielding mass weighting) — well within the design ' +
    'margin set by the 50× oversized day-0 signal-to-noise budget. The mission terminated ' +
    'by battery exhaustion on day 71, not by chain failure. Explorer 4 also detected the ' +
    'September 1958 Operation Argus high-altitude nuclear tests artificial electron belts ' +
    '(declassified 1982). The post-1962 mission-design literature crystallised from the ' +
    'Explorer 4 + Pioneer 3 dataset: Holmes-Siedle & Adams 2002 §6 builds the canonical ' +
    'cumulative-dose treatment; NASA SP-3024 (1966) gave the equation its first formal ' +
    'mission-handbook form; Vette 1991 AE-8 trapped-electron environment is the modern ' +
    'descendant. ELC 1.5 distinguishes Domain 12 sub-family from ELC 1.10 (transit-TID + ' +
    'SEU; brief-traversal regime) and ELC 1.33 (environmental-electrical-discharge; ' +
    'instantaneous vacuum-transition arc-over): the three together establish that ' +
    'Domain 12 covers three disjoint mechanism-family regimes spanning the radiation-' +
    'hardening problem space.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-bipolar-bias-stability',
      description:
        'Emitter-resistor DC negative-feedback degeneration is the era-universal anti-drift technique that ' +
        'Explorer 4 used against cumulative-TID-driven I_CBO rise; the same topology is the structural ' +
        'foundation of long-duration rad-hard bipolar bias schemes',
    },
    {
      type: 'dependency',
      targetId: 'elec-discriminator-threshold',
      description:
        'Diode-coupled discriminator threshold over mission life: as cumulative TID degrades preamp gain, ' +
        'the discriminator margin shrinks monotonically; the elapsed time at which the smallest target pulses ' +
        'fall below threshold defines T_mission, the mission-life budget for sustained-dwell missions',
    },
    {
      type: 'related',
      targetId: 'elc-1.10-radiation-hardening-germanium',
      description:
        'Sibling Domain 12 entry. ELC 1.10 framed Domain 12 as transit-TID + SEU under brief particle-flux ' +
        'exposure (Pioneer 3, ~38 hours). ELC 1.5 inherits the linear-superposition framework and extends it ' +
        'with the time-integrated cumulative-dose D(t) term that dominates over mission lifetimes longer than ' +
        'belt traversal time. The k_β and k_I drift coefficients carry over unchanged; what changes is the ' +
        'integration window — from 38 hours to 70 days continuous',
    },
    {
      type: 'related',
      targetId: 'elc-1.33-paschen-corona-vacuum-transition',
      description:
        'Sibling Domain 12 entry. ELC 1.33 framed Domain 12 as environmental-electrical-discharge hardening ' +
        '(Ranger 6 corona-discharge in transitional vacuum; instantaneous ascent-event mechanism). ' +
        'ELC 1.5 reframes Domain 12 as cumulative-dose long-duration dwell (sustained-mission-life mechanism). ' +
        'Together with ELC 1.10 (transit-TID + SEU), the three establish that Domain 12 covers three disjoint ' +
        'mechanism-family regimes: brief-transit, environmental-discharge, and sustained-dwell',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.5-long-form-harmonic-motion',
      description:
        'The cumulative-dose integral D(t) = ∫₀ᵗ Φ·LET dτ is itself a sustained-accumulation gesture ' +
        'that resolves at the mission-life budget point (the elapsed time where D(t) crosses D_failure). ' +
        'The MUS 1.5 long-form harmonic motion is the structural rhyme: a time-integrated gesture that ' +
        'resolves at structural cadence. Both are time-integrated forms with thresholded resolution',
    },
  ],
  metadata: {
    elcDegree: '1.5',
    domain: 12,
    domainName: 'Radiation hardening',
    domainSubFamily: 'long-duration cumulative-TID dwell (vs transit-TID in ELC 1.10; vs environmental-discharge in ELC 1.33)',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'Explorer 4 Anton 314 paired thin-walled Geiger-Müller tubes + CsI(Tl) scintillator + RCA 6342A photomultiplier + 2N43-class germanium-PNP charge-sensing preamp + 1N34A discriminator + monostable count-stretcher (Van Allen / Frank, State University of Iowa; JPL / ABMA flight build); 70-day continuous inner Van Allen belt dwell 1958-08-01 → 1958-10-05',
    keyEquation: 'D(t) = ∫₀ᵗ Φ(τ)·LET dτ ; h_FE(D) = h_FE,0(1 − k_β·D) ; T_mission = (D_failure − D_initial) / Φ̄·LET',
    benchReplication: {
      activeBipolar: '2N3906 silicon PNP (Vishay 2N3906-T, ON Semi PN3906BU) — modern bench substitute; three orders of magnitude lower I_CBO than 1958 germanium; PNP polarity matched to negative-going PMT signal',
      eraOriginal: 'GE 2N43 germanium PNP alloy-junction (1957-1958 production; obsolete; surplus only at $5-25 per unit with no provenance)',
      flightGradeRHA: 'Honeywell HX1810 SOI bipolar (200 krad TID, SEL-immune); ADI ADA4084-2 RHA op-amp (100 krad TID); ADI RH117 RHA regulator (50 krad TID)',
      cumulativeTidEmulationSweep: 'R_B1 perturbation surrogate (470 kΩ → 2.2 MΩ maps to D = 0 → 80 krad cumulative dose; mission day = 0 → 70 on Explorer 4 profile)',
      missionLifeBudget: 'T_mission = (50 krad − 0) / 1.3×10⁻³ rad/s ≈ 446 days (well in excess of 70 days actually flown; mission terminated by battery exhaustion not chain failure)',
      pmtCathodeSubstitute: 'For PMT-equipped detector lab: NOS RCA 6342A or modern Hamamatsu R6357. For educational bench: charge-injection rig (1V step + 100 fF coupling stub) at scint_input emulates PMT pulse',
    },
    references: [
      'Van Allen, J.A. and Frank, L.A. "Radiation Around the Earth to a Radial Distance of 107,400 km", Nature 183 (1959), 430-434 — the Pioneer 3 + Explorer 4 combined flight result',
      'Cladis, J.B., Davidson, G.T., and Newkirk, L.L. (eds.) (1971). The Trapped Radiation Handbook. DNA-2524H',
      'Holmes-Siedle, A. and Adams, L. "Handbook of Radiation Effects" (Oxford UP 2002), chapters 3 (TID in bipolars), 6 (cumulative-dose budget methodology), 8 (PMT cathode TID drift)',
      'Messenger, G.C. and Ash, M.S. "The Effects of Radiation on Electronic Systems" (Van Nostrand 1986; 2e 1992), §4 cumulative-dose model',
      'Larin, F. "Radiation Effects in Semiconductor Devices" (Wiley 1968)',
      'NASA SP-3024 (1966). Models of the Trapped Radiation Environment Vol. I: Inner Zone Protons and Electrons — the mission-design handbook for cumulative-dose integration',
      'Vette, J.I. (1991). The AE-8 Trapped Electron Model Environment. NSSDC/WDC-A-R&S 91-24',
      'Pickel, J.C. and Blandford, J.T. "Cosmic-Ray-Induced Soft Errors in Static MOS RAMs", IEEE Trans. Nucl. Sci. NS-27 (1980), 1006-1015',
      'GE Transistor Manual, 7th edition (1964), pp. 78-80 — 2N43 germanium PNP characterisation',
      'Honeywell HX1810 Series Radiation-Hardened SOI Bipolar Family Datasheet (2024)',
      'DARPA / DTIC (1982). Operation Argus: A Combined Effects Test (declassified, originally 1958). DTIC AD-A019215',
      'MIL-STD-883 Method 1019 — TID test method',
      'MIL-STD-750 Method 1080 — displacement-damage test',
      'JESD57 — single-event-effect test procedures',
      'ECSS-Q-ST-30C — space reliability assurance',
    ],
  },
  complexPlanePosition: {
    real: 0.28,
    imaginary: 0.96,
    magnitude: Math.sqrt(0.28 ** 2 + 0.96 ** 2),
    angle: Math.atan2(0.96, 0.28),
  },
};
