import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.10 — TID and SEU effects on early germanium-transistor amplifiers
 * during Van Allen-belt traversal: the Pioneer 3 dual GM-counter front end.
 *
 * Generated by the v1.49.581 ELC Wave-1 backfill (slot E1-B).
 * Cross-references: NASA 1.10 (Pioneer 3 / Van Allen belt discovery), MUS 1.10
 * (Lace Lichen — slow-fade-to-silence cadence; structural rhyme of cumulative
 * TID drift as monotone gesture that resolves before the next discrete event).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const tidSeuGermanium: RosettaConcept = {
  id: 'elc-1.10-radiation-hardening-germanium',
  name: 'TID and SEU effects on early germanium-transistor amplifiers',
  domain: 'electronics',
  description:
    'A radiation-hardening primitive describing how cumulative total-ionising-dose (TID) ' +
    'exposure and single-event-upset (SEU) heavy-ion strikes degrade and disturb a 1958-vintage ' +
    'germanium bipolar amplifier signal chain. The model has three additive parameter shifts ' +
    'whose dependences on cumulative dose D and instantaneous LET separate cleanly: ' +
    'β(D) = β₀(1 − k_β·D) with k_β ≈ 1×10⁻⁵ per rad for 1958 Ge NPNs; ' +
    'I_CBO(D) = I_CBO,0 + k_I·D with k_I ≈ 50 nA per krad; ' +
    'ΔV_BE(SEU) = Q_dep / C_je where Q_dep is the heavy-ion-deposited charge in the base-emitter ' +
    'depletion region and C_je is the junction capacitance. The crossover between cumulative ' +
    'gain loss and instantaneous false-count probability defines the belt-survival window for ' +
    'any non-shielded bipolar amplifier. The canonical flight exemplar is Pioneer 3 (Juno II ' +
    'AM-3, 1958-12-06), whose 38-hour Van Allen belt traversal validated the linear superposition ' +
    'model retrospectively: germanium 2N1308-class transistors drifted within tolerance, the ' +
    'bias network did not saturate, the discriminator margin held against single-event upsets, ' +
    'and the count-stretcher rejected residual transients — producing the first observation of ' +
    'the second (outer) Van Allen belt and establishing the radial-distance characterisation of ' +
    'the inner zone (Van Allen & Frank, Nature 183, 1959). The Pickel-Blandford 1978/1980 SEU ' +
    'literature gave the formalism its modern form twenty years after Pioneer 3 flew the mechanism.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-bipolar-bias-stability',
      description:
        'Emitter-resistor DC negative-feedback degeneration is the era-universal anti-drift technique that ' +
        'Pioneer 3 used against TID-driven I_CBO rise; the same topology is the structural foundation of ' +
        'modern rad-hard bipolar bias schemes',
    },
    {
      type: 'dependency',
      targetId: 'elec-discriminator-threshold',
      description:
        'Diode-coupled discriminator threshold defines the SEU false-count cross-section: as cumulative TID ' +
        'degrades preamp gain, the SEU-induced ΔV_BE transient that does not exceed threshold at nominal ' +
        'bias may exceed it after dose accumulation, making the SEU cross-section an emergent function of ' +
        'mission duration',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.10-slow-fade-cadence',
      description:
        'Cumulative TID is itself a slow fade — a monotone drift in the bias point that does not produce ' +
        'any single dramatic event but, integrated over hours, shifts the discriminator margin. The MUS 1.10 ' +
        'slow-fade-to-silence cadence is the structural rhyme: a structurally-weighted slow gesture that ' +
        'resolves before the next discrete event arrives',
    },
  ],
  metadata: {
    elcDegree: '1.10',
    domain: 12,
    domainName: 'Radiation hardening',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'Pioneer 3 dual Anton 213 Geiger-Müller counter analog front end — 2N1308-class germanium NPN charge-sensing preamp + 1N34A discriminator + monostable count-stretcher',
    keyEquation: 'β(D) = β₀(1 − k_β·D) ; I_CBO(D) = I_CBO,0 + k_I·D ; ΔV_BE(SEU) = Q_dep / C_je',
    benchReplication: {
      activeBipolar: '2N2222A silicon NPN (Vishay 2N2222A-T, ON Semi PN2222A) — modern bench substitute; three orders of magnitude lower I_CBO than 1958 germanium',
      eraOriginal: 'GE 2N1308 germanium NPN alloy-junction (1957-1958 production; obsolete; surplus only at $5-15 per unit with no provenance)',
      flightGradeRHA: 'Honeywell HX1800-series bipolar (200 krad TID, SEL-immune); ADI ADA4084-2 RHA op-amp (100 krad TID); ADI RH117 RHA regulator (50 krad TID)',
      tidEmulationSweep: 'R_B1 perturbation surrogate (470 kΩ → 1.5 MΩ maps to 0 → 50 krad equivalent dose)',
      seuEmulation: '1 ns FET-switched 1 fF charge injection at q1_base (sweep 0.1-100 fC = 0.1-100 fA·s = LET 1-100 MeV·cm²/mg equivalent)',
    },
    references: [
      'Pickel, J.C. and Blandford, J.T. "Cosmic-Ray-Induced Errors in MOS Memory Cells", IEEE Trans. Nucl. Sci. NS-25 (1978), 1166-1171',
      'Pickel, J.C. and Blandford, J.T. "Cosmic-Ray-Induced Soft Errors in Static MOS RAMs", IEEE Trans. Nucl. Sci. NS-27 (1980), 1006-1015',
      'Messenger, G.C. and Ash, M.S. "The Effects of Radiation on Electronic Systems" (Van Nostrand 1986; 2e 1992)',
      'Holmes-Siedle, A. and Adams, L. "Handbook of Radiation Effects" (Oxford UP 2002), chapters 3 (TID in bipolars) and 5 (SEU in junctions)',
      'Larin, F. "Radiation Effects in Semiconductor Devices" (Wiley 1968)',
      'Van Allen, J.A. and Frank, L.A. "Radiation Around the Earth to a Radial Distance of 107,400 km", Nature 183 (1959), 430-434',
      'GE Transistor Manual, 7th edition (1964), pp. 187-189 — 2N1308 NPN characterisation',
      'Honeywell HX1800 Series Radiation-Hardened Bipolar Logic Family Datasheet (2024)',
      'ADI ADA4084-2 Radiation-Hardened Precision Op-Amp Datasheet (2024)',
      'MIL-STD-883 Method 1019 — TID test method',
      'JESD57 — single-event-effect test procedures',
    ],
  },
  complexPlanePosition: {
    real: 0.18,
    imaginary: 0.94,
    magnitude: Math.sqrt(0.18 ** 2 + 0.94 ** 2),
    angle: Math.atan2(0.94, 0.18),
  },
};
