import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.19 — Cabin-pressure analog-to-PCM telemetry: pressure-to-frequency
 * conversion via Statham strain-gauge bridge, redundant-switch majority
 * voting, and the Freedom 7 Environmental Control System data chain.
 *
 * Generated by the v1.49.581 ELC Wave-4 backfill (E4-D agent).
 * Cross-references: NASA 1.19 (Mercury-Redstone 3 / Freedom 7, first US
 * suborbital crewed flight; Shepard 1961-05-05), MUS 1.19 (cabin-tone
 * structural rhyme — pressure as audible drone; redundant-vote consensus
 * primitive matched to the data-converter's voting strategy).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const pressurePcmTelemetry: RosettaConcept = {
  id: 'elc-1.19-pressure-pcm-telemetry',
  name: 'Cabin-pressure analog-to-PCM telemetry: P→f conversion + redundant-switch majority vote',
  domain: 'electronics',
  description:
    'A data-conversion primitive describing how a strain-gauge Wheatstone bridge ' +
    'transducer (Statham P23-class four-active-arm cabin-pressure cell) drives a ' +
    'discrete-transistor instrumentation pre-amplifier whose output controls the ' +
    'timing-resistor of a relaxation oscillator, encoding cabin atmospheric pressure ' +
    'as the period of a pulse stream that is then sampled and quantised at the IRIG ' +
    'PAM/PCM commutator. The conversion equation is f_out = 1 / (T_centre × ' +
    '(1 + α × ΔP/P_FS)), where ΔP is the pressure deviation from 5 psia (the Mercury ' +
    'cabin set-point) and α is the bridge-to-VCO sensitivity. Redundancy is layered: ' +
    'two independent pressure switches (one set at 4.6 psia warning, one at 4.0 psia ' +
    'abort threshold) feed a discrete-diode majority-vote OR-gate that asserts the ' +
    'cabin-pressure-loss flag only when at least one switch is closed AND the analog ' +
    'channel reads below threshold — three sensors voting two-of-three for the ' +
    'most safety-critical environmental discrete on the spacecraft. The structural ' +
    'insight is that the analog pressure channel and the digital switch-vote channel ' +
    'are independent failure domains, so a single transducer failure cannot suppress ' +
    'the abort signal and a single switch failure cannot trigger a false abort. ' +
    'The canonical flight exemplar is the McDonnell Aircraft Corporation Mercury ' +
    'capsule Environmental Control System (ECS) cabin-pressure subassembly flown on ' +
    'Mercury-Redstone 3 / Freedom 7 (Alan B. Shepard Jr., MR-7 Redstone launch ' +
    '1961-05-05), the first US human spaceflight. The Statham P23-class cell ran at ' +
    '5 psia full-scale (Mercury used a 100% O2 5 psia cabin instead of 14.7 psia ' +
    'sea-level air to lower the structural pressure-vessel mass) with a 4 kHz centre ' +
    'frequency at the relaxation oscillator and ±400 Hz/psi conversion sensitivity; ' +
    'the IRIG PAM/PCM commutator sampled the channel at 11.7 sps. The Freedom 7 ' +
    'topology is the historical ancestor of every modern strain-gauge → V/F → ADC ' +
    'pressure-sensor chain and of every modern voted-redundancy environmental ' +
    'discrete in human spaceflight life-support.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-bolometer-ppm-telemetry',
      description:
        'In-domain predecessor: Domain-8 ELC degree at 1.13 encoded analog input ' +
        'as inter-pulse interval (single-channel PPM time-domain encoding); 1.19 ' +
        'adapts the same multivibrator topology to a strain-gauge bridge driving a ' +
        'voltage-to-frequency converter, preserving the time-domain-encoding ' +
        'pedagogical primitive and adding redundant-switch majority-vote as the ' +
        'safety-critical second channel',
    },
    {
      type: 'dependency',
      targetId: 'elec-tape-storage-telemetry',
      description:
        'In-domain predecessor: Domain-8 ELC degree at 1.4 decoupled write-time ' +
        'from read-time via storage-then-replay; 1.19 decouples a redundant-vote ' +
        'discrete from the analog pressure channel via independent-failure-domain ' +
        'topology, extending the Domain-8 decoupling family from time-domain to ' +
        'fault-domain decoupling',
    },
    {
      type: 'dependency',
      targetId: 'elec-feedback-stability',
      description:
        'Relaxation oscillator depends on the closed-loop positive-feedback ' +
        'structure of the cross-coupled NPN pair; the Schmitt-trigger threshold ' +
        'derives the period from a passive divider of the bus rail, making the ' +
        'oscillator inherently bus-rail-tolerant under battery droop',
    },
    {
      type: 'dependency',
      targetId: 'elec-opamp-configurations',
      description:
        'Bridge pre-amp is a discrete differential common-emitter pair driving a ' +
        'single-ended output — the canonical pre-op-amp-era instrumentation ' +
        'amplifier topology. Era-original is a 2N1308 germanium NPN pair; modern ' +
        'replacement is an INA series instrumentation amp',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.19-cabin-tone-redundant-vote',
      description:
        'Two-of-three voting decouples false-alarm probability from missed-detection ' +
        'probability in the data-converter; chord-voicing redundancy decouples ' +
        'pitch-perception from any single voice in music. Both are consensus ' +
        'gestures that survive single-channel corruption: a Mercury cabin abort ' +
        'survives a single switch failure, and a sustained chord survives a single ' +
        'voice dropping out',
    },
  ],
  metadata: {
    elcDegree: '1.19',
    domain: 8,
    domainName: 'Data conversion',
    era: 'tube-ge',
    eraYears: '1957-1962',
    flightHardware: 'Statham P23-class four-active-arm strain-gauge cabin-pressure transducer (5 psia full-scale, ±0.5 % FS) + Mercury ECS pressure-switch pair (4.6 psia warning + 4.0 psia abort, hermetic Bourdon-tube sense element) + 2N1308-class germanium-NPN discrete instrumentation pre-amp + cross-coupled astable VCO at 4 kHz centre + 1N34A diode majority-vote gate + IRIG PAM/PCM 11.7-sps commutator (Mercury-Redstone 3 / Freedom 7, 1961-05-05)',
    keyEquation: 'f_out = 1 / (T_centre × (1 + α × ΔP/P_FS)) ; with α ≈ 0.10 for Statham P23-class four-arm bridge; sampled at 11.7 sps and quantised to PCM at the commutator',
    benchReplication: {
      activeTransducer: 'Honeywell 24PCEFA1G amplified pressure sensor — 0–5 psia absolute, 0.5–4.5 V ratiometric output, ±0.25 % FS accuracy, surface-mount',
      eraOriginal: 'Statham PA208TC P23-class strain-gauge pressure transducer (1961 bench-available, 5 psia FS, four-active-arm Wheatstone bridge, 350 Ω arms)',
      preAmp: '2N3904 silicon NPN substitute for era-original GE 2N1308 germanium NPN; rework base divider for V_BE = 0.65 V (silicon)',
      timingCapacitor: '100 nF polypropylene film C_T (centre period 250 µs at 4 kHz with R_TIMING = 2.5 kΩ); modern replacement for era-original 100 nF mica',
      conversionSensitivity: '400 Hz/psi at the linear regime (P ∈ [3 psia, 7 psia]); equivalent to 80 Hz / 100 Pa ratiometric for the 24PCEFA1G',
      voteGate: '1N4148 silicon switching diodes substitute for era-original 1N34A germanium point-contact diodes in the OR-vote',
    },
    references: [
      'NASA Space Task Group. (1961). "Postlaunch Memorandum Report for Mercury-Redstone No. 3." MSC, 16 June 1961 (declassified). Cabin-pressure transducer + ECS chain section pp. 4-5 to 4-12.',
      'NASA. (1962). "Project Mercury Familiarization Manual." SP-45 / SEDR-104, McDonnell Aircraft Corp. — the canonical MR-3 mission report and ECS subsystem reference.',
      'Statham Instruments, Inc. (1960). "Type P23 Pressure Transducer — Specification Sheet." Los Angeles, CA. Era-original strain-gauge bridge spec for 5 psia full-scale aerospace cells.',
      'Honeywell Sensing & Productivity Solutions. (2024). "24PCEFA1G Series Amplified Pressure Sensors." Datasheet rev. K. Fort Mill, SC.',
      'IRIG Standard 106 (1961). "Telemetry Standards." Inter-Range Instrumentation Group, Range Commanders Council. PAM/PCM commutator timing.',
      'Sedra, A. S., & Smith, K. C. (2020). Microelectronic Circuits (8e), Oxford UP — ch. 14 Wheatstone bridge instrumentation; ch. 17 cross-coupled astable VCO; §13.7 voted-redundant logic gates',
      'Razavi, B. (2017). Design of Analog CMOS Integrated Circuits (2e), McGraw-Hill — §17.7 voltage-to-frequency conversion and time-encoding ADCs',
      'Horowitz, P., & Hill, W. (2015). The Art of Electronics (3e), Cambridge UP — §8.6 strain-gauge bridge instrumentation; §13.4 voted-redundancy logic',
      'Lyman, J., & Phillips, N. S. (1957). "Strain-gauge transducers for aerospace pressure measurement." ISA Transactions 5(2): 88-97.',
      'NSSDC Master Catalog: Mercury-Redstone 3 (Freedom 7). NSSDCA ID MERCR3.',
    ],
  },
  complexPlanePosition: {
    real: 0.19,
    imaginary: 0.83,
    magnitude: Math.sqrt(0.19 ** 2 + 0.83 ** 2),
    angle: Math.atan2(0.83, 0.19),
  },
};
