import type { RosettaConcept } from '../../../../rosetta-core/types.js';

/**
 * ELC 1.31 — Successive-approximation 9-bit ADC with capacitor-array DAC
 * and sample-and-hold: comparator-trip-point error budget, droop-rate
 * margin, and the Ranger 5 bus-regulator brownout that corrupted the
 * ADC reference.
 *
 * Generated by the v1.49.581 ELC Wave-5 backfill (E5-F agent).
 * Cross-references: NASA 1.31 (Ranger 5 squib-fired battery short ended
 * the JPL Block II hard-lander mission at T+17 minutes; ~30,000 km past
 * lunar miss point on 1962-10-21), MUS 1.31 (silent-corruption structural
 * rhyme — instrument-tuning drift that the performer cannot hear, the
 * music-domain analog of the data-converter's silent code-corruption
 * under V_REF collapse).
 * Subject derivation rubric: .planning/missions/v1-49-581-bundle/ELC-subject-derivation.md §5
 * Authoring template:        .planning/missions/v1-49-581-bundle/ELC-infra-spec.md §3
 */
export const sarAdcBusBrownout: RosettaConcept = {
  id: 'elc-1.31-sar-adc-bus-brownout',
  name: 'Charge-redistribution 9-bit SAR ADC + V_REF passive-divider rail brownout-corruption mode',
  domain: 'electronics',
  description:
    'A data-conversion primitive describing how a successive-approximation register ' +
    '(SAR) ADC with a binary-weighted capacitor-array DAC and sample-and-hold front-end ' +
    'resolves an N-bit conversion in N clock cycles via a binary search through the DAC ' +
    'and a comparator referenced to V_REF. The conversion identity is ' +
    'V_input ≈ (Σ_k=N-1..0 b_k × 2^k) × V_REF / 2^N, with the bit decisions b_k generated ' +
    'one per clock cycle by the SAR controller comparing V(hold_node) to V(dac_out_trial). ' +
    'The Ranger Block II central-computer telemetry chain implemented this as a hand-built ' +
    '9-bit silicon-discrete SAR (2N697 NPN comparator differential pair + Crystalonics 2N4416 ' +
    'JFET sample-and-hold buffer + hand-screened silver-mica binary-weighted capacitor-array ' +
    'from C_LSB = 1 pF to C_MSB = 256 pF; total 511 pF) clocked from the spacecraft 38.4 kHz ' +
    'reference and digitising 90 analog channels at the commutator rate. The structural ' +
    'insight is that the conversion fidelity at design point is dominated by capacitor-array ' +
    'mismatch (DNL ≈ ±0.5 LSB at MSB) and comparator offset (e_OFF ≈ ±0.21 LSB at room ' +
    'temperature), but the ADC is no better than its V_REF — and a V_REF tied to a passive ' +
    'divider of the spacecraft main bus is no better than the main-bus regulator. The ' +
    'failure-mode anchor of this degree is the Ranger 5 squib-fired battery short at ' +
    'T+17 minutes (1962-10-18 16:59 UTC) which collapsed the main bus from +29.5 V to ' +
    '~+11 V; the V_REF rail followed proportionally, the V_REF buffer current-limited and ' +
    'sagged under DAC load, and every digitised sample for the surviving nine hours of ' +
    'secondary-battery operation returned codes pinned at zero or full-scale — silent ' +
    'corruption with no flag to downstream telemetry. The Block III redesign (Ranger 6 ' +
    'onwards, 1964) decoupled V_REF from V_BUS via a Zener-clamped reference regulator ' +
    '(5.1 V Zener + 2N1490 series-pass + 100 µF tantalum bulk), making V_REF brownout-' +
    'tolerant down to V_BUS = +6 V. The Ranger Block II SAR is the historical ancestor of ' +
    'every modern monolithic charge-redistribution SAR-ADC chip family, from the µA702-era ' +
    'pre-monolithic builds (Allen 1974, IEEE J. Solid-State Circuits 9(3): 100-104) through ' +
    'the modern 12-bit ADS7042 in a 1.5 mm × 1.5 mm WSON-8 package. The conversion identity ' +
    'is invariant across the 1962-to-2026 span; only the silicon technology that realises ' +
    'the comparator, capacitor array, sample-and-hold, and SAR controller has changed.',
  panels: new Map(),
  relationships: [
    {
      type: 'dependency',
      targetId: 'elec-comparator-differential-pair',
      description:
        'SAR conversion depends on a comparator with input-referred offset ≤1 LSB across ' +
        'the operating temperature range. Era-original 2N697 hand-screened pair gives ' +
        'V_OS ≤ 1 mV after screening at +25 °C; thermal drift consumes ~±0.21 LSB across ' +
        '+25 °C → +60 °C. Modern monolithic comparators (LM393) match this via internal ' +
        'V_OS specification.',
    },
    {
      type: 'dependency',
      targetId: 'elec-binary-weighted-capacitor-array-dac',
      description:
        'SAR conversion depends on a binary-weighted capacitor-array DAC whose element ' +
        'matching sets the DNL contribution. Era-original silver-mica array hand-screened ' +
        'to ±0.1 % matching gives ±0.5 LSB DNL at MSB transition for a 9-bit converter. ' +
        'Modern monolithic SAR ADCs use trim + digital error correction to recover the ' +
        'same DNL margin at 12 bits or higher.',
    },
    {
      type: 'dependency',
      targetId: 'elec-jfet-source-follower-sample-hold',
      description:
        'SAR conversion depends on a sample-and-hold buffer whose droop rate over the ' +
        'conversion window is below 1 LSB. Era-original 2N4416 silicon JFET source-follower ' +
        'with C_HOLD = 100 pF gives droop ≈ 0.024 LSB at +25 °C, rising to ~0.24 LSB at ' +
        '+60 °C. Modern monolithic SAR ADCs integrate the S/H on-die with the comparator ' +
        '(ADS7042 internal C_HOLD = 24 pF; gate-leak <1 pA on-die).',
    },
    {
      type: 'dependency',
      targetId: 'elec-tape-storage-telemetry',
      description:
        'In-domain predecessor: ELC 1.4 (Explorer 3 endless-loop magnetic-tape recorder) ' +
        'encoded continuous orbital data at one rate and replayed at K_pb = 7.5x on uplink ' +
        'command — sample-rate-conversion via mechanical speed change of the storage ' +
        'medium. This degree extends the Domain-8 family from the storage-medium primitive ' +
        'to the canonical amplitude-domain charge-redistribution SAR primitive.',
    },
    {
      type: 'dependency',
      targetId: 'elec-bolometer-ppm-telemetry',
      description:
        'In-domain predecessor: ELC 1.13 (Explorer 7 bolometer thermistor-bridge + ' +
        'cross-coupled astable multivibrator) encoded analog input as inter-pulse ' +
        'interval — analog-to-frequency time-domain encoding within a single channel. ' +
        'This degree complements the time-domain primitive with the amplitude-domain ' +
        'SAR primitive, completing the Domain-8 conversion-strategy taxonomy across ' +
        'time-domain (1.13), storage-medium (1.4), and amplitude-domain (1.31).',
    },
    {
      type: 'dependency',
      targetId: 'elec-passive-divider-bus-rail',
      description:
        'Bus-rail-coupling failure mode: the V_REF rail is generated as a passive-divider ' +
        'fraction of the regulated +29.5 V main bus (alpha = 0.1723; V_REF = 5.083 V at ' +
        'design point). Bus-droop-tolerant by design: V_REF tracks bus droop transparently. ' +
        'But bus-collapse-intolerant: when V_BUS falls below the V_REF buffer input common-' +
        'mode floor (~+12 V), V_REF sags under DAC load and the conversion silently ' +
        'corrupts. The Block III redesign decoupled this via a Zener-clamped regulator.',
    },
    {
      type: 'analogy',
      targetId: 'mus-1.31-instrument-tuning-drift-silent-corruption',
      description:
        'The data-converter SAR ADC silently returns wrong codes under V_REF collapse: ' +
        'the codes are within range; the downstream telemetry cannot distinguish the ' +
        'corruption from valid data. Music-domain analog: a stringed instrument whose ' +
        'tuning has drifted but whose performer cannot hear the drift produces in-key ' +
        'notes that are systematically wrong. Both are silent-corruption modes that ' +
        'cannot self-flag — the failure surfaces only when an external reference (the ' +
        'ground operator, the audience) detects the drift.',
    },
  ],
  metadata: {
    elcDegree: '1.31',
    domain: 8,
    domainName: 'Data conversion',
    era: 'si-discrete',
    eraYears: '1962-1968',
    flightHardware: 'JPL Hamilton-Standard Ranger Block II central-computer 9-bit silicon-discrete SAR ADC behind the analog-to-PCM commutator (90 analog channels at 38.4 kHz commutator rate; 234 µs per 9-cycle conversion); V_REF passive-divider from +29.5 V regulated Ag-Zn primary battery bus (Eagle-Picher GAP-7239 main + Yardney HR-7 secondary buffer); Atlas-Agena B 1962-10-18 16:59 UTC LC-12 Cape Canaveral; squib-fired contactor weld at T+17 minutes collapsed main bus to +11 V; 9-hour secondary-battery survival with silently-corrupted telemetry; ~30,000 km past lunar miss point on 1962-10-21',
    keyEquation: 'V_input ≈ (Σ_k=N-1..0 b_k × 2^k) × V_REF / 2^N ; with b_k generated one per cycle by binary search via the comparator. Brownout-corruption inequality: V_REF must remain ≥ V_buffer_floor for the conversion to be valid; Block II violated this at V_BUS ≤ +12 V, Block III decoupled V_REF from V_BUS down to V_BUS = +6 V.',
    benchReplication: {
      activeAdc: 'Texas Instruments ADS7042IDCUT 12-bit 1-MSps SAR ADC, WSON-8 1.5 mm × 1.5 mm (Mouser 595-ADS7042IDCUT)',
      eraOriginal: 'JPL hand-built 9-bit silicon-discrete SAR (2N697 comparator + 2N4416 JFET S/H + silver-mica capacitor-array + discrete-flip-flop SAR controller; pre-monolithic, hand-trimmed across the binary-weighted ladder)',
      voltageReference: 'TI LM4040AIM3-5.0 5.000 V ±0.1 % shunt reference, SOT-23 (Mouser 595-LM4040AIM3-5.0) — Block-III-equivalent V_REF stability that decouples the reference rail from the main bus',
      sampleHoldBuffer: 'ON Semi 2N5457 silicon JFET TO-92 (Mouser 512-2N5457RLRMG) — modern substitute for unobtainable Crystalonics 2N4416 with similar V_GS_off, I_DSS, and gate-leak ~100 pA at +25 °C',
      capacitorArray: 'Vishay/KEMET COG/NPO 0805 SMD ceramic caps (1, 2, 4, 8, 16, 32, 64, 128, 256 pF, ±1 % tolerance) — pedagogically-faithful Path B build; ADS7042 monolithic Path A skips discrete array',
      conversionResolution: '9 bits era-original (511 codes; LSB = 9.8 mV at V_REF = 5.0 V) vs 12 bits modern (4096 codes; LSB = 1.22 mV at V_REF = 5.0 V) — order-of-magnitude resolution improvement',
    },
    references: [
      'Allen, P. E. (1974). "A successive-approximation A-D converter using emitter-coupled silicon transistors." IEEE J. Solid-State Circuits 9(3): 100-104',
      'Hall, R. C. (1977). Lunar Impact: A History of Project Ranger. NASA SP-4210, §4 (Ranger 5 failure-mode chain) and §5 (Block III redesign rationale)',
      'JPL Tech Report 32-380 (1963). Ranger 5 Mission Operations and Performance Report',
      'Razavi, B. (2017). Design of Analog CMOS Integrated Circuits (2e), McGraw-Hill — ch. 12 sample-and-hold; ch. 17.6 SAR ADCs',
      'Kester, W. (2005). Data Conversion Handbook (Newnes / Analog Devices) — ch. 3 SAR architectures; ch. 6 capacitor-array DAC mismatch',
      'Maloberti, F. (2007). Data Converters (Springer) — ch. 5 SAR architecture, capacitor mismatch, comparator metastability',
      'Tirrell, M. M. NASA SP-4210 §4 — JPL Block II / Block III architecture overview',
      'Texas Instruments. ADS7042 datasheet rev. K, https://www.ti.com/lit/ds/symlink/ads7042.pdf',
      'NSSDC Master Catalog: Ranger 5. NSSDCA ID 1962-055A',
      'Horowitz, P., & Hill, W. (2015). The Art of Electronics (3e), Cambridge UP — §13.6 sample-and-hold droop; §13.9 SAR ADCs',
    ],
  },
  complexPlanePosition: {
    real: 0.31,
    imaginary: 0.74,
    magnitude: Math.sqrt(0.31 ** 2 + 0.74 ** 2),
    angle: Math.atan2(0.74, 0.31),
  },
};
