/**
 * SVGO config for SCRIBE round-trip-aware optimization — T3 cartridge thin wrapper.
 *
 * Canonical source: src/scribe/svg-validator/svgo-config.ts
 *   createSvgoConfig({ preserveRoundTrip: true })
 *
 * Default SVGO strips <metadata>, custom namespaces, data-* attributes, and IDs.
 * ALL of these are load-bearing for SCRIBE round-tripping (mission Doc 06 §4.1).
 * This config opts out of destructive defaults while allowing safe optimizations.
 *
 * Substrate invariants (NEVER modify — Component 09 conformance test asserts):
 *   removeTitle: false
 *   removeDesc: false
 *   removeMetadata: false
 *   cleanupIds: false
 *   keepDataAttrs: true
 *   unknownContent: false
 *
 * Component 03 sync'd-copy approach:
 *   Canonical config is generated by createSvgoConfig({ preserveRoundTrip: true })
 *   in src/scribe/svg-validator/svgo-config.ts. This file is the static export
 *   of that config for environments where the TypeScript source cannot be run.
 *
 * Usage:
 *   svgo --config=svgo-roundtrip.config.js input.svg -o output.svg
 *
 * Or programmatically:
 *   import { optimize } from 'svgo';
 *   import config from './svgo-roundtrip.config.js';
 *   const result = optimize(svgString, config);
 *
 * Mission: SCRIBE (v1.49.621), Track T3 CODE-SVG-HDL-BRIDGE.
 */

module.exports = {
  multipass: true,
  js2svg: { pretty: true, indent: 2 },
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          // SUBSTRATE INVARIANT: Never strip <metadata> — SCRIBE round-trip
          // data lives there.
          removeMetadata: false,

          // SUBSTRATE INVARIANT: Never strip title/desc — a11y requirement.
          removeTitle: false,
          removeDesc: false,

          // SUBSTRATE INVARIANT: Don't strip unknown namespaces — xmlns:scribe
          // is required per Doc 06 I-CROSS-2.
          removeUnknownsAndDefaults: {
            keepDataAttrs: true,         // preserve data-node-id etc.
            keepAriaAttrs: true,         // preserve a11y attrs (T2 Doc 06)
            unknownAttrs: false,         // keep custom namespaced attrs
            defaultAttrs: false,         // keep attrs that match defaults
            unknownContent: false,       // keep elements in unknown ns
          },

          // SUBSTRATE INVARIANT: Don't renumber IDs — SCRIBE node IDs
          // must match between <scribe:node id=...> and <g class="node" id=...>.
          cleanupIds: false,

          // Safe to keep these off for round-trip readability.
          removeViewBox: false,
          removeXMLProcInstruction: false,
          collapseGroups: false,
          mergePaths: false,
          convertShapeToPath: false,
        },
      },
    },

    // Explicit additional preservations (some SVGO versions need this
    // even with overrides on preset-default).
    {
      name: 'removeUnknownsAndDefaults',
      params: {
        keepDataAttrs: true,
        keepAriaAttrs: true,
        unknownAttrs: false,
        defaultAttrs: false,
        unknownContent: false,
      },
    },
  ],
};
