/**
 * Tests for scripts/closure-verify-cf.mjs (v1.49.641 C2).
 *
 * Validates the closure-verification probe runner that codifies Lesson #10199's
 * W0 gate as an executable tool. Covers:
 *   - usage / --help output
 *   - npm-audit probe (records, exit codes)
 *   - file-snapshot probe (present + absent paths)
 *   - hidden-transitive-guard probe (clean + dirty cases)
 *   - record file structure (frontmatter-like headers, status section)
 *
 * Records are written to .planning/ during test runs; the afterEach cleans
 * test-id-prefixed files so test runs don't accrue clutter.
 */

import { describe, it, expect, afterEach } from 'vitest';
import { existsSync, readFileSync, unlinkSync, mkdirSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const SCRIPT = resolve(process.cwd(), 'scripts', 'closure-verify-cf.mjs');
const TEST_CF_PREFIX = 'cf-test-cluster8';

function runProbe(args) {
  return spawnSync('node', [SCRIPT, ...args], {
    cwd: process.cwd(),
    encoding: 'utf-8',
  });
}

function recordPathFor(cfId) {
  return resolve(process.cwd(), '.planning', `c0-${cfId.toLowerCase()}-closure-verification-record.md`);
}

function cleanRecord(cfId) {
  const p = recordPathFor(cfId);
  if (existsSync(p)) unlinkSync(p);
}

describe('closure-verify-cf.mjs', () => {

  afterEach(() => {
    // Clean any test-id-prefixed records
    for (const id of [
      `${TEST_CF_PREFIX}-npm`,
      `${TEST_CF_PREFIX}-fs-present`,
      `${TEST_CF_PREFIX}-fs-absent`,
      `htg-${TEST_CF_PREFIX}-clean`,
    ]) {
      cleanRecord(id);
    }
  });

  describe('--help', () => {
    it('exits 0 and prints usage', () => {
      const r = runProbe(['--help']);
      expect(r.status).toBe(0);
      expect(r.stdout).toContain('Usage:');
      expect(r.stdout).toContain('npm-audit');
      expect(r.stdout).toContain('hidden-transitive-guard');
    });

    it('shows usage when no probe type given', () => {
      const r = runProbe([]);
      // Empty args treated as help request — exit 0 + usage shown
      expect(r.status).toBe(0);
      expect(r.stdout).toContain('Usage:');
    });

    it('exits 1 on unknown probe type', () => {
      const r = runProbe(['nonexistent-probe']);
      expect(r.status).toBe(1);
      expect(r.stderr).toContain('unknown probe type');
    });
  });

  describe('npm-audit probe', () => {
    it('writes a record file with the expected sections', () => {
      const cfId = `${TEST_CF_PREFIX}-npm`;
      const r = runProbe(['npm-audit', cfId]);
      // Exit code is 0 if no advisories, 1 if there are; either is a valid probe outcome
      expect([0, 1]).toContain(r.status);

      const recordPath = recordPathFor(cfId);
      expect(existsSync(recordPath)).toBe(true);

      const body = readFileSync(recordPath, 'utf-8');
      expect(body).toContain(`# C0 — ${cfId} Closure-Verification Record (npm-audit probe)`);
      expect(body).toContain('## Status');
      expect(body).toMatch(/STATUS:.*`(resolved-upstream|still-real)`/);
      expect(body).toContain('## Routing decision');
      expect(body).toContain('Auto-generated by `scripts/closure-verify-cf.mjs npm-audit');
    });

    it('records a STATUS consistent with the npm-audit result', () => {
      // De-brittled (v1.49.1043): this test used to hard-assert `r.status === 0`
      // (no high advisories), which made the pre-tag-gate re-trip whenever a NEW
      // upstream advisory landed in a transitive dev-dep — outside this project's
      // closure and remediated separately via package.json overrides (v1037 esbuild,
      // v1042 vite+protobufjs). The probe's real contract is that it maps the audit
      // result to the recorded STATUS correctly: exit 0 ↔ resolved-upstream,
      // exit 1 ↔ still-real (closure-verify-cf.mjs:155,217). Assert THAT, not that
      // the dependency tree happens to be clean. The sibling test at line ~82 uses
      // the same [0,1] tolerance.
      const cfId = `${TEST_CF_PREFIX}-npm`;
      const r = runProbe(['npm-audit', cfId]);
      expect([0, 1]).toContain(r.status);

      const body = readFileSync(recordPathFor(cfId), 'utf-8');
      if (r.status === 0) {
        expect(body).toMatch(/STATUS:.*`resolved-upstream`/);
      } else {
        expect(body).toMatch(/STATUS:.*`still-real`/);
      }
    });

    // ─── Severity threshold parameter (v1.49.644 C3 — Lesson #10208) ───
    describe('severity parameter', () => {
      it('defaults to high when no severity given (backward compat)', () => {
        const cfId = `${TEST_CF_PREFIX}-npm`;
        runProbe(['npm-audit', cfId]);
        const body = readFileSync(recordPathFor(cfId), 'utf-8');
        expect(body).toContain('**Severity threshold:** `high`');
        expect(body).toContain('npm audit --audit-level=high');
      });

      it('accepts explicit moderate severity and threads it through to npm', () => {
        const cfId = `${TEST_CF_PREFIX}-npm`;
        runProbe(['npm-audit', cfId, 'moderate']);
        const body = readFileSync(recordPathFor(cfId), 'utf-8');
        expect(body).toContain('**Severity threshold:** `moderate`');
        expect(body).toContain('npm audit --audit-level=moderate');
      });

      it('accepts low + critical severities', () => {
        const cfId = `${TEST_CF_PREFIX}-npm`;
        for (const sev of ['low', 'critical']) {
          runProbe(['npm-audit', cfId, sev]);
          const body = readFileSync(recordPathFor(cfId), 'utf-8');
          expect(body).toContain(`**Severity threshold:** \`${sev}\``);
        }
      });

      it('rejects invalid severity with exit 1 and informative error', () => {
        const r = runProbe(['npm-audit', `${TEST_CF_PREFIX}-npm`, 'bogus']);
        expect(r.status).toBe(1);
        expect(r.stderr).toContain('invalid severity');
        expect(r.stderr).toContain('low, moderate, high, critical');
      });
    });
  });

  describe('file-snapshot probe', () => {
    it('marks status=resolved-upstream when target file is absent', () => {
      const cfId = `${TEST_CF_PREFIX}-fs-absent`;
      const r = runProbe(['file-snapshot', cfId, 'this-path-definitely-does-not-exist.md']);
      expect(r.status).toBe(0);  // file-snapshot always exits 0 (operator interprets)

      const body = readFileSync(recordPathFor(cfId), 'utf-8');
      expect(body).toMatch(/STATUS:.*`resolved-upstream`/);
      expect(body).toContain('target file is absent');
    });

    it('marks status=inconclusive + emits snapshot when target exists', () => {
      const cfId = `${TEST_CF_PREFIX}-fs-present`;
      const r = runProbe(['file-snapshot', cfId, 'package.json']);
      expect(r.status).toBe(0);

      const body = readFileSync(recordPathFor(cfId), 'utf-8');
      expect(body).toMatch(/STATUS:.*`inconclusive`/);
      expect(body).toContain('## First 20 lines (snapshot)');
      expect(body).toContain('gsd-skill-creator');  // from package.json name
    });
  });

  describe('hidden-transitive-guard probe', () => {
    it('reports 0 hidden transitives for a clean direct dep', () => {
      // fast-xml-parser is a direct dep with no nested subtree pulled in
      const r = runProbe(['hidden-transitive-guard', 'fast-xml-parser']);
      expect(r.status).toBe(0);  // 0 = no hits
      expect(r.stdout).toContain('HIDDEN TRANSITIVES: 0');

      const recordPath = recordPathFor(`htg-${TEST_CF_PREFIX}-clean`);
      // Note: actual filename is htg-fast-xml-parser, but our cleanup is by test prefix.
      // We'll just verify the script ran cleanly without expecting a specific record path.
    });

    it('handles missing package gracefully', () => {
      const r = runProbe(['hidden-transitive-guard', 'this-package-is-not-installed']);
      // npm ls fails for unknown packages but the script should still emit a report
      expect(r.stdout).toContain('subtree size: 0');
    });
  });

  describe('auto probe (v1.49.642 C1 — CF-14)', () => {
    const SPEC_DIR = resolve(process.cwd(), '.planning', 'cf-probes');
    const TEST_SPEC_ID = `${TEST_CF_PREFIX}-auto`;
    const testSpecPath = () => resolve(SPEC_DIR, `${TEST_SPEC_ID.toLowerCase()}.yaml`);

    afterEach(() => {
      try { unlinkSync(testSpecPath()); } catch { /* ignore */ }
      cleanRecord(TEST_SPEC_ID);
    });

    it('reports missing spec file with helpful template', () => {
      const r = runProbe(['auto', 'CF-does-not-exist']);
      expect(r.status).toBe(1);
      expect(r.stderr).toContain('probe spec not found');
      expect(r.stderr).toContain('create one with:');
      expect(r.stderr).toContain('cf_id: CF-does-not-exist');
    });

    it('validates required fields in spec', () => {
      const malformed = `cf_id: ${TEST_SPEC_ID}\nprobe_type: file-snapshot\n`;
      mkdirSync(SPEC_DIR, { recursive: true });
      writeFileSync(testSpecPath(), `${malformed}\n`, 'utf-8');

      const r = runProbe(['auto', TEST_SPEC_ID]);
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/missing required field/);
    });

    it('dispatches to file-snapshot probe via spec', () => {
      const specYaml = `cf_id: ${TEST_SPEC_ID}
probe_type: file-snapshot
probe_args:
  path: package.json
routing_rules:
  resolved-upstream: retire
  inconclusive: proceed
notes: |
  Test spec for auto dispatch.
`;
      mkdirSync(SPEC_DIR, { recursive: true });
      writeFileSync(testSpecPath(), `${specYaml}\n`, 'utf-8');

      const r = runProbe(['auto', TEST_SPEC_ID]);
      expect(r.status).toBe(0);
      // Routing should map "inconclusive" → "proceed" since package.json exists
      expect(r.stdout).toContain('routing_rules[inconclusive] => proceed');
      // Record file should be written by the file-snapshot probe
      const body = readFileSync(recordPathFor(TEST_SPEC_ID), 'utf-8');
      expect(body).toMatch(/STATUS:.*`inconclusive`/);
    });

    it('rejects invalid probe_type in spec', () => {
      const specYaml = `cf_id: ${TEST_SPEC_ID}
probe_type: not-a-real-probe
probe_args: {}
routing_rules: {resolved-upstream: retire}
`;
      mkdirSync(SPEC_DIR, { recursive: true });
      writeFileSync(testSpecPath(), `${specYaml}\n`, 'utf-8');

      const r = runProbe(['auto', TEST_SPEC_ID]);
      expect(r.status).toBe(1);
      expect(r.stderr).toContain('invalid probe_type');
    });

    it('rejects auto as probe_type (prevents recursion)', () => {
      const specYaml = `cf_id: ${TEST_SPEC_ID}
probe_type: auto
probe_args: {}
routing_rules: {resolved-upstream: retire}
`;
      mkdirSync(SPEC_DIR, { recursive: true });
      writeFileSync(testSpecPath(), `${specYaml}\n`, 'utf-8');

      const r = runProbe(['auto', TEST_SPEC_ID]);
      expect(r.status).toBe(1);
      expect(r.stderr).toContain('invalid probe_type "auto"');
    });

    // ─── Severity threshold via probe_args.severity (v1.49.644 C3) ───
    it('threads probe_args.severity through to npm-audit (apply-to-self for Lesson #10208)', () => {
      const specYaml = `cf_id: ${TEST_SPEC_ID}
probe_type: npm-audit
probe_args:
  severity: moderate
routing_rules:
  resolved-upstream: retire
  still-real: proceed
notes: |
  Apply-to-self test for the v1.49.644 C3 threshold-enhancement.
`;
      mkdirSync(SPEC_DIR, { recursive: true });
      writeFileSync(testSpecPath(), `${specYaml}\n`, 'utf-8');

      const r = runProbe(['auto', TEST_SPEC_ID]);
      expect([0, 1]).toContain(r.status);  // 0 if no vulns at moderate+, 1 otherwise
      expect(r.stdout).toContain('severity=moderate');

      const body = readFileSync(recordPathFor(TEST_SPEC_ID), 'utf-8');
      expect(body).toContain('**Severity threshold:** `moderate`');
      expect(body).toContain('npm audit --audit-level=moderate');
    });
  });
});
